### ISSUE TITLE
Bug: Questor GUI not popping out after ping timeout/etc/reconnect

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#10]
Questor GUI is not popping out after a eve reconnect. I am using Innerspace and starting with bin/exefile
this problem seems to come around now and then with questor... i think its the settings file that fucks it up

**Comment by ISeeDEDPpl** [comment]
It is the fact that eve is being restarted on it own (reboot on crash/disconnect). It used to be an option that we could disable. 

I _thought_ I'd fixed this about 3 weeks ago. 

case QuestorState.CheckEVEStatus:
                    .... <other unrelated code here> ...
                    // If Questor window not visible, schedule a restart of questor in the uplink so that the GUI will start normally
                    if (!m_Parent.Visible && CloseQuestorflag) //GUI isn't visible and CloseQuestorflag is true, so that his code block only runs once
                    {
                        CloseQuestorflag = false;
                        //m_Parent.Visible = true; //this does not work for some reason - innerspace bug?
                        Cache.Instance.ReasonToStopQuestor = "The Questor GUI is not visible: did EVE get restarted due to a crash or lag?";
                        Logging.Log(Cache.Instance.ReasonToStopQuestor);
                        Cache.Instance.CloseQuestorCMDLogoff = false;
                        Cache.Instance.CloseQuestorCMDExitGame = true;
                        Cache.Instance.SessionState = "Exiting";
                        if (State == QuestorState.CheckEVEStatus)
                        {
                            State = QuestorState.CloseQuestor;
                        }
                        return;

I have a hard time reproducing this condition though. I have not had the issue reoccur on my end since I added that bit, so I am uncertain if it resolves the issue or not.

**Comment by ghost** [comment]
this still isnt working for me after a ping timeout.

**Comment by ghost** [comment]
<Dim> odd.. I just had an eve restart and the gui window came up
<Dim> but the gui window doesnt come up if i have a ping timeout
@RixiM that makes sense to me at first blush
@RixiM a timeout won't result in a client restart?
<Dim> ping timeout makes the client restart
<Lysis> Dim would it happen, perhaps, if your client ran out of the prescribed limit of ram?
<Dim> no
<Dim> it didnt
<Lysis> ah ok, just not up on the latest features and how they iteract
@RixiM Dim: so what restarted your client this time?
<Dim> not sure..
<Dim> about to find out
<Lysis> I hate that crap
<Lysis> that's the stuff that if it happened to me I'd get all paranoid about
<Dim> i think it was just one of those random eve restarts
<Dim> yeah
<Dim> lysis knows what im talking about
<Dim> one client restarts while the others done
<Dim> dont
<Lysis> umm perhaps it was server instability
<Dim> i dont think it was a wallet balance timeout
<Lysis> dude, i swear botters are a prime source of intel for bugfixes, seeing as they run multiple clients on sometimes similar hardware.... ccp should hire us :P
<Dim> nope it wasnt a wallet timeout

**Comment by ghost** [comment]
This was the agent interaction crash that was happening.

**Comment by ISeeDEDPpl** [comment]
it should say in the logs why it restart if it was questor that performed the restart. If questor restarted in 99% of cases it restarts questor using the uplink, which should always allow the gui to work. 

The problem is when eve spontaneously restarts (lag? crash? etc?)

**Comment by ghost** [comment]
This might be an issue we need to bother lax about.

**Comment by ghost** [comment]
This is a Lax fix.
