### ISSUE TITLE
Drone boats

### ISSUE THREAD

**Issue by tetrikx** [ISeeDEDPpl/Questor#102]
After the last commit cc9519f91c270febf4f9793e5ea8163d93fcbd48 the drone boats cannot be used anymore.

Example of errors: 
drones moved in cargohold (51 or 28 of them)
arm phase looping due to drones arming process

Unrelated error: after starting in space, questor doesnt try to finish the mission once in station

**Comment by ISeeDEDPpl** [comment]
this has been fixed locally. I'll commit the fix here shortly

**Comment by ISeeDEDPpl** [comment]
this should be resolved, please test, drones are working perfectly on multiple toons for me now.
