### ISSUE TITLE
Speed tank issues

### ISSUE THREAD

**Issue by dalikman** [ISeeDEDPpl/Questor#103]
https://github.com/ISeeDEDPpl/Questor/commit/45f547c23a3db3673f6f3800a64778823359617a seems to have broken speed tanking.

Tested and the ship no longer orbits when attacking NPCs, confirmed the following in the charname.xml
`
<orbitdistance>xxxxxx</orbitdistance>
<speedTank>true</speedTank>
`
same xml used with previous commits and other forks and does not display this issue.

**Comment by ISeeDEDPpl** [comment]
please define what actions you are using when speed tank does not orbit the target. I assume clearpocket? any others?

**Comment by ISeeDEDPpl** [comment]
It would be helpful to see a console log of this if possible.

**Comment by ISeeDEDPpl** [comment]
ok, found and fixed the issue. I'll commit the fix after ive tested a mission

**Comment by ISeeDEDPpl** [comment]
fixed, please test and open _a new_ issue with console logs if you experience any oddness
