### ISSUE TITLE
Suggestion: Graceful Client Shutdown Button (for manual shutdown)

### ISSUE THREAD

**Issue by Karr** [ISeeDEDPpl/Questor#105]
After the unload and before  the delayed start.  Check if enabled, client would shut down.

This way we could shut down clients gracefully for updates or maintenance or for whatever reason.  Useful when there are many clients running.

**Comment by ISeeDEDPpl** [comment]
This has been added as "ExitWhenIdle" a button available in the schedule tab of the expanded gui. 

Eventually I plan on having the schedules tab allow you to adjust the shutdown time of that session.

**Comment by Karr** [comment]
Graceful shutdowns.  For anyone reading this.  Something that is helpful is to just unselect the AUTOSTART.  When a mission is completed it just sits there and waits.  Doesn't shut down, but gives you the options to shut it down at that point.

UNSELECT AUTOSTART
