### ISSUE TITLE
Wallet Balance Settings Vs. Schedules.xml

### ISSUE THREAD

**Issue by hehbro** [ISeeDEDPpl/Questor#106]
Assuming default setting of 

<walletbalancechangelogoffdelay>40</walletbalancechangelogoffdelay>

If you launch a character through the scheduler with more than 40 minutes before launch, the char will launch and immediately log off 

DATE TIME;0;Quitting!!;;0;NUM;Wallet Balance did not change for over 40min;0;0;0;0;0;0;0;

Would like it to Ignore the check on startup,

Thanks

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/324abb6b5c97ac8307d01cedb09b73a0514bd9d1
