### ISSUE TITLE
Suggestion: Drone control setting in settings file to not assist main ships target

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#11]
One issue ive had with questor is that sometimes it will make my light drones attack battleships while theres frigates or cruisers running around that they could be killing instead.

**Comment by ISeeDEDPpl** [comment]
In some cases you'd want the concentrated fire and others you'd want them killing the smallest targets first. I can see the logic in wanting it configurable. I'll add this to my todo list.  Overall the drones behave 'well' though so whatever changes are made they will need to be tested awhile.

**Comment by ghost** [comment]
Maybe we could have them prioritize on frigates if present... or cruisers.. add a setting for it maybe? If no frigates/cruisers present then assist main ship? with frigates being the highest priority.

**Comment by ISeeDEDPpl** [comment]
This is all done within cache.cs...

```
        // Get the closest high value target
        var highValueTarget = targets.Where(t => t.TargetValue.HasValue && t.Distance < distance).OrderByDescending(t => t.TargetValue.Value).ThenBy(OrderByLowestHealth()).ThenBy(t => t.Distance).FirstOrDefault();
        // Get the closest low value target
        var lowValueTarget = targets.Where(t => !t.TargetValue.HasValue && t.Distance < distance).OrderBy(OrderByLowestHealth()).ThenBy(t => t.Distance).FirstOrDefault();
```

the choice of high or low value targets is now a character and mission level option
dronesKillHighValueTargets, true if you want drones killing BSs first
dronesKillHighValueTargets, false if you want the default behavior of frigates first. 

keep in mind that the priority targets will always be killed first, so you could have drones set to kill high value targets and if you get a webbing frigate or a frigate with a point on you it will switch to the priority target.

**Comment by ghost** [comment]
To be reopened another day :)
