### ISSUE TITLE
Use of corphangar during UnloadLoot state

### ISSUE THREAD

**Issue by happel** [ISeeDEDPpl/Questor#113]
Recently I saw some commits regarding the use of the corphangar function in Eve. Currently Questor seems to 'get stuck' (for lack of a better definition) after docking and attempting to open the corporate hangars. This happens during the UnloadLoot state after the bot has turned in a mission as well as after it is done salvaging. The result is that Questor never finishes unloading and has to be manually put in a different state again to continue. Opening the corp hangars seems to work well during the Arm phase however. So far I've encountered this problem since the new inventory interface was introduced.

This is the log when I turn on debugstates. It's not particularly interesting, so if there is any particular debug state you need me to enable just let me know.

19:36:54 [CombatMissionsBehavior] UnloadLoot.State is OpenHangars
19:36:55 [Cleanup.State is] CheckModalWindows
19:36:55 [Panic.State is ] Idle
19:36:55 [CombatMissionsBehavior] UnloadLoot.State is OpenHangars
19:36:56 [Cleanup.State is] CheckWindowsThatDontBelongInSpace
19:36:56 [Panic.State is ] Idle
19:36:56 [CombatMissionsBehavior] UnloadLoot.State is OpenHangars
19:36:57 [Cleanup.State is] Idle
19:36:57 [Panic.State is ] Idle
19:36:57 [CombatMissionsBehavior] UnloadLoot.State is OpenHangars
19:36:58 [Cleanup.State is] Idle
19:36:58 [Panic.State is ] Idle
19:36:58 [CombatMissionsBehavior] UnloadLoot.State is OpenHangars
19:36:59 [Cleanup.State is] Idle
19:36:59 [Panic.State is ] Idle
19:36:59 [CombatMissionsBehavior] UnloadLoot.State is OpenHangars

**Comment by xelj** [comment]
same problem

**Comment by ISeeDEDPpl** [comment]
corp hangars are not working and is a known issue. I'll disable there use (and force local hangars, so that nothing gets stuck, until questor supports corp hangrs again you should change your config to use local hangars.

**Comment by happel** [comment]
Thanks a lot for the update ISeeDEDPpl. Wasn't sure if they were functional yet.

**Comment by ISeeDEDPpl** [comment]
this should now be resolved. please test and report back. 

thank bbday if it works for you.

**Comment by xelj** [comment]
works fine for me, but only if corpangar name in uppercase
ps. looks like that commit "temporarily disable the manual setting of factions for those that cant be detected by the logo...
this man get re-enabled later."  dont work, Q again in infinity loop when faction without logo

**Comment by ISeeDEDPpl** [comment]
open an issue for that with logs pls.
