### ISSUE TITLE
the questor stay stop in idle after docked in a station if it relog while in salvaging

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#115]
If the questor crash and restart while it was outside in salvaging ship ( noctis ), when it come back in a station it stay stopped in idle and don't go ahead. In that case i press simply delayed start and it continue work perfectly.

**Comment by tetrikx** [comment]
Same issue as in #111

**Comment by Chryst** [comment]
The problem seems solved so i cose it
