### ISSUE TITLE
Add automatic skill train

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#116]
That questor have everything except the automatic skill train.

For are a ligh function you need say it to check and work only where there is a free room in skill queque. Example it can do a check only at log in. Or only when in base every 6 or 10 hours.

**Comment by Agasper** [comment]
DirectEve does not support skill change

**Comment by Chryst** [comment]
Are months it is supported.

**Comment by Chryst** [comment]
CLOSE
