### ISSUE TITLE
Slow salvaging

### ISSUE THREAD

**Issue by xelj** [ISeeDEDPpl/Questor#117]
Before activating salvagers Q waits 5-10 seconds. As a result, given the number of wrecks, the process is quite slow.
At the same time the question - unloading the loot in the corporate hangar is not working at the moment?

**Comment by ISeeDEDPpl** [comment]
corp hangars are still broken at the moment and need quite a bit of infrastructure changes in arm and unload before they will work again. we need to re-plumb things to use one inventory window rather than the 'many' we use now. 

can you provide a log showing the 'slowness' you speak of?

**Comment by ISeeDEDPpl** [comment]
in time.cs: LootingDelay_milliseconds = 3500

you can try adjusting that down.... but iirc we had issues doing that before we had the inventory window handling right. 
I wouldnt go below 2000, but you are welcome to adjust, test, and report back your findings.

**Comment by xelj** [comment]
Salvaging Vengeance take 35min, Assault 27, with perfect noctis and t2 tractors
Now I stopped using salvaging, but log for example:
03:18:11 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:11 [DedicatedSalvageBehavior: Salvage] Opening Cargohold of active ship: waiting [4sec]
03:18:12 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:13 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:14 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:15 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:15 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:15 [Salvage.NavigateIntorangeOfWrecks] Approaching [Coreli Guardian Initiate Wreck] which is [13k away]
03:18:16 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:16 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:16 [Salvage] Locking [Coreli Guardian Initiate Wreck][13k][ID:9000000000000351884][13k away]
03:18:17 [Salvage] Locking [Corelatis Squad Leader Wreck][22k][ID:9000000000000346326][22k away]
03:18:17 [Salvage] Locking [Core Vice Admiral Wreck][22k][ID:9000000000000345340][22k away]
03:18:17 [Salvage] Locking [Corelatis Squad Leader Wreck][23k][ID:9000000000000346400][23k away]
03:18:17 [Salvage] Locking [Core Flotilla Admiral Wreck][23k][ID:9000000000000345704][23k away]
03:18:17 [Salvage] Locking [Coreli Guardian Spy Wreck][24k][ID:9000000000000352074][24k away]
03:18:17 [Salvage] Locking [Corelatis Squad Leader Wreck][26k][ID:9000000000000346695][26k away]
03:18:17 [Salvage] Locking [Coreli Guardian Scout Wreck][30k][ID:9000000000000352404][30k away]
03:18:17 [Salvage] Locking [Corelatis Squad Leader Wreck][31k][ID:9000000000000346599][31k away]
03:18:17 [Salvage] Locking [Corelum Guardian Chief Patroller Wreck][31k][ID:9000000000000346236][31k away]
03:18:18 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:18 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:19 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:19 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:20 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:20 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:21 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:22 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:22 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:23 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:23 [Salvage] Activating tractorbeam [4] on [Corelatis Squad Leader Wreck][31k][ID: 9000000000000346599]
03:18:23 [Salvage] Activating tractorbeam [4] on [Coreli Guardian Spy Wreck][24k][ID: 9000000000000352074]
03:18:23 [Salvage] Activating tractorbeam [4] on [Core Vice Admiral Wreck][22k][ID: 9000000000000345340]
03:18:23 [Salvage] Activating tractorbeam [4] on [Corelatis Squad Leader Wreck][26k][ID: 9000000000000346695]
03:18:24 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:24 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:25 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:25 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:26 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:26 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:27 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:27 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:28 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:28 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:29 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:29 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:30 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:30 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:31 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:31 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:31 [Salvage.NavigateIntorangeOfWrecks] Approaching [Coreli Guardian Spy Wreck] which is [7k away]
03:18:32 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:32 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:32 [Salvage] Activating salvager [1] on [Coreli Guardian Spy Wreck][ID: 9000000000000352074]
03:18:33 [Salvage] Activating salvager [2] on [Coreli Guardian Spy Wreck][ID: 9000000000000352074]
03:18:33 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:33 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:34 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:34 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:35 [Salvage.NavigateIntorangeOfWrecks] Stop ship, ClosestWreck [1020] is in scooprange + [1790] and we were approaching
03:18:35 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:36 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:36 [Salvage.NavigateIntorangeOfWrecks] Stop ship, ClosestWreck [653] is in scooprange + [1790] and we were approaching
03:18:36 [Salvage] Activating tractorbeam [4] on [Corelatis Squad Leader Wreck][25k][ID: 9000000000000346400]
03:18:36 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:37 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:38 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:38 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:39 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:39 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:39 [Salvage] Activating tractorbeam [4] on [Corelatis Squad Leader Wreck][26k][ID: 9000000000000346400]
03:18:39 [Salvage] Activating tractorbeam [4] on [Core Flotilla Admiral Wreck][25k][ID: 9000000000000345704]
03:18:40 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:40 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:41 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:41 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
03:18:42 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
03:18:42 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold

**Comment by ISeeDEDPpl** [comment]
you managed to only give less than 1 min of logs... and they look quite busy. 
in current experimental I am seeing all tractors and salvagers stay busy a very high % of the time. if this is still an issue for you you need to postat least 10 min of salvaging logs so I can see what is happening (or not happening).
