### ISSUE TITLE
Bug: <action name="ClearWithinWeaponsRangeOnly" />

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#12]
<action name="ClearWithinWeaponsRangeOnly" /> Errors out at acceleration gates. When used it will just sit at one.

It doesn't seem to think its done clearing pocket.

Move to background works.

Haven't tested ClearWithinWeaponsRangeOnly by itself.

Here's an example of a pocket:

```
<pocket id="0">
  <damagetype>Explosive</damagetype>
  <actions>
<action name="MoveToBackground">
    <parameter name="Target" value="Acceleration Gate" />
</action>
<action name="ClearWithinWeaponsRangeOnly" />
<action name="ClearPocket" />
<action name="Activate">
    <parameter name="Target" value="Acceleration Gate" />
</action>
  </actions>
</pocket>
```

**Comment by ISeeDEDPpl** [comment]
Can you re-test this? i corrected an issue with this action and it needs to be tested.

**Comment by ghost** [comment]
This seems to be working now!

**Comment by ghost** [comment]
If it gets to the accel gate and theres still npcs to kill, it will kill all the npcs but it wont activate the gate. it just sits at the gate. this is using:

```
<pocket id="0">
  <damagetype>Explosive</damagetype>
  <actions>
<action name="MoveToBackground">
    <parameter name="Target" value="Acceleration Gate" />
</action>
<action name="ClearWithinWeaponsRangeOnly" />
<action name="ClearPocket" />
<action name="Activate">
    <parameter name="Target" value="Acceleration Gate" />
</action>
  </actions>
</pocket>
```

i think it finishes moving to gate and clearwithinweprange... then goes to clear pocket then uses activate gate, but the activate gate is somehow not approaching to where it wants to be for activating the gate.
