### ISSUE TITLE
Agent name crash

### ISSUE THREAD

**Issue by Sko11** [ISeeDEDPpl/Questor#120]
If there is no agent name in the xml file, the shorting of the agent names cause crash after start of the questor.

**Comment by ISeeDEDPpl** [comment]
can you get me a log of this?
start eve with the innerspace default profile (or similar)
login to eve manually
bring up the innerspace console
type "log thenameofmylogfilehere.log"
then start questor: "dotnet questor questor"
then if/when it crashes bring up that log file you created above and send it to me. on the forums as a PM, on IRC in a priv chat or here if you are sure youve cleaned up the log to not have your login name / pass / toon

**Comment by ISeeDEDPpl** [comment]
fixed in latest experimental.

**Comment by ISeeDEDPpl** [comment]
in does however still require an agent to be entered, it just doesnt crash anymore. eventually we should eliminate the need for an agentname to determine "homestation" so that agentname will no longer be a requirement.
