### ISSUE TITLE
Orbiting in combat helper mode

### ISSUE THREAD

**Issue by Sko11** [ISeeDEDPpl/Questor#121]
When I try to kill with combat helper in an anomlay or in a belt, the orbiting is every time 0. My orbit distance in the xml is 90000. So what kind of value will be use in this case..?

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/22dfab0d06b837f0cd7499c1556042b276dbe6b3

fixed in latest experimental.

**Comment by Sko11** [comment]
Thanks!!!! :)

**Comment by Sko11** [comment]
Amm... I had to copy my all xml to the root of the innerspace because it doesn't found them....

**Comment by ISeeDEDPpl** [comment]
it finds them there? It should be telling you in the console log what xml it is TRYING to load and if duccessful which XML it DID load
