### ISSUE TITLE
bug scheduler

### ISSUE THREAD

**Issue by xelj** [ISeeDEDPpl/Questor#124]
When you run 2 or more clients and start-up time has not come yet, on reaching the start-up time works only one client. The second and subsequent close game after the login and character selection. It is easy to check, if you run 2 clients and set the start time in 3-5 minutes from the current one.

**Comment by ISeeDEDPpl** [comment]
they should be restarting the client (if anything)... we need the console output when that occurs if you want it fixed. If I try to reproduce and create said console output for every issue Id never code anything =/ If you can't or dont want to provide the logs I'll eventually get to it but It'll definitely get fixed faster w logs.

**Comment by xelj** [comment]
Yes, one more problem that I forgot to write - in the above-described bug does not create a log of the console. A little later, try to copy directly from the client.

**Comment by xelj** [comment]
How can I enable logging before loading charname.xml? I managed to see red text in the console, but do not have time to read it.

**Comment by oldmeat** [comment]
For me work correctly, but i set start second client few minutes later.
But i delete 'runtime' option from schedules file.

**Comment by ISeeDEDPpl** [comment]
yes, runtime is not supported anymore and will be removed when we merge in the multipleschedules branch. 

could you please reproduce this issue with the multipleschedules branch? If that branch works well for you Ill merge it into experimental.

**Comment by ISeeDEDPpl** [comment]
xelj, the closest you ca come currently is to load questor via an innerspace script... and start the logging  there.. something like.

`
;copy and paste into a file (like debugquestor.iss)
;to use it you'd change your innerspace profile  (or make a new one) to do: runscript debugquestor.iss "ThisIsTheNameOfMyToonHere"
;the log file will be in your innerspace directory.
function main(string charName)
{
    log myInnerspaceDiagnosticLogFile.log
    wait 30
    Echo [${Time}] Starting Questor with schedule(2 of 2) with character: [${charName}]
    Echo [${Time}] dotnet questor questor -x -c ${charName}
    dotnet questor questor -x -c "${charName}"
}
`

**Comment by oldmeat** [comment]
I use experimental branch and for me schedules work fine. 
I dont test multipleschedules branch.

**Comment by ISeeDEDPpl** [comment]
if this is still an issue for you please reproduce it with the multipleschedules branch.
