### ISSUE TITLE
Halted on trial account

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#125]
07:38:28 o[yStartupo] wLogin account [XXXXX]
07:38:28 o[yStartupo] wWaiting for Character Selection Screen
07:39:08 o[yStartupo] wwindowtitles:modal::Welcome to EVE Online XXXXX.You are on a 14 day trial. Your account was created on June XX, 2012 meaning that you have XX days left on your trial.At any time you can log in to the account management page and change your trial account to a paying account and continue playing your characterCurrently there are XXXX players on the server and of that XXX are trial accounts.
07:39:08 o[yStartupo] rWe've got an unexpected window, auto login halted.
07:39:08 o[yStartupo] rwindow.Name is: modal
07:39:08 o[yStartupo] rwindow.Html is: Welcome to EVE Online XXXX.You are on a 14 day trial. Your account was created on June XX, 2012 meaning that you have XX days left on your trial.At any time you can log in to the account management page and change your trial account to a paying account and continue playing your characterCurrently there are XXXXX players on the server and of that XXX are trial accounts.
07:39:08 o[yStartupo] rwindow.Caption is: 
07:39:08 o[yStartupo] rwindow.Type is: form.MessageBox
07:39:08 o[yStartupo] rwindow.ID is: 
07:39:08 o[yStartupo] rwindow.IsDialog is: True
07:39:08 o[yStartupo] rwindow.IsKillable is: True
07:39:08 o[yStartupo] rwindow.Viewmode is: 
07:39:08 o[yStartupo] rWe've got an unexpected window, auto login halted.

Just halted on the pop up trial account window.

I ran it again and click ok for the popup window and completed the log in.

**Comment by ISeeDEDPpl** [comment]
fixed. please test.

**Comment by Pluckyduck** [comment]
fixed rolled right on.
