### ISSUE TITLE
24 Jun ISDP-ee88bde - Exp

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#126]
Complied with VS'10 Express-no errors

Just after undocking, this started spamming and did not warp off.

16:44:57 o[yTravelero] gSetting destination to [yXXXXig]
16:45:18 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:18 o[yQuestor: ReloadAmmoo] wOpening Cargohold of active ship: waiting [3sec]
16:45:19 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:20 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:21 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:22 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:23 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:24 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:25 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:26 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:27 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:28 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:29 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:30 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:31 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:32 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:33 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:34 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:35 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:36 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:37 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:38 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:39 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:41 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:42 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:43 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:44 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:45 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:46 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:47 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:48 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:49 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:50 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:51 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:52 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:53 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:54 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:55 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:56 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:57 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:58 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:45:59 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:00 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:01 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:02 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:03 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:04 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:05 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:06 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:07 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:08 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:09 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:23 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:24 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:25 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:26 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:47 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:48 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:49 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:50 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:51 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]
16:46:52 o[yTravelero] gWarping to [yXXXXig][y57.36g AU away]

**Comment by ISeeDEDPpl** [comment]
this should be fixed. please confirm.

**Comment by Pluckyduck** [comment]
ISeeDEDPpl-Questor-8fc8c39 no problems to report, running first test now (currently running first mission).
