### ISSUE TITLE
Moving out of range between unlocking and looting

### ISSUE THREAD

**Issue by karope** [ISeeDEDPpl/Questor#127]
While speed tanking or moving, the tractor beam deactivates before a wreck can be looted.  This prevents looting as the wreck or container will be out of range within a matter of seconds.

**Comment by ISeeDEDPpl** [comment]
what ship are you having this issue with?

**Comment by karope** [comment]
Vargur

**Comment by ISeeDEDPpl** [comment]
this can be fixed but is going to involve some fairly invasive changes to salvage.cs... 
enough that Id like to test it for awhile before committing. I'll likely commit this to a different branch for testing.

**Comment by ISeeDEDPpl** [comment]
this fix was merged into experimental a few weeks ago:
https://github.com/ISeeDEDPpl/Questor/commit/56ac89a1845195ebf19eb10208ee45fc783caf76
