### ISSUE TITLE
out of ammo bugs

### ISSUE THREAD

**Issue by xelj** [ISeeDEDPpl/Questor#128]
1.  After commit https://github.com/ISeeDEDPpl/Questor/commit/cee7bc61fad4b74212ad0797185fa0195150ea66 Q try reload ammo after undock. But when mission without faction logo (rogues drone, merc, eom, wc etc) type of damage selected by default as em until the ship reaches the first pocket. As a result, if you select the type of damage in mission.xml not em, after undock Q tries reload ammo with em type, but the em ammo in cargo will not be, and q enter a state of outofammo.
   While for solutions, you can delete rows 173,336 and 362 (begin from "if (!Combat.ReloadAll") in Questor.Modules/Actions/TravelerDestination.cs.
2. If Q enter into outofammo state, it dont exit from this state even after return to base, and we get infinity loop "go to mission--out of ammo--return to base--go to mission"
3. In outofammo state after return to base Q take only 1 unit ammo. Perhaps is the cause the previous bug.

And last, not bug. Now Q enter in outofammo state when ammo in cargo less than   minimumAmmoCharges (  ) from charname.xml. Maybe better if it will happen when the number of ammo is less or equal than the number of weapons?

**Comment by ISeeDEDPpl** [comment]
This should be resolved in experimental, if you find any ammo issues please open a new issue with logs if possible.
