### ISSUE TITLE
Bug: Switching a manual state OUT OF panic state.

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#13]
After a gank attempt sometimes i like to go back and loot. its impossible to get questor to change state out of panic (and into combat helper or idle or i think any other state) until it docks itself and resets.

**Comment by ISeeDEDPpl** [comment]
This has been fixed as part of the GUI changes:

```
    private void QuestorStateComboBox_SelectedIndexChanged(object sender, EventArgs e)
    {
        _questor.State = (QuestorState)Enum.Parse(typeof(QuestorState), QuestorStateComboBox.Text);
        // If you are at the controls enough to change states... assume that panic needs to do nothing
        _panic.State = PanicState.Resume;
    }
```

When you manually change the questor state using the GUI the panic state is reset to panic.resume.
