### ISSUE TITLE
Unload loot Freight Container and other in 2 weeks ago commit

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#131]
In this commit https://github.com/ISeeDEDPpl/Questor/commit/2aa1af3b1a2af7175afd0d8e70cacee81bb21c9f everything work fine and stable, Unload Loot to Freight Container also. Only sometimes, rare ... autostartt not always start.

**Comment by ghost** [comment]
2 week old commit has working freight container code.

**Comment by ghost** [comment]
Maybe if hes here when youre here you can have him test the commits for you.

**Comment by ghost** [comment]
@ISDP

**Comment by oldmeat** [comment]
ping

**Comment by Chryst** [comment]
I hope someone implement it in that code...

**Comment by ISeeDEDPpl** [comment]
this issue has been resolved in current experimental.
