### ISSUE TITLE
Moving away from targets

### ISSUE THREAD

**Issue by Agasper** [ISeeDEDPpl/Questor#132]
When bot can't target group of NPC on a mission, he writing in the log:

> 22:09:05 [CombatMissionCtrl.ClearPocket] Using Weapons Range: Approaching target [Mercenary Commander][ID: 9000000000000130887][112k away]
> 22:09:35 [Questor] Wallet Balance Has Not Changed in [ 6 ] minutes.
> 22:10:23 [CombatMissionCtrl.ClearPocket] Using Weapons Range: Approaching target [Mercenary Commander][ID: 9000000000000130888][119k away]
> 22:10:35 [Questor] Wallet Balance Has Not Changed in [ 7 ] minutes.
> 22:11:41 [CombatMissionCtrl.ClearPocket] Using Weapons Range: Approaching target [Yarl Uzbeki][ID: 9000000000000130932][133k away]

and fly away to the opposite direction from the NPC until reached warp range (150 km), then he try to fly back and repeat nearly 150km.

Config:

> ammo range = 200000
> optimalRange = 0

DE: v1.330.4560.41707
Questor commit 87ededb

is it normally ?

**Comment by ISeeDEDPpl** [comment]
no, not normal. 

I need the rest of the console log from a mission. you chopped out olot of entries that may be useful. 
speed tank?

you can enable additional logging as well... <debugNavigateOnGrid>true</debugNavigateOnGrid>
the log generated while that debug setting is true will be VERY large (10-20x larger than normal Id guess), so do not run all day with that setting on... Only a few missions at a time.

**Comment by Agasper** [comment]
i correct it by change ammo range to 75000 (lock range), but i will try to repeat this bug with logging.
p.s. speedtank = false

**Comment by ISeeDEDPpl** [comment]
what was your ammo range before? I assume it was larger than your lock range... we should be checking for that everywhere (but evident ally not if adjusting that down made a difference)...

**Comment by Agasper** [comment]
i wrote in first post:

> ammo range = 200000
> optimalRange = 0
