### ISSUE TITLE
Strange bug with ammo

### ISSUE THREAD

**Issue by Agasper** [ISeeDEDPpl/Questor#133]
Sometimes on some missions bot stucked with ammo. For example mission "Silence the informant" with no faction (it doesnt matter, bot alto stucked with factional missions). Mission XML contains Kinetic ammo type. Bot takes some Kinetic missiles and fly to the mission, but when travelling bot writes:

>  [Combat] ReloadNormalAmmo: not enough [`any type`] ammo in cargohold: MinimumCharges: [6]

at activation gate:

> [Combat] Out of Ammo!

then bot travelling to the home. When bot at the station he normally unload loot, check the mission, and takes 1 ammo. 

> [Arm] Moving [1] units of Ammo [Scourge Cruise Missile] from [('InventorySecondary_StationItems', 60003886)] to CargoHold

Then actions repeated.

For the last 3 days this bug appears about 5 times. Sometimes it works when delete from mission XML line with damage type.

Log from last mission: http://pastebin.com/UjSJNwew
Full log (with 2 cycles of stuck): http://pastebin.com/SxkYHjpn

**Comment by ISeeDEDPpl** [comment]
thank you for the bug report this may help to resolve the issue in experimental. Until then you can use the FixReloadAllIssue branch.

**Comment by ISeeDEDPpl** [comment]
this should be resolved in experimental. please update the issue if you see the issue in current experimental.
