### ISSUE TITLE
Jetting loot per ISK/m3 causing extremely long loot times

### ISSUE THREAD

**Issue by grdk** [ISeeDEDPpl/Questor#136]
This is mostly a problem after we are not allowed to place items into system-created cans (e.g. a can which spawned from a salvaged wreck). Due to this IIRC the ISK/m3 algo is now jetting cans more often now, but it'll end up processing the to-be -looted queue very very _VERY_ slow. The bot will attempt to jet a few items at once, grab some stuff out of the can its inspecting, then do the same thing again to the next can (after waiting out the delay for jetting cans). You end up with an overview full of jetcans (I counted something like 30+ cans?). The only way to get out of this sooner is to ofc change the state to GotoBase where it'll return and turn in the mission as normal.

I only saw this behavior on a few Golems, though after mission salvagers using <unloadLootAtStation>false</unloadLootAtStation> might get this too?

Maybe the fix should include something like:
IF no more wrecks
AND bot has attempted to jet more than 3-5 cans IN A ROW in order to make room for more valuable loot
THEN Done and GotoBase

Here's a console snippet (it was still trying to jet cans for 40 mins before I manually set GotoBase):

21:19:52 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
21:20:19 [Salvage] Jettisoning [2] items to make room for the more valuable loot
21:20:53 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
21:21:54 [Questor] Wallet Balance Has Not Changed in [ 5 ] minutes.
21:22:55 [Questor] Wallet Balance Has Not Changed in [ 6 ] minutes.
21:23:25 [Salvage] Jettisoning [1] items to make room for the more valuable loot
21:23:28 [Salvage] Looting container [Cargo Container][2k][ID: 1007183624410], [6] valuable items
21:23:28 [Salvage] Opening container [Cargo Container][0k][ID: 1007183665967]
21:23:30 [Salvage] Stacking items
21:23:35 [Salvage] Done stacking
21:23:37 [Salvage] Container [Cargo Container][0k][ID: 1007183665967] contained no valuable items
21:23:37 [Salvage] Opening container [Cargo Container][0k][ID: 1007183648703]
21:23:40 [Salvage] Looting container [Cargo Container][0k][ID: 1007183648703], [2] valuable items
21:23:43 [Salvage] Opening container [Cargo Container][1k][ID: 1007183642144]
21:23:55 [Questor] Wallet Balance Has Not Changed in [ 7 ] minutes.
21:25:57 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
21:26:30 [Salvage] Jettisoning [8] items to make room for the more valuable loot
21:26:58 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
21:27:58 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
21:28:59 [Questor] Wallet Balance Has Not Changed in [ 5 ] minutes.
21:29:36 [Salvage] Jettisoning [1] items to make room for the more valuable loot
21:29:39 [Salvage] Looting container [Cargo Container][1k][ID: 1007183642144], [3] valuable items
21:29:39 [Salvage] Opening container [Cargo Container][0k][ID: 1007183701886]
21:29:41 [Salvage] Stacking items
21:29:46 [Salvage] Done stacking
21:29:48 [Salvage] Container [Cargo Container][0k][ID: 1007183701886] contained no valuable items
21:29:48 [Salvage] Opening container [Cargo Container][0k][ID: 1007183683570]
21:29:51 [Salvage] Container [Cargo Container][0k][ID: 1007183683570] contained no valuable items
21:29:58 [Salvage] Opening container [Cargo Container][1k][ID: 1007183628658]
21:30:00 [Questor] Wallet Balance Has Not Changed in [ 6 ] minutes.
21:31:00 [Questor] Wallet Balance Has Not Changed in [ 7 ] minutes.
21:32:01 [Questor] Wallet Balance Has Not Changed in [ 8 ] minutes.
21:32:42 [Salvage] Jettisoning [2] items to make room for the more valuable loot
21:33:01 [Questor] Wallet Balance Has Not Changed in [ 9 ] minutes.
21:34:01 [Questor] Wallet Balance Has Not Changed in [ 10 ] minutes.
21:35:02 [Questor] Wallet Balance Has Not Changed in [ 11 ] minutes.
21:35:48 [Salvage] Jettisoning [4] items to make room for the more valuable loot
21:35:51 [Salvage] Looting container [Cargo Container][1k][ID: 1007183628658], [2] valuable items
21:35:51 [Salvage] Opening container [Cargo Container][0k][ID: 1007183736579]
21:35:53 [Salvage] Stacking items
21:35:58 [Salvage] Done stacking
21:36:00 [Salvage] Looting container [Cargo Container][0k][ID: 1007183736579], [1] valuable items
21:36:00 [Salvage] Opening container [Cargo Container][1k][ID: 1007183618646]
21:36:03 [Questor] Wallet Balance Has Not Changed in [ 12 ] minutes.
21:37:03 [Questor] Wallet Balance Has Not Changed in [ 13 ] minutes.
21:38:04 [Questor] Wallet Balance Has Not Changed in [ 14 ] minutes.
21:38:55 [Salvage] Jettisoning [1] items to make room for the more valuable loot
21:39:04 [Questor] Wallet Balance Has Not Changed in [ 15 ] minutes.
21:40:05 [Questor] Wallet Balance Has Not Changed in [ 16 ] minutes.
21:41:06 [Questor] Wallet Balance Has Not Changed in [ 17 ] minutes.
21:42:01 [Salvage] Jettisoning [1] items to make room for the more valuable loot
21:42:04 [Salvage] Looting container [Cargo Container][1k][ID: 1007183618646], [3] valuable items
21:42:04 [Salvage] Opening container [Cargo Container][0k][ID: 1007183753561]
21:42:06 [Questor] Wallet Balance Has Not Changed in [ 18 ] minutes.
21:42:06 [Salvage] Stacking items
21:42:11 [Salvage] Done stacking
21:42:14 [Salvage] Container [Cargo Container][0k][ID: 1007183753561] contained no valuable items
21:42:20 [Salvage] Opening container [Cargo Container][1k][ID: 1007183628920]
21:43:07 [Questor] Wallet Balance Has Not Changed in [ 19 ] minutes.
21:44:08 [Questor] Wallet Balance Has Not Changed in [ 20 ] minutes.
21:45:07 [Salvage] Jettisoning [1] items to make room for the more valuable loot
21:45:09 [Questor] Wallet Balance Has Not Changed in [ 21 ] minutes.
21:46:10 [Questor] Wallet Balance Has Not Changed in [ 22 ] minutes.
21:47:11 [Questor] Wallet Balance Has Not Changed in [ 23 ] minutes.
21:48:11 [Questor] Wallet Balance Has Not Changed in [ 24 ] minutes.
21:48:13 [Salvage] Jettisoning [1] items to make room for the more valuable loot
21:49:12 [Questor] Wallet Balance Has Not Changed in [ 25 ] minutes.
21:50:13 [Questor] Wallet Balance Has Not Changed in [ 26 ] minutes.
21:51:19 [Salvage] Jettisoning [1] items to make room for the more valuable loot
21:51:22 [Salvage] Looting container [Cargo Container][1k][ID: 1007183628920], [4] valuable items
21:51:22 [Salvage] Opening container [Cargo Container][0k][ID: 1007183804341]
21:51:24 [Salvage] Stacking items
21:51:29 [Salvage] Done stacking
21:51:31 [Salvage] Looting container [Cargo Container][0k][ID: 1007183804341], [1] valuable items
21:51:31 [Salvage] Opening container [Cargo Container][1k][ID: 1007183635065]
21:52:13 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
21:53:14 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
21:54:15 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
21:54:25 [Salvage] Jettisoning [1] items to make room for the more valuable loot
21:54:28 [Salvage] Looting container [Cargo Container][1k][ID: 1007183635065], [4] valuable items
21:54:28 [Salvage] Opening container [Cargo Container][0k][ID: 1007183839152]
21:54:30 [Salvage] Stacking items
21:54:35 [Salvage] Done stacking
21:54:37 [Salvage] Container [Cargo Container][0k][ID: 1007183839152] contained no valuable items
21:54:43 [Salvage] Opening container [Cargo Container][0k][ID: 1007183769515]
21:54:46 [Salvage] Container [Cargo Container][0k][ID: 1007183769515] contained no valuable items
21:54:46 [Salvage] Opening container [Cargo Container][0k][ID: 1007183719253]
21:54:52 [Salvage] Container [Cargo Container][0k][ID: 1007183719253] contained no valuable items
21:54:52 [Salvage] Opening container [Cargo Container][0k][ID: 1007183786955]
21:54:55 [Salvage] Container [Cargo Container][0k][ID: 1007183786955] contained no valuable items
21:55:01 [Salvage] Opening container [Cargo Container][1k][ID: 1007183633952]
21:55:16 [Questor] Wallet Balance Has Not Changed in [ 5 ] minutes.
21:56:16 [Questor] Wallet Balance Has Not Changed in [ 6 ] minutes.
21:57:16 [Questor] Wallet Balance Has Not Changed in [ 7 ] minutes.
21:57:31 [Salvage] Jettisoning [2] items to make room for the more valuable loot
21:58:17 [Questor] Wallet Balance Has Not Changed in [ 8 ] minutes.
21:59:18 [Questor] Wallet Balance Has Not Changed in [ 9 ] minutes.
22:00:18 [Questor] Wallet Balance Has Not Changed in [ 10 ] minutes.
22:00:37 [Salvage] Jettisoning [1] items to make room for the more valuable loot
22:01:19 [Questor] Wallet Balance Has Not Changed in [ 11 ] minutes.
22:02:20 [Questor] Wallet Balance Has Not Changed in [ 12 ] minutes.
22:03:21 [Questor] Wallet Balance Has Not Changed in [ 13 ] minutes.
22:03:43 [Salvage] Jettisoning [3] items to make room for the more valuable loot
22:03:46 [Salvage] Looting container [Cargo Container][1k][ID: 1007183633952], [5] valuable items
22:03:46 [Salvage] Opening container [Cargo Container][0k][ID: 1007183874185]
22:03:48 [Salvage] Stacking items
22:03:53 [Salvage] Done stacking
22:03:58 [Salvage] Looting container [Cargo Container][0k][ID: 1007183874185], [1] valuable items
22:03:58 [Salvage] Opening container [Cargo Container][0k][ID: 1007183890637]
22:04:21 [Questor] Wallet Balance Has Not Changed in [ 14 ] minutes.
22:05:22 [Questor] Wallet Balance Has Not Changed in [ 15 ] minutes.
22:06:23 [Questor] Wallet Balance Has Not Changed in [ 16 ] minutes.
22:06:49 [Salvage] Jettisoning [1] items to make room for the more valuable loot
22:06:52 [Salvage] Looting container [Cargo Container][0k][ID: 1007183890637], [2] valuable items
22:06:52 [Salvage] Opening container [Cargo Container][0k][ID: 1007183906819]
22:06:55 [Salvage] Container [Cargo Container][0k][ID: 1007183906819] contained no valuable items
22:07:01 [Salvage] Opening container [Cargo Container][0k][ID: 1007183856438]
22:07:04 [Salvage] Container [Cargo Container][0k][ID: 1007183856438] contained no valuable items
22:07:04 [Salvage] Opening container [Cargo Container][0k][ID: 1007183821894]
22:07:07 [Salvage] Container [Cargo Container][0k][ID: 1007183821894] contained no valuable items
22:07:13 [Salvage] Opening container [Cargo Container][1k][ID: 1007183631494]
22:07:16 [Salvage] Container [Cargo Container][1k][ID: 1007183631494] contained no valuable items
22:07:16 [Salvage] Opening container [Cargo Container][1k][ID: 1007183637696]
22:07:23 [Questor] Wallet Balance Has Not Changed in [ 17 ] minutes.
22:08:24 [Questor] Wallet Balance Has Not Changed in [ 18 ] minutes.
22:09:24 [Questor] Wallet Balance Has Not Changed in [ 19 ] minutes.
22:09:55 [Salvage] Jettisoning [1] items to make room for the more valuable loot
22:10:25 [Questor] Wallet Balance Has Not Changed in [ 20 ] minutes.

**Comment by grdk** [comment]
Ah, and in FixReloadAllIssue as I mentioned in the priv convo.

**Comment by ISeeDEDPpl** [comment]
This should be fixed. please test.
