### ISSUE TITLE
quotation symbols in mission names aren't  supported

### ISSUE THREAD

**Issue by bugc** [ISeeDEDPpl/Questor#137]
There are several missions (encountered on Lvl1) with quotation symbols in names, like U:0027, U:0022 [ ' " ]
I've defined them as blacklisted - doesn't help. Console output shows them missing xml definition. Could be, [ " ] is not allowed in filenames, but [ ' ] is also not recognized (I made such a mission_def.xml when realised no difference).

My suggestion is to check how blacklist section is parsed (if quotation marks are stored in strings) , next - mission filenames should substitute quot to something else or just omit?

Because of the issue Questor stops on 'undefined' and 'non-blacklisted' names.

Thus possible workaround could be - decline undefined \ non-blacklisted missions on regular basis in Questor. But several of these missions are worth to keep running.

**Comment by Ganondorf0** [comment]
http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

**Comment by bugc** [comment]
Granondorf, thats really interesting, no offence. I found workaround - just omit those chars in filename and within xml  as they are cuted by Questor (like there aren't such symbols in original names). Worked, 'll keep tracking.
