### ISSUE TITLE
Pop up not closing.

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#138]
Mission pop up for The right hand of Zazzmatazz does not close out.

This is the location of one of Jakerion Pahydan's outposts. Jakerion is an infamous outlaw who controls a loose-knit criminal organziation which splits itself from the Serpentis a few years ago. 'The Seven" it is called, named after the small group of comrades within the Serpentis who founded the organization.

**Comment by ISeeDEDPpl** [comment]
this should now be fixed in experimental
