### ISSUE TITLE
Aftermission salvage bug

### ISSUE THREAD

**Issue by evelover** [ISeeDEDPpl/Questor#139]
Sitting on base in salvage ship after mission The Assault and write this
17:46:05 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:06 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:07 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:08 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:09 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:10 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:11 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:12 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:13 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:14 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:15 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:16 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:17 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:18 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:19 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:20 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:21 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:22 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:23 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:24 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:25 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:26 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:27 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base
17:46:28 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base

**Comment by ISeeDEDPpl** [comment]
this should now be resolved in latest experimental.
