### ISSUE TITLE
Questor doesn't recognize already accepted Mission

### ISSUE THREAD

**Issue by Tokka72** [ISeeDEDPpl/Questor#140]
Got a disconnect while a mission was running.

After reconnect and starting questor, questor is always trying to complete the mission instead of continuing the mission. It also can't handle the popup that the mission can't be complete because it isn't finished.

19:22:33 [AgentInteraction] Start conversation [Start Mission]
19:22:33 [AgentInteraction] Waiting for conversation
19:22:35 [AgentInteraction] Replying to agent
19:22:42 [AgentInteraction] Saying [Complete Mission]
19:22:42 [AgentInteraction] Closing conversation
19:22:49 [AgentInteraction] Attempting to close Agent Window
19:22:51 [AgentInteraction] Done
19:22:52 [CombatMissionsBehavior] UnloadLoot: Begin
19:22:52 [CombatMissionsBehavior.Unloadloot] We are on mission
19:22:53 [CombatMissionsBehavior] Random start delay of [60] seconds
19:23:29 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
19:23:54 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 701 MB
19:23:55 [AgentInteraction] Start conversation [Start Mission]
19:23:55 [AgentInteraction] Waiting for conversation
19:23:56 [AgentInteraction] Replying to agent
19:24:03 [AgentInteraction] Saying [Complete Mission]
19:24:03 [AgentInteraction] Closing conversation
19:24:10 [AgentInteraction] Attempting to close Agent Window
19:24:12 [AgentInteraction] Done
and so on...

**Comment by ISeeDEDPpl** [comment]
update to latest experimental this was fixed about 24hrs ago.
