### ISSUE TITLE
Build c645c15: Problems Salvaging: Questor can't remove Bookmark

### ISSUE THREAD

**Issue by Tokka72** [ISeeDEDPpl/Questor#141]
10:50:04 [CombatMissionsBehavior.Salvage] You are unable to delete the bookmark named: [XXXX: 0842] if it is a corp bookmark you may need a role
10:50:05 [CombatMissionsBehavior.Salvage] Finished salvaging the room
10:50:05 [CombatMissionsBehavior.Salvage] salvage: no unlooted containers left on grid

Questor then hangs in a loop. After manually removing the Bookmark, which is NOT a corp bookmark questor continues properly.

The character has director roles so even corporate boomarks shouldn't be problem.

**Comment by ISeeDEDPpl** [comment]
this should now be resolved in latest experimental.
