### ISSUE TITLE
1122a03327 exp 10 July 

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#142]
After mission salvaging with multi bookmarks seem to be broken, both times was with 4 bookmarks. 

 I had it run normal with missions with only one bm but broken on the ones with more than one.

It will salvage the first bookmark and then return home to loop back to the first one with out deleting the bookmark.

sample log

19:00:20 [Cache.StackLootHangar] Stacking Item Hangar: waiting [4sec]
19:00:21 [UnloadLoot] Done
19:00:21 [CombatMissionsBehavior.Unloadloot] There are [ 4 ] more salvage bookmarks left to process
19:00:21 [CombatMissionsBehavior.UnloadLoot] The last after mission salvaging session was [60min] ago
19:00:22 [CombatMissionsBehavior.BeginAftermissionSalvaging] Next Bookmark refresh in [3min]
19:00:24 [Arm] Opening Ship Hangar: waiting [4sec]
19:00:28 [Arm] Activating salvage ship
19:00:29 [Arm] Making [sucky sucky] active
19:00:39 [Arm] Done
19:00:40 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_ShipCargo_xxx', xxxxx)]
19:00:41 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('Inventory', None)]
19:00:43 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_StationItems', 6xxxx)]
19:00:44 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_StationShips', 6xxxx)]
19:00:45 [CombatMissionsBehavior.BeginAftermissionSalvaging] Salvaging at first oldest bookmarks
19:00:45 [TravelerDestination.BookmarkDestination] Destination set to bookmark [thebookmark: 2215]
19:00:49 [Traveler] Setting destination to [a system]
19:01:12 [Traveler] Warping to [b system][16.97 AU away]
19:02:02 [Traveler] Jumping to [b system]
19:02:22 [Traveler] Warping to [c system][0 AU away]
19:02:31 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
19:02:58 [Traveler] Jumping to [c system]
19:03:18 [Traveler] Warping to [d system][52.26 AU away]
19:03:32 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
19:04:20 [Traveler] Jumping to [d system]
19:04:39 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
19:04:39 [Traveler] Warping to [a system][102.03 AU away]
19:05:40 [Questor] Wallet Balance Has Not Changed in [ 5 ] minutes.
19:05:58 [Traveler] Jumping to [a system]
19:06:17 [TravelerDestination.BookmarkDestination] Warping to bookmark [thebookmark: 2215][3.7 AU away]
19:06:40 [Questor] Wallet Balance Has Not Changed in [ 6 ] minutes.
19:07:04 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [thebookmark: 2215]
19:07:05 [CombatMissionsBehavior: Salvage] Opening Cargohold of active ship: waiting [3sec]
19:07:08 [Salvage.NavigateIntorangeOfWrecks] Approaching [a large wreck] which is [15k away]

cleaned room

19:09:05 [CombatMissionsBehavior.Salvage] Finished salvaging the room
19:09:05 [CombatMissionsBehavior.Salvage] salvage: no unlooted containers left on grid
19:09:05 [CombatMissionsBehavior.Salvage] We have salvaged all bookmarks, go to base
19:09:06 [CombatMissionsBehavior.TravelToAgentsStation] Destination: [home station]
19:09:06 [TravelerDestination.StationDestination] Destination set to [home station]
19:09:10 [Traveler] Setting destination to [home system]
19:09:11 [Traveler] Warping to [d system][ AU away]
19:09:58 [Traveler] Jumping to [d system]
19:10:18 [Traveler] Warping to [c system][ AU away]
19:11:36 [Traveler] Jumping to [c system]
19:11:57 [Traveler] Warping to [b system][ AU away]
19:13:00 [Traveler] Jumping to [b system]
19:13:19 [Traveler] Warping to [home system][0 AU away]
19:13:55 [Traveler] Jumping to [home system]
19:14:15 [TravelerDestination.StationDestination] Warp to and dock at [home station][16.97 AU away]
19:15:05 [TravelerDestination.StationDestination] Dock at [home station] which is [-1k away]
19:15:13 [TravelerDestination.StationDestination] Arrived in station
19:15:13 [CombatMissionsBehavior.TravelToAgentsStation] Arrived at destination
19:15:14 [CombatMissionsBehavior] UnloadLoot: Begin
19:15:29 [Cache.OpenAmmoHangar] Opening Item Hangar: waiting [3sec]
19:15:33 [UnloadLoot] Moving Ammo to AmmoHangar [('InventorySecondary_StationItems', 60sdfsf)][sdfsdf]
19:15:33 [UnloadLoot] Waiting for items to move to AmmoHangar
19:15:37 [Cache.StackAmmoHangar] Stacking Item Hangar: waiting [4sec]
19:15:41 [UnloadLoot] Loot was worth an estimated [sdffdsf] isk in buy-orders
19:15:42 [UnloadLoot] Stacking items in Loot Hangar: resuming in [ 3 sec ]
19:15:46 [Cache.StackLootHangar] Stacking Item Hangar: waiting [4sec]
19:15:47 [UnloadLoot] Done
19:15:47 [CombatMissionsBehavior.Unloadloot] There are [ 4 ] more salvage bookmarks left to process
19:15:47 [CombatMissionsBehavior.UnloadLoot] The last after mission salvaging session was [7min] ago
19:15:48 [CombatMissionsBehavior.BeginAftermissionSalvaging] Next Bookmark refresh in [2min]
19:15:51 [Arm] Opening Ship Hangar: waiting [3sec]
19:15:55 [Arm] Activating salvage ship
19:15:56 [Arm] Done
19:15:57 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_ShipCargo_1sfsdf', 1sfdafdafd)]
19:15:58 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('Inventory', None)]
19:15:59 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_StationItems', sdfsfsf6)]
19:16:00 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_StationShips', 6sfdsfd)]
19:16:01 [CombatMissionsBehavior.BeginAftermissionSalvaging] Salvaging at first oldest bookmarks
19:16:01 [TravelerDestination.BookmarkDestination] Destination set to bookmark [thebookmark: 2215]
19:16:04 [Traveler] Setting destination to [a system]
19:16:27 [Traveler] Warping to [b system][16.97 AU away]
19:16:59 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
19:17:14 [Traveler] Jumping to [b system]
19:17:43 [Traveler] Warping to [c system][0 AU away]
19:18:19 [Traveler] Jumping to [c system]
19:18:40 [Traveler] Warping to [d system][52.26 AU away]
19:19:42 [Traveler] Jumping to [d system]
19:20:02 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
19:20:02 [Traveler] Warping to [a system][102.03 AU away]
19:21:03 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
19:21:22 [Traveler] Jumping to [a system]
19:21:42 [TravelerDestination.BookmarkDestination] Warping to bookmark [thebookmark: 2215][3.7 AU away]
19:22:03 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
19:22:29 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [thebookmark: 2215]
19:22:30 [CombatMissionsBehavior: Salvage] Opening Cargohold of active ship: waiting [4sec]
19:22:34 [CombatMissionsBehavior.Salvage] Finished salvaging the room
19:22:34 [CombatMissionsBehavior.Salvage] salvage: no unlooted containers left on grid
19:22:34 [CombatMissionsBehavior.Salvage] We have salvaged all bookmarks, go to base
19:22:35 [CombatMissionsBehavior.TravelToAgentsStation] Destination: [home station]
19:22:35 [TravelerDestination.StationDestination] Destination set to [home station]
19:22:40 [Traveler] Setting destination to [home system]
19:22:41 [Traveler] Warping to [d system][3.7 AU away]
19:23:29 [Traveler] Jumping to [d system]
19:23:49 [Traveler] Warping to [c system][102.03 AU away]

**Comment by ISeeDEDPpl** [comment]
part of this has been fixed, probably not all of it. Ill look at generating another log with an aftermission salvage toon tomorrow and debugging this more. I cant easily proceed without a log... if one were to magically appear it would speed the progress toward a fix.

**Comment by ISeeDEDPpl** [comment]
ok, plese recompile from latest experimental: and attempt to reproduce...

at least: b221d9b206befe3a388058796ea5608ffbc19fa5
https://github.com/ISeeDEDPpl/Questor/commits/experimental

**Comment by ISeeDEDPpl** [comment]
this is resolved as far as I can tell.
