### ISSUE TITLE
[Settings] WARNING! unable to find [C:\Program Files\InnerSpace\.NET Programs\.xml] loading default generic, and likely incorrect, settings: WARNING!

### ISSUE THREAD

**Issue by xelj** [ISeeDEDPpl/Questor#144]
09:22:13 [Settings] WARNING! unable to find [C:\Program Files\InnerSpace.NET Programs.xml] loading default generic, and likely incorrect, settings: WARNING!
I get this messages few times in different VM's and random situation. After this Q close eve. This message not redacted, looks like that Q lost character name.

**Comment by ISeeDEDPpl** [comment]
its eve that lost the charactername... this is happening on disconnects seemingly. the client restarts normally. this is not a bug that needs fixing from what I can tell.

**Comment by xelj** [comment]
The problem is that the client is not restarted.
