### ISSUE TITLE
general freight container bugged

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#147]
it get stuck in "unload loot" if use general freight container

it find the continer, but get stuck when it do unload loot

19:12:49 [CombatMissionsBehavior.TravelToAgentsStation] Arrived at destination
19:12:51 [CombatMissionsBehavior] UnloadLoot: Begin
19:13:08 [Cache.OpenAmmoHangar] Opening Item Hangar: waiting [5sec]
19:13:15 [UnloadLoot] Moving Ammo to AmmoHangar [('InventorySecondary_StationItems', 60004027)][16672750]
19:13:15 [UnloadLoot] Waiting for items to move to AmmoHangar
19:13:20 [Cache.StackAmmoHangar] Stacking Item Hangar: waiting [3sec]
19:13:23 [UnloadLoot] Loot was worth an estimated [2.124.560] isk in buy-orders
19:14:54 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
19:15:54 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
19:16:55 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.

**Comment by Chryst** [comment]
I have see if i do select all and move all the items of the noctis manually inside the general freight container it continue work perfect.

I have simply move all the items in the noctis cargo in the general freight container.

**Comment by dedo1911** [comment]
Today i've tried the container for the first time and had the same problem :(

Need a fix

**Comment by Chryst** [comment]
Up

**Comment by dedo1911** [comment]
I've just replaced the UnloadLoot.cs from a previous version, before the corp hangar fix and it works perfectly with the latest experimental (+ that old unloadloot.cs).

I'll work on the next days on a merge with the latest UnloadLoot and that old one.

**Comment by Chryst** [comment]
I have test it and is working using the old unloadloot.cs

**Comment by ISeeDEDPpl** [comment]
this issue has been resolved in current experimental.
