### ISSUE TITLE
out of ammo stucked in mission with marauder

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#148]
I have find today my marauder stucked in mission in out of ammo, 

It was in mission from about 254 mins and was out of ammo.

Possible he have lost all ammo for fire a frigate and missing it.

**Comment by Pluckyduck** [comment]
so how about that log

**Comment by ISeeDEDPpl** [comment]
yes, a console log would be helpful.

**Comment by dedo1911** [comment]
If you restart the bot while in space and use GoToMission, it can't use the drones anymore. You have to come back in station and start it with delayedstart. So drones works again.
That's what you need to fix

**Comment by Chryst** [comment]
Is happend only 1 time in 1 month so is a very rare problem but i have write it.

It simply continue spam out of ammo. 254 minutes spamming out of ammo with 6-7 enemies continue firing it.

Becouse i use cap stable fit. So it was stay 254 minutes spamming out of ammo.

In your setting not cap stable i think it go away due end of cap.

Is simply only 1 line of spamming writing out of ammo.

Next time i copy past the console, but is a very very rare error.

I thinkbecous he have fire all the ammo in a frigate outside drone range missing it continuously.

**Comment by xelj** [comment]
same problem

**Comment by ISeeDEDPpl** [comment]
Dedo1911, the issue you mentioned has been fixed in current experimental, and is a different issue from the outofammo problem.

**Comment by ISeeDEDPpl** [comment]
I would like logs of this outofammo problem. all console messages are logged to daily logs in /log/nameoftoon/console/<dalilyloghere>

if you have experienced this issue, get me a console log snippit please.

**Comment by Chryst** [comment]
VARGUR SPAM :)

1:10:44 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:10:52 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:11:03 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:11:13 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:11:23 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:11:31 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:11:40 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276589][8k away]
01:11:46 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276589][8k away]
01:11:52 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:11:58 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276588][8k away]
01:12:06 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:12:10 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:12:18 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:12:29 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:12:39 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:12:49 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
01:12:57 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]

and after an hour with that spam... he start aother spam....

02:12:19 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
02:12:28 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
02:12:36 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
02:12:46 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
02:12:56 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
02:13:05 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
02:13:13 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
02:13:23 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
02:13:27 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276589][8k away]
02:13:35 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276589][8k away]
02:13:44 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276589][8k away]
02:13:50 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276590][8k away]
02:14:00 [Combat] Activating weapon [1] on [Guristas Kyoukan][ID: 9000000000000276588][8k away]
02:14:06 [Combat] Reloading [1] with [Fusion L][49][TypeID: 199]
02:14:07 [Combat] Targeting high value target [Rachen Mysuna][ID:9000000000000276586]{1} [50k away]
02:14:08 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:10 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:12 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:14 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:16 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:18 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:20 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:23 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:25 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:27 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:29 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:31 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]
02:14:33 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [2]

**Comment by ISeeDEDPpl** [comment]
What branch and git revision? I cant seem to reproduce this by bringing very little ammo and letting it run out... every time I do it switches to combat.outofammo and then switches to combatmissionbehavior.gotobase as it is supposed to. 

I am testing with current experimental

**Comment by Chryst** [comment]
Is a build of some days ago, if now it work well to know, so we can close the issue.

Can you please try fix the general freight container so i restart use the last build ? I'm using a build of some days ago.

I have try fix it myselft but i'm unable to fix it.

**Comment by Chryst** [comment]
If you want check in the last gano unstable the general freight container and in your past version it was working. Don't know why it don't work now with the actual version :(
