### ISSUE TITLE
full cargo, then stuck

### ISSUE THREAD

**Issue by dedo1911** [ISeeDEDPpl/Questor#149]
While running Enemies Aboud 5/5 in Vargur, the cargo has been fully filled while salvaging and it left some containers in space.
It was stuck watching those containers and wasnt able to grab those assets because of full cargo.

It had to come back to station and empty the cargo instead of floating in space....

**Comment by ISeeDEDPpl** [comment]
log? I dont see why this would happen. console logs will at least give me a clue.
