### ISSUE TITLE
Questorstatistic

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#15]
still not read date to the log

**Comment by ISeeDEDPpl** [comment]
yeah, questor statistics is looking in the wrong folder for the logs. I have some changes in my local tree that are almost complete that will solve this.

**Comment by marivx** [comment]
Need to save log file with .log extension Pe questorstatistics not read the date

**Comment by ISeeDEDPpl** [comment]
no, questorstatistics needs to read the csv file =) 

I'll look into the date issue once it is reading the logs from the correct places.

**Comment by marivx** [comment]
if you change this file in .log  it work fine
