### ISSUE TITLE
blitz and diz bug

### ISSUE THREAD

**Issue by xelj** [ISeeDEDPpl/Questor#151]
Several times during blitz thrown  diz after the mission was completed and the ship beginning warp to base. After that, Q immediately passed to the state CompleteMission, not trying to kill a scramblers.
3 sec between "Starting Action.Done" and "Start Conversation [Complete Mission]"

17:24:25 [CombatMissionCtrl.Kill [target: Shadow] [ignoreattackers: true]] All targets killed Shadow
17:24:25 [CombatMissionCtrl] Finished Action.Kill [target: Shadow] [ignoreattackers: true]
17:24:25 [CombatMissionCtrl] Starting Action.Done
17:24:26 [Combat] Activating weapon [1] on [Mercenary Wingman][ID: 9000000000000026396][42k away]
17:24:28 [AgentInteraction] Start Conversation [Complete Mission]
17:26:01 [Panic] Start panicking, shield [68%] below [70%] S[68%] A[100%] C[42%] below [15%]
17:26:05 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
17:27:05 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
17:28:05 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
17:29:05 [Questor] Wallet Balance Has Not Changed in [ 5 ] minutes.

**Comment by ISeeDEDPpl** [comment]
That sounds like a manual intervention issue, did you have the questor window selected and use the mouse wheel to change the state by accident? (I thought I had fixed that damn mousewheel problem though)...

Can you add 
`
<debugTraveler>true</debugTraveler>
<debugGotoBase>true<debugGotoBase>
`
to your characters settings xml file? They add a bit of verbosity to the gotobase process. 

Has this happened more than once? If this is repeatable it seems to be an issue with traveler thinking it is at the destination when it is not. I sill need the debug logs noted above before we can fix this particular issue if its repeatable.

**Comment by xelj** [comment]
I am absolutely sure that this is not due to manual intervention.

During the last 2 weeks it happened 3 times from 12 bots. I'll try turn debug, but I do not know whether this will happen again. To fix, I tried to change in CombatMissionBehavior.cs

``` C
    //if (_States.CurrentTravelerState == TravelerState.AtDestination)
      if ((_States.CurrentTravelerState == TravelerState.AtDestination)  && (!Cache.Instance.InSpace))
```

**Comment by Chryst** [comment]
Are you sure is not your mission xml ?

**Comment by xelj** [comment]
yes
Recon2

``` C
<mission>
  <pockets>
  <pocket id="0">
      <actions>
       <action name="Activate">
          <parameter name="target" value="Acceleration Gate" />
        </action>
      </actions>
    </pocket>
    <pocket id="1">
      <actions>
        <action name="MoveTo">
          <parameter name="target" value="Acceleration Gate (Locked Down)" />
        </action>
        <action name="Done" />
      </actions>
    </pocket>
  </pockets>
</mission>
```

Stop The Thief

``` C
<mission>
<bring>Reports</bring>
  <pockets>
    <pocket id="0">
      <damagetype>Thermal</damagetype>
      <actions>
        <action name="Kill">
            <parameter name="Target" value="Mercenary Overlord" />
            <parameter name="IgnoreAttackers" value="true" />
        </action>
        <action name="Kill">
          <parameter name="Target" value="Shadow" />
          <parameter name="IgnoreAttackers" value="true" />
        </action>
        <action name="Done" />
      </actions>
    </pocket>
  </pockets>
</mission>
```

**Comment by ISeeDEDPpl** [comment]
very odd. you are using current (within the last few days) experimental I assume...

**Comment by xelj** [comment]
experimental Jul 17, 2012. But the problem was and before, at least 10 days ago

**Comment by xelj** [comment]
While that is not repeated, it seems that the fix has helped.
