### ISSUE TITLE
missionammo -> Out of Ammo

### ISSUE THREAD

**Issue by xelj** [ISeeDEDPpl/Questor#152]
When we have missionammo in mission.xml. Q takes right ammo, but when arrived at the bookmark enter in outofammo state. 
But if you take the standard type of ammo from charname.xml, then Q uses ammo specified in mission.xml, without going into a state of outofammo.

For example: in mission.xml we have 

``` C
<missionammo> 
 <ammo typeId="27435" damageType="EM" range="95000" quantity="500" /> //caldari navy mjolnir
</missionammo>
```

in charname.xml

``` C
<ammoType typeId="24509" damageType="EM"       range="105000" quantity="3000" /> //fury mjolnir
```

and mission against Amarr (EM)
Q takes 500 units typeId="27435"(caldari navy mjolnir) in arm phase and after that:

15:43:57 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [Encounter (Deadspace) - xxx]
15:43:58 [Combat] Out of Ammo!
15:43:59 [CombatMissionsBehavior.TravelToAgentsStation] Destination: [xxx]
15:43:59 [TravelerDestination.StationDestination] Destination set to [xxx]
15:44:02 [Traveler] Setting destination to [xxx]
15:44:04 [Traveler] Warping to [xxx][7.01 AU away]
15:44:05 [debug ReloadAll] Entering reloadAll function (again) - it iterates through all weapon stacks [2]
15:44:05 [Combat] ReloadNormalAmmo: We have ammo loaded that does not have a full reload available, checking cargo for other ammo
15:44:05 [Combat] ReloadNormalAmmo: unable to find any alternate ammo in your cargo

But if we manually take 10 units typeId="24509" (fury mjolnir) Q dont enter into outofammo and use right type ammo -- caldari navy mjolnir

**Comment by ISeeDEDPpl** [comment]
If I am reading this correctly there is an issue with missionammo when the mission ammo being added doesn't change the damage type. (Which is a very odd corner case by the way, why the hell would you do this?)

**Comment by xelj** [comment]
On some missions, a lot of small ships, and with navy missiles easier and faster to kill them.

**Comment by ISeeDEDPpl** [comment]
Personally I use faction ammo on all missions but I am nuts. this may be fixable but it unfortunately low on the list. the issue as stated above is that the damage type doesn't change so it causes problems. I'll see if I can find an elegant solution

**Comment by ISeeDEDPpl** [comment]
this should be resolved in current experimental. please confirm
