### ISSUE TITLE
reload on 'activate gate' IS not working

### ISSUE THREAD

**Issue by bugc** [ISeeDEDPpl/Questor#153]
Using 2 last builds (after switched from FixAmmo to Experimental fork) seems Q lost ammo reload on gate activation.

// UPD
Ok, let me clear my point. In console log I see: "07:44:40 [CombatMissionCtrl] Activate: [Acceleration Gate] Move to next pocket after reload command and change state to 'NextPocket'" Sure, mustn't trust everything. But the meaning is still reasonable - to reload before next gate is good for first kills (scramblers f.i)

Fact is - Q does not reload before warp. Neither it reloads when ECM jammed. Take these as wishlist.

**Comment by ISeeDEDPpl** [comment]
this has been fixed for a long time now.
