### ISSUE TITLE
grouped weapon sticks for more than cycle

### ISSUE THREAD

**Issue by bugc** [ISeeDEDPpl/Questor#154]
I'm using groups of HM to safe some ammo, sometime it works fine - 2 groups fire than in half-cycle fires 3d group + TP, but some times (especially after group was reloaded) it become stuck for _several_ cycles. This causes DPS loss and ammo expenses.
need workaround or fix

**Comment by ISeeDEDPpl** [comment]
need console logs AND game logs for the same timestamps pls.

**Comment by bugc** [comment]
ok, check please my debug settings if nothing missed for your interest
  debugStates>false
  debugPerformance>false
  detailedCurrentTargetHealthLogging>false
  debugLootWrecks>false
  debugActivateWeapons>false
  debugreloadorChangeAmmo>false
  debugStatistics>false
  debugGotobase>false
  debugIdle>false
  debugAutoStart>false
  debugDecline>false
  debugHangars>false
  debugLogging>false
  debugSalvage>false
  debugUI>false
  debugAttachVSDebugger>false
  useInnerspace>true
  debugAutostart>true
  debugIdle>true

**Comment by bugc** [comment]
here they are 
https://docs.google.com/open?id=0B6as88qHJJXlUGpzWW1VenFSMDg - console
https://docs.google.com/open?id=0B6as88qHJJXlTnhKcVpabUNaZjg - combat
http://youtu.be/GUQNF8KtgJ4 - video for visual timing. first 20 sec and about 1:20 positions; seems it happens after reload, misses 2-3 cycles. When I encountered this situation delays were longer by my opinion (was a bit late, could be wrong).

**Comment by ISeeDEDPpl** [comment]
`
<debugActivateWeapons>true</debugActivateWeapons>
<debugreloadorChangeAmmo>true</debugreloadorChangeAmmo>
`
would both be nice. I haven't yet looked at the logs above. Ill take a look in the next few hrs.

**Comment by bugc** [comment]
When I did record again I come to conclusion there is no real issue. The delay could happen for 2 or 3 cycles after group was reloaded and another group started reloading with a little delay just after first. in this case first group is waiting second gropu's readiness. Perhaps it is not as real is but always works. In rare conditions 2 groups are missing cycles when one continues from time before those 2 were reloading. After my investigation I think that's fine, false alarm.

BTW you can watch vid from above. If needed I'll do another record with logs.
