### ISSUE TITLE
We do not have Loyalty points with current agent yet, still -1

### ISSUE THREAD

**Issue by tavotevas** [ISeeDEDPpl/Questor#155]
This is what me and my friend are getting when Questor should be talking to agent to take a mission. This may happen when questor just started, right after completing a mission, after working fine for n hours. I can manually fix it by changing Behavior State to Delayed start or Start (i believe anything else would work if i took the mission manually). 

16:49:30 [CombatMissionsBehavior.Salvage] salvage: no unlooted containers left on grid
16:49:30 [CombatMissionsBehavior.Salvage] We have salvaged all bookmarks, go to base
16:49:31 [CombatMissionsBehavior.TravelToAgentsStation] Destination: [Simela IV - Moon 7 - Sisters of EVE Academy]
16:49:31 [TravelerDestination.StationDestination] Destination set to [Simela IV - Moon 7 - Sisters of EVE Academy]
16:49:35 [Traveler] Setting destination to [Simela]
16:49:36 [Traveler] Warping to [Simela][36.53 AU away]
16:50:31 [Traveler] Jumping to [Simela]
16:50:49 [TravelerDestination.StationDestination] Warp to and dock at [Simela IV - Moon 7 - Sisters of EVE Academy][51.92 AU away]
16:51:47 [TravelerDestination.StationDestination] Dock at [Simela IV - Moon 7 - Sisters of EVE Academy] which is [1k away]
16:51:57 [TravelerDestination.StationDestination] Arrived in station
16:51:58 [CombatMissionsBehavior.TravelToAgentsStation] Arrived at destination
16:51:58 [CombatMissionsBehavior] UnloadLoot: Begin
16:52:18 [Cache.OpenAmmoHangar] Opening Item Hangar: waiting [5sec]
16:52:24 [UnloadLoot] Moving Ammo to AmmoHangar [('InventorySecondary_StationItems', 60012646)][16672750]
16:52:24 [UnloadLoot] Waiting for items to move to AmmoHangar
16:52:28 [Cache.StackAmmoHangar] Stacking Item Hangar: waiting [3sec]
16:52:31 [UnloadLoot] Loot was worth an estimated [483,497] isk in buy-orders
16:52:32 [UnloadLoot] Stacking items in Loot Hangar: resuming in [ 4 sec ]
16:52:36 [Cache.StackLootHangar] Stacking Item Hangar: waiting [4sec]
16:52:37 [UnloadLoot] Done
16:52:37 [CombatMissionsBehavior.BeginAftermissionSalvaging] Salvaging at first oldest bookmarks
16:52:37 [CombatMissionsBehavior.Unloadloot] No more salvaging bookmarks. Setting FinishedSalvaging Update.
16:52:38 [Questor] Checking: Current time [07/22/2012 16:52:38] StopTimeSpecified [True] StopTime [ 7/23/2012 2:11:36 AM] ManualStopTime = 7/23/2012 2:11:35 AM
16:52:39 [Questor] Start Mission Behavior
16:52:40 [Statistics] WriteMissionStatistics: We do not have loyalty points with the current agent yet, still -1
16:52:41 [Statistics] Printing All Statistics Related Variables to the console log:
16:52:41 [Statistics] Mission Name: [The Missing Convoy]
16:52:41 [Statistics] Total Missions completed this session: [1]
16:52:41 [Statistics] StartedMission: [ 1/1/0001 12:00:00 AM]
16:52:41 [Statistics] FinishedMission: [ 1/1/0001 12:00:00 AM]
16:52:41 [Statistics] StartedSalvaging: [ 7/22/2012 4:43:02 PM]
16:52:41 [Statistics] FinishedSalvaging: [ 7/22/2012 4:52:37 PM]
16:52:41 [Statistics] Wealth before mission: [ 10174134.909]
16:52:41 [Statistics] Wealth after mission: [ 11665390.429]
16:52:41 [Statistics] Value of Loot from the mission: [483497]
16:52:41 [Statistics] Total LP after mission: [6249]
16:52:41 [Statistics] Total LP before mission: [-1]
16:52:41 [Statistics] LostDrones: [0]
16:52:41 [Statistics] DroneRecalls: [5]
16:52:41 [Statistics] AmmoConsumption: [462]
16:52:41 [Statistics] AmmoValue: [462]
16:52:41 [Statistics] Panic Attempts: [0]
16:52:41 [Statistics] Lowest Shield %: [100]
16:52:41 [Statistics] Lowest Armor %: [100]
16:52:41 [Statistics] Lowest Capacitor %: [100]
16:52:41 [Statistics] Repair Cycle Time: [0]
16:52:41 [Statistics] MissionXMLIsAvailable: [True]
16:52:41 [Statistics] MissionCompletionerrors: [0]
16:52:41 [Statistics] the stats below may not yet be correct and need some TLC
16:52:41 [Statistics] Time Spent IN Mission: [0sec]
16:52:41 [Statistics] Time Spent In Range: [0]
16:52:41 [Statistics] Time Spent Out of Range: [0]
16:52:41 [Statistics] writing mission log1 to [ C:\Program Files\InnerSpace.NET Programs\log_MyEVECharacterNameRedacted_\missionstats_MyEVECharacterNameRedacted_.Statistics.log ]
16:52:41 [Statistics] writing mission log2 to [ C:\Program Files\InnerSpace.NET Programs\log_MyEVECharacterNameRedacted_\missionstats_MyEVECharacterNameRedacted_.DatedStatistics.log ]
16:52:42 [Cache] Agent
16:52:42 [Statistics] writing mission log3 to [ C:\Program Files\InnerSpace.NET Programs\log_MyEVECharacterNameRedacted_\missionstats_MyEVECharacterNameRedacted_.CustomDatedStatistics.csv ]
16:52:42 [Cache] Agent

**Comment by ISeeDEDPpl** [comment]
I clarified the message you get when that happens and made sure that it can only iterate 20x before giving up. the log you show here it only had to retry once though. The 2nd try it completed successfully and continued. at what point does it hang? this log doesn't actually show a problem I can see, Is this a good example of a problem log? when this occurs it just sits in station? It would be nice to have a log of this issue with 

`
<debugAutostart>true</debugAutostart> 
<debugIdle>true<debugIdle>
`
it would also be nice to know what 'state' everything is in or changing between in the QuestorUI states tab.

**Comment by ISeeDEDPpl** [comment]
FYI:  I cant find "[Cache] Agent" in the code or my console logs at all. 
Did you possibly hand edit those lines?

**Comment by tavotevas** [comment]
16:52:39 [Questor] Start Mission Behavior
 16:52:40 [Statistics] WriteMissionStatistics: We do not have loyalty points with the current agent yet, still -1   <-- This where it stops and does absolutelly nothing. No i did not edit these lines, the debug thing will take some time, i dont know when my error will appear again.  

What does that line mean anyway?

**Comment by tavotevas** [comment]
its not the full log if thats what you mean

**Comment by tavotevas** [comment]
Oh yeah, now that i read this all i must add, that line appears right when the agent window is supposed to open

**Comment by tavotevas** [comment]
my bad, the problem is that the bot does not believe the autostart button, it just finishes the mission. We thought its the lines above fault cuz it was red lol. So, after making all the logs the questor just remains idle. It does not enter error state or something

**Comment by xelj** [comment]
> > FYI: I cant find "[Cache] Agent" in the code or my console logs at all.

cache.cs find Logging.Log("Cache", "Agent",

**Comment by ISeeDEDPpl** [comment]
xelj, notice that line has more logging there. It is odd that the logging line mentioned ONLY has "[Cache] Agent" with nothing following it. Nothing I can find in questor would do that, so it is odd.

**Comment by tavotevas** [comment]
problem solved. Looks like my friend had torrents up all the time

**Comment by tavotevas** [comment]
.
