### ISSUE TITLE
restart after scheduled start

### ISSUE THREAD

**Issue by dedo1911** [ISeeDEDPpl/Questor#156]
I've set the scheduler to start @ 22:00 then stop @ 12:00.
Sometimes it happens that it have to close eve and relog.
After the client restart it's stuck at the logon screen and in console it says that will start in more than 1200 minuts (so the next day).

**Comment by ISeeDEDPpl** [comment]
break this up into 2 or 3 different schedules covering the same time period and you'll have less of a problem. see the example schedules.xml in the output directory for syntax.
