### ISSUE TITLE
Questor Won't Start

### ISSUE THREAD

**Issue by jakesmurf** [ISeeDEDPpl/Questor#158]
When I try to start questor or even valuedump etc from an EVE IS window, the window locks and does not unfreeze.  

When I try to start questor from the IS console I get the below included errors.  

I've rebuilt questor a million times, done a fresh EVE and Innerspace install several times, reinstalled dotnet, python, the works.  

The only other information I can provide is while debugging the csproj I get errors on several instances of Cache.Whatever.  I'm not sure if this is normal - I don't get any build errors while building though.  I've tried using the provided bin as well as manual builds.  

Exception during event execution: System.TypeInitializationException: The type initializer fo
'.' threw an exception. ---> System.AccessViolationException: Attempted to read or write
protected memory. This is often an indication that other memory is corrupt.

   at ..()

   at ..( )

   at ...ctor( , IntPtr , Boolean )

   at ...cctor()

   --- End of inner exception stack trace ---

   at ...ctor(Boolean )

   at ..(DirectEve , Object , LSEventArgs )

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32

**Comment by ISeeDEDPpl** [comment]
1st thing, you didnt copy the *.pdb files to the .net directory so the exception above does not have the exact location of the error. 

2, it sounds like you either arent building with the same version of directeve as you are attempting to run questor with or you are running a fork.branch that is unsupported. 

have you tried downloading questor from: https://github.com/ISeeDEDPpl/Questor/tree/experimental
direct link: https://github.com/ISeeDEDPpl/Questor/zipball/experimental

and running #compile#.bat and when that finishes run #transfertolive#.bat and then start eve with innerspace and in the innerspace console type "dotnet questor questor"

if that works you'll want to configure the scheduler next.

**Comment by jakesmurf** [comment]
I recopied the compiled .pdb's to the directory and I'm getting the exact same error in innerspace still.  

I deleted everything from the .NET Programs folder as well as the folder I compile in.  I downloaded your latest release and compiled with the DE version that was included in the .ZIP.  I also tried deleting everything again and compiling with DaTeach's latest DE straight from the license website.  Still no dice.  

I've tried using both of the .bats and I'm still getting this error.  Scheduler is already configured.  I'd been running questor before but took a couple months off and now I can't get it to work.  Not sure what's changed but I had no problems compiling many times before.  

Thanks a bunch for your help by the way, just hope I can figure out what is causing this error.  

If it helps I'm getting the error on two machines, both are Vista 64 systems - but I have successfully compiled a working version on a Windows 7 platform.  I tried copying that .NET programs directory over directly and it doesn't work.  It's got to be something I have going on locally but I have no idea what it could be.

**Comment by ISeeDEDPpl** [comment]
well, if you are getting the error with #compile#.bat and #transfertolive#.bat assume there is something wrong with your config files. Can you re-merge the example settings.xml from the output directory into your characters settings xml file? 

you _really_ should be getting line numbers int eh exception if its questor crashing and you have the *.pdb files in .net programs.

**Comment by jakesmurf** [comment]
I get the error when trying to run questor from the Innerspace console.  I also get the same error when I try to run valuedump or (I'm pretty sure) all the other executables except QuestorSettings.exe.  

I just can't understand why it won't work on two PCs but it works on the other.  I tried copying the entire innerspace folder, questor executables, dotnet installer, etc from the working PC and I'm still getting the same thing.  Is there anything in the world outside of questor that questor could get a read/write error from besides EVE/Innerspace/Dotnet/Questor?  I really appreciate all your suggestions by the way.  

When I try to debug in Visual C# it gives me a TypeInitilization error on this line...

private DateTime _lastSessionChange = Cache.Instance.StartTime;

I think it also throws a few similar errors in other things that call Cache.Something.  Could this information help?

**Comment by ISeeDEDPpl** [comment]
without more info this issue cannot more forward. If you have it working on 2 other PCs then Id say the problem is localized to a configuration issue on the PC where it is failing. 

Is anyone else seeing this issue happen to them?
