### ISSUE TITLE
ValueDump in QM

### ISSUE THREAD

**Issue by dedo1911** [ISeeDEDPpl/Questor#159]
I just found ValueDump as i was just using Q for mission running.
It's really useful, but i found a problem while running it from QuestorManager.
I've figured out to create a task which allows me to:
- Goto a station i choose
- Move everything from hangar to cargo
- Goto Jita 4-4
- Sell it with valuedump+refining option

Well, it works till it have to sell stuff. It just dont start the task with valuedump.
I've opened valuedump with "dotnet valuedump" and the standalone version of it works perfectly.
It's possible to have it merged with questor manager to create tasks like that? :)

**Comment by ISeeDEDPpl** [comment]
yes, Ill look into that tonight / tomorrow.

**Comment by dedo1911** [comment]
Has this been fixed?

**Comment by ISeeDEDPpl** [comment]
fixed in the Valuedump branch
