### ISSUE TITLE
ReloadNormalAmmo Bug

### ISSUE THREAD

**Issue by test1234567xx** [ISeeDEDPpl/Questor#161]
Hello,
in mission for example World Collide i have in World Collide.xml:

damagetypes>
damagetype>EM</damagetype>
damagetype>Explosive</damagetype>
/damagetypes>

in my char.xml i have:

ammoTypes>
ammoType typeId="207" damageType="EM"        range="70000" quantity="5500" />
ammoType typeId="209" damageType="Kinetic"   range="70000" quantity="5500" />
ammoType typeId="209" damageType="Thermal"   range="70000" quantity="5500" />
ammoType typeId="209"  damageType="Explosive" range="70000" quantity="5500" />
ammoType typeId="2629"  damageType="Explosive" range="70000" quantity="3500" />
/ammoTypes>

Q take in cargo 2 kind of missiles.... EM and Kinetic but i recieve:

15:07:47 [Combat] ReloadNormalAmmo: We have ammo loaded that does not have a full reload available, checking cargo for other ammo
15:07:47 [Combat] ReloadNormalAmmo: found [5780] units of [Scourge Heavy Missile] changed DamageType to [Kinetic]

But Q continue to reload EM missiles and fire them....

edit: if i manually load kinetic missiles and fire them, then Q is able to reload.

**Comment by test1234567xx** [comment]
i want to add that the problem seems to be only in missions with 2 kind of pirates... ie. Sansha (EM) and A. Cartel (Explosive).

Q should switch to Kinetic missiles when arrive in Cartel room, but Q continue to reload EM missiles and fire them also against Cartel.

in missions with only 1 typo of missiles in cargo there is no problem.
o7

**Comment by ISeeDEDPpl** [comment]
this should be resolved in current experimental. please confirm.

**Comment by test1234567xx** [comment]
now testing :) thanks!

**Comment by test1234567xx** [comment]
in worlds collide.... same setup as the first post....

now Q only uses kinetic missile instead of EM. but this time no messages appeared on the console log.

**Comment by test1234567xx** [comment]
update: if launchers are empty Q have not problems switching ammo correctly.

maybe should be usefull before every mission and entering in every new room on a mission first unload all ammos from launchers and then load the correct ones?

**Comment by ISeeDEDPpl** [comment]
yeah, unfortunately questor (Directeve) cannot unload ammo from guns afaik.

**Comment by ISeeDEDPpl** [comment]
that was why the previous code tried to 'guess' which ammo (and damage type)  to use based on what was in your cargo if the ammo in your guns didnt have enough in the cargo to reload.

**Comment by Chryst** [comment]
That problem is already solved. I think you can close it.
