### ISSUE TITLE
Marauder stucked infinity

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#163]
WORLD COLLIDE drones on core adrmiral and turrets on guristas veteran

VENGEANCE drones in rachen misuna and turrests on guristas kyoukan

It continue stay hours in that situation... Until he finish all the ammo...

So i continue have the drones on the battleship and the turrets on the frigate, and the situation don't change.

So i continue miss all the fire on the frigate, and the drones can't kill the battleship.

So i'm stucked forever. That is the opposite of what it need to do.

And in char xml i have turrets fire on frigate false, and drones that need kill only the frigate....

**Comment by ISeeDEDPpl** [comment]
"And in char xml i have turrets fire on frigate false, and drones that need kill only the frigate...."
yeah, that setting never did what it was intended to do and was poorly thought out in general. if we truely want that setting to do what it intends to do it would have to be done at target selection time and it is currently not being done there.

the best thing we could do would be to add a 'timeout' to a target if it isnt killed in say... 5-10 min (configurable?). we should ignore that target for 2 min allowing other things to be targeted / killed instead and then un-ignore after the 2min. This should solve most of the corner cases where the targeting choices werent perfect.

**Comment by Chryst** [comment]
I think the fastest and easyest solution is if we have drone that need fight only the frigate, they need fight only the frigate and not the other ships. That resolve the issue for sure at 100 %.

I get stucked becouse they continue stay on battleship, and if they are setted as frigate only, they need fight and go out only if there are frigate. If there aren't they need stay docked inside the ship.

I think that is the best solution and is more easy to do in programming.

**Comment by Chryst** [comment]
Solved
