### ISSUE TITLE
[Combat] Out of Ammo! - The Rogue Slave Trader

### ISSUE THREAD

**Issue by ecommercehq** [ISeeDEDPpl/Questor#164]
Seems like my chars are getting stuck on this mission after my latest compile of the fork.

Accepts mission just fine, warps in starts to kill ships then says out of amo, returns, loops through mission stuff, goes back then says the same and starts the process over again.

Using speed tank tengu, plenty of amo in cargo and fully loaded launchers.

**Comment by xelj** [comment]
Do you use special ammo (missionammo in mission.xml) for this mission?

**Comment by Tokka72** [comment]
I usually let questor decline the mission because i recognized that questor jets the ammo to scoop the prisoners if there isn't enough free cargo. After that the ammo problems and the above mentioned loop occurs.

**Comment by ISeeDEDPpl** [comment]
this should be resolved in latest experimental... 

the "fix" that caused this issue was worse than the problem it was meant to resolve.
