### ISSUE TITLE
Request: if shield tanked, stop when armor is below threshold

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#165]
If you are a shield tanker and you panic and go below minimum armor threshold, it would be best to error out on dock.  This will keep it from doing the forever loop of panic docking.

**Comment by ISeeDEDPpl** [comment]
The closest we can come to this is to set a flag when in space and armor or hull is below a certain percentage to:

1) disable autostart
2) gotobase
3) shutdown questor and/or go into error

While docked eve does not calculate hull, armor, shields the same as when we are in space and thus it gets fairly confusing to try to us the docked hull / armor / shield percentages for anything remotely useful. We can certainly keep it from "looping" more than once though if we permanetly 'error' if below a certain armor percentage or a certain hull percentage. I'll look into adding something.

**Comment by Pluckyduck** [comment]
I would say to flag it to error so that it would stop and it would require you to find out what is wrong.  The gotobase and disabling autostart would be easy to over look the real problem and just restart.

**Comment by ISeeDEDPpl** [comment]
note: if you disable autostart and call CloseQuestor() questor (and eve) will close and not restart via the uplink. (of course if you restart it via some external means like a windows scheduled task then all bets are off). 

it might be best to disable autostart, gotobase and go into QuestorState.Error AND pause questor so that it will not check for or care about the walletbalancetimer stuff.

**Comment by Pluckyduck** [comment]
ISDP, i was not going to ask for something that over the top but i can see the places it would not be over the top.  Thank you.

**Comment by ISeeDEDPpl** [comment]
with the repairshop being integrated I dont think we need to do anything special here. 
(unless ppl want to be able to mission out of places where their is no station repair?! surely that has to be rare)

**Comment by Pluckyduck** [comment]
thanks, ISDP, will test first chance i get.
