### ISSUE TITLE
check if the mission is finished first of go to salvage

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#17]
need this fix because if you crash and questor just have some  bm for salvage,  when relog him come back to base bring the salvager ship and go to the mission and PUFFFFF

**Comment by ISeeDEDPpl** [comment]
if (_combat.State != CombatState.OutOfAmmo &&                          //if we arent out of ammo  
Settings.Instance.AfterMissionSalvaging &&                                     //if your settings have after mission salvaging on
Cache.Instance.BookmarksByLabel(Settings.Instance.BookmarkPrefix + " ").Count > 0 &&  //if we have salvage bookmarks
(Cache.Instance.mission == null || Cache.Instance.mission.State == (int)MissionState.Offered)) ..if we dont have a mission at all or if the mission we have is in the offered state (not the accepted state)

This should cover everything....
Does this maybe not cover storyline missions?! I'll look into fixing that corner case...

**Comment by marivx** [comment]
not work :(

18:53:14 AgentInteraction: Don
18:53:15 UnloadLoot: Begin
questor block in this step if log in with mission just open
i tink the problem is corp hangar, because if use personaly hangar work fine

**Comment by ISeeDEDPpl** [comment]
> > 18:53:14 AgentInteraction: Don
> > 18:53:15 UnloadLoot: Begin
> > questor block in this step if log in with mission just open
> > i think the problem is corp hangar, because if use personaly hangar work fine

Thas a different issue, and is now fixed.

**Comment by ISeeDEDPpl** [comment]
can you confirm this is still an issue? easiest way to test would be to 
a) start a regulr (not storyline) mission.... 
b) pause questor and warp off. 
c) make a bookmark with the correct prefix default is "salvage:" 
d) close questor
e) restart questor and see what she does...

**Comment by marivx** [comment]
i think is fix now
