### ISSUE TITLE
Feature request: add schedule with only stop time

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#170]
I mean add a schedule with 2 or 3 stop time and it stop at the first time it meet the schedule.

Schedule example:

<char user="" pw="" name="" stop="11:00" stop2="17:00" stop3="23:00"/

He need stop at the first time he meet.

Example1 

I log in at 13.30 it need stop at 17.00.

Exampel 2 

I log in at 19.21 it need stop at 23.00.

**Comment by ISeeDEDPpl** [comment]
no, you misunderstand how to use the schedule properly. Match start and stop times and it works fine. If your suggestion were implemented if questor were to get started (who cares how really, manualy?) at 23:01 it would run for 11  hours before stopping, which is NOT desired behavior, and should not be desired behavior.
