### ISSUE TITLE
Feature request: automatic skill train

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#171]
That save a lot of time and Gano have said me is easy to implement.

If possible, when you have time can you add that ?

Thx

**Comment by sigmastk** [comment]
And it would be nice to be a special behavior , like dedicated salvager.. It would be nice to be able to just load once per day char to check if there is room in skill queue and put missing skill and level from xml file until skill queue is full. And possible to log off. 

That would be just AWESOME :D

**Comment by sigmastk** [comment]
Is there any1 interested in this ? :)

**Comment by ISeeDEDPpl** [comment]
yes, are you offering to write and share it?

**Comment by sigmastk** [comment]
well if I know how I would definatly :) I was asking is any1 interested to write it :) I can and will test it and possible find any bugs if I know how ... 

I want to help as much as I know ...

**Comment by bbday** [comment]
maybe i can writing... give me a couple of day i need to finding time (i'm busy in real life just now).

It is possible to doing like a xml file with a list of skills that you wanna tranning, and when questor is on startup can check the skills.

**Comment by ISeeDEDPpl** [comment]
the skilltrainer if it ever exists will be a separate app called by questor when docked and will not be part of questor itself. 

the hooks already exists in questor to launch the skill trainer when docked
