### ISSUE TITLE
COURIER/DELIVERY - GALLENTE

### ISSUE THREAD

**Issue by Irenicus1977** [ISeeDEDPpl/Questor#172]
We need to update Storyline.cs and add some Gallente COURIER MISSIONS:
/\* COURIER/DELIVERY - GALLENTE */
 {"On the Run", new GenericCourier()},
{"A Fathers Love", new GenericCourier()},
{"A Greener World", new GenericCourier()},
{"Eradication", new GenericCourier()},
{"Evacuation", new GenericCourier()},

**Comment by ISeeDEDPpl** [comment]
have you tested these?

**Comment by ISeeDEDPpl** [comment]
committed
https://github.com/ISeeDEDPpl/Questor/commit/7ffcdaa599bde89beb64ea0c67c38e5b67416910
and
https://github.com/ISeeDEDPpl/Questor/commit/755932d224576832395c65278b1eceb0e06957d8
