### ISSUE TITLE
Questor Manager: Action Item Grab/Drop needs to ignore current ship

### ISSUE THREAD

**Issue by grdk** [ISeeDEDPpl/Questor#175]
Popup dialogue:

Flying Between Hangars!

You can't fly your active ship into someone else's hangar. If you have another ship then activate the other ship, and try again. If you do not have another ship then get one and activate that ship and try again.

Maybe we can just close the dialogue box instead? If the box is closed then QM continues on its way with the next job.

**Comment by grdk** [comment]
Whoops, forgot to add this bit of info. This only affects:
Action Item > Ship Hangar > Action All Items > Grab

I haven't really tested QM's features before this run, but I would presume that if you specify a specific item (ship) to grab, it wouldn't grab the active/current ship... unless of course the active/current ship is of the same type that is being grabbed?

**Comment by ISeeDEDPpl** [comment]
there were 2 issues.

1) the "Flying Between Hangars!" popup should have been closed, that is now fixed.
2) Grabbing "All Items" should have assumed the ship you are currently flying shouldn't be grabbed, that is now fixed.
