### ISSUE TITLE
Storyline: Close Agent Convo if Lowsec Mission detected

### ISSUE THREAD

**Issue by grdk** [ISeeDEDPpl/Questor#178]
This is fairly low priority.

Currently the Agent Convo window stays open if a lowsec storyline was detected. It doesn't affect Questor in any way, as Questor will continue on with the next storyline/regular mission, but it should be closed eventually.

**Comment by Chryst** [comment]
Yeah i confirm that. Same problem.

**Comment by ISeeDEDPpl** [comment]
the agent convo should now be closed when declining storylines. please confirm.

**Comment by grdk** [comment]
Alright, I attempted to test this today but ran into an issue with AlwaysRepairDrones which was part of the commits I merged into my fork - basically it'll hang somewhere trying to open some windows. I'll send you the log snippet a bit later when I have the chance.

**Comment by ISeeDEDPpl** [comment]
this is working fine.
