### ISSUE TITLE
BuyLPI

### ISSUE THREAD

**Issue by sigmastk** [ISeeDEDPpl/Questor#179]
Is there any problem with buylpi, or it is not working only for me ?

I have following exception :

---

14:37:37 [BuyLPI] Starting BuyLPI...
DirectEve: Exception during license check: Unknown error "-1073741819".
Unhandled exception in application.
Outer Exception: System.Security.Cryptography.CryptographicException: Unknown error "-1073741819".
   at DirectEve.DirectEve..ctor(IFramework framework)
   at BuyLPI.BuyLPI.Main(String[] args) in **************\ISeeDEDPpl-Questor-0fe22fe\BuyLPI\BuyLPI.cs:line 79
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)
   at LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly2()
   at LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly()
   at LavishVMRuntime.LVMDomainManager.AssemblyExecuter(Object Obj)

---

Its standalone version, from ISeeDEDPpl build on 20.08.2012 .... (I haven't seen that there is anything else done on BuyLPI since then)

**Comment by grdk** [comment]
It's:

dotnet buylpi buylpi <item name/typeid> <optional quantity>

If you're using a item name description, makes sure you put it in "quotes."

I just used it yesterday and it works fine.

**Comment by ISeeDEDPpl** [comment]
lic error == bad

**Comment by sigmastk** [comment]
ISDP, you mean there is some settings in toon.xml regarding buylpi ?

I know syntax, I have used it before (not in recent history though). I know it is dontet bulpi buypli "name of intem" #of times to take it.

Or buylpi buypli idofitem #of times to take it.

I got this when I start it :

12:27:46 [BuyLPI] Starting BuyLPI...
DirectEve: Exception during license check: Unable to verify your
support license, please try again later !
Unhandled exception in application.

And I have like twice more activated license than I am using. I even tried with anonymous license .. and same error.

**Comment by ISeeDEDPpl** [comment]
well if directeve is not working we have no hope in buylpi. 
are you sure you have the directeve.lic file in the same directory as directeve.dll, buylpi.exe and questor.modules.dll (default would be Innerspace/.Net Programs)

I should have noticed that lic error this morning =/ my reply made no sence in that context. if directeve is not passing its lic check then buylpi (or anything else, valuedump, questor, etc... cant possibly ever work)

**Comment by sigmastk** [comment]
Everything else is working flawlessly. I'am using your exp fork, and everything else is working awesome. I regularly use questor, questormanager and valuedump on same computer and often on same toon.

I have .lic buylpi.exe and questor.modules.dll in same dir innerspace/.NET programs.

Obviously I am doing something wrong :( I just cannot figure what :(

**Comment by ISeeDEDPpl** [comment]
There does not appear to be a bug to fix here. I recommend you simplify.

Try running buylpi with no other questor or questor related programs running. 
literally type exactly

"dotnet buylpi buylpi"

at an innerspace console.
if that does not spit out roughly:
`
BuyLPI Syntax:
BuyLPI DotNet BuyLPI BuyLPI <TypeName or TypeId> [Quantity]
BuyLPI (Quantity is optional)
BuyLPI
BuyLPI Example:
BuyLPI DotNet BuyLPI BuyLPI \"Caldari Navy Mjolnir Torpedo\" 10
BuyLPI *OR*
BuyLPI "DotNet BuyLPI BuyLPI 27339 10
`
then something is wrong w the directeve.dll, directeve.lic questor.modules.dll or buylpi.exe files in your .net programs directory. have you made sure to recompile buylpi with the same version of the directeve.dll you used for questor? (easy way is to just use #compile#.bat to compile questor and all the questor related programs at once)

**Comment by sigmastk** [comment]
You are right, it is not bug!

I have resolved it, when I use :

ext isxstealth;
BlockMiniDump true;
StealthModule isxstealth.dll;

and then start questor

then valuedump is not working. When log onto eve w/o that its working like a charm :)

Thank you for your time and effort to help me out on this. You're awesome :D
