### ISSUE TITLE
Questor Manager: Action Item Grab doesn't pull from corp hangar

### ISSUE THREAD

**Issue by grdk** [ISeeDEDPpl/Questor#181]
AFAIK, it pulls ships from the local hangar fine after the last fix to ignore the current ship.

If an Action Item to grab a ship(s) from a corp hangar is queued up, it'll attempt to pull the ship out into the current ship cargohold, but hangs and just sits there waiting.

Here's the relevant log snippet, though it doesn't look like it really tells us much:

01:35:43 [QuestorManager] Arrived at destination
01:35:47 [QuestorManager] Grab: Begin
01:35:59 [Grab] Opening Hangar
01:36:00 [Grab] Opening Cargohold of active ship: waiting [3sec]
01:36:04 [Grab] Opening Cargo Hold
01:36:36 [Grab] Opening Item Hangar: waiting [3sec]
01:36:39 [Grab] Opening Ship Hangar: waiting [4sec]

**Comment by ISeeDEDPpl** [comment]
does grabbing items from the corp hangar work? i.e. is this ships specific or is their an issue with grabbing ANYTHING from the corp hangar via questormanager atm?

**Comment by grdk** [comment]
OK, just worked through this with ISeeDEDPpl.

Conclusion:
- Doesn't grab items OR ships from corp hangar correctly atm

**Comment by ISeeDEDPpl** [comment]
this should now be working.
