### ISSUE TITLE
Decline Mission not closing window

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#186]
Hi, 

I have a rather strange issue which I am not sure is Questor related.

I have 4 chars plus a dedicated salvager.  Total 5.

On the 4th Char, when a black listed mission comes up, questor declines it, however it somehow does not register as a decline and the same mission window just refreshes.  This stays in this loop of decline / refresh / decline until Questor restarts the client.

All other clients decline missions just fine.  I have created a brand char.xml but it has not made a difference.

Any ideas?

**Comment by Pluckyduck** [comment]
working part of the issue now, dont know if it is questor or not.  
1. Clear your cache files, let it restart and then close the client.
2. Delete back up cache files
3. Reset the Mission Decline pop up warning and check the dont ask again and manually click "yes"
4. Either restart the client completely or idle in drop down window
5. close the agent interaction window
6. select start from drop down or hit Autostart button.

This should clear the error for a little while.  I have had to do this on a few of the clients.  I am unsure what is causing this and it is hard to get the client to repeat error.

**Comment by I3Questor** [comment]
Arggg... I wish I hadn't done this now.  Before it was only 1 client doing it.  Now they all are. :(  Now I am just considering not black listing anything because the amount of time wasted with the bot waiting for a timeout then the restart, I'm pretty sure is less than the time wasted on the black listed missions.

Not blaming anyone, its just the way my cookie crumbles.. :(

**Comment by Pluckyduck** [comment]
i have not had this problem in a while, i am running on an older branch though.

**Comment by chantling** [comment]
Just noticed I'm having this issue as well.  Saw it the other day and thought it was a fluke.  Then I re-enabled the agent mission decline warning b/c Questor was trying to decline a mission I didn't want it to.  Looked through cleanup.cs and noticed that the warning was set to close, not to answer yes.  Probably should be changed.

@I3Questor: when you decline a mission, do you get a warning?  If so, click the checkbox to disable the warning and see if this issue goes away.  You likely had the warning disabled for all of your toons except the one, and when you reset the cache, you re-enabled the warning for all of them.

**Comment by I3Questor** [comment]
Thanks for the tip Chantling, I have all the warnings disabled and it still happens unfortunately.

**Comment by ISeeDEDPpl** [comment]
yes, I agree. that does sound like the cause. Ive fixed it locally and will commit to experimental and the storylinefix branch after a few hrs of testing.

**Comment by ISeeDEDPpl** [comment]
if you can isolate a portion of the console log where this is happening maybe there is clue. If nothing else it'll likely tell me where to add more logging
