### ISSUE TITLE
wait for mission decline timer not working

### ISSUE THREAD

**Issue by drokk99** [ISeeDEDPpl/Questor#188]
getting annoyed with coming back to find a bot stuck, with the agent unavailable due to standings loss..

this explains it all i think.

23:44:10 [AgentInteraction] Agent decline timer detected. Current standings: 2.92. Minimum standings: 6.2
23:44:10 [AgentInteraction] Current standings [2.92] is above our configured minimum [6.2]. Declining [Worlds Collide]
23:44:10 [AgentInteraction] Saying [Decline]

last time I checked 2.92 is NOT above 6.2.

also seems to be using agent standings and not corp or faction, I gather it should use the highest one.

**Comment by ISeeDEDPpl** [comment]
yeah that whole sections looks like it needs refactoring. 

when dealing with multiagents how many diff scenarios are there really?

```
                    // we have low standings and no agent to switch to (or only 1 configured)
                    // we have low  standings and we DO have an agent to switch to
                    // we have decent standings and can decline again
                    //
                    // what other scenario is there? 
```

remember at this point eve has already told us that this agent has a decline timer active so the question is really  a matter of decline current mission, switch agents or wait afaik. 
At the moment that is NOT what the code does unfortunately. 

FYI it is in agentinteraction.cs around line 783 (which likely does not need to necessarily be changed) or 797 (2nd criteria)

If no one else has managed to give this attention by next weekend Ill take a look. Ive been pretty busy lately though with a bit less time for coding.

**Comment by chantling** [comment]
The bot doesn't properly start the decline timer the mission if you're only using one agent.  You can fix that by changing line 748 from

```
if (Cache.Instance.AgentEffectiveStandingtoMe <= Settings.Instance.MinAgentBlackListStandings && Cache.Instance.AllAgentsStillInDeclineCoolDown)
```

to

```
if (Cache.Instance.AgentEffectiveStandingtoMe <= Settings.Instance.MinAgentBlackListStandings && ((Cache.Instance.AllAgentsStillInDeclineCoolDown && Settings.Instance.MultiAgentSupport) || !Settings.Instance.MultiAgentSupport))
```

As for the incorrect effective standings, that's DirectEve's EffectiveStanding().  Checks only the specified agent's personal standing towards you.  AFAIK, there's no way to programmatically get the agent's corporation or faction standing towards you.  I ended up going back to the old way of scraping the mission window's html to get my effective standing, as the agent's personal standing towards me is worthless.

**Comment by ISeeDEDPpl** [comment]
this has been fixed in the bleedingedge branch and needs testing.
