### ISSUE TITLE
storyline fix branch bug

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#191]
I didnt get a chance to test with just normal hanger.  I would close the ammo hanger manually and it would continue on.

snippet of the log

 [UnloadLoot.StackHangars] Closing Corp Window: XXXX (for ammo)
 [Cache.OpenCorpLootHangar] OpenCorpLootHangar: Open Secondary Window
 [Cache.OpenCorpLootHangar] OpenCorpLootHangar: Open Secondary Window
 [Cache.OpenCorpLootHangar] OpenCorpLootHangar: Open Secondary Window
 [Cache.OpenCorpLootHangar] OpenCorpLootHangar: Open Secondary Window

**Comment by ISeeDEDPpl** [comment]
ok, lets try this again without breaking totally unrelated things =/ 

https://github.com/ISeeDEDPpl/Questor/commit/9cd1b3288afb307d3da02c3bde013562eb18f9d5

**Comment by grdk** [comment]
Plucky, AFAIK this is a totally unrelated bug (has to do with corp hangars specifically). Sometimes it gets stuck opening the secondary window from the inventory tree. If you leave it alone and have "restart after ISK hasn't increased xx minutes blah blah" it'll eventually restart questor and continue on. If you catch this before that you'll have to close the inventory window and it'll open it correctly the 2nd time.

**Comment by Pluckyduck** [comment]
k
