### ISSUE TITLE
request: to be able to turn off station repair

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#192]
request the feature to turn off station repair for armor tankers, <stationrepair>true/false</stationrepair> working on it right now but very slow going.

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/70e49493f4b0537de20efc833553bc68da9cd935
default if not specified is true (repair)
if you dont want to use repair set it to false. 

longer term we probably want to set an isk value ceiling and somehow read the repair bill before committing to repairing.
we might also want to consider only running repair if we have armor damage and are a shield tank...
or maybe something simpler, 
*\* if we have armor damage wait (the cycle time of your repairer) before docking and see if you armor damage goes down.... if it does rinse repeat until all armor damage is gone before you dock (I like this solution the best as it does not involve special code paths for shield vs armor). **

who wants to implement it: p
