### ISSUE TITLE
minimumAmmoCharges ignored?

### ISSUE THREAD

**Issue by KingMike** [ISeeDEDPpl/Questor#195]
Hey,

It seems minimumAmmoCharges is being ignored. All launchers are being run to 0 then reloading. 
Also no reload between pockets at all. I remember it used to reload  some 4 months ago or so...
Using experimental branch from 3 days ago.

cheers!

**Comment by Chryst** [comment]
Yes the autoreload outside station and at gates don't work. I confirm that.

In past it was working perfect.

Btw the reload when the ammo reach 0 for me are ok. No sense reload first than the 0.

But for sure is important it autoreload with full ammo in pocket and outside station, so we can save time.

**Comment by ISeeDEDPpl** [comment]
it seems to me that this setting was previously broken and forcing a reload when hitting minimumAmmoCharges every time without fail, in otherwords it actually reduced the available ammo by this number, youd NEVER get to fire the last piece of ammo. Thus this caused MORE reloads than necessary. If I were to re0impliment this sanely how would it make the most sense? reload when ammo in the guns is below this number AND we are not shooting anything?

**Comment by Pluckyduck** [comment]
it is 10 seconds to reload.....

**Comment by ghost** [comment]
turn auto reload weapons off in eve also.

**Comment by Pluckyduck** [comment]
necro!

**Comment by ISeeDEDPpl** [comment]
this has been fixed.
