### ISSUE TITLE
drones.cs: private void GetDamagedDrones()

### ISSUE THREAD

**Issue by ISeeDEDPpl** [ISeeDEDPpl/Questor#198]
`
private void GetDamagedDrones()
        {
            foreach (EntityCache drone in Cache.Instance.ActiveDrones)
            {
                if (Settings.Instance.DebugDroneHealth) Logging.Log("Drones: GetDamagedDrones", "Health[" + drone.Health + "]" + "S[" + Math.Round(drone.ShieldPct,3) + "]" + "A[" + Math.Round(drone.ArmorPct,3) + "]" + "H[" + Math.Round(drone.StructurePct,3) + "][ID" + drone.Id + "]", Logging.white);
            }
            Cache.Instance.DamagedDrones = Cache.Instance.ActiveDrones.Where(d => d.Health < Settings.Instance.BelowThisHealthLevelRemoveFromDroneBay);
        }
`
rework this to be a little less broken... now that we can repair we just need to track drone armor (or certain percentage of total hp?) and set a flag in space if we need to repair. NEVER unset this from space and during repair reset the flag. Something like: DronesNeedRepair True/False...

we can also make a special repair routine that would ONLY repair drones (by groupID) (if needed) that way armor tanked ships arent paying through the nose to repair armor.

**Comment by Karr** [comment]
this would be a great addition to the code.  Have it ONLY repair the drones after each mission.  I am sure everyone would enjoy this.  I agree with your last comment regarding the groupID so the armor tanked ships aren't paying through the nose to repair armor.  I will post finding on drone repairs here shortly.

**Comment by Karr** [comment]
ok, confirmed.  Just turned off the autostart and examined the drones.  Vespa II's were not repaired.  Manually repaired them.

**Comment by Karr** [comment]
btw.. I did not change any code.  Did you want me to use your code above and try it?  Let me know and what file to replace this in.

**Comment by ISeeDEDPpl** [comment]
no, the code above is what is currently in drone.cs

**Comment by ISeeDEDPpl** [comment]
this is not needed, if we can repair drones on every trip to station there is no need to track damaged drones. 

https://github.com/ISeeDEDPpl/Questor/commits/AlwaysRepairDrones
