### ISSUE TITLE
Feature Request: Ancillary Shield Booster

### ISSUE THREAD

**Issue by Bubsan** [ISeeDEDPpl/Questor#199]
Is it possible to use Small/Medium/Large/X-Large Ancillary Shield Booster?
I tried but it seems Questor does not recognize it as a module, maybe because it has charges (Cap Booster Charges). It's relatively new addition to Eve.

It would be awesome if support for this module is added to Questor because it does not use ship's capacitor but charges and marauders have already large cargohold where lot of charges can be brought in mission or whatever is questor botting so adding to defence is very noticable and fewer defence modules are needed releasing slots for gank modules thus speeding up missions.

Just a thought...

**Comment by ISeeDEDPpl** [comment]
in order to support this type of module we need to support loading (and reloading) the cap charges... while adding this we might as well add loading of scripts to modules that support them. 

I'll consider adding this over the next few weeks. I have already started the ground work necessary.

**Comment by Bubsan** [comment]
Thank you very much for your answer and all previous and future efforts you've made!

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/391f27f776ba8234f8e84cab02160b8370f59b9b

this reloads cap injectors but does not yet use them in combat!

THIS NEEDS TESTING, DO NOT AFK with an ancillary shield booster until you know it works! you have been warned.
YOU HAVE TO ADD YOUR CAP CHARGES TO YOUR SAVED FITS! YOU HAVE TO HAVE FITTING SUPPORT ON! Arm does NOT and will not put the cap booster charges in your cargo the fitting manager of eve MUST do it for you! make sure you test multiple missions in a row while watching it! This is a new type of module and needs extra scrutiny.... please file issues on github if you see any

**Comment by Bubsan** [comment]
Thank you very much for this! I will post issues as they appear...
