### ISSUE TITLE
Suggestion: Setting in settings file to change Priority Targets.

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#20]
Suggestion is to have settings in the settings.xml to be able to change priorities per character, instead of in the compile.

**Comment by ISeeDEDPpl** [comment]
unfortunately the priorities number isnt _really_ used in questor. It checks to make sure things are in the priority list and uses a fairly hard coded list of things to check for 1st, then generically checks for ANY priority target
