### ISSUE TITLE
militants left behind

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#200]
is there a reason Militants are being left behind on after mission salvage?

**Comment by ISeeDEDPpl** [comment]
I tend to have a large pile in my toons hangars so I have not noticed.

I will say that there is a list of items that we should not pickup...

`
public bool IsAliveandWontFitInContainers
        {
            get
            {
                if (TypeId == 41) return true;      // Garbage
                if (TypeId == 42) return true;      // Spiced Wine
                if (TypeId == 42) return true;      // Antibiotics
                if (TypeId == 44) return true;      // Enriched Uranium
                if (TypeId == 45) return true;      // Frozen Plant Seeds
                if (TypeId == 3673) return true;    // Wheat
                if (TypeId == 3699) return true;    // Quafe
                if (TypeId == 3715) return true;    // Frozen Food
                if (TypeId == 3717) return true;    // Dairy Products
                if (TypeId == 3721) return true;    // Slaves
                if (TypeId == 3723) return true;    // Slaver Hound
                if (TypeId == 3725) return true;    // Livestock
                if (TypeId == 3727) return true;    // Plutonium
                if (TypeId == 3729) return true;    // Toxic Waste
                if (TypeId == 3771) return true;    // Ectoplasm
                if (TypeId == 3773) return true;    // Hydrochloric Acid
                if (TypeId == 3775) return true;    // Viral Agent
                if (TypeId == 3777) return true;    // Long-limb Roes
                if (TypeId == 3779) return true;    // Biomass
                if (TypeId == 3804) return true;    // VIPs
                if (TypeId == 3806) return true;    // Refugees
                if (TypeId == 3808) return true;    // Prisoners
                //if (TypeId == 3810) return true;    // Marines **Common Mission Completion Item
                if (TypeId == 12865) return true;   // Quafe Ultra
                if (TypeId == 13267) return true;   // Janitor
                if (TypeId == 17765) return true;   // Exotic Dancers
                if (TypeId == 22208) return true;   // Prostitute
                if (TypeId == 22209) return true;   // Refugee
                if (TypeId == 22210) return true;   // Cloned SOE officer
                //if (TypeId == 25373) return true;   // Militants **Common Mission Completion Item
                // people (all the different kinds - ugh?)
                return false;
            }
        }
`
as you can see though militants and marines are commented out so should be picked up during after mission salvaging.

**Comment by Pluckyduck** [comment]
thanks, i didnt know where to look and i was hoping it was this simple,

**Comment by Pluckyduck** [comment]
in what file is this located?  It seems to be still not picking them up.
