### ISSUE TITLE
COURIER/DELIVERY - GALLENTE

### ISSUE THREAD

**Issue by Irenicus1977** [ISeeDEDPpl/Questor#201]
We need to update Storyline.cs and add some Gallente COURIER MISSIONS:
/\* COURIER/DELIVERY - GALLENTE */
{"The Natural Way", new GenericCourier()},

It was tested :)

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/64f7957644236cd95693ab85af7a78e8fcf06925

**Comment by Irenicus1977** [comment]
Please add "Very Important Pirates" - Mimatar/COURIER/DELIVERY Mission
