### ISSUE TITLE
Punctuation in the name of mission xml files

### ISSUE THREAD

**Issue by drokk99** [ISeeDEDPpl/Questor#202]
I have noticed that a few of the missions now need to have the punctuation correct in the xml files, e.g. instead of Generals Quarters it now needs General's Quarters as the target. Also some of the storylines need to have the punctuation added to the name in storyline.cs

edit:
I see that grdk fork has the storyline ones done.

**Comment by ISeeDEDPpl** [comment]
All special characters should have been removed before forming the filename of the XML to search for...

https://github.com/ISeeDEDPpl/Questor/commit/198eba0fd3aa40b45facaa1d69b10b93cc73d7c0

If after this fix you are still seeing mission XMLs that need ' in the name somewhere please open an issue. I just searched through all of questor and did not see any other places that need attention but that does not mean I did not miss something =/
