### ISSUE TITLE
Valuedump issue

### ISSUE THREAD

**Issue by happel** [ISeeDEDPpl/Questor#206]
When trying to refine and sell my missionloot I am presented with the following error:

14:14:41 [ValueDumpUI] Updated [Secure Radar Backup Cluster I] refine materials
14:14:41 [ValueDumpUI] Updated [Heavy Modulated Energy Beam I] refine materials
Exception during event execution: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at ValueDump.ValueDumpUI.OnFrame(Object sender, EventArgs e) in c:\Users\123\Documents\GitHub\Questor\ValueDump\ValueDumpUI.cs:line 321

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

This only happens when I have "Refine loot" checked. Selling without refining works well. Seeing as I don't hear others about this problem, I might be doing something wrong. Unfortunately I'm not sure where to start to solve this problem, so I was hoping someone could steer me in the right direction.

**Comment by ISeeDEDPpl** [comment]
You've managed to run across a fairly common problem. 
There are items that are not in our 2 year old likely manually generated InvTypes.xml.
I worked around it by skipping them: https://github.com/ISeeDEDPpl/Questor/commit/bf01ac57bfd91f05c101543da268c1545ebb86e1
https://github.com/ISeeDEDPpl/Questor

**Comment by happel** [comment]
I previously managed to work around it by using an older version of Valuedump, or deleting/moving a couple of items, but I wasn't able to find out the culprit this time. Thanks a lot for the fix! I'll give it a try tonight.
