### ISSUE TITLE
bbday's drop mission action

### ISSUE THREAD

**Issue by ISeeDEDPpl** [ISeeDEDPpl/Questor#207]
needs testing...

I am not sure if the issue is in that action itself or the function it calls from cache.cs but it is not completing correctly and seems to keep opening the can you specified as the target container over and over. 

I do not use this action myself,the comments above were taken from irc and molested into the sentence above.

**Comment by Irenicus1977** [comment]
I have an error while using this action:
17:44:21 [MissionController.DropItem] Open Cargo
17:44:26 [CombatMissionCtrl] Drop: if (openCargoRetryNumber > 5) - error
17:44:27 [CombatMissionCtrl] Drop: if (openCargoRetryNumber > 5) - error
17:44:28 [CombatMissionCtrl] Drop: if (openCargoRetryNumber > 5) - error
17:44:29 [CombatMissionCtrl] Drop: if (openCargoRetryNumber > 5) - error
17:44:30 [CombatMissionCtrl] Drop: if (openCargoRetryNumber > 5) - error

I am using this xml file:
      actions>
        <action name="DropItem"
          <parameter name="Item" value="Neurowave Pattern Scanner" /
          <parameter name="Target" value="The Anomaly" /
          <parameter name="Quantity" value="1" /
        </action

**Comment by ISeeDEDPpl** [comment]
yes, it is broken at the moment. keep pinging this issue and I am sure eventually Ill fix it =/ 
maybe some code ferry (bbday?) will send me a merge request with the fix(s) necessary.
