### ISSUE TITLE
Full COnsole Displayed

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#209]
Hi,

I am currently running version:
ISeeDEDPpl-Questor-2f4fe6d

And It has gone back to showing the full Questor Console (with all the details showing)

Is there a way I can change it back to the mini console that only shows State, behaviour, autostart, etc without the full Show Details window?

Thanks

**Comment by ISeeDEDPpl** [comment]
yes, toggle the details button... 

Ill fix it in github here shortly

**Comment by ISeeDEDPpl** [comment]
corrected.
