### ISSUE TITLE
Dedicated Salvager Cargo Full Issue

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#211]
Hi,

The dedicalted salvager seems to be acting strangely again.  It salvages everything just fine until the cargo is full. Then it just idles at the bookmark.  

It should rtb to unload and continue salvaging.

Please have a look when you have time.

**Comment by Chryst** [comment]
Sorry but i don't have that problem. With what version ?

**Comment by ISeeDEDPpl** [comment]
I am not sure what would cause that other than the UnloadLootAtStation setting not being true. 
I just made changes to the Dedicated Salvager behavior to basically ignore that setting. It will always return to base when full now. 

https://github.com/ISeeDEDPpl/Questor/commit/9b8ff31e664b83417c99240dd08c9c714c45be16
