### ISSUE TITLE
Problem with accepted mission.

### ISSUE THREAD

**Issue by Lakiska** [ISeeDEDPpl/Questor#212]
If i have a accepted misiion in my journal. the questor doesnt detect it.. why??

How can i do for make that start with the accepted mission?

Somebody know?

**Comment by Chryst** [comment]
What version are you using ? I'm using the last and i haven't find that problem with accepted missions.

Simply i have never find that problem with any of the last version.

**Comment by ISeeDEDPpl** [comment]
Is the accepted mission a non-storyline (i.e. regular mission) for an agent other than your configured agent? If that is the case it is normal for questor to not travel to this unknown (to questor) agent to do a mission.
