### ISSUE TITLE
Noctis relog in space get the questor stuck until relog for time inactivity

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#214]
If the char relog when the char is in space with noctis, it come back to home, go to salvage bookmark, salvage all, come back to station and stay stopped in idle in station withouth go ahead.

After the idle it need go ahead in delayed start.

If i put delayed start manually all is perfect.

If the client relog in tengu or others fight ship all is perfect, so is only a problem if the char relog when is out in space in salvage state.

**Comment by ISeeDEDPpl** [comment]
So this is the aftermissionsalvager or the dedicated salvager?

I am assuming afterMissionSalvager.

**Comment by ISeeDEDPpl** [comment]
ok, this should resolve the hanging issue, it was getting stuck trying to write mission statistics (best guess).

please test.
https://github.com/ISeeDEDPpl/Questor/commit/710ef5397fa69bd51e527cd61d340cef3e26be8b

**Comment by Chryst** [comment]
Ok thx

**Comment by Chryst** [comment]
Issue solved perfect. Thx a lot
