### ISSUE TITLE
Crashing questor after accepting Mission

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#215]
Don t know why this is happening but since the new patch of eve my eve window crashed after talking with the agent to accept a mission or it crashes when already in combat. Also it throws out a error named like this:

15:30:40 [CombatMissionsBehavior.TravelToAgentsStation] Arrived at destination
Exception during event execution: System.AccessViolationException: Es wurde versucht, im geschützten Speicher zu lesen oder
zu schreiben. Dies ist häufig ein Hinweis darauf, dass anderer Speicher beschädigt ist.

   bei ..(IntPtr , IntPtr , IntPtr )

   bei ..(Dictionary`2 , Object[] )

   bei ..( , Object[] )

   bei ..( , String , Object[] )

   bei DirectEve.DirectAgentMission.(DirectEve )

   bei DirectEve.DirectEve.get_AgentMissions()

   bei Questor.Modules.Caching.Cache.GetAgentMission(Int64 agentId) in c:\questor\Questor.Modules\Caching\Cache.cs:Zeile
1416.

   bei Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\questor\Questor\Behaviors\CombatMissionsBehavior.cs:Zeile 888.

   bei Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\questor\Questor\Questor.cs:Zeile 537.

   bei ..(DirectEve , Object , EventArgs )

   bei DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   bei LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

Strange thing is this happen on two of my characters but the other are running fine althoug they also get this error. I hope someone can help me.

**Comment by ISeeDEDPpl** [comment]
see if latest experimental helps any...

https://github.com/ISeeDEDPpl/Questor/commit/afb9829655f397195f7d6b1a419fcfcf3a4e17e9

**Comment by kn0xv1lle** [comment]
Try it and unfortunately it doesnt helped.. Still get eve crashes and this error in console. Its pretty strange once eve crash when at station and once it crashed during combat. When inspace it just crashes without any error. When at Station it Crashed when getting Mission.

Exception during event execution: System.AccessViolationException: Attempted to read protected memory or
to write. This is often an indication that other memory is corrupt.

   bei ..(IntPtr , IntPtr , IntPtr )
bei ..(Dictionary`2 , Object[] )

   bei ..( , Object[] )

   bei ..( , String , Object[] )

   bei DirectEve.DirectAgentMission.(DirectEve )

   bei DirectEve.DirectEve.get_AgentMissions()

   bei Questor.Modules.Caching.Cache.GetAgentMission(Int64 agentId) in
c:\ISeeDEDPpl-Questor-1782fe0\Questor.Modules\Caching\Cache.cs:Zeile 1411.

   bei Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\ISeeDEDPpl-Questor-1782fe0\Questor\Behaviors\CombatMissionsBehavior.cs:Zeile 866.

   bei Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\ISeeDEDPpl-Questor-1782fe0\Questor\Questor.cs:Zeile 537.

   bei ..(DirectEve , Object , EventArgs )

   bei DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   bei LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by Chryst** [comment]
I dont' have that problem. For me all is ok. Try repair eve.

**Comment by ISeeDEDPpl** [comment]
or clear your cache. and/or add your agent as a contact to people and places...

**Comment by kn0xv1lle** [comment]
Didn t helpt at all. I don t know why eve crash at this two toons. Its just these two i delete all settings reinstalled innerspace eve nothing helped. Still get crashes when finishing mission with just this two. Other are running fine. 
But i still get this error.

Exception during event execution: System.AccessViolationException: Attempted to read or write protected memory. This is oft
an indication that other memory is corrupt.

   at ..(IntPtr , IntPtr , IntPtr )

   at ..(Dictionary`2 , Object[] )

   at ..( , Object[] )

   at ..( , String , Object[] )

   at DirectEve.DirectAgentMission.(DirectEve )

   at DirectEve.DirectEve.get_AgentMissions()

   at Questor.Modules.Caching.Cache.GetAgentMission(Int64 agentId) in
c:\ISeeDEDPpl-Questor-85e1c46\Questor.Modules\Caching\Cache.cs:line 1420

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\ISeeDEDPpl-Questor-85e1c46\Questor\Behaviors\CombatMissionsBehavior.cs:line 888

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\ISeeDEDPpl-Questor-85e1c46\Questor\Questor.cs:line 537

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

No idea why

**Comment by ISeeDEDPpl** [comment]
This is seemingly a DE issue. There should be a DirectEVE update that resolves this shortly. Ganondorf is aware and said he had already resolved the issue in his local copy of DirectEVE.

**Comment by kn0xv1lle** [comment]
Thanks Iseededppl. Really crashed my head on that.

**Comment by kn0xv1lle** [comment]
New log

Exception during event execution: System.AccessViolationException: Attempted to read or write protected memory. This
is often an indication that other memory is corrupt.

   at  . . (IntPtr , IntPtr , IntPtr )

   at  . . (Dictionary`2 , Object[] )

   at  . . (  , Object[] )

   at  . . (  , String , Object[] )

   at DirectEve.DirectAgentMission. (DirectEve )

   at DirectEve.DirectEve.get_AgentMissions()

   at Questor.Modules.Caching.Cache.GetAgentMission(Int64 agentId) in
c:\ISeeDEDPpl-Questor-8104b11\Questor.Modules\Caching\Cache.cs:line 1413

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\ISeeDEDPpl-Questor-8104b11\Questor\Behaviors\CombatMissionsBehavior.cs:line 883

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\ISeeDEDPpl-Questor-8104b11\Questor\Questor.cs:line
534

   at  . . (DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by ISeeDEDPpl** [comment]
new de likely fixes this issue. Ive updated github... you will need support instances to use the new DE.
