### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by happel** [ISeeDEDPpl/Questor#216]
After Questor has finished loading settings or changing the state in the GUI from Idle to Start the console is flooded repeatedly with this error:

```
18:41:49 [Questor] Start Mission Behavior
Exception during event execution: System.NullReferenceException: Object reference not set to an instanc
an object.

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\Users\asd\ISeeDEDPpl-Questor-d1a92ff\Questor\Behaviors\CombatMissionsBehavior.cs:line 442
   at Questor.Questor.OnFrame(Object sender, EventArgs e) in
c:\Users\asd\ISeeDEDPpl-Questor-d1a92ff\Questor\Questor.cs:line 545

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
```

Questor is compiled with the latest DirectEve.dll if that makes any difference.

**Comment by chantling** [comment]
commit 57b2cb6fe6a6dd779ef46d72e65c144e9708a9f2 doesn't fix the issue for me - debugging shows that ActiveShip doesn't exist in the current context when Questor is first started up.  Quick fix is to enclose that if statement with a try..catch block

```
                    try
                    {
                        if (!Statistics.Instance.MissionLoggingCompleted && Cache.Instance.DirectEve.ActiveShip != null && Cache.Instance.DirectEve.ActiveShip.GivenName.ToLower() == Settings.Instance.CombatShipName.ToLower())
                        {
                            Statistics.WriteMissionStatistics();
                            break;
                        }
                    }
                    catch
                    {
                    }
```

**Comment by Semaj79** [comment]
Confiming that im getting the same error as happel, compiled using the lastest direct eve dll and iseedead questor

**Comment by ISeeDEDPpl** [comment]
ok, this should resolve it, untested unfortunately: 

https://github.com/ISeeDEDPpl/Questor/commit/526e8a8327fa135021c21de769db671b12dccf8a
it turns off the statistics check for the first 5 min questor is running, there are no stats until after you have run a mission anyway and running a mission in under 5 min would be amazing =) 

This also uses a try/catch block here since evidently this DE function is unsafe at certain times (why is anyones guess though)

**Comment by ISeeDEDPpl** [comment]
fixed here: https://github.com/ISeeDEDPpl/Questor/commit/bb86a583957fa0bd74d83af4ab964bc280b1912c
