### ISSUE TITLE
Questor GUI - time does not restart with every mission and mission counter stays 0

### ISSUE THREAD

**Issue by Bubsan** [ISeeDEDPpl/Questor#217]
So, is it just me or there might be a problem with mission counter and time which does not restart with new mission?
Counter does not count, it stays 0 all the time and the time keeps going without restarting on new missions.

Using latest experimental.

**Comment by Chryst** [comment]
Is normal, that happend only the first mission i think.

**Comment by ISeeDEDPpl** [comment]
I'll take a look on my end , but every time Ive looked at it it has looked correct to me. I'll see if I can add some logging to that when it changes or similar. It'll probably be this weekend before I have a change to test this.

**Comment by EchuI** [comment]
Same problem. Counter always show 0, time few hundreds minutes after few hours boting
commit 526e8a8327

**Comment by ISeeDEDPpl** [comment]
it is a recent bug it seems. the statistics increment that number when they run. evidently they were not running in all cases. I am looking at the issue now. I am currently testing a fix.

**Comment by Bubsan** [comment]
Thank you ISeeDEDPpl! I'm glad it's being worked on and that, of course, it's not my paranoia only :)

**Comment by EchuI** [comment]
also dont work statistics, it seems that this one bug

**Comment by ISeeDEDPpl** [comment]
yes, it is. Statistics are hopefully working better in latest experimental.

**Comment by Bubsan** [comment]
It seems that in one of the recent releases (e8ee73c) mission counter and time is working again.
So, if someone else can also confirm this, maybe this issue can be closed...

**Comment by ISeeDEDPpl** [comment]
it is again working fine. there are other mission stat issues but those will be fixed as part of another already filed issue.
