### ISSUE TITLE
Last verion issue 526e8a8

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#218]
19:08:10 [CombatMissionsBehavior.Idle] Cache.Instance.DirectEve.ActiveShip.GivenName is not yet available... We need
to know what ship you are in to determine if we need to write stats or not.  retrying
19:08:11 [CombatMissionsBehavior.Idle] Cache.Instance.DirectEve.ActiveShip.GivenName is not yet available... We need
to know what ship you are in to determine if we need to write stats or not.  retrying
19:08:12 [CombatMissionsBehavior.Idle] Cache.Instance.DirectEve.ActiveShip.GivenName is not yet available... We need
to know what ship you are in to determine if we need to write stats or not.  retrying

Infinite spam of that.

**Comment by frbyles** [comment]
Did u make sure u hav the names correct of ship and ship n xml. ?  Name ur ship ingame then copy nd paste it into ur xml

Sent from my HTC Inspire™ 4G on AT&T

----- Reply message -----

**Comment by EchuI** [comment]
When Q start try open ship hangar if spaming this message

**Comment by Chryst** [comment]
With the other version except that i don't have that problem, so is possible there is an error ?

I have test a lot of the last ise version and i don't have that error with any of the versions i have test, so i think is a new error.

**Comment by Chryst** [comment]
Ok, i have understand the issue. It happend if the invenctory is closed at startup. ise can you please set it work with the invenctory close at startup same as in the past ?

Thanks

**Comment by ISeeDEDPpl** [comment]
no, the issue is some kind of timing issue... I attempted to solve that with a check to make sure we only ran mission statistics after 5 min after questor started but evidently that is not yet correct... Ill commit a fix here shortly.

**Comment by Chryst** [comment]
Kk thx

**Comment by ISeeDEDPpl** [comment]
ok, fixed. https://github.com/ISeeDEDPpl/Questor/commit/bb86a583957fa0bd74d83af4ab964bc280b1912c
