### ISSUE TITLE
Salvaging cae313b ( last Oct 13, 2012 version) error

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#219]
Sometime, the last room container give that error. Only pressing pick up on it the questor go ahead.

I don't have understand if in the verison next to that the problem is solved or no.

23:29:47 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:29:59 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:30:12 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:30:14 [Questor] Wallet Balance Has Not Changed in [ 31 ] minutes.
23:30:24 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:30:36 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:30:49 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:31:01 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:31:14 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:31:15 [Questor] Wallet Balance Has Not Changed in [ 32 ] minutes.
23:31:26 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:31:38 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:31:51 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:32:03 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:32:15 [Questor] Wallet Balance Has Not Changed in [ 33 ] minutes.
23:32:15 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:32:28 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:32:40 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:32:53 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:33:05 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:33:16 [Questor] Wallet Balance Has Not Changed in [ 34 ] minutes.
23:33:18 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:33:30 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:33:43 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:33:55 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:34:07 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:34:16 [Questor] Wallet Balance Has Not Changed in [ 35 ] minutes.
23:34:20 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:34:32 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:34:45 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:34:57 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:35:09 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:35:17 [Questor] Wallet Balance Has Not Changed in [ 36 ] minutes.
23:35:22 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:35:34 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:35:47 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:35:59 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:36:12 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:36:17 [Questor] Wallet Balance Has Not Changed in [ 37 ] minutes.
23:36:24 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]
23:36:36 [Salvage] Opening container [Cargo Container][0k][ID: 9000000000000309735]

HERE I HAVE PRESS BY HAND THE PICK UP ALL IN THE LAST ROOM CONTAINER

23:36:48 [CombatMissionsBehavior.Salvage] Finished salvaging the room
23:36:48 [CombatMissionsBehavior.Salvage] removing salvage bookmark:XXXXXXX
23:36:49 [CombatMissionsBehavior.Salvage] Finished salvaging the room
23:36:50 [CombatMissionsBehavior.Salvage] Finished salvaging the room
23:36:51 [CombatMissionsBehavior.Salvage] Finished salvaging the room
23:36:52 [CombatMissionsBehavior.Salvage] Finished salvaging the room
23:36:53 [CombatMissionsBehavior.Salvage] Finished salvaging the room
23:36:54 [CombatMissionsBehavior.Salvage] Finished salvaging the room
23:36:54 [CombatMissionsBehavior.Salvage] We have salvaged all bookmarks, go to base

**Comment by Chryst** [comment]
The problem seems solved with the last verson. But not sure. Waiting confirmation. Thx

**Comment by ISeeDEDPpl** [comment]
If this reoccurs a log with the character setting:
`<debugLootWrecks>true</debugLootWrecks>`
might be useful.

**Comment by Pluckyduck** [comment]
i found this one today as well.

**Comment by Chryst** [comment]
I have just find one stucked with frozen wood, metal scraps and wheat inside the container. And is the last container of the room.

Another stuck with the last container with inside metal scraps, dairy products, wheat.

Pressing loot all in the container all go ahead perfect.

**Comment by ISeeDEDPpl** [comment]
is this the after mission salvager or the dedicated salvager (or both?)

**Comment by Pluckyduck** [comment]
I have only seen it only on after mission salvager

**Comment by EchuI** [comment]
+1, after mission salvaging

**Comment by Chryst** [comment]
Only with noctis i have see it for the moment. Is rare.

**Comment by ISeeDEDPpl** [comment]
when you see it happening... edit your character settings xml and turn on 
`<debugLootWrecks>true</debugLootWrecks>`
then attach the resulting log here. 

it would be REALLY nice to have the log with debugLootWrecks on before the issue occurs but the log will be QUITE HUGE so that may not be possible.

**Comment by Chryst** [comment]
01:30:45 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:30:45 [Salvage] Opening container [Cargo Container][1k][ID: 1008261043474]
01:30:45 [Salvage] LootWrecks: Cache.Instance.ContainerInSpace.Window is ready
01:30:48 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:30:48 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:30:52 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:30:52 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:30:55 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:30:55 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:30:58 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:30:58 [Salvage] Opening container [Cargo Container][1k][ID: 1008261043474]

**Comment by Chryst** [comment]
01:31:25 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:31:28 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:28 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:31:32 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:32 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:31:35 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:35 [Salvage] Opening container [Cargo Container][1k][ID: 1008261043474]
01:31:35 [Salvage] LootWrecks: Cache.Instance.ContainerInSpace.Window is ready
01:31:38 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:38 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:31:41 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:41 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:31:44 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:44 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:31:47 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:47 [Salvage] Opening container [Cargo Container][1k][ID: 1008261043474]
01:31:47 [Salvage] LootWrecks: Cache.Instance.ContainerInSpace.Window is ready
01:31:50 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:50 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:31:53 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:53 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:31:56 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:56 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:31:59 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:31:59 [Salvage] Opening container [Cargo Container][1k][ID: 1008261043474]
01:31:59 [Salvage] LootWrecks: Cache.Instance.ContainerInSpace.Window is ready
01:32:02 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:32:02 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:32:03 [Questor] Wallet Balance Has Not Changed in [ 25 ] minutes.
01:32:05 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:32:05 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring
01:32:08 [Salvage.Lootwrecks] containerIDs contains [0] individual containerIDs
01:32:08 [Salvage.LootWrecks] We attempted to open [1008261043474] less than 10 sec ago, ignoring

**Comment by Chryst** [comment]
There was freedom fighters inside the wreck.

**Comment by Chryst** [comment]
Is all ok, the issue is solved with the revert. Thx
