### ISSUE TITLE
create a new log for CPU/GPU/Memory usage and take snapshots at various intervals.

### ISSUE THREAD

**Issue by ISeeDEDPpl** [ISeeDEDPpl/Questor#221]
`
<Pluckyduck> since last patch, was there any performance hit?
<ISeeDEDPpl--> not that I have noticed... are you seeing a performance hit?
<Pluckyduck> i added one guy to the mix and seem to be
<Pluckyduck> just wondering
<ISeeDEDPpl--> we could dump CPU usage (and GPU usage possibly?!) at certain points which might be a nice metric. 
<ISeeDEDPpl--> to refer back to later
<ISeeDEDPpl--> if done right it would allow us to chart CPU/GPU/Memory usage per mission. hrm... of course currently questor would not really know how many instances were going so in that since the numbers would only make sense to your unique setup but it would still be nice info to have. 
`

**Comment by Pluckyduck** [comment]
glad i could help!
