### ISSUE TITLE
station spam

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#222]
The guys were in station and this was spamed over and over....

http://pastebin.com/f55g9p0k

15:59:19 [CombatMissionsBehavior.TravelToAgentsStation] Setting Destination to [XXX.XXX Station] Cache.Instance.Mission == null - retry on next iteration
15:59:20 [CombatMissionsBehavior.TravelToAgentsStation] Arrived at destination
15:59:20 [CombatMissionsBehavior] Cache.Instance.Mission == null - retry on next iteration
15:59:21 [CombatMissionsBehavior.TravelToAgentsStation] Arrived at destination
15:59:21 [CombatMissionsBehavior] Cache.Instance.Mission == null - retry on next iteration
15:59:22 [CombatMissionsBehavior.TravelToAgentsStation] Arrived at destination
15:59:22 [CombatMissionsBehavior] Cache.Instance.Mission == null - retry on next iteration
15:59:24 [CombatMissionsBehavior.TravelToAgentsStation] Arrived at destination
15:59:24 [CombatMissionsBehavior] Cache.Instance.Mission == null - retry on next iteration
15:59:25 [CombatMissionsBehavior.TravelToAgentsStation] Arrived at destination
15:59:25 [CombatMissionsBehavior] Cache.Instance.Mission == null - retry on next iteration
15:59:26 [CombatMissionsBehavior.TravelToAgentsStation] Arrived at destination
15:59:26 [CombatMissionsBehavior] Cache.Instance.Mission == null - retry on next iteration

**Comment by ISeeDEDPpl** [comment]
fixed the spam, potentially replaced it with different spam =/

https://github.com/ISeeDEDPpl/Questor/commit/04f699e463c587f6e0dcbb1b5dde4fe81ac2b399

if you do get spam again pls attach the console logs again.

**Comment by ISeeDEDPpl** [comment]
this should now be fully resolved:

https://github.com/ISeeDEDPpl/Questor
