### ISSUE TITLE
Compile errors.

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#223]
ISeeDEDPpl-Questor-c7d315d

Lookup\Settings.cs(926,21): error CS0103: The name 'HighTierLootContainer' does
 not exist in the current context [ISeeDEDPpl-Questor-c7d315d  - Current\Questor.Modules\Questor.Modules.csproj]
Lookup\Settings.cs(927,25): error CS0103: The name 'HighTierLootContainer' does
 not exist in the current context [ISeeDEDPpl-Questor-c7d315d  - Current\Questor.Modules\Questor.Modules.csproj]
Lookup\Settings.cs(929,25): error CS0103: The name 'HighTierLootContainer' does
 not exist in the current context [ISeeDEDPpl-Questor-c7d315d  - Current\Questor.Modules\Questor.Modules.csproj]
Lookup\Settings.cs(929,49): error CS0103: The name 'HighTierLootContainer' does
 not exist in the current context [ISeeDEDPpl-Questor-c7d315d  - Current\Questor.Modules\Questor.Modules.csproj]
Done Building Project ISeeDEDPpl-Questor-c7d315d  - Current\Questor.Modules\Questor.Modules.csproj" (default targets) -- FAILED.

Done Building Project "ISeeDEDPpl-Questor-c7d315d
- Current\BuyLPI\BuyLPI.csproj" (Clean;Build target(s)) -- FAILED.

Build FAILED.

**Comment by ISeeDEDPpl** [comment]
fixed.

**Comment by I3Questor** [comment]
MSBUILD : error MSB1009: Project file does not exist.
Switch: .\BuyLPI\BuyLPI.csproj
Done building BUYLPI - see above for any errors - 1 of 7 builds
Press any key to continue . . .
Microsoft (R) Build Engine version 4.0.30319.17626
[Microsoft .NET Framework, version 4.0.30319.17626]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\questor\Questor.csproj
Done building Questor - see above for any errors - 2 of 7 builds
Press any key to continue . . .
Microsoft (R) Build Engine version 4.0.30319.17626
[Microsoft .NET Framework, version 4.0.30319.17626]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\Questor.Modules\Questor.Modules.csproj
Done building Questor.Modules - see above for any errors - 3 of 7 build
Press any key to continue . . .
Microsoft (R) Build Engine version 4.0.30319.17626
[Microsoft .NET Framework, version 4.0.30319.17626]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\updateinvtypes\UpdateInvTypes.csproj
Done building updateinvtypes - see above for any errors - 4 of 7 builds
Press any key to continue . . .
Microsoft (R) Build Engine version 4.0.30319.17626
[Microsoft .NET Framework, version 4.0.30319.17626]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\valuedump\ValueDump.csproj
Done building valuedump - see above for any errors - 5 of 7 builds
Press any key to continue . . .
Microsoft (R) Build Engine version 4.0.30319.17626
[Microsoft .NET Framework, version 4.0.30319.17626]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\QuestorManager\QuestorManager.csproj
Done building QuestorManager - see above for any errors - 6 of 7 builds
Press any key to continue . . .
