### ISSUE TITLE
error MSB1009: Project file does not exist.

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#225]
MSBUILD : error MSB1009: Project file does not exist.
Switch: .\BuyLPI\BuyLPI.csproj
Done building BUYLPI - see above for any errors - 1 of 7 builds
Press any key to continue . . .
Microsoft (R) Build Engine version 4.0.30319.17626
[Microsoft .NET Framework, version 4.0.30319.17626]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\questor\Questor.csproj
Done building Questor - see above for any errors - 2 of 7 builds
Press any key to continue . . .
Microsoft (R) Build Engine version 4.0.30319.17626
[Microsoft .NET Framework, version 4.0.30319.17626]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\Questor.Modules\Questor.Modules.csproj
Done building Questor.Modules - see above for any errors - 3 of 7 build
Press any key to continue . . .
Microsoft (R) Build Engine version 4.0.30319.17626
[Microsoft .NET Framework, version 4.0.30319.17626]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\updateinvtypes\UpdateInvTypes.csproj
Done building updateinvtypes - see above for any errors - 4 of 7 builds
Press any key to continue . . .
Microsoft (R) Build Engine version 4.0.30319.17626
[Microsoft .NET Framework, version 4.0.30319.17626]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\valuedump\ValueDump.csproj
Done building valuedump - see above for any errors - 5 of 7 builds
Press any key to continue . . .
Microsoft (R) Build Engine version 4.0.30319.17626
[Microsoft .NET Framework, version 4.0.30319.17626]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: .\QuestorManager\QuestorManager.csproj
Done building QuestorManager - see above for any errors - 6 of 7 builds
Press any key to continue . . .

**Comment by I3Questor** [comment]
Strange, but it does exist!  All the .csproj files are actually there.  What am I missing?

**Comment by ISeeDEDPpl** [comment]
What version?
How are you building?

I just downloaded: ISeeDEDPpl-Questor-0ea9a5d.zip
extracted it to a subdirectory... double clicked #compile#.bat
and everything compiled fine 7 of 7, there were some warnings but no errors. 

I think you ran the #compile#.bat without extracting the archive first. I was able to duplicate the same error you have there. you NEED to extract the archive before trying to compile =/
