### ISSUE TITLE
Eve Client Window Position

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#227]
Hi Guys,

As I am obviously coding brain dead so I wanted to ask if this is at all possible or if there is another solution.

Is it possible to get an option to specify X and Y coordinates for the Eve Client Window like we have for the Questor Console?

```
<!--                                                -->
<!-- X Position of Questor Window -->
<windowXPosition>90</windowXPosition>
<!-- needs to be customized -->
<!-- Y Position of Questor Window -->
<windowYPosition>90</windowYPosition>
<!-- needs to be customized -->
```

It would be so cool if we could get that.  Obviously this is very low priority.  Just something for ISDP to think about when he is sitting there plucking his pubic hairs...

**Comment by ISeeDEDPpl** [comment]
Yes, we can do this in questor if needed. I would PREFER you do this using isboxer though. 
If you cant or wont use isboxer please explain WHY. If you put together a good reason I will add this functionality to questor.

**Comment by I3Questor** [comment]
The honest answer is, I have no idea how to do it in isboxer.  If there is somewhere or someone that can point me in the right direction then I would be very thankful.

**Comment by EchuI** [comment]
Uncomfortable when a lot of settings in various programs. Now almost everything is stored in charname.xml, exception only login information for the bot.

**Comment by Chryst** [comment]
I think that is really unuseful.

**Comment by ISeeDEDPpl** [comment]
I3Questor, 
Open "IsBoxer Toolkit.exe" if you do not yet have it in your innerspace folder, download isboxer: www.isboxer.com

Once you have defined your characters (Innerspace profiles) and the ISBoxer CharacterSet (multiple characters which refer to innerspace profiles) you can inside the character set attach asn already defined WindowLayout.

If you need to create a windowlayout you can do so using the Window Layout Wizard which you access using the right click menu of the "window layouts" part of the tree in isboxer. 

If you still have questions I am available on IRC: irc.lavishsoft.com  channel: #questor

**Comment by EchuI** [comment]
But maybe you can at least give the name of the function to move windows? Or the appropriate command for innerspace without using isboxer.

**Comment by ISeeDEDPpl** [comment]
WindowCharacteristics

**Comment by frbyles** [comment]
On Thu, Oct 25, 2012 at 11:24 PM, ISeeDEDPpl notifications@github.comwrote:

> > WindowCharacteristics
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/ISeeDEDPpl/Questor/issues/227#issuecomment-9802535.
> > 
> > create a char and char set ie the wizzard make a region then wen all is
> > done edit the region move to where u lik how ever big u like etc

http://privatepaste.com/download/748288c281

**Comment by I3Questor** [comment]
ISDP has been awesome as usual and implemented the eve client position settings in the setting.xml.  

I am using version ISeeDEDPpl-Questor-9756ab5 and although i have set the window parameters, the eve window has not moved.

**Comment by sigmastk** [comment]
I do not use isboxer atm (I gave it a shot, but couldn't understand it corectlly (my bad I know :( ). You can adjust eve windows with console commands : 
WindowPos x,y example WindowPos 180,0
WindowSize WithxHeight example WindowSize 800x700

I use .iss script for every profile (do not use one with arguments but one for every toon). In every .iss script I have specified windows positions and size, you can play with this if you don't have time to play with isboxer or if you are dumb as I am :)

**Comment by ISeeDEDPpl** [comment]
this should now be fixed. I was using x as the delimiter for both the window size and the window position, which is wrong. 
Size uses an "x"
position uses a ","
Thank You sigmastk.

someone want to test this?

**Comment by sigmastk** [comment]
Np, any time :)
