### ISSUE TITLE
Last Version 0ea9a5d Errors stucked in others station that aren't the agent station

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#228]
If he is in the others stations or stoyline stations, it continue check for corp hangar and for general freight container. But they there aren't so it get stucked.

**Comment by ISeeDEDPpl** [comment]
the issue is that traveler is in AtDestination and it isnt being reset

**Comment by ISeeDEDPpl** [comment]
I'll commit the traveler changes Ive been working on shortly which fix that
