### ISSUE TITLE
Still No statistics written today

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#229]
I am now using the current version of Questor (ISeeDEDPpl-Questor-0ea9a5d)

Mission statistics logs are still not being recorded. (Last stats that were written was on the 21st)

**Comment by ISeeDEDPpl** [comment]
I just updated questor last night (again) to fix the statistics. It is now in its own sub-state of combatMissionsBehavior.
https://github.com/ISeeDEDPpl/Questor/commit/cd90bed146dd3726f03b3b9ac3bdfa3641e6b023
and
https://github.com/ISeeDEDPpl/Questor/commit/5ba00636100531ea4f9dec268a27228d5cdb7a30
both part of current experimental:
https://github.com/ISeeDEDPpl/Questor
