### ISSUE TITLE
cd90bed compile errors

### ISSUE THREAD

**Issue by drokk99** [ISeeDEDPpl/Questor#230]
(CoreCompile target) ->
  Activities\Traveler.cs(234,85): error CS1061: 'Questor.Modules.Lookup.Setting
s' does not contain a definition for 'HomeBookmarkName' and no extension method
 'HomeBookmarkName' accepting a first argument of type 'Questor.Modules.Lookup.
Settings' could be found (are you missing a using directive or an assembly refe
rence?) [C:\Users\73546850\Desktop\ISeeDEDPpl-Questor-cd90bed\Questor.Modules\Q
uestor.Modules.csproj]
  Activities\Traveler.cs(248,144): error CS1061: 'Questor.Modules.Lookup.Settin
gs' does not contain a definition for 'HomeBookmarkName' and no extension metho
d 'HomeBookmarkName' accepting a first argument of type 'Questor.Modules.Lookup
.Settings' could be found (are you missing a using directive or an assembly ref
erence?) [C:\Users\73546850\Desktop\ISeeDEDPpl-Questor-cd90bed\Questor.Modules\
Questor.Modules.csproj]

**Comment by Chryst** [comment]
Yes i confirm that.

**Comment by ISeeDEDPpl** [comment]
fixed.
