### ISSUE TITLE
Move Mission COmpletion Items to Items Hangar

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#233]
It would seem that this is working fine, however Q is still looking in the corp ammo hangar for the items and then spitting the dummy when it cant find any diamond tags or gate keys because they are all in the items hangar! :dancer:

**Comment by ISeeDEDPpl** [comment]
hrm... best thing would be having arm look in both places.

**Comment by ISeeDEDPpl** [comment]
this has been fixed in latest experimental:
https://github.com/ISeeDEDPpl/Questor/commit/50817f178d5655c2994ea92558f256513a955a1f

this has not been tested but I see no reason why it would cause any issues.
