### ISSUE TITLE
Dedicated Salvager playing up..

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#234]
Version: ISeeDEDPpl-Questor-8558a35 (24/10/2012)

Questor undocks, warps to salvage bm, then switches to salvage, then immediately switches again to GoToBase, then to UnloadLoot and just sits in space.

EDIT: This seems to happen when cargo is full.

20:48:40 [UnloadLoot] Stacking items in Loot Hangar: resuming in [ 2 sec ]
20:48:42 [Cache.StackLootHangar] Stacking Corporate Loot Hangar: waiting [3sec]
20:48:43 [UnloadLoot] Stacking items in LootHangar timed out, clearing item locks
20:48:43 [UnloadLoot] Done, stacking LootHangar
20:48:45 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_ShipCargo_1005294960687', 1005294960687L)]
20:48:47 [CombatMissionsBehavior.BeginAftermissionSalvaging] Remove old Bookmark: salvage: 1148 BookmarExpirationDate: 24/10/2012 11:48:47 AM
20:48:47 [CombatMissionsBehavior.BeginAftermissionSalvaging] Remove old Bookmark: salvage: 1145 BookmarExpirationDate: 24/10/2012 11:48:47 AM
20:48:47 [CombatMissionsBehavior.BeginAftermissionSalvaging] Salvaging at first oldest bookmarks
20:48:47 [DedicatedBookmarkSalvagerBehavior] CheckBookmarkAge: There are [ 24 ] more salvage bookmarks older then:10/24/2012 13:23:47, left to process
20:48:48 [Arm] Activating salvage ship
20:48:49 [Arm] Done
20:48:50 [DedicatedBookmarkSalvagerBehavior.Salvager] Salvaging at first oldest bookmarks created on: 24/10/2012 11:53:13 AM
20:48:50 [TravelerDestination.BookmarkDestination] Destination set to bookmark [salvage: 1220]
20:48:53 [TravelerDestination.BookmarkDestination] This is not the destination station, undocking
20:49:20 [TravelerDestination.BookmarkDestination] Warping to bookmark [salvage: 1220][15.46 AU away]
20:50:28 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [salvage: 1220]
20:50:28 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: Gate not found, we can start salvaging
20:50:29 [DedicatedSalvageBehavior: Salvage] Opening Cargohold of active ship: waiting [3sec]
20:50:32 [DedicatedBookmarkSalvagerBehavior] It has been over 20 min since we were last in warp. Assuming something went wrong: setting GoToBase
20:50:33 [Traveler.TravelHome] HomeBookmarkName bookmark not found! Looking for bookmark starting with [myHomeBookmark] found none.
20:50:34 [DedicatedBookmarkSalvagerBehavior] UnloadLoot: Begin
20:52:31 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
20:53:31 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
20:54:32 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
20:55:32 [Questor] Wallet Balance Has Not Changed in [ 5 ] minutes.
20:56:33 [Questor] Wallet Balance Has Not Changed in [ 6 ] minutes.
20:57:34 [Questor] Wallet Balance Has Not Changed in [ 7 ] minutes.
20:58:35 [Questor] Wallet Balance Has Not Changed in [ 8 ] minutes.
20:59:36 [Questor] Wallet Balance Has Not Changed in [ 9 ] minutes.
21:00:37 [Questor] Wallet Balance Has Not Changed in [ 10 ] minutes.
21:01:38 [Questor] Wallet Balance Has Not Changed in [ 11 ] minutes.
21:01:52 [DedicatedBookmarkSalvagebehavior] Found [16] salvage bookmarks ready to process.
21:01:52 [DedicatedBookmarkSalvagerBehavior.Salvager] Salvaging at first oldest bookmarks created on: 24/10/2012 12:25:15 PM
21:01:52 [TravelerDestination.BookmarkDestination] Destination set to bookmark [salvage: 1240]
21:01:54 [TravelerDestination.BookmarkDestination] Warping to bookmark [salvage: 1240][20.34 AU away]
21:02:51 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [salvage: 1240]
21:02:51 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: Gate not found, we can start salvaging
21:02:52 [DedicatedBookmarkSalvagerBehavior] It has been over 20 min since we were last in warp. Assuming something went wrong: setting GoToBase
21:02:54 [Traveler.TravelHome] HomeBookmarkName bookmark not found! Looking for bookmark starting with [myHomeBookmark] found none.
21:03:43 [DedicatedBookmarkSalvagerBehavior] It has been over 20 min since we were last in warp. Assuming something went wrong: setting GoToBase
21:03:44 [Traveler.TravelHome] HomeBookmarkName bookmark not found! Looking for bookmark starting with [myHomeBookmark] found none.

**Comment by ISeeDEDPpl** [comment]
unfortunately the dedicated salvager will be broken until I can resolve this tonight / tomorrow. Somewhere the traveler destination needs to be reset and or the mode changed from AtDestination to Idle (which actually kicks the traveler into gear)

It is working fine in the CombatMissionsBehavior so a careful eye could probably just compare the traveler bits from one behavior to the other.

**Comment by ISeeDEDPpl** [comment]
this is fixed in current experimental: 
https://github.com/ISeeDEDPpl/Questor/commit/7a6b3327d389129fcd658a8622dece9b52bcf817

the non-combat mission modes will eventually (not yet) need a "home" bookmark for the station they live out of. 
This bug was related to that. for now they fall back to using the agent station as before.
