### ISSUE TITLE
PANIC PANIC PANIC

### ISSUE THREAD

**Issue by frbyles** [ISeeDEDPpl/Questor#235]
Every time i warp to my mission it does this   

15:07:03 [-] -----------------------------------------------------------------
15:07:03 [-] -----------------------------------------------------------------
15:07:03 [Statistics.ObjectStatistics] Logging info on the [2] objects in this pocket to [C:\Users\Wmachine\Documents\InnerSpace.NET Programs\lo
Ly - Driving a Wedge - Get the Gallente (1 of 2) - 0 - ObjectStatistics.csv]
15:07:04 [Panic] Warping will be attempted again after [4sec]
15:07:04 [CombatMissionCtrl] No bookmark created because the pocket has [0] wrecks/containers and the minimum is [1]
15:07:04 [CombatMissionCtrl] Activate: [Acceleration Gate] Move to next pocket after reload command and change state to 'NextPocket'
15:07:05 [Panic] Warping will be attempted again after [3sec]
15:07:33 [Panic] We've warped off:  Current ShipType: [Ishtar] Current ShipName [XL]
15:07:33 [Panic] Warping to [Oasa IX - Moon 11 - Ytiri Storage][9.44 AU away]
15:07:34 [Panic] Warping will be attempted again after [4sec]
15:08:06 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.

it does it on all 5 of my chars maybe new fork or new DE not sure

and these are my Panic settings 

  
  

  
  <minimumShieldPct>30</minimumShieldPct>
    ------------------------- changed this from 0 to 99
  <minimumArmorPct>99</minimumArmorPct>
  
  <minimumCapacitorPct>5</minimumCapacitorPct>
  
  <safeShieldPct>90</safeShieldPct>
     ---------- also from 0 to 100   didn't seem to matter tho
  <safeArmorPct>100</safeArmorPct>
  
  <safeCapacitorPct>85</safeCapacitorPct>

**Comment by Chryst** [comment]
Sorry but is only you have that error, for sure you have some wrong setting in the char xml.

Use default value in shield and capacitor and all is ok.

**Comment by ISeeDEDPpl** [comment]
fixed in current experimental. the panic settings were set to panic when 1 BS entered grid with the mission and it was counting itself in that calc =/

**Comment by frbyles** [comment]
nah it was in ur frk wen u fixed it few minutes after i posted this all was
wrkn good
