### ISSUE TITLE
Issue: Changing state out of goto mission into goto base out side of jump range of a jump gate causes insane approach spam

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#24]
If you are outside a jump gate's jump activation range and you switch questor state from goto mission to goto base... it casues insane approach spam.

**Comment by ISeeDEDPpl** [comment]
Approaching what? can you paste some logs?

**Comment by ghost** [comment]
Approaching the star gate... theres no console spam.

EXCEPTION #10 logged at  04/05/2012 22:50:31 Unhandled exception in <TaskletExt object at 12ca33f8, abps=1001, ctxt='<NO CONTEXT>^<bound method MenuSvc.Approach of <svc.MenuSvc instance at (snip)>>'>

/client/script/ui/services/menusvc.py(5312) Approach

UserError: [ThrottleGeneric.notify] None - Please wait... {'remainingTime': u'Less than one second'}

EXCEPTION #11 logged at  04/05/2012 22:50:33 Unhandled exception in <TaskletExt object at 313ebd40, abps=1001, ctxt='<NO CONTEXT>^<bound method MenuSvc.Approach of <svc.MenuSvc instance at (snip)>>'>

/client/script/ui/services/menusvc.py(5312) Approach

UserError: [ThrottleGeneric.notify] None - Please wait... {'remainingTime': u'Less than one second'}

And keeps going...

**Comment by ghost** [comment]
Fixed in future push!

**Comment by ISeeDEDPpl** [comment]
this should be fixed. confirm please.
