### ISSUE TITLE
Dedicated salvager relog in space error

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#241]
http://www.thehackerwithin.com
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
05:36:05 [Questor] Schedule: setup correctly: stoptime is [07:30]
05:36:05 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 634 MB
05:36:05 [Settings] Loading Settings from [C:\InnerSpace.NET Programs\CHARNAME.xml]
05:36:05 [Settings] MissionsPath is: [C:\InnerSpace.NET Programs\Caldari L4 Missions EXP V 23]
05:36:05 [Settings] Found only one agent in your character XML: MultiAgentSupport is [False]
05:36:05 [Settings] Loading Mission Blacklist
05:36:05 [Settings] Mission Blacklist now has [10] entries
05:36:05 [Settings] Loading Mission Greylist
05:36:05 [Settings] Mission Greylist now has [10] entries
05:36:05 [Settings] Loading Faction Blacklist
05:36:05 [Settings] Faction Blacklist now has [0] entries
05:36:05 [Cache] Unable to get agent details: trying again in a moment [Object reference not set to an instance of an
object.]AgentId
05:36:05 [Logging] Unable to get agent details: trying again in a moment [Object reference not set to an instance of an
object.]AgentId
05:36:05 [Cache.CurrentAgent] [ AGENTNAME ] AgentID [ -1 ]
05:36:05 [Settings] Unable to locate agent [AGENTNAME]
05:36:05 [Settings] Unable to locate agent [AGENTNAME]
05:36:05 [Settings] Unable to locate agent [AGENTNAME]
05:36:05 [Settings] Unable to locate agent [AGENTNAME]
05:36:05 [Settings] Unable to locate agent [AGENTNAME]
05:36:09 [Questor] Checking: Current time [10/28/2012 05:36:09] StopTimeSpecified [True] StopTime [ 28/10/2012
07:30:00] ManualStopTime = 28/10/2012 15:34:23
05:36:10 [Questor] Start Salvaging Behavior
05:36:36 [Questor] Running Innerspace command: WindowText EVE - Vendicator Venrasia
05:36:36 [Questor] Running Innerspace command: windowtaskbar on Vendicator Venrasia
Tray icon enabled

AND HERE IT STAY STOPPED IN SPACE WITHOUTH DOING NOTHING

**Comment by I3Questor** [comment]
ISDP: Version: ISeeDEDPpl-Questor-dd73b31

Add the agent to your address book.  This stops it happening most of the time, however I agree, it will still sometimes happen if you restart in space.

Also make sure when you are docked in station, you click on the agent tab and that it loads.

**Comment by Chryst** [comment]
Solved thx
