### ISSUE TITLE
Daylight Savings Time - Time Change bug - everything dies

### ISSUE THREAD

**Issue by ISeeDEDPpl** [ISeeDEDPpl/Questor#242]
<ISeeDEDPpl_> evidentally their is a questor DST bug. If daylight savings time hasnt kicked over for you yet I wouldnt run questor when the time changes until we fix some issues with timers using local time =/

**Comment by sigmastk** [comment]
I had same issue, everything stopped until I restarted Q. But it aint that bi issue if you ask me. That's twice a year anyway and now I know about it :)

Thanks for the heads up, but I think that you should not waste time on this ;)

**Comment by ISeeDEDPpl** [comment]
well, for some parts of the world DST has not changed yet, but will change on the 4th of Nov...

**Comment by sigmastk** [comment]
I haven't look at it that way, sorry for comment though ...

I just thought that it wont be equal trade that you put your time into reengineering time "calc" just for this issue :)

**Comment by ISeeDEDPpl** [comment]
should be fixed: https://github.com/ISeeDEDPpl/Questor/commit/41d3415304b2286804d585fe31980f01fc8dbefc

anyone care to test it?
