### ISSUE TITLE
fittings

### ISSUE THREAD

**Issue by test1234567xx** [ISeeDEDPpl/Questor#243]
Hello!
i noted Q not changed the fit for a specific mission...
last experimental version of ISEEDEDPPL...

17:16:50 [Cache] Mission: Worlds Collide - Faction: Default - Fitting: world - Ship: - ChangeMissionShipFittings: True

i have fit for rat kinds and mission fit aswell... always worked fine. now dunno why he haven't changed.

other log taken from new mission where Q dont change fit:
19:32:24 [Arm] Opening Item Hangar: waiting [3sec]
19:32:27 [Arm] neededDrones: 1
19:32:27 [Arm] Move [ 1 ] Drones into drone bay
19:32:29 [Arm] neededDrones: 0
19:32:29 [Arm] Fitting
19:32:31 [Arm] Opening Cargohold of active ship: waiting [1sec]
19:32:32 [Arm] Moving [1250] units of Ammo [Scourge Fury Heavy Missile] from [ AmmoHangar ] to CargoHold
19:32:33 [Arm] Waiting for items
19:32:47 [Arm] Done

this is xml part for fittings: i removed "<" at the beginning of everyline here because i cannot paste with "<"...
factionfittings>
factionfitting faction="Default" fitting="basic" />
factionfitting faction="Blood Raiders" fitting="sansha" />
factionfitting faction="Sansha's Nation" fitting="sansha" />
factionfitting faction="Angel Cartel" fitting="cartel" />
factionfitting faction="Guristas Pirates" fitting="guristas" />
factionfitting faction="Serpentis" fitting="serpentis" />
factionfitting faction="Mordu's Legion Command" fitting="mordus" />
/factionfittings>
missionfittings>
missionfitting mission="Angel Extravaganza" fitting="angel"/>
missionfitting mission="Worlds Collide" fitting="world"/>
/missionfittings>

any idea?
thanks in advance.

**Comment by ISeeDEDPpl** [comment]
this is now fixed:
https://github.com/ISeeDEDPpl/Questor/commit/d6ad03a119162c1b9acb131e5c4236673beb913b

https://github.com/ISeeDEDPpl/Questor
