### ISSUE TITLE
Adjust Questor to ONLY target / kill within Combat.cs, use PriorityTarget list 

### ISSUE THREAD

**Issue by ISeeDEDPpl** [ISeeDEDPpl/Questor#244]
Adjust Questor to ONLY target / kill within Combat.cs, use PriorityTarget list 

At the moment we have both CombatMissionCtrl and Combat targeting things, this is non-optimal and is likely causing some problems. Utilize the PriorityTarget list more liberally. 

**_AND TEST THESE CHANGES THOROUGHLY IN A BRANCH**_

**Comment by bugc** [comment]
Perhaps this is reason why I wrote:
http://forum.thehackerwithin.com/yaf_postsm7142_Mission-Actions.aspx#post7142

**Comment by ISeeDEDPpl** [comment]
bugc, no that is a different issue. 

This issue however has been fixed in bleedingedge. bugc, I replied to your forum post, you need to update to bleedingedge and reproduce your issue. If you still have probs with ignored NOCs that ewar being killed open a new issue for that.
