### ISSUE TITLE
Loyaltypoint statistic borked on initial startup

### ISSUE THREAD

**Issue by chantling** [ISeeDEDPpl/Questor#245]
I just got around to tracking down an issue that's been annoying me for some time; every few missions are logged with my entire LP amount, rather than the amount I earned in my mission.  Somehow I've never noticed that the first mission run on startup is always screwed until today.  And then any additional missions that happen immediately after the bot restarts.  When completing a mission, Questor currently checks to ensure that the agent's loyaltypoint count is not -1, but there's apparently no such check when accepting the first mission after the bot is started.  Problem can be fixed in AgentInteraction.cs AcceptMission() method.  Add the following code:

``` c#
            if (Cache.Instance.Agent.LoyaltyPoints == -1)
            {
                if (LoyaltyPointCounter < 10)
                {
                    Logging.Log("AgentInteraction", "Loyalty Points still -1; retrying", Logging.Red);
                    _nextAgentAction = DateTime.Now.AddMilliseconds(500);
                    LoyaltyPointCounter++;
                    return;
                }
            }
            LoyaltyPointCounter = 0;
            Statistics.Instance.LoyaltyPoints = Cache.Instance.Agent.LoyaltyPoints;
```

immediately above

``` c#
            Logging.Log("AgentInteraction", "Saying [Accept]", Logging.Yellow);
            Cache.Instance.Wealth = Cache.Instance.DirectEve.Me.Wealth;
            accept.Say();
```

Add a private global int LoyaltyPointCounter with a value of 0 at the top and you should be golden. 

Technically shouldn't need to assign Cache.Instance.Agent.LoyaltyPoints to Statistics.Instance.LoyaltyPoints as that's done elsewhere (closing conversation? can't remember) but I was in a hurry and couldn't be arsed to track the code back to make sure nothing might go wrong without the assignment.

**Comment by ISeeDEDPpl** [comment]
this should now be part of experimental. thank you.
