### ISSUE TITLE
Salvager not moving loot to container

### ISSUE THREAD

**Issue by thul** [ISeeDEDPpl/Questor#246]
I have setup a loot container in my item hanger (personal hangar) after salvaging the bot doesnt seem to want to move the items it salvaged / looted. But if i manually put the loot in, it does continue.

Any idea what could cause this?

**Comment by ISeeDEDPpl** [comment]
yes, lootcontainer is currently broken (again).

I will look into fixing it over the next few days. for now use the local items hangar for loot (by removing the lootcontainer setting)

**Comment by thul** [comment]
even the item hangar doesn't seem to be working

18:39:34 [CombatMissionsBehavior.TravelHome] Arrived at destination
18:39:35 [CombatMissionsBehavior] UnloadLoot: Begin
18:39:37 [Unloadloot.MoveAmmo] Opening Cargohold of active ship: waiting [1sec]
18:39:39 [Unloadloot.MoveAmmo] Opening Item Hangar: waiting [3sec]
18:39:43 [Unloadloot.MoveAmmo] Stacking Item Hangar: waiting [3sec]
18:39:47 [UnloadLootState.MoveAmmo] Item Hangar: is closed
18:39:47 [UnloadLootState.MoveAmmo] Closing AmmoHangar Hangar
18:39:47 [UnloadLoot.MoveAmmo] Done Moving Ammo
18:39:47 [Unloadloot.MoveAmmo] Opening Item Hangar: waiting [5sec]
18:41:48 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.

this is the log, it just stays there. no output the bots seems to be waiting for the item hangar to be opened but its open already and its not registering it.

this is when questor is first started

**Comment by thul** [comment]
After doing a missiong and salvaging the bot returns home and attempts to put the loot in the item hangar and it seems to think it moved the items but didn't do anything though.

**Comment by Irenicus1977** [comment]
I have the same issue + 1
Using  latest commit 29dfd264a7

**Comment by ISeeDEDPpl** [comment]
this should no longer be a problem. please make it known if this issue is still occurring in a recent commit.
