### ISSUE TITLE
Null Pointer Reference during storyline agentinteraction

### ISSUE THREAD

**Issue by Hook80906** [ISeeDEDPpl/Questor#248]
I get a Null pointer reference exception every time a story line is attempted to be accepted on this line:

AgentInteraction.cs:

119            if (Agent.Window.AgentResponses == null || !Agent.Window.AgentResponses.Any())

It appears that the current agent is not being set properly. The agent window from the non storyline is open instead of the agent window from the storyline agent.

**Comment by ISeeDEDPpl** [comment]
should be fixed here: https://github.com/ISeeDEDPpl/Questor/commit/29dfd264a760d8b941e5ecfcfeca81852db9069e

probably ought to be tested...

**Comment by Hook80906** [comment]
Looks good so far. Successfully completed one storyline.
