### ISSUE TITLE
fitting: issue #243 still problems

### ISSUE THREAD

**Issue by test1234567xx** [ISeeDEDPpl/Questor#249]
referring to issue (closed) #243:

version f21bf (just compiled now):
same problem....

log:
23:43:56 [Arm.MoveDrones] Opening Item Hangar: waiting [5sec]
23:44:01 [Arm.MoveDrones] neededDrones: 1
23:44:01 [Arm.MoveDrones] Move [ 1 ] Drones into drone bay
23:44:03 [Arm.MoveDrones] neededDrones: 0
23:44:03 [Arm.MoveDrones] Fitting
23:44:04 [Arm.LoadSavedFitting] Default Fitting Name [def]
23:44:04 [Arm.LoadSavedFitting] Opening fitting manager: waiting [1sec]
23:44:05 [Arm] Closing Fitting Manager Window
23:44:06 [Arm.MoveItems] Opening Cargohold of active ship: waiting [1sec]

mission against angel should switch to "cartel" fit...
actual fit is not "default", but "sansha"... btw Q have to switch to "cartel"...

:(((

**Comment by Blafasl** [comment]
Can confirm with commit 29dfd264a760d8b941e5ecfcfeca81852db9069
Have the same Problem, he should switch to an angel fitting, but ignores it and tries to start the mission with the default one. Not the best idea on missions like Angel Extravaganza.

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/eb464c1a8f7fdab80efbbe500dd31e2e95bdfdf4
