### ISSUE TITLE
Bug: Agent Interaction bugged and crashing EVE or hanging questor @

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#25]
<eveguy> I have a guy who seems to hang on this:
<eveguy> 17:40:28 AgentInteraction: Replying to agent
<eveguy> 17:40:35 AgentInteraction: Saying [View Mission]
<eveguy> 17:40:59 Questor: Wallet Balance Has Not Changed in [ 2 ] minutes.
<eveguy> 17:41:02 AgentInteraction: Waiting for mission
<eveguy> 17:41:15 AgentInteraction: WaitForMission: mission == null : waiting

or

03:56:45 Questor: EVE instance: totalMegaBytesOfMemoryUsed - 876 MB
03:56:46 AgentInteraction: Start conversation [Start Mission]
03:56:47 AgentInteraction: Waiting for conversation

then crash and eve restart BUT with the GUI window opening again? WTF?

**Comment by ISeeDEDPpl** [comment]
See if this can be reproduced after the last round of changes. I have not experienced this with my toons.

**Comment by ISeeDEDPpl** [comment]
```
        var mission = Cache.Instance.DirectEve.AgentMissions.FirstOrDefault(m => m.AgentId == AgentId);
        if (mission == null)
        { 
            if (DateTime.Now.Subtract(_waitingonmissiontimer).TotalSeconds > 60)
            {
                Logging.Log("AgentInteraction: WaitForMission: mission == null : waiting");
                _waitingonmissiontimer = DateTime.Now;
                if (Math.Round(DateTime.Now.Subtract(Cache.Instance.lastKnownGoodConnectedTime).TotalMinutes) > 7)
                {
                    Cache.Instance.CloseQuestorCMDLogoff = false;
                    Cache.Instance.CloseQuestorCMDExitGame = true;
                    Cache.Instance.ReasonToStopQuestor = "AgentInteraction: WaitforMission: Journal would not open/refresh - mission was null: restarting EVE Session";
                    Logging.Log(Cache.Instance.ReasonToStopQuestor);
                    Cache.Instance.SessionState = "Quitting";
                }
            }

            return;
        }
```

may be causing eve to restart, but it needs to as the mission hasn't refreshed and will not refresh... and as you can see it should be logged both to the console and to the session log.  

This could have easily been related to the earlier slowness in station issues... if this issue repeats itself open a new issue please.
