### ISSUE TITLE
traveler problem

### ISSUE THREAD

**Issue by test1234567xx** [ISeeDEDPpl/Questor#251]
when Q need to change system for doing mission:

15:33:15 [Traveler] Error [Amarr] not found, most likely lag waiting [15] seconds.
15:33:50 [Traveler] Error [Amarr] not found, most likely lag waiting [15] seconds.
15:34:05 [Traveler] Error [Amarr] not found, most likely lag waiting [15] seconds.

version d6...

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/b1d93764a02e8405f1baf145926b57b015b2f2c6
