### ISSUE TITLE
Manual stop time wrong.

### ISSUE THREAD

**Issue by drokk99** [ISeeDEDPpl/Questor#253]
09:46:05 [Startup] We have successfully logged in
09:46:07 [Questor] Schedule: NOT setup correctly: stoptime set to [10] hours from now at [7:46 PM]
...
09:46:12 [Questor] Checking: Current time [11/02/2012 23:46:12] StopTimeSpecified [True] StopTime [ 3/11/2012 7:46:07 PM] ManualStopTime = 3/11/2012 9:44:04 AM
09:46:12 [Questor] Time to stop. ManualRestartTime reached. Quitting game.
09:46:12 [Questor] Settings.Instance.CharacterMode = [Combat Missions]
09:46:12 [QuestorState.CloseQuestor] Writing Session Data [1]
09:46:12 [Statistics: WriteSessionLogClosing] 3/11/2012 9:46:12 AM;0;Quitting!!;;0;668;ManualRestartTime reached.;0;0;0;0;0;0;0;

as you can see, while not using scheduler, it sets stop time to 10hrs from current, then sets it to current time a few seconds later and restarts.
Using 84cdd5

**Comment by ISeeDEDPpl** [comment]
is your local TimeZone 10 hours different from GMT?

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/e002200b9cf940caf33e177ec34df831def30df3
I think. 

needs testing.
