### ISSUE TITLE
lootitem issue commit a9dc743

### ISSUE THREAD

**Issue by EchuI** [ISeeDEDPpl/Questor#256]
```
<debugLootWrecks>true</debugLootWrecks>

10:07:47 [Combat] Activating weapon [1] on [Pithi Imputor][ID: 9000000000002013764][23k away]
10:07:54 [CombatMissionCtrl] Finished Action.ClearPocket
10:07:54 [CombatMissionCtrl] Starting Action.LootItem [item: Militants]
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.
   at Questor.Modules.Activities.CombatMissionCtrl.LootItemAction(Action action)
   at Questor.Modules.Activities.CombatMissionCtrl.PerformAction(Action action)
   at Questor.Modules.Activities.CombatMissionCtrl.ProcessState()
   at Questor.Behaviors.CombatMissionsBehavior.ProcessState()
   at Questor.Questor.OnFrame(Object sender, EventArgs e)
   at ..(DirectEve , Object , EventArgs )
   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
10:09:37 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
10:10:38 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
10:11:38 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
```

After manual opening of the cargohold error disappears, but Q still does not loot the missionitem

**Comment by ISeeDEDPpl** [comment]
I am not having any issues with lootitem atm, no exceptions and missions using this action complete successfully.

**Comment by EchuI** [comment]
commit df91c649fc, problem persists
Maybe any ideas?

```
10:28:09 [CombatMissionCtrl] Finished Action.ClearPocket
10:28:09 [CombatMissionCtrl] Starting Action.LootItem [target: Cargo Container] [item: AIMEDs]
10:28:10 [CombatMissionCtrl.LootItem [target: Cargo Container] [item: AIMEDs]] Approaching target [Cargo Container][ID: 9000000000000900810] which is at [42k away]
10:30:15 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
10:31:16 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
10:32:16 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
10:33:16 [Questor] Wallet Balance Has Not Changed in [ 5 ] minutes.
//manual closing cargohold
10:34:13 [Combat.TargetCombatants] Opening Cargohold of active ship: waiting [1sec]
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.
   at Questor.Modules.Activities.CombatMissionCtrl.LootItemAction(Action action)
   at Questor.Modules.Activities.CombatMissionCtrl.PerformAction(Action action)
   at Questor.Modules.Activities.CombatMissionCtrl.ProcessState()
   at Questor.Behaviors.CombatMissionsBehavior.ProcessState()
   at Questor.Questor.OnFrame(Object sender, EventArgs e)
   at ..(DirectEve , Object , EventArgs )
   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
10:34:17 [Questor] Wallet Balance Has Not Changed in [ 6 ] minutes.
```

**Comment by ISeeDEDPpl** [comment]
this should hopefully be fixed now. please test and re-post logs as needed. 
you should also try to have the *pdb files in your questor directory so that we get line numbers with exceptions like this one. 

https://github.com/ISeeDEDPpl/Questor/commit/91d08796b6d75b86a698a3fb31c9e92ddb8fde1a

**Comment by EchuI** [comment]
Now the manual closing of the cargohold does not cause an exception, but mission item is still not looted. Also, do not start the timer change wallet

```
<debugLootWrecks>true</debugLootWrecks>
<debugSalvage>true</debugSalvage>
```

```
22:12:32 [CombatMissionCtrl] Finished Action.ClearPocket
22:12:32 [CombatMissionCtrl] Starting Action.LootItem [target: Phenod's Broke-Ass Destroyer Wreck] [item: Phenod's DNA]
22:12:33 [CombatMissionCtrl.LootItem [target: Phenod's Broke-Ass Destroyer Wreck] [item: Phenod's DNA]] Approaching target [Phenod's
Broke-Ass Destroyer Wreck][ID: 9000000000000664785] which is at [14k away]
```

**Comment by ISeeDEDPpl** [comment]
is it just that one mission?
I am seeing LootItem work fine here during multiple missions... is it possible that it is just this one mission? just this one mission action (spelling, item we are pulling, etc?)

If I can narrow down what is broken it'll be easier to fix.

**Comment by EchuI** [comment]
No, all missions with lootitem. But there is one oddity - the bug does not occur in all the characters. I have already tried to re-create charname.xml, tried to copy it from those characters, which all works, only replacing the name of ship, agent, the type of ammunition and weapons.
For example:

```
<?xml version="1.0" encoding="utf-8" ?>
<mission>
  <pockets>
    <pocket id="0">
      <damagetype>Kinetic</damagetype>
      <actions>
        <action name="ClearPocket" />
        <action name="Activate">
          <parameter name="target" value="Acceleration Gate" />
        </action>
      </actions>
    </pocket>
    <pocket id="1">
      <damagetype>Kinetic</damagetype>
      <actions>
        <action name="ClearPocket" />
        <action name="Kill">
          <parameter name="Target" value="Warehouse" />
        </action>
        <action name="LootItem">
          <parameter name="Target" value="Cargo Container"/>
          <parameter name="Item" value="Small Sealed Cargo Containers"/>
        </action>
        <action name="Done" />
      </actions>
    </pocket>
  </pockets>
</mission>
```

**Comment by ISeeDEDPpl** [comment]
very odd. does anyone else have a toon that this is setting stuck while processing a lootitem action (or a general loot action)?

Echul, what ship, speed tank true or false? Do other loot actions work ok? (i.e. will this toon loot at all?)

**Comment by ceem82** [comment]
Having the issue, that both of my Golem-Toons doesn't loot anything, loot and mission-items.
In the console the action ist listed, but the ship does not loot anything. Sometimes it thinks it has looted and tries to go on.

My Tengu-Toons are working fine, looting mission-items and looting the rest with the noctis.

Error comes after upgrade to 428284b79c27ef91b31fed3180b1526b8bbff041, but I don't remember which Version I used before. Must have been one or two weeks old.

Going to make some logs.

**Comment by EchuI** [comment]
I tried both, with and without speedtank. I have also tried to change lootitem and loot, but both options do not work. In addition, I tried to change the type of ship, the type of weapon, agent. Tried to put the ship tractorbeam. Q does not loot a missionitem, even if you manually open the wreck or container.

**Comment by ISeeDEDPpl** [comment]
Is it possible you are seeing exception sin the innerspace console? try "log nameOfMyLogBlah.log" and then reproduce the issue and look at the log you created, it will be in the innerspace directory. It will possibly have a little more info... 

logs with debug options on like:
`<debugLootWrecks>true<debugLootWrecks>`
`<debugCargoHold>true<debugCargoHold>`
would be helpful

**Comment by ceem82** [comment]
14:49:06 o[y-o] t-----------------------------------------------------------------
14:49:06 o[y-o] t-----------------------------------------------------------------
14:49:06 o[yCombatMissionCtrlo] tMission Timer Currently At: [7] min
14:49:06 o[yCombatMissionCtrlo] tMax Range is currently: 60k
14:49:06 o[y-o] t-----------------------------------------------------------------
14:49:06 o[y-o] t-----------------------------------------------------------------
14:49:06 o[yCombatMissionCtrlo] oPocket [0] loaded, executing the following actions
14:49:06 o[yCombatMissionCtrlo] tAction [ 1 ] WaitUntilTargeted [timeout: 30]
14:49:06 o[yCombatMissionCtrlo] tAction [ 2 ] ClearPocket
14:49:06 o[yCombatMissionCtrlo] tAction [ 3 ] Loot [target: Cargo Container] [item: Gate Key]
14:49:06 o[yCombatMissionCtrlo] tAction [ 4 ] Activate [target: Acceleration Gate]
14:49:06 o[y-o] t-----------------------------------------------------------------
14:49:06 o[y-o] t-----------------------------------------------------------------
...
After waiting for getting targeted and after clearing the Pocket, Looting Action ist reached.
...
14:54:03 o[yCombatMissionCtrl.Loot [target: Cargo Container] [item: Gate Key]o] tApproaching target [Cargo Container][ID: 9000000000000100353][51k away]
14:54:04 o[yCombato] wDebugHangars: cargoHold window is ready and is a secondary inventory window
14:54:04 o[ySalvageo] wDebugHangars: cargoHold window is ready and is a secondary inventory window
14:54:05 o[yCombat.TargetCombatantso] wDebugHangars: cargoHold window is ready and is a secondary inventory window
...
Here it ends with repeating the last 3 Log-entries for over 1 hour, until I stopped the bot manually.
The Combat and Combat.TargetCombatants are also active after leaving the Missions.
...
15:52:56 o[yCombato] wDebugHangars: cargoHold window is ready and is a secondary inventory window
15:52:57 o[yCombat.TargetCombatantso] wDebugHangars: cargoHold window is ready and is a secondary inventory window
15:52:58 o[yCombato] wDebugHangars: cargoHold window is ready and is a secondary inventory window
15:52:59 o[yCombat.TargetCombatantso] wDebugHangars: cargoHold window is ready and is a secondary inventory window
15:53:00 o[yCombato] wDebugHangars: cargoHold window is ready and is a secondary inventory window
15:53:01 o[yCombat.TargetCombatantso] wDebugHangars: cargoHold window is ready and is a secondary inventory window
15:53:02 o[yCombato] wDebugHangars: cargoHold window is ready and is a secondary inventory window
15:53:04 o[yTravelerDestination.StationDestinationo] gArrived in station
...

This just happens on my Golem-Chars with Tractor and Salvager fitted. Tengu's are fine.
The Mission from the log was Dread Pirate Scarlet, but same behavior on other Missions. The Golem never uses Tractor or Salvager. (I'll try to make some logs with Salvage-Debug active)
Questor-Version was latest experimental.

**Comment by ceem82** [comment]
After upgrading to 917f6f93dce3006ea37b2e93b8a759751f6cd520 all is working fine again.

**Comment by ISeeDEDPpl** [comment]
anyone else having trouble with this using latest experimental or latest bleedingedge?

**Comment by Pluckyduck** [comment]
i have not had problem with the latest experimental, i have yet to test the bleedingedge.
