### ISSUE TITLE
last version not work

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#257]
not work i have this error

Exception during event execution: System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.

   in Questor.Modules.Activities.CombatMissionCtrl.LootAction(Action action) in
c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor.Modules\Activities\CombatMissionCtrl.cs:riga 1337

   in Questor.Modules.Activities.CombatMissionCtrl.PerformAction(Action action) in
c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor.Modules\Activities\CombatMissionCtrl.cs:riga 1491

   in Questor.Modules.Activities.CombatMissionCtrl.ProcessState() in c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor.Modules\Activities\CombatMissionCtrl.cs:riga 1642

   in Questor.Behaviors.CombatMissionsBehavior.ProcessState() in c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor\Behaviors\CombatMissionsBehavior.cs:riga 692

   in Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor\Questor.cs:riga 553

   in ..(DirectEve , Object , EventArgs )

   in DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   in LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by ISeeDEDPpl** [comment]
This has been fixed (I think).
please test and confirm.

**Comment by marivx** [comment]
Not work, not start to shoot the npc

**Comment by marivx** [comment]
in DirectEve.DirectContainer.StackAll()

   in Questor.Modules.Caching.Cache.StackItemsHangarAsLootHangar(String module) in
c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor.Modules\Caching\Cache.cs:riga 2744

   in Questor.Modules.Caching.Cache.StackLootHangar(String module) in
c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor.Modules\Caching\Cache.cs:riga 4148

   in Questor.Modules.Actions.UnloadLoot.MoveLoot() in
c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor.Modules\Actions\UnloadLoot.cs:riga 177

   in Questor.Modules.Actions.UnloadLoot.ProcessState() in
c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor.Modules\Actions\UnloadLoot.cs:riga 411

   in Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor\Behaviors\CombatMissionsBehavior.cs:riga 869

   in Questor.Questor.OnFrame(Object sender, EventArgs e) in
c:\Users\MatteoAcer\Desktop\Questor-experimental\Questor\Questor.cs:riga 553

   in ..(DirectEve , Object , EventArgs )

   in DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

**Comment by marivx** [comment]
still not work

**Comment by marivx** [comment]
16:56:56 [Cache.StackLootHangar] Stacking Item Hangar
16:56:57 [Cache.StackLootHangar] Stacking Item Hangar
16:56:59 [Cache.StackLootHangar] Stacking Item Hangar
16:57:00 [Cache.StackLootHangar] Stacking Item Hangar
16:57:01 [Cache.StackLootHangar] Stacking Item Hangar
16:57:02 [Cache.StackLootHangar] Stacking Item Hangar
16:57:03 [Cache.StackLootHangar] Stacking Item Hangar
16:57:04 [Cache.StackLootHangar] Stacking Item Hangar
16:57:05 [Cache.StackLootHangar] Stacking Item Hangar
16:57:06 [Cache.StackLootHangar] Stacking Item Hangar
16:57:07 [Cache.StackLootHangar] Stacking Item Hangar
16:57:08 [Cache.StackLootHangar] Stacking Item Hangar
16:57:09 [Cache.StackLootHangar] Stacking Item Hangar
16:57:10 [Cache.StackLootHangar] Stacking Item Hangar
16:57:11 [Cache.StackLootHangar] Stacking Item Hangar
16:57:12 [Cache.StackLootHangar] Stacking Item Hangar
16:57:13 [Cache.StackLootHangar] Stacking Item Hangar
16:57:14 [Cache.StackLootHangar] Stacking Item Hangar
16:57:15 [Cache.StackLootHangar] Stacking Item Hangar

**Comment by marivx** [comment]
There is problem when compile

not work

**Comment by Pluckyduck** [comment]
works fine on my end. are you using corp or personal hanger?  station container?

**Comment by Pluckyduck** [comment]
details of what step you made it to and settings, would very helpful for finding your error.

**Comment by marivx** [comment]
at me not compile

**Comment by marivx** [comment]
use the compile file but not work

**Comment by ISeeDEDPpl** [comment]
then you are doing it wrong. latest experimental currently compiles fine. can you hop on irc?
