### ISSUE TITLE
Troubles on salvaging

### ISSUE THREAD

**Issue by Agorash** [ISeeDEDPpl/Questor#259]
Everytime in auto goes to salvage:
03:28:44 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [XXXXXXXXXXXX]
03:28:45 [CombatMissionsBehavior.Salvage] We are full, go to base to unload
03:28:46 [CombatMissionsBehavior.TravelHome] Destination: [XXXXXXX - Moon XX - XXXXXXXXXXXXXXX]

Inventory is empty, not full. If I force it to pause and start on salvage may work or try again to go to base.

**Comment by Irenicus1977** [comment]
Have the same issue, using last commit 1cc0f2113a0c1c0c8984b52e99ec1fc25105093a

**Comment by Agorash** [comment]
I tested some times to force salvage without exit until I opened manually cargohold and forced it again. Seems to work when cargohold is open, can it be a solution? If it is, can be opened automatically?

**Comment by ISeeDEDPpl** [comment]
With latest experimental it should already be opened... I'll look at testing the after mission salvaging and dedicated salvager tomorrow night

**Comment by Agorash** [comment]
Updated last questor build modified today. I'm testing now, seems to be ok.
