### ISSUE TITLE
???: GUI Window opening after agent interaction eve restart 'crash' but not opening after PING TIMEOUT!

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#26]
Questor GUI window re-opens after the agent interaction crash... but not after a ping timeout reset.

**Comment by ISeeDEDPpl** [comment]
the agent interaction crash likely isnt a crash at all, but bot deciding to restart questor becuase it cant detect the agent interaction window.

**Comment by ghost** [comment]
Checking this out, doesnt seem likely ill get this again.
