### ISSUE TITLE
storyline not work

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#261]
12:40:12 [MaterialsForWar] PreAcceptMission: ItemHangar is null
12:40:13 [MaterialsForWar] PreAcceptMission: ItemHangar is null
12:40:14 [MaterialsForWar] PreAcceptMission: ItemHangar is null
12:40:15 [MaterialsForWar] PreAcceptMission: ItemHangar is null
12:40:16 [MaterialsForWar] PreAcceptMission: ItemHangar is null
12:40:17 [MaterialsForWar] PreAcceptMission: ItemHangar is null
12:40:18 [MaterialsForWar] PreAcceptMission: ItemHangar is null
12:40:19 [MaterialsForWar] PreAcceptMission: ItemHangar is null

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/fdc9fb480fff3375532bb0c02eda7f1ab0f7426a
