### ISSUE TITLE
Cannot activate listed ship

### ISSUE THREAD

**Issue by Agorash** [ISeeDEDPpl/Questor#262]
That's the log:

03:56:24 [Arm] Activating combat ship
03:56:25 [Arm.ActivateCombatShip] Found the following ships:
03:56:25 [Arm.ActivateCombatShip] []
03:56:25 [Arm.ActivateCombatShip] []
03:56:25 [Arm.ActivateCombatShip] []
03:56:25 [Arm.ActivateCombatShip] Could not find [XXXXXX] ship!
03:56:25 [Arm] Armstate.NotEnoughAmmo

Checked ship name, in older versions has no failed never. If I force to [Arm] again, in the first force try or second it switch to proper ship fine, but fails sometimes with no aparently reason.

**Comment by ISeeDEDPpl** [comment]
hrm.. ok, Ill look into it.

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/1b8458dfcd2fe14fcd514456c195d8bda429ff44
