### ISSUE TITLE
Unable to activate transport ship for Generic Courier Storyline

### ISSUE THREAD

**Issue by Hook80906** [ISeeDEDPpl/Questor#263]
GenericCourierStoryline.cs line 51 Should read:

```
        string transportshipName = Settings.Instance.TransportShipName.ToLower();
```

instead of:

```
        string transportshipName = Settings.Instance.TransportShipName;
```

**Comment by Pluckyduck** [comment]
a simple way of fighting this problem is to lower case your ship names to begin with.

**Comment by ISeeDEDPpl** [comment]
thx for the patch.

https://github.com/ISeeDEDPpl/Questor/commit/7d56348ab395c2d00d9ad7d1d836517daa8e717f

**Comment by marivx** [comment]
not work
