### ISSUE TITLE
Start time set to UTC time in program.cs

### ISSUE THREAD

**Issue by Hook80906** [ISeeDEDPpl/Questor#265]
Line 351 of  Program.cs

Should be:

```
        StartTime = DateTime.Now;
```

Instead of:

```
        StartTime = DateTime.UtcNow;
```

**Comment by ISeeDEDPpl** [comment]
fixed, thx

https://github.com/ISeeDEDPpl/Questor/commit/be5fb806358ff1993aedd9c03ade661fd6d6b7a6
