### ISSUE TITLE
IU assume its related to us losing the characterName when eve lags

### ISSUE THREAD

**Issue by grdk** [ISeeDEDPpl/Questor#266]
I assume its related to us losing the characterName when eve lags out (and auto logs off eve)... make an issue for that. Ill look into changing how the settings file is loaded (and re-loaded) so it is not so intertwined with Me.CharacterName

**Comment by Chryst** [comment]
Same, i confirm that problem.

**Comment by yomon598** [comment]
I think this is related to issue 272, which I submitted earlier.

**Comment by ISeeDEDPpl** [comment]
this has been fixed in the bleedingedge branch, and needs testing
