### ISSUE TITLE
Fix Mission Statistics - Value of salvage is incorrect (0?)

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#27]
Questor not properly write statistics in file. 
Example:
2012-04-04 09:20:50;Smuggler Interception;74;0;74;9619798;0;-155780;
I always salvage after the mission but questor not always write value of salvage.

**Comment by ghost** [comment]
The LP value is also wrong.

**Comment by ISeeDEDPpl** [comment]
Can you verify this is still a problem with current experimental?

**Comment by oldmeat** [comment]
LP now work properly, salvage on first mission dont count, two next mission salvage count properly. 
Test yet on other toons. Reviews tomorrow.
