### ISSUE TITLE
COURIER/DELIVERY - MINMATAR

### ISSUE THREAD

**Issue by Irenicus1977** [ISeeDEDPpl/Questor#270]
We need to update Storyline.cs and add some MINMATAR COURIER MISSIONS:
/\* COURIER/DELIVERY - MINMATAR */
{"Very Important Pirates", new GenericCourier()},

**Comment by ISeeDEDPpl** [comment]
done: https://github.com/ISeeDEDPpl/Questor/commit/c984ab6133e1328bfe4bed7357871eff3b9c1fde
