### ISSUE TITLE
storyline NOT WORKKK

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#273]
Accept mission and questor stop not move again....

13:05:08 [AgentInteraction] Detected configured damage type for [A Desperate Rescue] is [EM]
13:05:08 [AgentInteraction] Accepting mission [A Desperate Rescue]
13:05:12 [AgentInteraction] Loyalty Points still -1; retrying
13:05:13 [AgentInteraction] Saying [Accept]
13:05:13 [AgentInteraction] Closing conversation
13:05:18 [AgentInteraction] Attempting to close Agent Window
13:05:20 [AgentInteraction] Done
13:05:21 [TravelerDestination.MissionBookmarkDestination] Destination set to mission bookmark [Objective (Pick Up)
& Agent Base - Kakakela]
13:05:45 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
13:06:45 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
13:07:45 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.

**Comment by marivx** [comment]
material of war too , not work

**Comment by sigmastk** [comment]
I can confirm same issue.

**Comment by ISeeDEDPpl** [comment]
this could now be fixed, please confirm fixed or broken.

**Comment by marivx** [comment]
ATM all work fine
