### ISSUE TITLE
questor doesn't close client on exit

### ISSUE THREAD

**Issue by yomon598** [ISeeDEDPpl/Questor#276]
questor doesn't seem to close the eve client on exist;its state is UnloadLoot:Error and the console log reads:

04:41:48 [CombatMissionsBehavior] UnloadLoot: Begin
04:41:49 [Unloadloot.MoveAmmo] Moving [4] Ammo Stacks to AmmoHangar
04:41:50 [Unloadloot.MoveAmmo] will Continue in [ 2 ] sec
04:41:51 [Unloadloot.MoveAmmo] will Continue in [ 1 ] sec
04:41:53 [Unloadloot.MoveAmmo] Moving [1] Mission Completion items to ItemHangar
04:41:54 [Unloadloot.MoveAmmo] will Continue in [ 2 ] sec
04:41:55 [Unloadloot.MoveAmmo] will Continue in [ 1 ] sec
04:41:57 [StackItemsHangarAsAmmoHangar] test
04:41:57 [Unloadloot.MoveAmmo] Stacking Item Hangar
04:41:58 [UnloadLoot.MoveAmmo] Done Moving Ammo
04:41:58 [StackItemsHangarAsAmmoHangar] test
04:41:59 [UnloadLoot.MoveLoot] Moving [79] items from CargoHold to LootHangar
04:42:00 [Cache.StackLootHangar] Stacking Item Hangar
04:42:01 [UnloadLoot.MoveLoot] Loot was worth an estimated [17,048,382] isk in buy-orders
04:42:01 [CombatMissionsBehavior.Unloadloot] CharacterMode: [Combat Missions], AfterMissionSalvaging: [False], CombatMissionsBehaviorState: [Idle]
04:42:02 [Questor] Checking: Current time [11/23/2012 04:42:02] StopTimeSpecified [True] StopTime [ 11/23/2012 4:10:00 AM] ManualStopTime = 11/23/2012 9:27:06 AM
04:42:02 [Questor] Time to stop. StopTimeSpecified and reached. Quitting game.
04:42:02 [Questor] Settings.Instance.CharacterMode = [Combat Missions]
04:42:02 [QuestorState.CloseQuestor] Writing Session Data [1]
04:42:02 [Statistics: WriteSessionLogClosing] 11/23/2012 4:42:02 AM;0;Quitting!!;;1618727406.2704;646;StopTimeSpecified and reached.;62563019;32868561;367153;19464470.6496355;10225995.3420767;68536706.5719026;98227171;
04:42:02 [Statistics: WriteSessionLogClosing] Writing to session log [ C:\innerspace.NET Programs\log\CHARNAME\CHARNAME.Sessions.log
04:42:03 [Statistics: WriteSessionLogClosing] Questor is stopping because: StopTimeSpecified and reached.
04:42:03 [Questor] Autostart is false: Stopping EVE with quit command (if EVE is going to restart it will do so externally)
04:42:03 [Questor] Exiting eve in [20] seconds

Even though it says it will close eve in 20s, it does not do so.This is rather annoying because, unless careful, the characters can remain logged in long enough.

**Comment by Pluckyduck** [comment]
+1, this did cause my error notification to pop up but since the new updates the pop up went away but the client does not close.

**Comment by ISeeDEDPpl** [comment]
This should now be resolved.
