### ISSUE TITLE
Framework crashes

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#277]
Framework sometimes crashes when the end time of the tasks of file Schedules.

System.NullReferenceException: Object reference not set to an instance of an object.
   in ..( , String )
   in ..(DirectSession )
   in DirectEve.DirectSession.get_CharacterId()
   in DirectEve.DirectMe..ctor(DirectEve )
   in DirectEve.DirectEve.get_Me()
   in Questor.Modules.Logging.Statistics.WriteSessionLogClosing() in c:\Questor\Questor-experimental\Questor.Modules\Logging\Statistics.cs:line 359
   in Questor.Modules.BackgroundTasks.Cleanup.CloseQuestor() w c:\Questor\Questor-experimental\Questor.Modules\BackgroundTasks\Cleanup.cs:line 57
   in Questor.QuestorfrmMain.UpdateUiTick(Object sender, EventArgs e) in c:\Questor\Questor-experimental\Questor\QuestorUI.cs:line 588
   in System.Windows.Forms.Timer.OnTick(EventArgs e)
   in System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by I3Questor** [comment]
+1

Running current Experimental Version.

**Comment by ISeeDEDPpl** [comment]
fixed in current experimental.
