### ISSUE TITLE
loot and kill (others?) should match on contains, not starts with.

### ISSUE THREAD

**Issue by ISeeDEDPpl** [ISeeDEDPpl/Questor#28]
this would enable us to do things like:

action name="Loot"
          parameter name="target" value="Personnel Transport Wreck" /
          parameter name="Item" value="Militants" /
/action

and "Personnel Transport Wreck"
would match both 
Blood Raider Personnel Transport Wreck
Serpentis Personnel Transport Wreck
Guristas Personnel Transport Wreck (sp?)
etc...

**Comment by ahaw** [comment]
Added function EntitiesByNamePart. 
But it still need code changes

**Comment by ISeeDEDPpl** [comment]
On 2nd thought I implemented  %MissionName%-%FactionName%.xml as an optional way of naming the mission XMLs which solves the same problem this was looking to solve in an easier to understand and harder to break way.
