### ISSUE TITLE
Possible Request...for training check

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#280]
Is it possible to add how much training time that is left in queue to the end of the stats after the mission completion?

**Comment by ISeeDEDPpl** [comment]
I do not see why not. 
I can even have the email module email you if the bot is running and the training queue has less than 24hrs on it.
Eventually we should just add a skill training background task that does its thing in the background (including injecting skills while @ home base)... of all the people that have created skill training support none have yet stepped up with some code.  =/

**Comment by Chryst** [comment]
https://github.com/ISeeDEDPpl/Questor/issues/171

Will be very good if we do that :)

**Comment by ISeeDEDPpl** [comment]
The framework is done. I can add sending an email to the configured email address too if that would be helpful... I am undecided atm. 

The way its written now you can optionally run an innerspace script when your training queue is not full (that script can run another program or whatever you like...) We also emit an event that can be hooked by an external app using "LavishScript.Events.ExecuteEvent"

re-open if you want an email alert (once a day?)
