### ISSUE TITLE
[BUG] Windows 8 app crashes

### ISSUE THREAD

**Issue by Karr** [ISeeDEDPpl/Questor#282]
Running under Win8 64 and having issues with program crashes.

Guessing this crash is happening when the memory ceiling is cycling.
<EVEProcessMemoryCeiling>1150</EVEProcessMemoryCeiling>

Everything run perfectly and after some TIME, one of the clients (1 of many) would crash.  EVERY crash has been with the toon in that hanger.  So, guess from this alone that it has to do with the app trying to restart.

I could imagine finding the cause of this and fixing this will not be any easy challenge.

**Comment by ISeeDEDPpl** [comment]
have you tried running questor from the bleedingedge branch?

**Comment by Bubsan** [comment]
edited for stupid question :)

**Comment by ISeeDEDPpl** [comment]
please attempt to reproduce with latest experimental and report back. I do not have a win8 box to test with atm, but I do not think the crashes you were seeing were win8 specific and I think they were already fixed. If you still experience this issue We can get creative with debugging options.

**Comment by Karr** [comment]
If anyone else is running windows 8, please report your experiences.

**Comment by ISeeDEDPpl** [comment]
Are you still getting crashes? If you are can you nail it down to when or what was happening when it occurred? Is it only on restart of questor?

**Comment by ISeeDEDPpl** [comment]
ping.

**Comment by ISeeDEDPpl** [comment]
I assume no one else is crashing or having issues running innerspace /questor with windows 8. I am closing this issue. If you experience problems open a new issue please.
