### ISSUE TITLE
RepairShop .... drones....

### ISSUE THREAD

**Issue by test1234567xx** [ISeeDEDPpl/Questor#283]
Any idea?

17:09:01 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_ShipCargo_1008303139486', 1008303139486L)]
17:09:03 [Arm] Opening Ship Hangar: waiting [3sec]
17:09:06 [Arm] Activating combat ship
17:09:08 [Arm.RepairShop [Drones]] Opening repairshop window
17:09:10 [Arm.RepairShop [Drones]] Get Quote for Repairing [5] Drones
17:09:13 [Arm.RepairShop [Drones]] Get Quote for Repairing [5] Drones
17:09:16 [Arm.RepairShop [Drones]] Get Quote for Repairing [5] Drones
17:09:19 [Arm.RepairShop [Drones]] Get Quote for Repairing [5] Drones
17:09:21 [Arm.RepairShop [Drones]] Get Quote for Repairing [5] Drones
17:09:24 [Arm.RepairShop [Drones]] Get Quote for Repairing [5] Drones
17:09:26 [Arm.RepairShop [Drones]] Get Quote for Repairing [5] Drones

infinite loop :(
last version 12efd..

**Comment by Chryst** [comment]
With the last version is working. You can close.
