### ISSUE TITLE
autostart not work

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#284]
after patch not work autologin and questor block when must open the cargo hold

**Comment by marivx** [comment]
Exception during event execution: System.NullReferenceException: Riferimento a un oggetto non impostato su 
oggetto.

   in ..( )

   in ..( )

   in ..( )

   in ..( )

   in DirectEve.DirectLoginSlot.get_CharName()

   in Questor.Program.OnFrame(Object sender, EventArgs e) in
c:\Users\Acer\Desktop\Questor-experimental\Questor\Program.cs:riga 649

   in ..(DirectEve , Object , EventArgs )

   in DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   in LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by marivx** [comment]
Tray icon enabled
19:28:32 [Statistics: AmmoConsumptionStats] Opening Cargohold of active ship: waiting [3sec]
19:28:35 [Statistics: AmmoConsumptionStats] Opening Cargohold of active ship: waiting [3sec]
19:28:39 [Statistics: AmmoConsumptionStats] Opening Cargohold of active ship: waiting [3sec]
19:28:43 [Statistics: AmmoConsumptionStats] Opening Cargohold of active ship: waiting [3sec]
19:28:46 [Statistics: AmmoConsumptionStats] Opening Cargohold of active ship: waiting [3sec]
19:28:49 [Statistics: AmmoConsumptionStats] Opening Cargohold of active ship: waiting [3sec]

**Comment by Bubsan** [comment]
same problems here...

**Comment by I3Questor** [comment]
Using latest Experimental build.

+1
My Questor wont even get past the character selection screen.  If I manually select the character, I get the above errors.

Here is my console log:

08:23:09 [Startup] User: xxxxxxx Name: xxxxxx
08:23:09 [Startup] Schedule1: Start1: 5/12/2012 8:03:00 AM Stop1: 5/12/2012 9:30:00 PM
08:23:09 [Startup] Start Time: 5/12/2012 8:31:43 AM - Stop Time: 5/12/2012 9:30:00 PM
08:23:10 [Startup] Starting at 5/12/2012 8:31:43 AM. 8.55 minutes to go.
08:31:43 [Startup] Timer elapsed. Starting now.
08:32:18 [Startup] Login account [xxxxxxxx]
08:32:18 [Startup] Waiting for Character Selection Screen
08:36:58 [Startup] We have successfully logged in
08:37:01 [Questor] Schedule: setup correctly: stoptime is [9:30 PM]
08:37:01 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 317 MB
08:37:02 [Settings] Loading Settings from [Cxxxxxxxxxxx]
08:37:02 [Settings] MissionsPath is: [Cxxxxxxxx]
08:37:02 [Settings] Loothangar [LOOT]
08:37:02 [Settings] AmmoHangar [AMMO]
08:37:02 [Settings] Found only one agent in your character XML: MultiAgentSupport is [False]
08:37:02 [Settings] Loading Mission Blacklist
08:37:02 [Settings] Mission Blacklist now has [5] entries
08:37:02 [Settings] Loading Faction Blacklist
08:37:02 [Settings] Missions from the faction [Caldari State] will be declined
08:37:02 [Settings] Missions from the faction [Gallente Federation] will be declined
08:37:02 [Settings] Missions from the faction [Minmatar Republic] will be declined
08:37:02 [Settings] Missions from the faction [Amarr Empire] will be declined
08:37:02 [Settings] Missions from the faction [CONCORD Assembly] will be declined
08:37:02 [Settings] Missions from the faction [Ammatar Mandate] will be declined
08:37:02 [Settings] Missions from the faction [Khanid Kingdom] will be declined
08:37:02 [Settings] Missions from the faction [Thukker Tribe] will be declined
08:37:02 [Settings] Faction Blacklist now has [8] entries
08:37:02 [Cache.CurrentAgent] [ xxxxx ] AgentID [ xxxxx ]
08:37:02 [Logging][ xxxxxx ] AgentID [ xxxxx ]
08:37:04 [Questor] Checking: Current time [12/05/2012 08:37:04] StopTimeSpecified [True] StopTime [ 5/12/2012 9:30:00 PM] ManualStopTime = 5/12/2012 6:23:07 PM
08:37:04 [Questor] Start Mission Behavior
08:37:05 [CombatMissionsBehavior] Random start delay of [10] seconds
08:37:32 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: WindowText EVE - Drake Firerain
08:37:32 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: timedcommand 100 windowtaskbar on Drake Firerain
08:37:32 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: timedcommand 150 WindowCharacteristics -size 1024x768
08:37:32 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: timedcommand 200 WindowCharacteristics -pos 643x0
08:44:22 [Settings] CharacterName not defined! - Are we still logged in? Did we lose connection to eve? Questor should be restarting here.
08:44:22 [QuestorState.CloseQuestor] Writing Session Data [1]
08:44:22 [Statistics: WriteSessionLogClosing] 5/12/2012 8:44:22 AM;0;Quitting!!;;67876865.6972;317;;0;0;0;0;0;0;0;
08:44:22 [Statistics: WriteSessionLogClosing] Writing to session log [ C:\xxxxxxxx

**Comment by ISeeDEDPpl** [comment]
this has been fixed with an update of DE.

thank ganondorf when you see him.
