### ISSUE TITLE
ValueDump not working after "Retribution" Patch

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#285]
Q just and waits to load hangar items... 

11:29:28 [Valuedump] Updating reprocess prices
11:29:28 [Valuedump] Saving InvTypes.xml
11:30:28 [ValueDump] Waiting for items
11:30:28 [ValueDump] Loading hangar items

**Comment by ISeeDEDPpl** [comment]
no need to open issues until DE is updated... nearly everything questor related may be broken until then.

**Comment by ISeeDEDPpl** [comment]
retest w new DE please. there may be changes needed, valuedump is still untested by me.

**Comment by I3Questor** [comment]
Seems to be working fine. We can close this issue, I will start a new one if there are issues down the track.

**Comment by Chryst** [comment]
You can close it work.

**Comment by Disneyland** [comment]
tested with the previous de version hanger loading and dumping works fine.

and tested with the actual version - working.
