### ISSUE TITLE
Multi Agent Support is not working

### ISSUE THREAD

**Issue by Irenicus1977** [ISeeDEDPpl/Questor#286]
Here is the log
...
11:39:35 [Settings] MissionsPath is: [C:\Program Files (x86)\InnerSpace.NET Programs\Minmatar Missions 4 Level]
11:39:35 [Settings] Loothangar [ItemsHangar]
11:39:35 [Settings] AmmoHangar [AmmoHangar]
11:39:35 [Settings] Found more than one agent in your character XML: MultiAgentSupport is [True]
11:39:35 [Settings] Loading Mission Blacklist
11:39:35 [Settings] Mission Blacklist now has [11] entries
11:39:35 [Settings] Loading Faction Blacklist
11:39:35 [Settings] Missions from the faction [Caldari State] will be declined
11:39:35 [Settings] Missions from the faction [Gallente Federation] will be declined
11:39:35 [Settings] Missions from the faction [Minmatar Republic] will be declined
11:39:35 [Settings] Missions from the faction [Amarr Empire] will be declined
11:39:35 [Settings] Missions from the faction [CONCORD Assembly] will be declined
11:39:35 [Settings] Missions from the faction [Ammatar Mandate] will be declined
11:39:35 [Settings] Missions from the faction [Khanid Kingdom] will be declined
11:39:35 [Settings] Missions from the faction [Thukker Tribe] will be declined
11:39:35 [Settings] Faction Blacklist now has [8] entries
11:39:35 [Cache.CurrentAgent] [ *************\* ] AgentID [ *******\* ]
11:39:39 [Questor] Checking: Current time [12/09/2012 11:39:39] StopTimeSpecified [True] StopTime [ 09.12.2012 23:59:00] ManualStopTime = 09.12.2012 21:37:56
11:39:39 [Questor] Start Mission Behavior
11:39:40 [CombatMissionsBehavior] Random start delay of [36] seconds
11:40:05 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: WindowText EVE - _MyEVECharacterNameRedacted_
11:40:05 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: timedcommand 100 windowtaskbar on _MyEVECharacterNameRedacted_
....
11:43:49 [CombatMissionsBehavior.Unloadloot] CharacterMode: [Combat Missions], AfterMissionSalvaging: [False], CombatMissionsBehaviorState: [Idle]
11:43:51 [Questor] Start Mission Behavior
11:43:52 [CombatMissionsBehavior] Random start delay of [55] seconds
11:44:51 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 809 MB
11:44:51 [Storyline] Currently have [3] missions available
11:44:51 [Storyline] Currently have [0] storyline missions available
11:44:51 [Storyline] Currently have [0] storyline missions questor knows how to do
11:44:51 [Storyline] Currently have [0] storyline missions questor knows how to do and are not blacklisted
11:44:51 [AgentInteraction] Start conversation [Start Mission]
11:45:01 [AgentInteraction] Replying to agent
11:45:04 [AgentInteraction] Saying [View Mission]
11:45:14 [AgentInteraction] Waiting for mission
11:45:23 [AgentInteraction.WaitForMission] Opening Journal Window: waiting [2sec]
11:45:25 [AgentInteraction] [**************] standing toward me is [10,00], minAgentGreyListStandings: [-1,7]
11:45:25 [AgentInteraction] Mission enemy faction: Amarr Empire
11:45:25 [AgentInteraction] Declining blacklisted mission [In the Midst of Deadspace (1 of 5)]
11:45:25 [AgentInteraction] Mission enemy faction: Amarr Empire
11:45:25 [AgentInteraction] Declining blacklisted mission [In the Midst of Deadspace (1 of 5)] because of faction blacklist
11:45:34 [AgentInteraction] Saying [Decline]
11:45:34 [AgentInteraction] Replying to agent
11:45:37 [AgentInteraction] Replying to agent
11:45:40 [AgentInteraction] Saying [Request Mission]
11:45:40 [AgentInteraction] Waiting for mission
11:45:47 [AgentInteraction] [***************] standing toward me is [10,00], minAgentGreyListStandings: [-1,7]
11:45:47 [AgentInteraction] Mission enemy faction: Amarr Empire
11:45:47 [AgentInteraction] Declining blacklisted mission [War Situation (1 of 2)]
11:45:47 [AgentInteraction] Mission enemy faction: Amarr Empire
11:45:47 [AgentInteraction] Declining blacklisted mission [War Situation (1 of 2)] because of faction blacklist
11:45:56 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
11:45:56 [AgentInteraction] Agent decline timer detected. Current standings: 10. Minimum standings: 1
11:45:56 [AgentInteraction] Waiting 240 minutes to try decline again because waitDecline setting is set to true
11:45:56 [AgentInteraction.CloseConversation] will continue in [14400]sec
11:46:57 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
11:47:57 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
11:48:58 [Questor] Wallet Balance Has Not Changed in [ 5 ] minutes.
11:49:58 [Questor] Wallet Balance Has Not Changed in [ 6 ] minutes.
11:50:59 [Questor] Wallet Balance Has Not Changed in [ 7 ] minutes.
11:52:00 [Questor] Wallet Balance Has Not Changed in [ 8 ] minutes.
11:53:01 [Questor] Wallet Balance Has Not Changed in [ 9 ] minutes.
11:54:01 [Questor] Wallet Balance Has Not Changed in [ 10 ] minutes.
11:55:02 [Questor] Wallet Balance Has Not Changed in [ 11 ] minutes.

**Comment by ISeeDEDPpl** [comment]
I think this has been fixed here:
https://github.com/ISeeDEDPpl/Questor/commit/b95ee3db4c705891cdf674dcd258823fd1b87c80

please re-open if you are still seeing any multiagent support problems
