### ISSUE TITLE
looting certain containers is not yet working properly after retribution

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#287]
14:23:58 [Salvage] Opening container [Mercenary Overlord Wreck][0k][ID: 9000855923000103123]
14:24:04 [Salvage] Opening container [Mercenary Overlord Wreck][0k][ID: 9000855923000103123]
14:24:10 [Salvage] Opening container [Mercenary Overlord Wreck][0k][ID: 9000855923000103123]
14:24:16 [Salvage] Opening container [Mercenary Overlord Wreck][0k][ID: 9000855923000103123]
14:24:17 [Questor] Wallet Balance Has Not Changed in [ 32 ] minutes.
14:24:22 [Salvage] Opening container [Mercenary Overlord Wreck][0k][ID: 9000855923000103123]
14:24:29 [Salvage] Opening container [Mercenary Overlord Wreck][0k][ID: 9000855923000103123]
14:24:34 [Salvage] Opening container [Mercenary Overlord Wreck][0k][ID: 9000855923000103123]
14:24:39 [Salvage] Opening container [Mercenary Overlord Wreck][0k][ID: 9000855923000103123]
14:24:45 [Salvage] Opening container [Mercenary Overlord Wreck][0k][ID: 9000855923000103123]

**Comment by sigmastk** [comment]
I have same issue, for example when Q wants to pick up damsel or merceneries. Is there any additional log that you need us to "switch" on ?

**Comment by Pluckyduck** [comment]
Tested with bleeding edge merged in with exp.  same error during lootitem action and looting items during salvaging

**Comment by Chryst** [comment]
Yes salvage is totally not working.

**Comment by sigmastk** [comment]
Confirming that dedicated salvager is not working also. Same issue.

**Comment by test1234567xx** [comment]
same here:

18:07:19 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:07:23 [Salvage] Activating salvager [1] on [Angel Webifier Wreck][ID: 9000855953000295196]
18:07:24 [Salvage] Locking [Angel Viper Wreck][1k][ID:9000855953000294399][1k away]
18:07:25 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
18:07:25 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:07:28 [Salvage] Activating salvager [1] on [Gist War General Wreck][ID: 9000855953000290116]
18:07:30 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:07:36 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:07:41 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:07:47 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:07:54 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:08:00 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:08:06 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:08:12 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:08:19 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]
18:08:24 [Salvage] Opening container [Cargo Container][1k][ID: 1008686759725]

**Comment by ISeeDEDPpl** [comment]
Anyone still seeing issues with looting with the newest DE?
