### ISSUE TITLE
Dedicated Salvager not going to base

### ISSUE THREAD

**Issue by ISeeDEDPpl** [ISeeDEDPpl/Questor#288]
Dedicated Salvager is having problems too

22:31:08 [Questor] Wallet Balance Has Not Changed in [ 17 ] minutes.
22:32:09 [Questor] Wallet Balance Has Not Changed in [ 18 ] minutes.
22:33:10 [Questor] Wallet Balance Has Not Changed in [ 19 ] minutes.
22:34:09 [DedicatedBookmarkSalvagerBehavior] It has been over 20 min since we were last in warp. Assuming something went wrong: setting GoToBase
22:34:10 [Questor] Wallet Balance Has Not Changed in [ 20 ] minutes.
22:34:10 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:34:10 [DedicatedBookmarkSalvagerBehavior] Destination: [XXXXXX]
22:34:10 [TravelerDestination.StationDestination] Destination set to [XXXXXX]
22:34:11 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:34:12 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:34:14 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:34:14 [Traveler] Setting destination to [XXX]
22:34:15 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:34:15 [Traveler] Warping to [XXXXXX][19.98 AU away]
22:34:16 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:34:17 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:34:18 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:10 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:11 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:12 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:13 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:14 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:15 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:16 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:17 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:18 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:18 [Traveler] Jumping to [XXXXXX]
22:35:19 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:20 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:21 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:22 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:23 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:24 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:53 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:53 [TravelerDestination.StationDestination] Warp to and dock at [XXXXXX][26.41 AU away]
22:35:54 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:55 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:35:56 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:36:50 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:36:50 [TravelerDestination.StationDestination] Dock at [XXXXXX] which is [-1k away]
22:36:51 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:36:52 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:36:53 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.
22:37:03 [Traveler.TravelHome] HomeBookmarkName bookmark not found! using AgentsStation info instead: We were Looking for bookmark starting with [myHomeBookmark] found none.

**Comment by I3Questor** [comment]
Thanks ISDP, I was trying not to open too many issues, just in case you had a heart attack!

**Comment by dreadylein** [comment]
going home is working flawless, just cosmetical problem, spamning the log

**Comment by ISeeDEDPpl** [comment]
fixed
