### ISSUE TITLE
Item Hangar not open during ammo transfer

### ISSUE THREAD

**Issue by Sadoru2** [ISeeDEDPpl/Questor#289]
During the 'arm' phase the Item (ammo) hangar is not open. In my case it is the standard hangar inside the station.
If I open it manually, questor closes it during the 'unload loot' phase.

I think that to enable more human like behaviour, the ammo hangar should be open and active before we move stuff out of it. ;)

Log:

[Arm] Begin
[...]
[Arm] Closing Fitting Manager Window
[Arm.MoveItems] Moving [1000] units of Ammo [Scourge Javelin Torpedo] from [ AmmoHangar ] to CargoHold
[Arm.MoveItems] Moving [1000] units of Ammo [Scourge Torpedo] from [ AmmoHangar ] to CargoHold
[Arm.MoveItems] Waiting for items
[Arm] Done

**Comment by Sadoru2** [comment]
Still happening with https://github.com/ISeeDEDPpl/Questor/commit/543a833e734eed4cffc4e5157f40a73dadb41f93, the inventory window is now opened, but the cargo hold of the ship is selected (not the item/ammo inventory or the 'active ship').

For 'unload loot' no hangar is open besides: drones, ship hangar, active ship

Maybe my unified inventory settings are wrong ('always open in separate window' is not ticked).

**Comment by ISeeDEDPpl** [comment]
it is not necessary or desirable to have all possibly inventory windows open and UI visible when transferring inventory. the way the new inventory window works it is actually discouraged by ccp.
