### ISSUE TITLE
merging Bleedingedge change onto my folder

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#291]
How do i download bleedingedge changes, i can just download the main(exp) branch with zip button but that is no longer available with anything but the default branch?  

Also if you click the "Downloads" button to the right hand side, it just downloads the default branch (exp)

**Comment by Chryst** [comment]
Now you can download it.

**Comment by Pluckyduck** [comment]
thanks ISDP and to whoever else might have helped figured this one out.
