### ISSUE TITLE
Feature Request: Drone counter in mission.

### ISSUE THREAD

**Issue by Bubsan** [ISeeDEDPpl/Questor#293]
With the new AI implemented in latest release, it would be very helpful to implement some sort of drones monitoring tool while in missions. Drones are being killed much more now and if left with no drones, questor could very easily be stuck in mission shooting frigates with large guns killing nothing.
It would be nice for Questor to return the ship for drone reloading in station when their count drops <5.
Also, if reloading is done 3 times, stop Questor so player can manually check what's happening.

**Comment by ISeeDEDPpl** [comment]
reasonable request.

**Comment by ISeeDEDPpl** [comment]
This has been added to the bleedingedge branch. Once we have verified that it works well we can merge it into experimental. 

https://github.com/ISeeDEDPpl/Questor/commit/5ef517f5fed8790e04b1b0f7f1be30dcd279e8da

**Comment by Bubsan** [comment]
Thank you! Will try it out.

**Comment by Bubsan** [comment]
I finally managed to take some time and test this. I don't think it's working. I had 2 different bots in 2 different missions (Intercept the Saboteurs and Buzz Kill) stay in mission without any drones not returning to base for more drones.

I looked into a log but there's nothing I useful I could past here, only launching and recalling drones until all drones are gone.
