### ISSUE TITLE
Not replenishing drones in stations without Repair Service.

### ISSUE THREAD

**Issue by Bubsan** [ISeeDEDPpl/Questor#298]
Not sure if somebody reported this, but it seems Questor is not replenishing drones in stations without Repair service.
Stations with Repair service work fine.

Do I have to disable repair in settings file if my agent is in station without repair?

**Comment by ISeeDEDPpl** [comment]
Can you provide a console log of this occurring? I'd just need everything from at least: Arm.ActivateCombatShip to Arm finishing but not loading drones

**Comment by Bubsan** [comment]
Big, big mistake on me. Sorry, false alarm. Looks like it's working as intended!!!
Sorry once again.
This can be closed.
