### ISSUE TITLE
Salvage.cs

### ISSUE THREAD

**Issue by dawtips** [ISeeDEDPpl/Questor#299]
I don't know where to make suggestions so here is one:

Salvage.cs
-ProcessState() 
--case SalvageState.SalvageWrecks:
---inside of if (duplicates)
----remove Cache.Instance.NextSalvageAction = DateTime.UtcNow.AddSeconds(Time.Instance.SalvageStackItems_seconds);

And copy that exact piece of code to two places within:
-case SalvageState.WaitForStacking
--after the two instances of _States.CurrentSalvageState = SalvageState.TargetWrecks;

Doing this will prevent stacking every few seconds and implement the intended behavior, stacking every three minutes.

**Comment by ISeeDEDPpl** [comment]
thx

https://github.com/ISeeDEDPpl/Questor/commit/49aa529a24a66c33d992dd3b10d9cef80ce8130f
