### ISSUE TITLE
Double logged in char ?

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#300]
I have find a char logged in double. More than 1 time....

And it continue relog in an infinite loop.

**Comment by Chryst** [comment]
I have see that error is due becouse at the end time the char contineu go ahead withouth exiting the game.

**Comment by ISeeDEDPpl** [comment]
This is the same as the scheduled tab GUI bug, the manualStopTime is being set somehow.

**Comment by Chryst** [comment]
Seems ok now.
