### ISSUE TITLE
Multi Agent Support is not working

### ISSUE THREAD

**Issue by Irenicus1977** [ISeeDEDPpl/Questor#303]
https://github.com/ISeeDEDPpl/Questor/issues/286
b95ee3db4c705891cdf674dcd258823fd1b87c80 - this update is not resolving this issue.

---

22:55:41 [Settings] Found more than one agent in your character XML: MultiAgentSupport is [True]
22:55:41 [Settings] Loading Mission Blacklist
22:55:41 [Settings] Mission Blacklist now has [11] entries
22:55:41 [Settings] Loading Faction Blacklist
22:55:41 [Settings] Missions from the faction [Caldari State] will be declined
22:55:41 [Settings] Missions from the faction [Gallente Federation] will be declined
22:55:41 [Settings] Missions from the faction [Minmatar Republic] will be declined
22:55:41 [Settings] Missions from the faction [Amarr Empire] will be declined
22:55:41 [Settings] Missions from the faction [CONCORD Assembly] will be declined
22:55:41 [Settings] Missions from the faction [Ammatar Mandate] will be declined
22:55:41 [Settings] Missions from the faction [Khanid Kingdom] will be declined
22:55:41 [Settings] Missions from the faction [Thukker Tribe] will be declined
22:55:41 [Settings] Faction Blacklist now has [8] entries
22:55:41 [Cache.CurrentAgent] [ **\* ] AgentID [ **\* ]
22:55:45 [Questor] Checking: Current time [12/15/2012 22:55:45] StopTimeSpecified [False] StopTime [ 16.12.2012 8:55:41] ManualStopTime = 16.12.2012 8:55:40
22:55:45 [Questor] Start Mission Behavior
22:55:46 [CombatMissionsBehavior] Random start delay of [59] seconds
22:56:12 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: WindowText EVE - _MyEVECharacterNameRedacted_
22:56:12 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: timedcommand 100 windowtaskbar on _MyEVECharacterNameRedacted_
22:56:47 [CombatMissionsBehavior.TravelHome] Destination: [**_]
22:56:47 [TravelerDestination.StationDestination] Destination set to [**_]
22:56:49 [TravelerDestination.StationDestination] Arrived in station
22:56:49 [CombatMissionsBehavior.TravelHome] Arrived at destination
22:56:50 [CombatMissionsBehavior] UnloadLoot: Begin
22:56:51 [Unloadloot.MoveAmmo] Opening Cargohold of active ship: waiting [3sec]
22:56:55 [Unloadloot.MoveAmmo] using Local items hangar as Ammo hangar
22:56:55 [ReadyItemsHangarAsAmmoHangar] We are in Station
22:56:55 [StackAmmoHangar] Starting [Cache.Instance.StackItemsHangarAsAmmoHangar]
22:56:55 [StackItemsHangarAsAmmoHangar] test
22:56:55 [StackItemsHangarAsAmmoHangar] if (Cache.Instance.InStation)
22:56:55 [Unloadloot.MoveAmmo] Stacking Item Hangar
22:56:56 [UnloadLoot.MoveAmmo] Done Moving Ammo
22:56:56 [Unloadloot.MoveAmmo] using Local items hangar as Ammo hangar
22:56:56 [ReadyItemsHangarAsAmmoHangar] We are in Station
22:56:56 [StackAmmoHangar] Starting [Cache.Instance.StackItemsHangarAsAmmoHangar]
22:56:56 [StackItemsHangarAsAmmoHangar] test
22:56:56 [StackItemsHangarAsAmmoHangar] if (DateTime.UtcNow.Subtract(Cache.Instance.LastStackAmmoHangar).TotalSeconds < 15)]
22:56:56 [StackItemsHangarAsAmmoHangar] if (!Cache.Instance.DirectEve.GetLockedItems().Any())
22:56:56 [StackAmmoHangar] Finished [Cache.Instance.StackItemsHangarAsAmmoHangar]
22:56:57 [StackLootHangar] !Cache.Instance.StackItemsHangarAsLootHangar(Cache.StackLootHangar))
22:56:57 [StackItemsHangarAsLootHangar] if (Cache.Instance.InStation)
22:56:57 [StackItemsHangarAsLootHangar] if (!Cache.Instance.ReadyItemsHangarAsLootHangar(Cache.StackItemsHangar)) return false;
22:56:58 [StackLootHangar] !Cache.Instance.StackItemsHangarAsLootHangar(Cache.StackLootHangar))
22:56:58 [StackItemsHangarAsLootHangar] if (Cache.Instance.InStation)
22:56:58 [Cache.StackLootHangar] Stacking Item Hangar
22:56:59 [UnloadLoot.MoveLoot] Loot was worth an estimated [0] isk in buy-orders
22:56:59 [StackLootHangar] !Cache.Instance.StackItemsHangarAsLootHangar(Cache.StackLootHangar))
22:56:59 [CombatMissionsBehavior.Unloadloot] CharacterMode: [Combat Missions], AfterMissionSalvaging: [False], CombatMissionsBehaviorState: [Idle]
22:57:01 [Questor] Start Mission Behavior
22:57:02 [CombatMissionsBehavior] Random start delay of [44] seconds
22:57:50 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 765 MB
22:57:51 [Switch] Begin
22:57:52 [OpenShipsHangar] if (Cache.Instance.InStation)
22:57:52 [OpenShipsHangar] if (Cache.Instance.ShipHangar.Window.IsReady)
22:57:52 [SwitchShip] Activating combat ship
22:57:55 [CombatMissionsBehavior.TravelHome] Destination: [**_]
22:57:55 [TravelerDestination.StationDestination] Destination set to [**_]
22:57:57 [TravelerDestination.StationDestination] Arrived in station
22:57:57 [CombatMissionsBehavior.TravelHome] Arrived at destination
22:57:58 [CombatMissionsBehavior] UnloadLoot: Begin
22:57:59 [Unloadloot.MoveAmmo] using Local items hangar as Ammo hangar
22:57:59 [ReadyItemsHangarAsAmmoHangar] We are in Station
22:57:59 [StackAmmoHangar] Starting [Cache.Instance.StackItemsHangarAsAmmoHangar]
22:57:59 [StackItemsHangarAsAmmoHangar] test
22:57:59 [StackItemsHangarAsAmmoHangar] if (Cache.Instance.InStation)
22:57:59 [Unloadloot.MoveAmmo] Stacking Item Hangar
22:58:00 [UnloadLoot.MoveAmmo] Done Moving Ammo
22:58:00 [Unloadloot.MoveAmmo] using Local items hangar as Ammo hangar
22:58:00 [ReadyItemsHangarAsAmmoHangar] We are in Station
22:58:00 [StackAmmoHangar] Starting [Cache.Instance.StackItemsHangarAsAmmoHangar]
22:58:00 [StackItemsHangarAsAmmoHangar] test
22:58:00 [StackItemsHangarAsAmmoHangar] if (DateTime.UtcNow.Subtract(Cache.Instance.LastStackAmmoHangar).TotalSeconds < 15)]
22:58:00 [StackItemsHangarAsAmmoHangar] if (!Cache.Instance.DirectEve.GetLockedItems().Any())
22:58:00 [StackAmmoHangar] Finished [Cache.Instance.StackItemsHangarAsAmmoHangar]
22:58:01 [StackLootHangar] !Cache.Instance.StackItemsHangarAsLootHangar(Cache.StackLootHangar))
22:58:01 [StackItemsHangarAsLootHangar] if (Cache.Instance.InStation)
22:58:01 [Cache.StackLootHangar] Stacking Item Hangar
22:58:02 [UnloadLoot.MoveLoot] Loot was worth an estimated [0] isk in buy-orders
22:58:02 [StackLootHangar] !Cache.Instance.StackItemsHangarAsLootHangar(Cache.StackLootHangar))
22:58:02 [CombatMissionsBehavior.Unloadloot] CharacterMode: [Combat Missions], AfterMissionSalvaging: [False], CombatMissionsBehaviorState: [Idle]
22:58:03 [Questor] Checking: Current time [12/15/2012 22:58:03] StopTimeSpecified [True] StopTime [ 16.12.2012 8:55:41] ManualStopTime = 16.12.2012 8:55:40
22:58:04 [Questor] Start Mission Behavior
22:58:05 [CombatMissionsBehavior] Random start delay of [41] seconds
22:58:51 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 485 MB
22:58:51 [Storyline] Currently have [1] missions available
22:58:51 [Storyline] Currently have [0] storyline missions available
22:58:51 [Storyline] Currently have [0] storyline missions questor knows how to do
22:58:51 [Storyline] Currently have [0] storyline missions questor knows how to do and are not blacklisted
22:58:51 [AgentInteraction] Start conversation [Start Mission]
22:59:01 [AgentInteraction] Replying to agent
22:59:04 [AgentInteraction] Saying [View Mission]
22:59:13 [AgentInteraction] Waiting for mission
22:59:21 [AgentInteraction] [***] standing toward me is [10,00], minAgentGreyListStandings: [-1,7]
22:59:21 [AgentInteraction] There are No Bookmarks Associated with Attack of the Drones yet
22:59:21 [AgentInteraction] Declining low-sec mission
22:59:25 [AgentInteraction] Agent decline timer detected. Current standings: 10. Minimum standings: 1
22:59:25 [AgentInteraction] Waiting 127 minutes to try decline again because waitDecline setting is set to true
22:59:25 [AgentInteraction.CloseConversation] will continue in [7620]sec
22:59:42 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
23:00:42 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
23:01:43 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.

**Comment by ISeeDEDPpl** [comment]
this should now be fixed in bleedingedge and needs to be tested before I merge with experimental, please update this issue if it works for you.

https://github.com/ISeeDEDPpl/Questor/commit/5648bf3751135057220c091715ede71317afad0c

**Comment by Irenicus1977** [comment]
It is working, thanks ISeeDEDPpl
