### ISSUE TITLE
[Feature Req] Only use drones to kill scrambling frigates

### ISSUE THREAD

**Issue by Armadillo1** [ISeeDEDPpl/Questor#304]
This might be useful for Vargur users. As you can't hit most tacklers with guns due to low orbit anyway. So it'd be best if the bot would just continue dpsing bigger ships. When there's nothing else in range, it could help the drones too.

Note: this should apply only to !currently! scrambling frigs, not frigs in general.

**Comment by ISeeDEDPpl** [comment]
we would have to limit this behavior to certain gun types and ship classes...
only turrets and projectiles
when flying a battleship
and the target is going 500+ m/s and is within 15k?

the bigger (much bigger) issue is that drones have the same priority target list that guns do, we need to separate them out into two diff lists. I'll work on that.

**Comment by Armadillo1** [comment]
I like the part about 500+m/s and low range! Would be a great feature.

**Comment by Armadillo1** [comment]
It could all be even simplier. Use only drones on frigates orbiting '@less than x km' and use guns on other rats meanwhile.

To make it more adjustable, an option like "Only use drones on frigs even if scrammed" would also be great.

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/3fb4a92e6d12aa96b37e38fbf051cdaeff97198e
 !!!THIS NEEDS TESTING!!! - **\* I ran a dozen missions and did not hav…

…e a problem, but this very well may get you killed. ***

Adds 2 diff PriorityTarget lists, on for PrimaryWeapons and one for Drones. If drones are disabled behavior should not change (but needs to be verified!) If you do have drones then you should set the 3 new settings to the values you want.
!!!THIS NEEDS TESTING!!!

if you have ANY issues with the above commit please open a NEW issue with a good description of what is happening and console logs if at all possible. thank you.
