### ISSUE TITLE
Mission Decline is not working correctly

### ISSUE THREAD

**Issue by Irenicus1977** [ISeeDEDPpl/Questor#306]
I have the following settings in "settings.xml"
waitDecline>false</waitDecline

minAgentBlackListStandings>6.0</minAgentBlackListStandings

MinAgentGreyListStandings>6.0</MinAgentGreyListStandings

---

Here is the log:
23:13:00 [Settings] Found only one agent in your character XML: MultiAgentSupport is [False]
23:13:00 [Settings] Faction Fittings defined. Fitting manager will be used when appropriate.
23:13:00 [Settings] Loading Mission Fittings
23:13:00 [Settings] Mission Fittings now has [6] entries
23:13:00 [Settings] Loading Mission Blacklist
23:13:00 [Settings] Mission Blacklist now has [15] entries
23:13:00 [Settings] Loading Faction Blacklist
23:13:00 [Settings] Missions from the faction [Caldari State] will be declined
23:13:00 [Settings] Missions from the faction [Gallente Federation] will be declined
23:13:00 [Settings] Missions from the faction [Minmatar Republic] will be declined
23:13:00 [Settings] Missions from the faction [Amarr Empire] will be declined
23:13:00 [Settings] Missions from the faction [CONCORD Assembly] will be declined
23:13:00 [Settings] Missions from the faction [Ammatar Mandate] will be declined
23:13:00 [Settings] Missions from the faction [Khanid Kingdom] will be declined
23:13:00 [Settings] Missions from the faction [Thukker Tribe] will be declined
23:13:00 [Settings] Faction Blacklist now has [8] entries
......
23:14:29 [Storyline] Currently have [1] missions available
23:14:29 [Storyline] Currently have [0] storyline missions available
23:14:29 [Storyline] Currently have [0] storyline missions questor knows how to do
23:14:29 [Storyline] Currently have [0] storyline missions questor knows how to do and are not blacklisted
23:14:29 [AgentInteraction] Start conversation [Start Mission]
23:14:39 [AgentInteraction] Replying to agent
23:14:43 [AgentInteraction] Waiting for mission
23:14:51 [AgentInteraction] [Vreau Roergette] standing toward me is [8,80], minAgentGreyListStandings: [-1,7]
23:14:51 [AgentInteraction] Declining blacklisted mission [The Mordus Headhunters]
23:14:51 [AgentInteraction] Mission enemy faction: Mordu's Legion Command
23:14:51 [AgentInteraction] Faction fitting: Mordu's Legion Command
23:15:00 [AgentInteraction] Agent decline timer detected. Current standings: 8,8. Minimum standings: 6
23:15:00 [AgentInteraction] Current standings [8,8] is above our configured minimum [6]. Declining [The Mordus Headhunters] note: WaitDecline is false
23:15:00 [AgentInteraction] Saying [Decline]
23:15:00 [AgentInteraction] Replying to agent
23:15:06 [AgentInteraction] Replying to agent
23:15:09 [AgentInteraction] Saying [Request Mission]
23:15:09 [AgentInteraction] Waiting for mission
23:15:17 [AgentInteraction] [Vreau Roergette] standing toward me is [7,80], minAgentGreyListStandings: [-1,7]
23:15:17 [AgentInteraction] Declining blacklisted mission [Surprise Surprise]
23:15:17 [AgentInteraction] Mission enemy faction: Amarr Empire
23:15:17 [AgentInteraction] Declining blacklisted mission [Surprise Surprise] because of faction blacklist
23:15:23 [AgentInteraction] Agent decline timer detected. Current standings: 7,8. Minimum standings: 6
23:15:23 [AgentInteraction] Current standings [7,8] is above our configured minimum [6]. Declining [Surprise Surprise] note: WaitDecline is false
23:15:23 [AgentInteraction] Saying [Decline]
23:15:23 [AgentInteraction] Replying to agent
23:15:26 [AgentInteraction] Replying to agent
23:15:29 [AgentInteraction] Saying [Request Mission]
23:15:29 [AgentInteraction] Waiting for mission
23:15:35 [AgentInteraction] [***] standing toward me is [7,28], minAgentGreyListStandings: [-1,7]
23:15:35 [AgentInteraction] Declining blacklisted mission [The Score]
23:15:35 [AgentInteraction] Mission enemy faction: Serpentis
23:15:35 [AgentInteraction] Faction fitting: Serpentis
23:15:44 [AgentInteraction] Agent decline timer detected. Current standings: 7,28. Minimum standings: 6
23:15:44 [AgentInteraction] Current standings [7,28] is above our configured minimum [6]. Declining [The Score] note: WaitDecline is false
23:15:44 [AgentInteraction] Saying [Decline]
23:15:44 [AgentInteraction] Replying to agent
23:15:50 [AgentInteraction] Replying to agent
23:15:53 [AgentInteraction] Saying [Request Mission]
23:15:53 [AgentInteraction] Waiting for mission
23:15:59 [AgentInteraction] [***] standing toward me is [6,49], minAgentGreyListStandings: [-1,7]
23:15:59 [AgentInteraction] Declining blacklisted mission [The Right Hand Of Zazzmatazz]
23:15:59 [AgentInteraction] Faction fitting: Default
23:16:00 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
23:16:08 [AgentInteraction] Agent decline timer detected. Current standings: 6,49. Minimum standings: 6
23:16:08 [AgentInteraction] Current standings [6,49] is above our configured minimum [6]. Declining [The Right Hand Of Zazzmatazz] note: WaitDecline is false
23:16:08 [AgentInteraction] Saying [Decline]
23:16:08 [AgentInteraction] Replying to agent

---

There is an error:
Questor is declining mission and factions that are not in blacklist:
1. The Mordus Headhunters / Mordu's Legion Command
2. The Score / Serpentis
3. The Right Hand Of Zazzmatazz

To my mind Questor is trying to decline because there is an Agent decline timer :)

**Comment by Irenicus1977** [comment]
I change waitDecline from false to true and set to true some debug settings. Here is the log.

00:01:21 [Settings] Found only one agent in your character XML: MultiAgentSupport is [False]
00:01:21 [Settings] Faction Fittings defined. Fitting manager will be used when appropriate.
00:01:21 [Settings] Loading Mission Fittings
00:01:21 [Settings] Mission Fittings now has [6] entries
00:01:21 [Settings] Loading Mission Blacklist
00:01:21 [Settings.LoadBlackList] [1] Blacklisted mission Name [Enemies Abound (1 of 5)]
00:01:21 [Settings.LoadBlackList] [2] Blacklisted mission Name [Onslaught]
00:01:21 [Settings.LoadBlackList] [3] Blacklisted mission Name [The Anomaly (2 of 3)]
00:01:21 [Settings.LoadBlackList] [4] Blacklisted mission Name [New Frontiers - Raw Materials (1 of 7)]
00:01:21 [Settings.LoadBlackList] [5] Blacklisted mission Name [Mission of Mercy]
00:01:21 [Settings.LoadBlackList] [6] Blacklisted mission Name [Cut-Throat Competition]
00:01:21 [Settings.LoadBlackList] [7] Blacklisted mission Name [Dead Drift]
00:01:21 [Settings.LoadBlackList] [8] Blacklisted mission Name [Pick Your Poison]
00:01:21 [Settings.LoadBlackList] [9] Blacklisted mission Name [Mysterious Sightings (2 of 4)]
00:01:21 [Settings.LoadBlackList] [10] Blacklisted mission Name [After The Seven (4 of 5) Ruse]
00:01:21 [Settings.LoadBlackList] [11] Blacklisted mission Name [Dread Pirate Scarlet]
00:01:21 [Settings.LoadBlackList] [12] Blacklisted mission Name [Recon (1 of 3)]
00:01:21 [Settings.LoadBlackList] [13] Blacklisted mission Name [The Blockade]
00:01:21 [Settings.LoadBlackList] [14] Blacklisted mission Name [The Assault]
00:01:21 [Settings.LoadBlackList] [15] Blacklisted mission Name [Worlds Collide]
00:01:21 [Settings] Mission Blacklist now has [15] entries
00:01:21 [Settings] Loading Faction Blacklist
00:01:21 [Settings] Missions from the faction [Caldari State] will be declined
00:01:21 [Settings] Missions from the faction [Gallente Federation] will be declined
00:01:21 [Settings] Missions from the faction [Minmatar Republic] will be declined
00:01:21 [Settings] Missions from the faction [Amarr Empire] will be declined
00:01:21 [Settings] Missions from the faction [CONCORD Assembly] will be declined
00:01:21 [Settings] Missions from the faction [Ammatar Mandate] will be declined
00:01:21 [Settings] Missions from the faction [Khanid Kingdom] will be declined
00:01:21 [Settings] Missions from the faction [Thukker Tribe] will be declined
00:01:21 [Settings] Faction Blacklist now has [8] entries
00:01:21 [Cache.CurrentAgent] [ Agent ] AgentID [ AgentID ]
00:01:23 [Questor] Checking: Current time [12/18/2012 00:01:23] StopTimeSpecified [True] StopTime [ 18.12.2012 10:01:20] ManualStopTime = 18.12.2012 10:01:19
00:01:23 [Questor.SkillQueueCheck] Training Queue is full. [90,96 is more than 24 hours]
00:01:23 [Questor] Start Mission Behavior
00:01:24 [CombatMissionsBehavior] Random start delay of [24] seconds
00:01:50 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: WindowText EVE - _MyEVECharacterNameRedacted_
00:01:50 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: timedcommand 100 windowtaskbar on _MyEVECharacterNameRedacted_
00:01:50 [CombatMissionsBehavior.TravelHome] Destination: [Station]
00:01:50 [TravelerDestination.StationDestination] Destination set to [Station]
00:01:53 [TravelerDestination.StationDestination] Arrived in station
00:01:53 [CombatMissionsBehavior.TravelHome] Arrived at destination
00:01:54 [CombatMissionsBehavior] UnloadLoot: Begin
00:01:55 [Unloadloot.MoveAmmo] Opening Cargohold of active ship: waiting [3sec]
00:01:58 [StackItemsHangarAsAmmoHangar] test
00:01:58 [Unloadloot.MoveAmmo] Stacking Item Hangar
00:01:59 [UnloadLoot.MoveAmmo] Done Moving Ammo
00:01:59 [StackItemsHangarAsAmmoHangar] test
00:02:01 [Cache.StackLootHangar] Stacking Item Hangar
00:02:03 [UnloadLoot.MoveLoot] Loot was worth an estimated [0] isk in buy-orders
00:02:03 [CombatMissionsBehavior.BeginAftermissionSalvaging] Salvaging at first oldest bookmarks
00:02:03 [CombatMissionsBehavior.Unloadloot] No more salvaging bookmarks. Setting FinishedSalvaging Update.
00:02:05 [Questor] Start Mission Behavior
00:02:06 [CombatMissionsBehavior] Random start delay of [43] seconds
00:02:52 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 731 MB
00:02:52 [Storyline] Currently have [1] missions available
00:02:52 [Storyline] Currently have [0] storyline missions available
00:02:52 [Storyline] Currently have [0] storyline missions questor knows how to do
00:02:52 [Storyline] Currently have [0] storyline missions questor knows how to do and are not blacklisted
00:02:52 [AgentInteraction] Start conversation [Start Mission]
00:02:52 [AgentInteraction.StartConversation] Attempting to Interact with the agent named [Agent] in [System]
00:02:53 [AgentInteraction.StartConversation] if (DateTime.UtcNow < Cache.Instance.NextAgentWindowAction)
00:02:54 [AgentInteraction.StartConversation] if (DateTime.UtcNow < Cache.Instance.NextAgentWindowAction)
00:02:55 [AgentInteraction.StartConversation] if (DateTime.UtcNow < Cache.Instance.NextAgentWindowAction)
00:02:56 [AgentInteraction.StartConversation] if (DateTime.UtcNow < Cache.Instance.NextAgentWindowAction)
00:02:57 [AgentInteraction.StartConversation] if (DateTime.UtcNow < Cache.Instance.NextAgentWindowAction)
00:02:58 [AgentInteraction.StartConversation] if (DateTime.UtcNow < Cache.Instance.NextAgentWindowAction)
00:02:59 [AgentInteraction.StartConversation] if (DateTime.UtcNow < Cache.Instance.NextAgentWindowAction)
00:03:00 [AgentInteraction.StartConversation] if (DateTime.UtcNow < Cache.Instance.NextAgentWindowAction)
00:03:01 [AgentInteraction.StartConversation] if (DateTime.UtcNow < Cache.Instance.NextAgentWindowAction)
00:03:02 [AgentInteraction.StartConversation] AgentWindow is ready
00:03:02 [AgentInteraction] Replying to agent
00:03:05 [AgentInteraction.ReplyToAgent] AgentWindow is ready
00:03:05 [AgentInteraction.ReplyToAgent] we have Agent.Window.AgentResponces
00:03:05 [AgentInteraction.ReplyToAgent] if (Purpose != AgentInteractionPurpose.AmmoCheck) //do not change the AgentInteractionPurpose if we are checking which ammo type to use.
00:03:05 [AgentInteraction] Waiting for mission
00:03:19 [AgentInteraction.WaitForMission] AgentWindow is ready
00:03:19 [AgentInteraction] [Agent] standing toward me is [6,19], minAgentGreyListStandings: [-1,7]
00:03:19 [AgentInteraction] Declining blacklisted mission [The Score]
00:03:19 [AgentInteraction] Mission enemy faction: Serpentis
00:03:19 [AgentInteraction] Faction fitting: Serpentis
00:03:26 [AgentInteraction.DeclineMission] AgentWindow is ready
00:03:26 [AgentInteraction] Agent decline timer detected. Current standings: 6,19. Minimum standings: 1
00:03:26 [AgentInteraction] Waiting 194 minutes to try decline again because waitDecline setting is set to true
00:03:26 [AgentInteraction.CloseConversation] will continue in [11640]sec

**Comment by ISeeDEDPpl** [comment]
Do you by chance have 
debugAllMissionsOnBlackList = true?
or
debugAllMissionsOnGreyList = true?
those two options are for testing the Blacklist/Greylist functionality and literally put ALL missions on the blacklist or greylist and would create the issue described.

**Comment by Irenicus1977** [comment]
Sorry, close this issue
