### ISSUE TITLE
delay issue on 42ab6f8431 - 17.2 Dec Exp

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#309]
Seem to get alot of huge delays when nothing else is with in range while speed tanking?

11:09:55 [Combat] Activating painter [1] on [Angel Viper][ID: BIGNUMBER][38k away]
11:11:24 [CombatMissionCtrl.ClearPocket] Out of range. ignoring orbit around structure.
11:11:24 [CombatMissionCtrl.ClearPocket] Initiating Orbit [Gistatis Praefectus][ID: ANOHTERBIGNUMBER]

**Comment by ISeeDEDPpl** [comment]
not sure. Can I get a longer log snippit? What about the timers listed in the details tab... if one of them somehow is 3 min in the future it would cause what you are seeing...  this is going to be a bear to debug if I cant reproduce it =/

**Comment by Pluckyduck** [comment]
ISDP, i will try to work with this one by the weekend.  Please do not devote more time to it until i can figure out all of the cases for it.

**Comment by bugc** [comment]
Perhaps this will help you: I saw my toon flying to nowhere away from NPCs for minute or two, but when reached max. weapon range (according to character.xml ranges) it turned back, targeted smth and changed weapon. So, my clue is Q was on short range weapon but something in orbiting process was not executed so it flies away being sure it is orbiting, but when distance exceeded max range next decision was taken.
This could lead to 2 minutes lag in logfile.

**Comment by ISeeDEDPpl** [comment]
if this is still happening I need more of the console log when it occurs, potentially a snippet of the whole pocket.

**Comment by Pluckyduck** [comment]
i have not noticed it but will monitor it again today.

**Comment by Pluckyduck** [comment]
I did not have anything to report and sorry for not reporting the negative findings.
