### ISSUE TITLE
Questor starts 1 min after full character login

### ISSUE THREAD

**Issue by KingMike** [ISeeDEDPpl/Questor#31]
questor now starts 1 minute after the toon gets fully logged in.
it will say activating character --> this will log in the toon 
then 1 min later questor starts.

if this happens after eve crash and restart during mission and you have to stay 1 min with no hardeners in the middle of the pocket you will die.

**Comment by ISeeDEDPpl** [comment]
Well, its one minute from login... and it takes about 45sec to land on grid so its not as bad as you make it out to be. That being said, It not jumping out at me what change in questor to cause this. It looks more like a ccp change that the session isn't "ready" until then. 

Anyone else wanna take a look at program.cs?
