### ISSUE TITLE
Feature request. Materials for war preparation

### ISSUE THREAD

**Issue by Armadillo1** [ISeeDEDPpl/Questor#310]
This storyline needs an option to bring Kernite from your main station instead of buying it in the station where the mission agent is. As some stations don't have Kernite on the market. It's easier to just stock up some kernite..and use an industrial to haul it to the storyline agent.

**Comment by Pluckyduck** [comment]
+1

**Comment by Armadillo1** [comment]
It would be so good that i can't resist bumping it..

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/efef179aa62a3cafe14130f909328249685bf276

if their are any bugs with this new functionality please open a new issue with console logs (if possible)

**Comment by Pluckyduck** [comment]
thanks
