### ISSUE TITLE
for bleedingedge commit aef98be3a101ae

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#311]
If there is trouble pickingup or dropping of items during a courier mission retry up to 20 before pausing questor and logging the error for a human to debug as needed

would this be used to move large amounts of cargo, the 40k ones?  if it run back and forth up to 20 times moving stuff that would be cool. if this is just something else please advise,

PD

**Comment by ISeeDEDPpl** [comment]
log?

**Comment by Pluckyduck** [comment]
just asking what the 20 retries are for, was thinking that this might allow for the high cargo requirements courier missions to be completed with smaller haulers.
