### ISSUE TITLE
Feature request: Courier mission behavior

### ISSUE THREAD

**Issue by ljk1291** [ISeeDEDPpl/Questor#315]
hi,
im wondering if it would be possible for you to implement a simple courier mission state to make it easy to grind standings quickly to lvl3 missions?
i dont think it would be too difficult.
All it would need to do is interact with the agent, grab items at A,go from position A - B, drop items at B, grab items at B, go back to A and complete the mission.
All these functions are available in QuestorManager, im just not sure how to implement them into questor and create a new state for it.

**Comment by Pluckyduck** [comment]
you can do the standing missions by buying tags and trading them in.  If you are only looking for the quick standing gain.

**Comment by drokk99** [comment]
It's closer than you think.. All you need to do is add mission names to agentinteraction and mission names and items to couriermissionctrl, recompile and set the agent name to a courier agent..

Would be even better if agentinteraction and couriermissionctrl could pull the names from an xml, then there would be no need to recompile whenever you add new missions.

**Comment by Pluckyduck** [comment]
nice to know.

**Comment by ljk1291** [comment]
ah thank you drokk99 i never noticed that. 
Now just to find a resource where courier missions and items needed are listed to start adding them.

**Comment by Daxten** [comment]
You can read the item out of the HTML

**Comment by ISeeDEDPpl** [comment]
If you manage to work on this I accept code contributions.. you can post patches to an issue (with a link to a post on something like privatepaste.com) or commit to github and do a pull request.
