### ISSUE TITLE
Value Dump wrong quantity spam

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#317]
Value Dump wrong quantity spam

Is rare but i have see value dump stucked in a wrong quantity spam when i was with only 4-5 items in hangar.

**Comment by ISeeDEDPpl** [comment]
log?

**Comment by evelover** [comment]
[ValueDump] Starting QuickSell for Small Hull Repairer I  
[ValueDump] Selling 10 of Small Hull Repairer I [Sell price: 86В 101,10] [Median buy price: 99В 998,90]  
[ValueDump] 1 items left to sell  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I  
[ValueDump] Starting QuickSell for Heat Sink I

**Comment by Chryst** [comment]
Yes i confirm is that the spam. Happend oly when we left aproximately 10 items in the hangar.

**Comment by Chryst** [comment]
Any news on that fix ?

**Comment by Chryst** [comment]
After some investigations is the DE cache that cause the problem and EVE client, so we can't do nothing for resolve that i think.
