### ISSUE TITLE
BEdge af0b18ef4a - dedicated salvager

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#318]
useGate is set to True but q found a gate and 
 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: We found gate in salvage bookmark. Going back to Base

if you need more of a log let me know.

PD

**Comment by ISeeDEDPpl** [comment]
duplicate

**Comment by Pluckyduck** [comment]
sorry about the duplicate.
