### ISSUE TITLE
more than 1 rep modules needs adjustment in defense.cs

### ISSUE THREAD

**Issue by ISeeDEDPpl** [ISeeDEDPpl/Questor#32]
<grdk> just swapped in two SSB's and testing now
<grdk> it's a bit strange, the activation delays cause the SSB's to alternate their cycles
<ISeeDEDPpl> ahh...
<ISeeDEDPpl> grdk, ok, let me fix that
<grdk> This is only when let's say, I set the activation at 95%, and 1 cycle boosts it back to 95-ish, then in the meantime it falls below 95% again
<ISeeDEDPpl> yeah, it needs to be fixed for multiple reps anyway, that is common with armor
<grdk> When the shield falls way below 95% both run until they're supposed to stop
<grdk> It doesn't really bother my that bot, but mods that have high activation costs might be messed up
<ISeeDEDPpl> its a relatively easy fix, we just need a delay assigned to _each_ module rather than a global delay. it'll probably work out better that way anyway

**Comment by ahaw** [comment]
why you see it as a problem? for me it is perfectly fine.

**Comment by ISeeDEDPpl** [comment]
This seems to be working fine. if there is an issue to be resolved a new issue should be opened with a good description of the issue.
