### ISSUE TITLE
Q is ignoring actions from mission.xml

### ISSUE THREAD

**Issue by bugc** [ISeeDEDPpl/Questor#320]
On buzz-kill mission Q is ignoring <action>s as described on our forum http://is.gd/WhXWpL
Here are log snipped http://tny.cz/0d763256 and mission.xml http://tny.cz/b8fdc116; I was using bleedingedge binaries

Everything goes wrong just from the beginning - Q doesn't start with assault cruisers but  reports action as done. Perhaps I misplaced tags in XML?

`<mission>`
`<pockets>`
`<pocket id="0">`
`<damagetype>Explosive</damagetype>`
`<actions>`
`<action name="WaitUntilTargeted">`
`<parameter name="Timeout" value="10"></parameter>`
`</action>`
`<action name="Kill">`
`<parameter name="target" value="Arch Gistum Centurion" />`
`<parameter name="target" value="Arch Gistum Phalanx" />`
`</action>`
`<action name="Ignore">`
`<parameter name="Add" value="Arch Gistii Ruffian" />`
`<parameter name="Add" value="Arch Gistii Thug" />`
`</action>`
`<action name="ClearPocket" />`
`<action name="Ignore">`
`<parameter name="Clear" value="true"></parameter>`
`</action>`
`<action name="Kill">`
`<parameter name="IgnoreAttackers" value="true"></parameter>`
`<parameter name="Target" value="Arch Gistii Ruffian" />`
`</action>`
`<action name="Kill">`
`<parameter name="IgnoreAttackers" value="true"></parameter>`
`<parameter name="Target" value="Arch Gistii Thug" />`
`</action>`
`<action name="Done" />`
`</actions>`
`</pocket>`
`</pockets>`
`</mission>`

21:07:40 [CombatMissionCtrl.WaitUntilTargeted [timeout: 10]] Nothing targeted us within [ 10sec]!
21:07:40 [CombatMissionCtrl] Finished Action.WaitUntilTargeted [timeout: 10]
21:07:40 [CombatMissionCtrl] Starting Action.Kill [target: Arch Gistum Centurion] [target: Arch Gistum Phalanx]
21:07:41 [CombatMissionCtrl.Kill [target: Arch Gistum Centurion] [target: Arch Gistum Phalanx]] All targets killed Arch Gistum Centurion[Arch Gistum Phalanx]
21:07:41 [CombatMissionCtrl] Finished Action.Kill [target: Arch Gistum Centurion] [target: Arch Gistum Phalanx]
21:07:41 [CombatMissionCtrl] Starting Action.Ignore [add: Arch Gistii Ruffian] [add: Arch Gistii Thug]
21:07:42 [CombatMissionCtrl.Ignore [add: Arch Gistii Ruffian] [add: Arch Gistii Thug]] Updated ignore list
21:07:42 [CombatMissionCtrl.Ignore [add: Arch Gistii Ruffian] [add: Arch Gistii Thug]] Currently ignoring: Arch Gistii Ruffian[Arch Gistii Thug]
21:07:42 [CombatMissionCtrl] Finished Action.Ignore [add: Arch Gistii Ruffian] [add: Arch Gistii Thug]
21:07:42 [CombatMissionCtrl] Starting Action.ClearPocket

**Comment by bugc** [comment]
Look, I've placed xml as it was to GITHUB, but first strings are omitted. Perhaps smth is wrong with line ends? Anyway, original mission xml is in archive under 2d link

**Comment by ISeeDEDPpl** [comment]
It looks to me like the NPCs have not yet spawned when it starts processing the actions. The log indicates that the actions are being processed. If you watch it when it is doing this I am 099% sure that there sare no NPCs yet on grid. You likely need to have it wait longer. Something like:

`<action name="WaitUntilTargeted">`
`<parameter name="Timeout" value="30"></parameter>`
`</action>`

**Comment by bugc** [comment]
Haven't been here 4 long time. I'm testing what you supposed to be right. Buzz is rather rare mission in my experience. But I'm pessimistic, because by design of mission there are assault cruisers by warp in - no need waiting them at all. Let's check if bigger timer solves.
Check this, Q does recognize shiptypes when performing clearpocket, they are first <action> in my .xml
17:59:58 [CombatMissionCtrl.ClearPocket] Adding [Angel Assault Cruiser][ID: [truncatedID]10543] as a primary weapon priority target
17:59:58 [CombatMissionCtrl.ClearPocket] Adding [Angel Assault Cruiser][ID: [truncatedID]10543] as a drone priority target
17:59:58 [CombatMissionCtrl.ClearPocket] Initiating Orbit [Angel Assault Cruiser][ID: [truncatedID]10543]
17:59:59 [Combat] Targeting high value target [Angel Assault Cruiser][ID: [truncatedID]10541][27k away] highValueTargets.Count [3]
18:00:00 [Defense] Shields: [86%] Cap: [92%] Shield Booster: [1] activated

**Comment by bugc** [comment]
http://tny.cz/10cf2716 - log snipped
NO change even by 45 sec delay. Initial spawn is being ignored as don't exists, only 'clearpocket' ran as supposed.

**Comment by Pluckyduck** [comment]
can you get on IRC?

**Comment by bugc** [comment]
I'm checking now idea Pluckyduck told me with straight definition to ignore attackers and what ship types to ignore.

**Comment by bugc** [comment]
so, no progress and same shit:
I'm arriving at beacon, waiting until targeted (ok, I'm), next action should be Kill 2 kinds of assault cruisers in initial spawn, but Q reports they are all killed even when 1st one is just locked down and no shoot done. All the actions with and without 'ignoreattackers' 'breakonattack' are ignored until 'done'. 
Because I wrote several mission definitions and they are fine I suppose something is wrong with current mission. Lucky to me 'Clearpocket' is working and tengu is capable just rush until last angel standing. Let's close as 'sad but true' issue.
