### ISSUE TITLE
Add PS3 popup message

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#322]
Add PS3 popup message

**Comment by ISeeDEDPpl** [comment]
care to explain what that means?

**Comment by ISeeDEDPpl** [comment]
clues?

**Comment by ljk1291** [comment]
i think he means something to do with dust on the playstation 3

**Comment by ISeeDEDPpl** [comment]
I do not understand this issue. if you can articulate what you want / need then you have a better chance of getting your issue resolved.
