### ISSUE TITLE
Declining blacklisted mission

### ISSUE THREAD

**Issue by EchuI** [ISeeDEDPpl/Questor#323]
```
  <waitDecline>true</waitDecline>
  <minAgentBlackListStandings>-1.0</minAgentBlackListStandings>
  <minAgentGreyListStandings>-1.0</minAgentGreyListStandings>

12:55:31 [AgentInteraction] Waiting for mission
12:55:36 [AgentInteraction] [xxx] standing toward me is [8.59], minAgentGreyListStandings: [-1]
12:55:36 [AgentInteraction] Mission enemy faction: Serpentis
12:55:36 [AgentInteraction] Declining blacklisted mission [The Blockade]
12:55:36 [AgentInteraction] Mission enemy faction: Serpentis
12:55:42 [AgentInteraction] Agent decline timer detected. Current standings: 8.59. Minimum standings: -1
12:55:42 [AgentInteraction] Waiting 240 minutes to try decline again because waitDecline setting is set to true
12:55:42 [AgentInteraction.CloseConversation] will continue in [14400]sec
```

**Comment by Pluckyduck** [comment]
doing as it is supposed to do.  only use waitdecline when you are using a very low level character or do not want to loose any standing.

**Comment by Irenicus1977** [comment]
Everything is correct, to decline mission you need to change waitDecline to false.
fc3a14c4eefa93d4b18421e35128126be4927993
" Fix the Mission decline stuff to respect both the WaitDecline setting… …

… (which has been broken for... ever?) and the standing setting: MinAgentBlackListStandings

WaitDecline has been broken so long that we should at least temporarily change the default to false... (arguably we need to change it to use a different setting altogether)"

**Comment by EchuI** [comment]
ok, thx
