### ISSUE TITLE
Slow down popup message

### ISSUE THREAD

**Issue by Chryst** [ISeeDEDPpl/Questor#325]
Is better add it to close automatically or keep it alive ?

**Comment by ISeeDEDPpl** [comment]
example?

**Comment by ljk1291** [comment]
i have the problem when questor removes a lot of old bookmarks as a dedivated salvager

**Comment by ISeeDEDPpl** [comment]
what problem? can I get a better description? log message? screenshot?

**Comment by I3Questor** [comment]
Ok let me try to shed some light on this for you ISDP.

There are times when (especially when using a dedicated salvager) corporate bookmarks build up to (eg) 50 or more of which 15 or 20 of them are past the 2 hour mark.  A good time for this would be downtime.  When Q logs in again, it sees these expired bookmarks and tries to delete them... Even then throws up a window to say SLOW DOWN bla bla (sorry I cant remember the exact text).

This error can be reproduced manually by trying to delete around 15 bookmarks at once.

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/62c609c64ae655d8797c84d3300a106ff85acbb6
