### ISSUE TITLE
no drone bay repair bug

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#328]
http://pastebin.com/XN6vq4nh

tengus with no drone bay seem to get this on every panic and will loop until stopped.

manually going in to turning off repair will stop the loop and go back to mission.

tested with golem with drones and does not cause the error.

**Comment by ISeeDEDPpl** [comment]
Do you have 
`<UseDrones>true</UseDrones>`
 or 
`<UseDrones>false</UseDrones>`
on that tengu?

**Comment by Pluckyduck** [comment]
<useDrones>false</useDrones>
  
  <droneTypeId>0</droneTypeId>

**Comment by ISeeDEDPpl** [comment]
ok, I just made a commit to bleedingedge that should fix that for ships w no drone bay (and thus useDrones = false)
