### ISSUE TITLE
After mission salvaging is broken

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#329]
After mission bot change ship to salvage ship and go to wrecks. 
He use tractor beams and draws them to each other and scoop loot, and very often after this for few minutes nothing happen ... sometimes use 1 salvager, sometimes use tractor. 
This increased the time of salvage twice or more.

**Comment by Pluckyduck** [comment]
what branch are you using?  Turn on  the setting <debugSalvage>true</debugSalvage> and remove any bookmark names.  These are items that help find the trouble.

**Comment by Pluckyduck** [comment]
[08:36] <Horatio> i closed my issue "After Misssion Salvaging" because i download the latest build and everything work properly. Thx for Your interest and sorry for my mistake
