### ISSUE TITLE
Dedicated Salvager BleedingEdge bug, re-opened

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#330]
http://pastebin.com/sMwN7kyQ

was seeming to work, i finally got a true chance to test it out.  

logs are in pastebin.

**Comment by I3Questor** [comment]
+1

I am having exactly the same issue.
Using version: fa69683c72a703b297c11f72883f6b3525042d6f

**Comment by ISeeDEDPpl** [comment]
well this issue does not exist in experimental. This is a bug introduced by the new behavior of skipping in progress mission bookmarks rather than just going back to base and waiting (which is a reasonable thing to do tbh). 

I added more logging to bleedingedge. I am going to need a log of this occurring to figure out why the pruning of the bookmarks within CloseScanRange is not working properly. I would generate the log myself but I do not use the dedicated salvager and this is a corner case... my bookmarks that have ages 45min are almost never still in an active mission. because of the nature of this problem it may take multiple logs and logging changes to get this resolved.

**Comment by I3Questor** [comment]
No worries ISDP. I will generate logs for you. So in the interim you suggest switching back to Experimenta?

EDIT:

Here is a log file mate.
http://db.tt/DoLMoVjs

ISeeDEDPpl notifications@github.com wrote:

> well this issue does not exist in experimental. This is a bug
> introduced by the new behavior of skipping in progress mission
> bookmarks rather than just going back to base and waiting (which is a
> reasonable thing to do tbh). 
> 
> I added more logging to bleedingedge. I am going to need a log of this
> occurring to figure out why the pruning of the bookmarks within
> CloseScanRange is not working properly. I would generate the log myself
> but I do not use the dedicated salvager and this is a corner case... my
> bookmarks that have ages 45min are almost never still in an active
> mission. because of the nature of this problem it may take multiple
> logs and logging changes to get this resolved. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ISeeDEDPpl/Questor/issues/330#issuecomment-12580835

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by Pluckyduck** [comment]
I was going to maybe suggest that we leave this feature alone and return back to the older way.  it took a couple of days to finally catch this situation to be able to log it.  Thoughts?

**Comment by Pluckyduck** [comment]
Sir,

  Logs as requested, i put on a short timer to cause the conflict to increase in chances.

http://pastebin.com/rXSjGUjc

PD

**Comment by I3Questor** [comment]
Been testing the new commits for the last 4 hours and salvager seems to be running fine. You can close this issue for now.

I am testing 9528ed45bcd27e013b8895fee13d7796e594ecbd

**Comment by Pluckyduck** [comment]
it was a revert and thanks for helping with the test.

**Comment by I3Questor** [comment]
No need to thank me mate, I use a dedicated salvager too.

**Comment by Pluckyduck** [comment]
was working on making it better, or working with ISDP to make it better.

**Comment by I3Questor** [comment]
yeah would love to see the salvager work better.
Would also love to see salvage stats!

**Comment by I3Questor** [comment]
is there any way we can have a dedicated salvager move to the next bookmark instead of going back to base?
The way it is right now, there are 40 bookmarks to salvage and yet the salvager is waiting for one of my chars to complete his mission because there is a gate in the oldest bm.

**Comment by ISeeDEDPpl** [comment]
yes, that is what this was attempting to do (and failing). Someone will need to debug why... If I get really bored Ill look into it again, but it'll likely be awhile.
