### ISSUE TITLE
Valuedump not selling anything

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#334]
HI,

Both in experimental and bleeding edge, Value Dump is not selling anything. There are buy orders, however Vd says "no orders".

I havent used it in quite a while so I have no idea when this issue started.

**Comment by ljk1291** [comment]
Weird just used it and it worked fine for me, are you sure youre using the latest build with the newest DE and questormodules.dll?

**Comment by Daxten** [comment]
you must manual change sell mode to simple

**Comment by ISeeDEDPpl** [comment]
Ive had multiple reports of it working fine. If you are having trouble I'll need a console log.
