### ISSUE TITLE
ISDP - Exp - 8cb03d2e6f - 3.4 Feb 2013

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#336]
was moving the gate key over for dread pirate mission

http://pastebin.com/X1YHN8d1

error-ed out and paused.

**Comment by Pluckyduck** [comment]
http://pastebin.com/UVKV1ayT  

happened again.

**Comment by ISeeDEDPpl** [comment]
this should now be fixed. there was a problem with the hangarIDs that has been fixed. if it repeats itself please open a new issue.
