### ISSUE TITLE
The Rogue Slave Trader (1 of 2) - permanent looting bug-loop

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#344]
So here it is, I was getting bugged on this mission ever since half a year ago. Finnally I've been able to pin the cause down. I am using the default mission xml that comes with questor for this mission, as it's standard one. 

When bug occurs:
After kill action is done on "Slave Pen" ir proceeds to atcion Loot with parameters Cargo Container and "Prisoners", but as  it approaches the container, in order to make room for 50 units of Prisoners (that take up 375 m3) Questor jettisons ship's ammo. Thus making another instance of "Cargo Container" , it then checks this new cargo container for "Prisoners" item value and returns "no valuable items found", then proceeds on checking every other wreck in the mission pocket to find "Prisoners" and fails.

When endless loop caused by the bug above begins:

It seems that Questor is not able to differentiate between two instances of "Cargo Container" them being close next to each other. As it checks first Cargo Container with prisoners, Questor decides to make room for them first, then makes  another can, and instantly opens that new can (which it just jettisoned with excess ammo) while still thinking it was the same one. Then returns result "no valuable items found" then checks all other wrecks, then throws an error and retries redoing the mission from scratch - so it then goes back to base, unloads loot, loads a fresh load of ammo and goes back, checks the container, finds it wont fit (again), jettisons, and there we go, we are in a permanent loop until the can with Prisoners expires in 2 hours or Questor logs off after no wallet income, thus resulting in being unable to complete mission. 

Possible causes:
 My guess would be that when new inventory window was introduced, cans  are opened in the same item window, when an item is jettisoned, inventory window switches to new can automatically. Or Questor has no hardcoded logic to deal with this new issue of single inventory window and new jetcans when the required cargo volume is occupied with ammo. The ship used here is Tengu, with a usual load of ammo for this mission being 165/440 m3.

Check:
Cargo Container and jetcan handling bits of code
Loot objects containing same name handling bits of code
Jettison to make room for mission objective  item handling  bits of code. 

Hope you find this information and insights useful. (This behavior should not happen with bigger ships, like marauders because of huge cargo space they have by default, or people  just put this mission into ignore list as it is not profitable, that's probably the reason the bug didn't come out into light before)

Here is the console log:

14:11:58 [CombatMissionCtrl] Finished Action.ClearPocket
14:11:58 [CombatMissionCtrl] Starting Action.Kill [target: Slave Pen]
14:11:59 [CombatMissionCtrl.Kill [target: Slave Pen]] Using Weapons Range \* 0.8d [24 k]: Approaching target [Slave Pen][ID: [truncatedID]51728][35k away]
14:12:15 [CombatMissionCtrl.Kill [target: Slave Pen]] Adding [Slave Pen][ID: [truncatedID]51728] as a primary weapon priority target
14:12:15 [CombatMissionCtrl.Kill [target: Slave Pen]] Adding [Slave Pen][ID: [truncatedID]51728] as a drone priority target
14:12:16 [Combat] Targeting priority target [Slave Pen][ID: [truncatedID]51728][29k away] highValueTargets.Count [0]
14:12:21 [Combat] Activating weapon [1] on [Slave Pen][ID: [truncatedID]51728][26k away]
14:12:23 [CombatMissionCtrl.Kill [target: Slave Pen]] Using Weapons Range: Stop ship, target is more than 5k inside weapons range
14:12:24 [CombatMissionCtrl.Kill [target: Slave Pen]] Using Weapons Range: Stop ship, target is more than 5k inside weapons range
14:12:48 [CombatMissionCtrl.Kill [target: Slave Pen]] All targets killed Slave Pen
14:12:48 [CombatMissionCtrl] Finished Action.Kill [target: Slave Pen]
14:12:48 [CombatMissionCtrl] Starting Action.ClearPocket
14:12:54 [CombatMissionCtrl] Finished Action.ClearPocket
14:12:54 [CombatMissionCtrl] Starting Action.Loot [target: Cargo Container] [item: Prisoners]
14:12:55 [CombatMissionCtrl.Loot [target: Cargo Container] [item: Prisoners]] Approaching target [Cargo Container][ID: [truncatedID]54682][24k away]
14:13:44 [Salvage] Opening container [Cargo Container][1k][ID: [truncatedID]54682]
14:13:50 [Salvage] Opening container [Cargo Container][1k][ID: [truncatedID]54682]
14:13:50 [Salvage] Jettisoning [1] items to make room for the more valuable loot
14:13:51 [CombatMissionCtrl.Loot [target: Cargo Container] [item: Prisoners]] Approaching target [Sansha's Demon Wreck][ID: [truncatedID]52770][25k away]
14:13:53 [Salvage] Opening container [Cargo Container][0k][ID: [truncatedID]90535]
14:13:59 [Salvage] Opening container [Cargo Container][2k][ID: [truncatedID]90535]
14:13:59 [Salvage.LootWrecks] Container [Cargo Container][2k][ID: [truncatedID]90535] contained no valuable items
14:14:13 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
14:14:20 [CombatMissionCtrl.Loot [target: Cargo Container] [item: Prisoners]] Approaching target [Sansha's Demon Wreck][ID: [truncatedID]52770][11k away]
14:15:30 [Combat] Opening Cargohold of active ship: waiting [3sec]

---

**Comment by CasualBod** [comment]
Here is mission xml. replaced first "<" opening with "[" here cause github makes mission xml text invisible inside of <-> brackets

[?xml version="1.0" encoding="utf-8" ?>
[mission>
 [pockets>
    [pocket id="0">
      [damagetype>EM</damagetype>
      [actions>
        [action name="ClearPocket" />
        [action name="Kill">
          [parameter name="Target" value="Slave Pen" />
        [/action>
        [action name="ClearPocket" />
        [action name="Loot">
          [parameter name="Target" value="Cargo Container" />
          [parameter name="Item" value="Prisoners" />
        [/action>
        [action name="Done" />
      [/actions>
    [/pocket>
  [/pockets>
[/mission>

**Comment by ISeeDEDPpl** [comment]
ok, yeah, that was a gnarly bug... I think I have fixed it in bleedingedge, but it needs testing. please test and report back. https://github.com/ISeeDEDPpl/Questor/commit/17c23e70c1b6e6a291667a4d51db9cf92ebeb18d

**Comment by CasualBod** [comment]
Thanks for looking into it, i'll report back when I run through this mission again, it may take a while :)

**Comment by CasualBod** [comment]
FIXED. All worked like a charm now, successfully ran 2 times, thanks! Using build from BleedinEdge (latest) 23d0591a664053ef1088469fce43ad9334c20b63

XX:13:26 [CombatMissionCtrl] Starting Action.Loot [target: Cargo Container] [item: Prisoners]
XX:13:27 [CombatMissionCtrl.Loot [target: Cargo Container] [item: Prisoners]] Approaching target [Cargo Container][ID: [truncatedID]09426][24k away]
XX:14:11 [Salvage] Opening container [Cargo Container][1k][ID: [truncatedID]09426]
XX:14:16 [Salvage] Opening container [Cargo Container][1k][ID: [truncatedID]09426]
XX:14:18 [Salvage] Jettisoning [1] items to make room for the more valuable loot
XX:14:23 [Salvage] Opening container [Cargo Container][0k][ID: [truncatedID]28901]
XX:14:29 [Salvage] Opening container [Cargo Container][0k][ID: [truncatedID]09426]
XX:14:34 [Salvage] Opening container [Cargo Container][0k][ID: [truncatedID]09426]
XX:14:34 [Salvage.LootWrecks] Looting container [Cargo Container][0k][ID: [truncatedID]09426], [1] valuable items
XX:14:35 [CombatMissionCtrl.Loot [target: Cargo Container] [item: Prisoners]] LootEverything: We are done looting
XX:14:35 [CombatMissionCtrl] Finished Action.Loot [target: Cargo Container] [item: Prisoners]
XX:14:35 [CombatMissionCtrl] Starting Action.Done
