### ISSUE TITLE
Questor doesn't put loot in loot container

### ISSUE THREAD

**Issue by DarkBahamuth** [ISeeDEDPpl/Questor#347]
Hi all,
I'm having a strange behaviour of questor in the late build (28 febraury). After the aftermission salvaging questor opens the loot container, stacks items in it, but leave items in the cargohold. 
This is the console log
<code>
19:29:51 [TravelerDestination.StationDestination] Arrived in station
19:29:51 [CombatMissionsBehavior.TravelHome] Arrived at destination
19:29:53 [CombatMissionsBehavior.TravelHome] Arrived at destination
19:29:54 [CombatMissionsBehavior.TravelHome] Arrived at destination
19:29:55 [CombatMissionsBehavior] UnloadLoot: Begin
19:30:11 [UnloadLoot.MoveAmmo] Stacking Item Hangar
19:30:17 [UnloadLoot.MoveLoot] Moving [86] items from CargoHold to LootHangar
19:30:22 [Cache.StackLootHangar] Opening Inventory Window: waiting [2sec]
19:30:27 [Cache.StackLootHangar] Loot Container window named: [ ('InventoryStation', None) ] was found and its contents are being stacked
</code>
As for the settings.xml, i'm using 

  lootHangar/>
  ammoHangar/>
  bookMarkHangar/>
  lootContainer>Loot</lootContainer

**Comment by Daxten** [comment]
First please update to the lates commit, there were some problems with this which got fixed.

Did it work before?
Are you using a Freight Container and no Station Container?

**Comment by DarkBahamuth** [comment]
It was working before, I'm using a Giant Freight Container (named "Loot"). I tried with the new release but it doesn't work.
I am not that good in programming but I could try to give a look, just I can't find where the "LootContainer" variable is used in the unloadloot routine (assuming i should look in questor.modules/actions/unloadloot.cs)

**Comment by ISeeDEDPpl** [comment]
It is supposed to be obfuscated a bit... in cache.instance.readyloothangar it decides where your loot hangar is configured, either itemhangar, corporatehangar or lootcontainer. 

if (!Cache.Instance.ReadyItemsHangarAsLootHangar(module)) return false;
or
if (!Cache.Instance.ReadyCorpLootHangar(module)) return false;
or
if (!Cache.Instance.ReadyLootContainer(module)) return false;

that way unloadloot does not have to know where it is dumping to.

"public bool ReadyLootContainer(String module)" is the function you are looking for. 
you should be able to test it from the GUI in the inventory tab.

before you go on a debugging spree make sure you are using the latest rev of bleedingedge. It would be a shame to fix the same bug twice =)

**Comment by DarkBahamuth** [comment]
Latest release of bleeding worked (probably I downloaded an experimental before the merge)
