### ISSUE TITLE
Stuck in ClearPocket

### ISSUE THREAD

**Issue by Daxten** [ISeeDEDPpl/Questor#350]
Hey, I could reproduce the problem. Again last Pocket in WorldsCollide

http://www.privatepaste.com/d4b93d8519

Sitting there doing nothing after killing the first few ships (rest doesn't aggro me automaticly)

**Comment by Daxten** [comment]
sorry tha's not everything let me repost the log in a sec when the bot has written everything to the disc

**Comment by Daxten** [comment]
Okay that was actualy everything :) until line "02:17:18 [Questor] Wallet Balance Has Not Changed in [ 6 ] minutes.
"
after that I manualy targeted a ship

**Comment by Pluckyduck** [comment]
loot and be done with the mission? only the ones that auto agro are required.

**Comment by Daxten** [comment]
I dont know what that has to do with the problem Pluckyduck? I know that I can loot and end the Missions but that won't fix the Problem with Questor got here

**Comment by Pluckyduck** [comment]
so you are only have it with that pocket, and it was a suggestion.

**Comment by Daxten** [comment]
The Problem is that it doesnt even finish the clear pocket command, as you can see in the log and description :)

**Comment by ISeeDEDPpl** [comment]
not sure on this one. Ill need to do some debugging here... 
it is either the __clearPocketTimeout timestamp setting / checking or something that was changed when the "if (target != null)" was added

**Comment by ISeeDEDPpl** [comment]
Is this still occurring with latest bleedingedge? (as of April 7th 2013: 49b1caa4faa412c82ce8dbbd0bab4e3df02c2a8c)

this SHOULD be fixed, but needs testing.

**Comment by ISeeDEDPpl** [comment]
if anyone sees this happening they need to open a new issue w a console log.
