### ISSUE TITLE
Nullpointer in Defense.cs

### ISSUE THREAD

**Issue by Daxten** [ISeeDEDPpl/Questor#351]
I get sometimes a Nullpointer in Defense.cs:579, I'm using an Afterburner.

It loops the NullpointerExc a few times and then resumes, I will try to get more info on this

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/99dc825930a7eb334af4746faf493afbb33c2c17
