### ISSUE TITLE
directeve.dll

### ISSUE THREAD

**Issue by drokk99** [ISeeDEDPpl/Questor#358]
Forgive me if I am wrong here but shouldn't the new directeve go into the directeve folder and not the output, just uses the old DE to compile and copies it over.

**Comment by ISeeDEDPpl** [comment]
yes, it should... fail.

**Comment by ISeeDEDPpl** [comment]
...and THIS is why you should always make sure you are using the latest directeve before compiling. =(
https://github.com/ISeeDEDPpl/Questor/commit/fadd8048b304b21cceccea9b3ccbce0c969a9f98
