### ISSUE TITLE
Statistics and salvage time

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#36]
Doesn't work. Always in this case have value 0

**Comment by ISeeDEDPpl** [comment]
Do you use after mission salvaging? which of the 3 log formats have the problem?

**Comment by oldmeat** [comment]
Yes, i always use after mission salvaging. Questor should write in .NET Programs/log/CharacterName/missionstatts/CharacterName.statistics.txt time of salvage, but he did'nt.
Before i report bug salvage value, now work but it happens that this is not done:

2012-04-08 01:21:27;Pirate Invasion;42;0;43;11016101;0;5458;
2012-04-08 02:02:27;Pot and Kettle - Wounded Hunter (1 of 5);40;0;40;1895260;29502694;4183;
2012-04-08 03:13:56;Buzz Kill;71;0;71;10890990;7023997;6967;

In all these missions bot use after mission salvaging and get salvage and loot, but in mission Pirate Invasion do not count salvage value. 
I update before UpdateInvTypes but it did not help.

**Comment by ISeeDEDPpl** [comment]
ok, I think this has something to do with more than one salvage run to and from the station to the mission. I'll look into it.
