### ISSUE TITLE
on panic firing to not targeted ID, possible priority \ locking issue

### ISSUE THREAD

**Issue by bugc** [ISeeDEDPpl/Questor#360]
Hi ISDPpl. I was investigating why 3 ships were down by NPC in _one_ day when I realized this issue. Log to see console is there: http://tny.cz/16e6fdca

So, 5 of targets were locked (char's limited by 5) when some ugly frigate scrambled me. Q did NOT unlock but tried to shoot the dare down. EVE responded 2 to 4 times: you group of bla-bla tried to shoot but target is not locked yet (or something with same meaning: fired but to target with no lock on it). Yes it were Guristas with possible dump but I didn't see dump on me, overview might stuck, but still 5 of 5 possible targets were locked on far distance (~50km, frig is in close).

According to log you can see it took too much time to deal with ugly frigate. And no damage done (because no lock was to time Q tried to activate primary weapon but failed). In previous implementations it was as: some of actual targets was unlocked to make lock on scrambler to shoot down. And my ship is able to vaporize any frigate in less than 15sec. So I adjusted damage\tank to this condition. When 3-4 scramblers are not dealt timely ship is being stopped, popped and welcome jita with you new shiny malls.

Please say something if I am wrong, probably it is too late at night now and I missed something. Until your respond I would suggest ppl check capacitor stability and tanking in general. I belive 3 tengu were down by co-indecent, but you could imagine my paranoia when I looked at 'last night results' ___

**Comment by bugc** [comment]
...another mission - Buzz Kill - there are lots of frigates if wrong fork is summoned. Was watching for minutes how Q fly around structure with max_targets locked under scrambler. Mission was fine with cap.unstable fitting - I was able shoot them down with previous logic when some of already locked targets was dropped to allow lock tackler.

**Comment by bugc** [comment]
seems it is same shit to https://github.com/ISeeDEDPpl/Questor/issues/356

**Comment by ISeeDEDPpl** [comment]
this was a DE bug that should now be fixed in bleedingedge (one instance of DE is all we ever use now)
