### ISSUE TITLE
Storyline mission - sits in station:

### ISSUE THREAD

**Issue by DanAsBjorn** [ISeeDEDPpl/Questor#362]
Taken from logs:

"21:46:41 [Questor] Start Mission Behavior
21:46:42 [CombatMissionsBehavior] Random start delay of [0] seconds
21:46:45 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 656 MB
21:46:45 [Storyline] Currently have [3] missions available
21:46:45 [Storyline] Currently have [1] storyline missions available
21:46:45 [Storyline] Currently have [1] storyline missions questor knows how to do
21:46:45 [Storyline] Currently have [1] storyline missions questor knows how to do and are not blacklisted
21:46:45 [CombatMissionsBehavior] Storyline detected, doing storyline.
21:46:47 [CombatMissionsBehavior.TravelHome] Destination: [x - Moon x - x]
21:46:47 [TravelerDestination.StationDestination] Destination set to [x IV - x x- x]
21:46:50 [TravelerDestination.StationDestination] Arrived in station
21:46:50 [CombatMissionsBehavior.TravelHome] Arrived at destination
21:46:51 [Storyline] Currently have [3] missions available
21:46:51 [Storyline] Currently have [1] storyline missions available
21:46:51 [Storyline] Currently have [1] storyline missions questor knows how to do
21:46:51 [Storyline] Currently have [1] storyline missions questor knows how to do and are not blacklisted
21:46:51 [Storyline] Going to do [Materials For War Preparation] for agent [x x] x[x]
21:46:54 [TravelerDestination.StationDestination] Destination set to [xx X - Moon x - xx]
21:49:19 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
21:50:20 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
21:51:21 [Questor] Wallet Balance Has Not Changed in [ 5 ] minutes.
21:52:22 [Questor] Wallet Balance Has Not Changed in [ 6 ] minutes.
21:53:22 [Questor] Wallet Balance Has Not Changed in [ 7 ] minutes.
21:54:23 [Questor] Wallet Balance Has Not Changed in [ 8 ] minutes.
21:55:24 [Questor] Wallet Balance Has Not Changed in [ 9 ] minutes.

This is printed on the console:

Exception during event execution: System.Collections.Generic.KeyNotFoundException: The given key was not present in the
dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at Questor.Modules.Caching.Cache.CheckifRouteIsAllHighSec() in
c:\xyz\Questor.Modules\Caching\Cache.cs:line 2610

   at Questor.Storylines.Storyline.GotoAgent(StorylineState nextState) in
c:\xyz\Questor-BleedingEdge\Questor\Storylines\Storyline.cs:line 406

   at Questor.Storylines.Storyline.ProcessState() in
c:\xyz\Questor\Storylines\Storyline.cs:line 513

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\xyz\Questor\Behaviors\CombatMissionsBehavior.cs:line 1307

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in
c:\xyz\Questor-BleedingEdge\Questor\Questor.cs:line 631

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by Daxten** [comment]
I can confirm that this is a bug, but I dont know what exactly is going wrong here..
Ive fixed it internaly by catching the error, but that's no real fix since it won't check for that Key if it is in HighSec

**Comment by DanAsBjorn** [comment]
Referenced here in Feburary and closed: https://github.com/ISeeDEDPpl/Questor/issues/337

**Comment by DanAsBjorn** [comment]
Explained here although goes over my head unfortunately: https://github.com/ISeeDEDPpl/Questor/issues/187

**Comment by EchuI** [comment]
same problem

**Comment by EchuI** [comment]
At your own risk - disable highsec scanning for storyline

temporary solution - comment out the following in cache.cs:

```
            Cache.Instance.RouteIsAllHighSecBool = false;
            // Find the first waypoint
            List<long> currentPath = DirectEve.Navigation.GetDestinationPath();
            if (currentPath == null || !currentPath.Any()) return false;
            if (currentPath[0] == 0) return false; //No destination set - prevents exception if somehow we have got an invalid destination

            for (int i = currentPath.Count - 1; i >= 0; i--)
            {
                DirectSolarSystem solarSystemInRoute = Cache.Instance.DirectEve.SolarSystems[currentPath[i]];
                if (solarSystemInRoute.Security < 0.45)
                {
                    //Bad bad bad
                    Cache.Instance.RouteIsAllHighSecBool = false;
                    return true;
                }
            }
```

As a result, you should get the following code:

```
        public bool CheckifRouteIsAllHighSec()
        {
            //Cache.Instance.RouteIsAllHighSecBool = false;
            //// Find the first waypoint
            //List<long> currentPath = DirectEve.Navigation.GetDestinationPath();
            //if (currentPath == null || !currentPath.Any()) return false;
            //if (currentPath[0] == 0) return false; //No destination set - prevents exception if somehow we have got an invalid destination

            //for (int i = currentPath.Count - 1; i >= 0; i--)
            //{
            //    DirectSolarSystem solarSystemInRoute = Cache.Instance.DirectEve.SolarSystems[currentPath[i]];
            //    if (solarSystemInRoute.Security < 0.45)
            //    {
            //        //Bad bad bad
            //        Cache.Instance.RouteIsAllHighSecBool = false;
            //        return true;
            //    }
            //}
            Cache.Instance.RouteIsAllHighSecBool = true;
            return true;
        }
```

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/64303d13af26a978d8e7a76460bdfb1cb441d43e
probably fixes this. it is pretty difficult to reproduce however so any help in testing this would be appreciated.

**Comment by ISeeDEDPpl** [comment]
test latest bleedingedge pls. this was seemingly caused by stations in the autopilot path
