### ISSUE TITLE
Dedicated BM salvager

### ISSUE THREAD

**Issue by grio43** [ISeeDEDPpl/Questor#363]
When the salvager warps to a BM that is dated, it will try to remove the BM. It sits at error removing bookmark!bmname: 123

I remove that BM. it tries to remove other dated BMs and get stuck for each one. I remove them all by hand than everything starts working fine again. No issues for the rest of the day due to the salvager keeping up all BMs and removing them after completion.

**Comment by ISeeDEDPpl** [comment]
bad? workaround in bleedingedge for this... a large number of expired bookmarks will be troublesome until this section of code is reworked a bit.
