### ISSUE TITLE
Initiating new orbiting takes a lot of time

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#369]
Well another thing which is happening to questor is that when he kills a locked  target in range he just fly for 1 or 2 minutes in one direction without setting a new orbit to targets which are out of range and not attacking us. Log is like this:

:24:37 [Combat] Activating painter [1] on [Centus Slave Lord][ID: [truncatedID]33014][32k away]
:24:39 [Combat] Activating painter [2] on [Centus Slave Lord][ID: [truncatedID]33014][32k away]
:24:41 [Combat] Out of range. ignoring orbit around structure.
:24:41 [Combat] Initiating Orbit [Centus Slave Lord][at 15k][ID: [truncatedID]33014]
:24:51 [Combat] Activating weapon  [1] on [Centus Slave Lord][ID: [truncatedID]33014][33k away]
:24:51 [Combat] Activating weapon  [2] on [Centus Slave Lord][ID: [truncatedID]33014][33k away]
:24:55 [Combat] Activating weapon  [3] on [Centus Slave Lord][ID: [truncatedID]33014][31k away]
:25:11 [Combat] Activating weapon  [3] on [Centus Slave Lord][ID: [truncatedID]33014][25k away]
:26:12 [CombatMissionCtrl.ClearPocket] Out of range. ignoring orbit around structure.
:26:12 [CombatMissionCtrl.ClearPocket] Initiating Orbit [Centus Mutant Lord][at 15k][ID: [truncatedID]33263]

**Comment by ISeeDEDPpl** [comment]
speed tank == true, I assume

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/87405473e4287969b0555cbc02ceda71f4739b45
