### ISSUE TITLE
Combat not switching to webbers

### ISSUE THREAD

**Issue by nico-rip** [ISeeDEDPpl/Questor#372]
While running Duo of Death I noticed that even though we were targetting the spider drones (heavy webbers), we were not making them the highest priority and killing them first.

Latest BleedingEdg: fb68d6bc803a6072522cc0ee22983c46586cd84d

Private paste of redacted log: http://privatepaste.com/f7b8159b98

Combat/Salvage ship names as well as system names have also been redacted

Relevant pieces of config:

insideThisRangeIsHardToTrack 0

addDampenersToPrimaryWeaponsPriorityTargetList true
addECMsToPrimaryWeaponsPriorityTargetList true
addNeutralizersToPrimaryWeaponsPriorityTargetList true
addTargetPaintersToPrimaryWeaponsPriorityTargetList true
addTrackingDisruptorsToPrimaryWeaponsPriorityTargetList true
addWarpScramblersToPrimaryWeaponsPriorityTargetList true
addWebifiersToPrimaryWeaponsPriorityTargetList true

optimalRange 0

**Comment by ISeeDEDPpl** [comment]
this has been fixed here: https://github.com/ISeeDEDPpl/Questor/commit/8a45ef1e0439a4dfded15c9fbd8ae47f6a7546b3

please test. it should now prioritize within the prioritytarget lists much better (previously if we were shooting ANY priority target (including the ones added at a low priority by the MissionController) it would wait until that NPC was dead before switching targets. now it will switch away if their is any high priority target targeted (the targeting part will need to be fixed separately if it is an issue).
