### ISSUE TITLE
Possible handling of Inproper agent configuration

### ISSUE THREAD

**Issue by nico-rip** [ISeeDEDPpl/Questor#373]
Right now if you configure your settings to use an agent that is not available to you Questor hangs at that agent waiting to reply. If there is a way to handle this and skip (maybe blacklist the agent for the session) and keep on trucking it would be sweet

**Comment by ISeeDEDPpl** [comment]
Ive added this to questor. You can adjust the values in your characters settings xml if they are wrong. (do they take skills into account?)
`<standingsNeededToAccessLevel1Agent>-11</standingsNeededToAccessLevel1Agent>`
`<standingsNeededToAccessLevel2Agent>1</standingsNeededToAccessLevel2Agent>`
`<standingsNeededToAccessLevel3Agent>3</standingsNeededToAccessLevel3Agent>`
`<standingsNeededToAccessLevel4Agent>5</standingsNeededToAccessLevel4Agent>`
`<standingsNeededToAccessLevel5Agent>7</standingsNeededToAccessLevel5Agent>`
it will move on to the next agent if your standings dip below this (even without having to decline a mission like the other code elsewhere)... this probably needs some cleanup and combining of the other similar code in the decline mission portion of agent interaction. but its in, it works.
