### ISSUE TITLE
Build error on latest commit

### ISSUE THREAD

**Issue by nico-rip** [ISeeDEDPpl/Questor#375]
BleedingEdge version: abd38451247d562ae1e2e369efdb66828001d717

![Untitled](https://f.cloud.github.com/assets/4204186/418263/b51b2340-ac9a-11e2-990f-e1e52d14823a.png)

Got this error using the compile file

**Comment by nico-rip** [comment]
Got it to build. questor.modules is missing the reference to htmlagilitypack and the agent interactions is missing the using statement in the latest commit

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge and experimental
