### ISSUE TITLE
ENH: Complete a previously accepted mission

### ISSUE THREAD

**Issue by nico-rip** [ISeeDEDPpl/Questor#376]
Description says it all. It would be a nice addition if we could complete a mission that was already accepted for a configured agent. This way when we have issues and have to restart eve/q for whatever reason it doesnt error out trying to "complete mission"

**Comment by ISeeDEDPpl** [comment]
It already does this. Can you provide a log where it is not working as expected?

**Comment by nico-rip** [comment]
Was informed that this SHOULD work. Apparently it will try to complete the mission in conversation, fail since the mission isnt complete, and will catch it the 2nd time around and run the mission. Will verify one way or another and post logs if need be.

**Comment by nico-rip** [comment]
Ok this is the case :D. Sorry Ded
