### ISSUE TITLE
Bleeding Edge latest build: … 1c9c435b93 Caching\Cache.cs(3131,217): error CS0103:

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#377]
Caching\Cache.cs(3131,217): error CS0103: name "**entity**" does not exist in the current context. ...
[... \Questor.Modules\Questor.Modules.csproj]

**Comment by ISeeDEDPpl** [comment]
seems to only be an issue in the logging... fixed.

**Comment by kn0xv1lle** [comment]
Getting also an error when compiling
 "C:\Questor-BleedingEdge\BuyLPI\BuyLPI.csproj" (Clean;Build target) (1) ->
"C:\Questor-BleedingEdge\Questor.Modules\Questor.Modules.csproj" (default targe
t) (2:2) ->
(CoreCompile target) ->
  Caching\Cache.cs(3133,217): error CS0103: The name '__entity' does not exist
in the current context [C:\Questor-BleedingEdge\Questor.Modules\Questor.Modules
.csproj]
