### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#378]
"C:\Questor-BleedingEdge\BuyLPI\BuyLPI.csproj" (Clean;Build target) (1) ->
"C:\Questor-BleedingEdge\Questor.Modules\Questor.Modules.csproj" (default targe
t) (2:2) ->
(CoreCompile target) ->
  Caching\Cache.cs(3133,217): error CS0103: Der Name "__entity" ist im aktuelle
n Kontext nicht vorhanden. [C:\Questor-BleedingEdge\Questor.Modules\Questor.Mod
ules.csproj]

```
4 Warning(s)
1 Error(s)
```

**Comment by ISeeDEDPpl** [comment]
fixed.

**Comment by kn0xv1lle** [comment]
Thanks i see ;)
