### ISSUE TITLE
The latest Bleeding Edge, targeting is broken

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#383]
commit: ebfe9860b715782db56d5da8fab88d9d4d8c3c01

My ship target only one ship, when he kill npc, wait about 15sec and target another one. 
Edit: He target ship in a given unit of time ... If i shoot to BS which takes longer, he then have time to trace the second ship

**Comment by Pluckyduck** [comment]
http://pastebin.com/28iP2GJA

break out for the test with break out point with setting changes.  

PD

**Comment by ISeeDEDPpl** [comment]
Can we get a similar log with 
`<debugTargetCombatants>true</debugTargetCombatants>`

**Comment by nico-rip** [comment]
http://privatepaste.com/5f83e01e2d

**Comment by Pluckyduck** [comment]
04:13 Webber locked but not fired on,,,finished killing throx

04:17 is broken time

04:18 manually locking target to finish mission

04:21 end

log part 1 of 2

http://pastebin.com/kXBJk8d0

log part 2 of 2

http://pastebin.com/xag0uVQd

**Comment by nico-rip** [comment]
So after running a few more, I am noticing that it takes a mob or two for it to kick in and decide that it wants to target multiple things. But after it kills 1 or 2 mobs by only targetting 1 at a time, it does kick in and start targetting everything like it should.

**Comment by Pluckyduck** [comment]
15:35:18 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets below
15:35:18 [Combat.TargetCombatants] [1] Name [Pleasure Hub Patroller] Distance [40.28] TypeID [13163] groupID [818]
15:35:18 [Combat.TargetCombatants] [2] Name [Pleasure Hub Patroller] Distance [35.68] TypeID [13163] groupID [818]
15:35:18 [Combat.TargetCombatants] [3] Name [Pleasure Hub Patroller] Distance [36.96] TypeID [13163] groupID [818]
15:35:18 [Combat.TargetCombatants] [4] Name [Kruul's Henchman] Distance [34.89] TypeID [11598] groupID [818]
15:35:18 [Combat.TargetCombatants] [5] Name [Kruul's Henchman] Distance [35.6] TypeID [11598] groupID [818]
15:35:18 [Combat.TargetCombatants] [6] Name [Kruul's Henchman] Distance [34.51] TypeID [11598] groupID [818]
15:35:18 [Combat.TargetCombatants] [7] Name [Kruul's Henchman] Distance [34.64] TypeID [11598] groupID [818]
15:35:18 [Combat.TargetCombatants] [8] Name [Kruul's Henchman] Distance [36.1] TypeID [11598] groupID [818]
15:35:18 [Combat.TargetCombatants] [9] Name [Kruul's Henchman] Distance [35.79] TypeID [11598] groupID [818]
15:35:18 [Combat.TargetCombatants] [10] Name [Kruul's Henchman] Distance [35.58] TypeID [11598] groupID [818]
15:35:18 [Combat.TargetCombatants] [11] Name [Kruul's Henchman] Distance [35.56] TypeID [11598] groupID [818]
15:35:18 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets above
*
*
*
*
*
20:35:18 [Combat.TargetCombatants] TargetingMe [0] lowValueTargetingMe [0] highValueTargetingMe [0]
*
- everything in the room was targeting me
  *
  15:35:18 [Combat.TargetCombatants] DebugTargetCombatants: 0 dronePriority targets
  15:35:18 [Combat.TargetCombatants] DebugTargetCombatants: 0 primaryWeaponPriority targets
  15:35:18 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in highValueTargetingMe)
  15:35:18 [Combat.TargetCombatants] DebugTargetCombatants: 0 highValueTargetingMe targets
  15:35:18 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in lowValueTargetingMe)
  15:35:18 [Combat.TargetCombatants] DebugTargetCombatants: 0 lowValueTargetingMe targets
  15:35:18 [Combat.TargetCombatants] DebugTargetCombatants: 0 NotYetTargetingMe targets

**Comment by ISeeDEDPpl** [comment]
it SHOULD be fixed in bleedingedge.

**Comment by ISeeDEDPpl** [comment]
confirmed fixed.
