### ISSUE TITLE
NulReferenceException in Combat

### ISSUE THREAD

**Issue by nico-rip** [ISeeDEDPpl/Questor#388]
http://privatepaste.com/49d1cd7fba

Gonna test without the kill command at the beginning of the pocket and see what happens

**Comment by nico-rip** [comment]
Tried without the kill command and it didnt change the outcome. I believe this has to do with the ignores actually. It looks like it targets one of the ignored mobs, unlocks it, but is still trying to orbit/kill that mob.

**Comment by nico-rip** [comment]
Ok so I took it down to a bare minimum, single ship left in the pocket, with a simple ClearPocket command. Still does the same thing so really not sure whats going on here.

**Comment by ISeeDEDPpl** [comment]
fixed.
