### ISSUE TITLE
Not activating weapons or offensive modules

### ISSUE THREAD

**Issue by nico-rip** [ISeeDEDPpl/Questor#389]
http://privatepaste.com/acc83091b2

Ok almost there, seems that targetting is working properly and we are returning a valid target, but its still not activating any modules. FYI the log is WITH debugactivate true

**Comment by Status12** [comment]
I am getting the same thing. Questor only targets 2 enemies at a time, and keeps trying to retarget other enemies (while not activating any weapon modules).

**Comment by ISeeDEDPpl** [comment]
should be fixed, other bugs there though, fixing em as I see em.
