### ISSUE TITLE
Questor try shoot to not exist target and freezing again

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#391]
The latest build:Bleeding Edge: 27eac64f7e3115b246d379c3b0bf191c408e32f0

First client:
Eve client send information: You cannot attack/target to non exist ship. Or something like that.And he stuck in this loop.
http://privatepaste.com/1092786c75

Second client freeze like before ...
http://privatepaste.com/455b416692

**Comment by ISeeDEDPpl** [comment]
fixed?

https://github.com/ISeeDEDPpl/Questor/commit/7e6ea33be6268073a65a63feec270a47e1dd20e2

**Comment by ISeeDEDPpl** [comment]
this has been fixed afaik, hopefully we do not have any more of these. bleedingedge is a bit rough atm. I should have it behaving sometime tonight/ tomorrow.
