### ISSUE TITLE
Searching target although its dead

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#393]
Well questor shoot a target, target died he still think that the dead target its the best target and wants to shoot it.

13:34:51 [Drones] [Pithi Arrogator][ID: [truncatedID]03768][49k away] is now the target for drones
13:34:52 [Drones] [Pithi Arrogator][ID: [truncatedID]03768][50k away] is now the target for drones
13:34:52 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:34:53 [Drones] Recalling [ 3 ] drones because no NPC is targeting us within dronerange
13:34:54 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:34:56 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:34:58 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:00 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:02 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:04 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:06 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:08 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:10 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:12 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:14 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:16 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:19 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]
13:35:21 [CombatMissionCtrl.ClearPocket] Adding [Habitat] Speed [0k/s] Distance [8,08] [ID: [truncatedID]03337] as a
PrimaryWeaponPriorityTarget [PriorityKillTarget]

Stuck here althoug there are other Targets on grid.

**Comment by nico-rip** [comment]
kn0x is this a KillAction that you are using in the XML?

**Comment by ISeeDEDPpl** [comment]
likely. if this is not fixed in bledingedge, it will be shortly.
