### ISSUE TITLE
in bleeding : issue on autojump

### ISSUE THREAD

**Issue by bugc** [ISeeDEDPpl/Questor#394]
http://i44.tinypic.com/4j5ngl.jpg
You can not navigate this way with the selected object as it is too far away...

it happens after each gate, manual moving towards destination solves
when no move Q stick in cloak

**Comment by lDarko** [comment]
I have the same problem.

**Comment by ISeeDEDPpl** [comment]
does this still exist in bleedingedge? you can test by setting the destination in eve and using the traveler option in the pull down menu....

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge, by Nico
