### ISSUE TITLE
Problem with NPCs range.

### ISSUE THREAD

**Issue by lDarko** [ISeeDEDPpl/Questor#395]
Hi all :)

I noticed that often, during a mission, my ship start going away from NPCs. 
When it go out of missile and targeting range, Questor does nothing to fix this problem, and the ship continues going away from the battlefield. 
How can i fix that?

That's the log: 
I can't see the problem :S

10:50:58 [Combat] Activating weapon [1] on [Pith Extinguisher][ID: [truncatedID]75682][32k away]
10:51:04 [Combat] Activating weapon [1] on [Pith Extinguisher][ID: [truncatedID]75682][29k away]
10:51:51 [Combat] Targeting high value target [Pithatis Revolter][ID: [truncatedID]81850][34k away] highValueTargets.Count [1]
10:51:53 [Combat] Targeting priority target [Pith Extinguisher][ID: [truncatedID]75682][13k away] highValueTargets.Count [1]
10:51:55 [Panic] Adding [Pithatis Revolter][ID: [truncatedID]81850] as a PrimaryWeaponPriorityTarget
10:51:55 [Combat] Targeting high value target [Pithatis Enforcer][ID: [truncatedID]81855][34k away] highValueTargets.Count [1]
10:51:56 [Combat] Activating weapon [1] on [Pithatis Revolter][ID: [truncatedID]81850][31k away]
10:51:59 [Combat] Out of range. ignoring orbit around structure.

**Comment by ISeeDEDPpl** [comment]
is this experimental or bleedingedge?

**Comment by kn0xv1lle** [comment]
Looks like experimental

**Comment by Pluckyduck** [comment]
I have this problem in EXP but it will pick up around 30 seconds to 1 minute later.

**Comment by ISeeDEDPpl** [comment]
this is fixed in bleedingedge (which probably has other issues atm). bleedingedge will be merged back into experimental when it stabilizes shortly

**Comment by lDarko** [comment]
Perfect, thanks for the infos :)
