### ISSUE TITLE
combat issue

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#396]
When in combat its looking targets but don t shoot and spam thos

Exception during event execution: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz
festgelegt.

   bei Questor.Modules.Caching.Cache.GetBestTarget(IEnumerable`1 _potentialTargets, Double distance, Boolean
lowValueFirst, String callingroutine) in c:\Questor-BleedingEdge\Questor.Modules\Caching\Cache.cs:Zeile 3178.

   bei Questor.Modules.Activities.CombatMissionCtrl.AddPriorityKillTargetsAndMoveIntoRangeAsNeeded(IEnumerable`1 targets,
Double range, Int32 targetedby, Boolean MoveShip) in
c:\Questor-BleedingEdge\Questor.Modules\Activities\CombatMissionCtrl.cs:Zeile 123.

   bei Questor.Modules.Activities.CombatMissionCtrl.ClearPocketAction(Action action) in
c:\Questor-BleedingEdge\Questor.Modules\Activities\CombatMissionCtrl.cs:Zeile 582.

   bei Questor.Modules.Activities.CombatMissionCtrl.PerformAction(Action action) in
c:\Questor-BleedingEdge\Questor.Modules\Activities\CombatMissionCtrl.cs:Zeile 1857.

   bei Questor.Modules.Activities.CombatMissionCtrl.ProcessState() in
c:\Questor-BleedingEdge\Questor.Modules\Activities\CombatMissionCtrl.cs:Zeile 2085.

   bei Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\Questor-BleedingEdge\Questor\Behaviors\CombatMissionsBehavior.cs:Zeile 700.

   bei Questor.Questor.EVEOnFrame(Object sender, EventArgs e) in c:\Questor-BleedingEdge\Questor\Questor.cs:Zeile 614.

   bei DirectEve.DirectEve.(Object , EventArgs )

   bei DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

**Comment by nico-rip** [comment]
I will look into this, this evening.

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge.
