### ISSUE TITLE
Experimental - Weapon Cycling Issue

### ISSUE THREAD

**Issue by lDarko** [ISeeDEDPpl/Questor#397]
Often in mission when the bot starts shooting NPCs it just continues cycling and decycling weapons.

That' s the log:

14:53:57 [Combat] Initiating Orbit [Zor][at 20k][ID: [truncatedID]23780]
14:53:57 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][35k away]
14:54:07 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][34k away]
14:54:18 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][30k away]
14:54:28 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][26k away]
14:54:38 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][22k away]
14:54:49 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][20k away]
14:54:59 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][21k away]
14:55:09 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][21k away]
14:55:20 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][22k away]
14:55:30 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][21k away]
14:55:41 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][21k away]
14:55:51 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][21k away]
14:56:01 [Combat] Activating weapon [1] on [Zor][ID: [truncatedID]23780][21k away]

As you can see it just shoot one cycle and then deactive the weapon to turn it on again after some seconds.

Is this a bug? Or I' m doing something wrong?

**Comment by lDarko** [comment]
EDIT: seems like that the problem is when i use ammos different from Scourge Missiles.

I fly a Tengu, and when i use Scourge (T1/T2) i have no problem.
With Inferno, Mjolnir and Nova i have this issue.

Hope it can help solving it :)

**Comment by lDarko** [comment]
I noticed that when using ammos different from Scourge, i have this problem of continuous decycling guns only when the bot have to shoot at battleships.

**Comment by lDarko** [comment]
Second Edit: I'm having problems with Scourge Missiles too.

**Comment by ISeeDEDPpl** [comment]
Is this still occurring with latest bleedingedge? I have had no one that was able to reproduce this issue. Please provide another log if you are still having similar problems with bleedingedge.

**Comment by lDarko** [comment]
I didn't try the new BleedingEdge yet, but i noticed that maybe it was my falut because i wrote something wrong in my char's xml. I' ll let you know if i'm still having this problem :)
