### ISSUE TITLE
targeting issues (Bleeding - 5047428f31 - 10.5 May)

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#398]
Working a mission over with Kill command vs clearpocket.  

was working fine and then something went haywire.

Last 4 things to kill was locked up but Q was not seeing that it was locked up.

log below

http://pastebin.com/F6QZpzt6

or

01:11:39 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][2] targets already, LockTarget failed (unknown reason)
01:11:39 [Combat] Targeting high value target [Corelatis Captain Sentry][ID: [truncatedID]42797][39k away] highValueTargets.Count [2]
01:11:39 [CombatMissionCtrl.Kill [target: Guardian Veteran]] All targets killed Guardian Veteran
01:11:39 [CombatMissionCtrl] Finished Action.Kill [target: Guardian Veteran]
01:11:39 [CombatMissionCtrl] Starting Action.Activate [target: Gate To The Serpentis Base]
01:11:40 [CombatMissionCtrl.Activate] Approaching target [Gate To The Serpentis Base][ID: [truncatedID]42816][85k away]
01:11:41 [Combat] Targeting preferred primary weapon target [Guardian Veteran][ID: [truncatedID]42790][47k away] potentialHighValueTargets.Count [0]
01:11:41 [CombatMissionCtrl] Activate: Delaying approach for: [14] seconds
01:11:42 [CombatMissionCtrl] Activate: Delaying approach for: [13] seconds
01:11:43 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][3] targets already, can retarget in [18]
01:11:43 [Combat] Targeting high value target [Corelatis High Captain][ID: [truncatedID]42800][50k away] highValueTargets.Count [3]
01:11:45 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][3] targets already, can retarget in [16]
01:11:47 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [14]
01:11:50 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [12]
01:11:52 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [9]
01:11:54 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [7]
01:11:56 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [5]
01:11:58 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [3]
09:09:00 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [1]
09:09:02 [Combat] Targeting preferred primary weapon target [Guardian Veteran][ID: [truncatedID]42790][47k away] potentialHighValueTargets.Count [0]
09:09:04 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [18]
09:09:06 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [16]
09:09:09 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [14]
09:09:11 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [12]
09:09:13 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [9]
09:09:15 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [7]
09:09:17 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [5]
09:09:19 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [3]
09:09:21 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [1]
09:09:23 [Combat] Targeting preferred primary weapon target [Guardian Veteran][ID: [truncatedID]42790][47k away] potentialHighValueTargets.Count [0]
09:09:25 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [18]
09:09:28 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [16]
09:09:30 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [14]
09:09:32 [EntityCache.LockTarget] [TargetCombatants.PreferredPrimaryWeaponTarget] tried to lock [Guardian Veteran][46.89k][[truncatedID]42790][4] targets already, can retarget in [12]

**Comment by ISeeDEDPpl** [comment]
this should be fixed.
if their are targeting issues they are highly likely to be different now.

**Comment by Pluckyduck** [comment]
thanks @ISeeDEDPpl
