### ISSUE TITLE
Bleeding edge unlocking locking issue when there is more then one scrambler, webber

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#399]
When there is more then one scrambler or webber questor unlocks the old scrambler and tries to primary the other. When the other stop scrambling/webbing and the other is scrambling he unlocks the old scrambler. 
Would be better if questor still primary the old  webber/scrambler until he is dead or don t  unlock him because retargeting always tooks a lot of time.

**Comment by nico-rip** [comment]
https://github.com/nico-rip/Questor/commit/4719a80e11458a26e9600320255cbbd22495a05d

This should fix it.
