### ISSUE TITLE
Finished Mission and wont dock.

### ISSUE THREAD

**Issue by Blinker** [ISeeDEDPpl/Questor#4]
15:42:55 MissionController: Reloading All [1005604619827] with [Mjolnir Heavy Missile][207]
15:42:58 Traveler.StationDestination: Destination set to [Station Name]
15:42:59 Traveler: (traveler.cs) Setting destination to [System]
15:43:00 Traveler: (traveler.cs) Warping to [Stargate (System)]
15:43:54 Questor: Wallet Balance Has Not Changed in [ 3 ] minutes.
15:44:02 Traveler: (traveler.cs) Jumping to [System]
15:44:13 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:44:13 Traveler.StationDestination: Warp to and dock at [Station Name]
15:44:51 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:45:12 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:45:34 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:45:55 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:46:16 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:46:37 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:46:57 Questor: Wallet Balance Has Not Changed in [ 2 ] minutes.
15:46:59 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:47:20 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:47:41 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:47:58 Questor: Wallet Balance Has Not Changed in [ 3 ] minutes.
15:48:03 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:48:24 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:48:45 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:48:58 Questor: Wallet Balance Has Not Changed in [ 4 ] minutes.
15:49:06 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:49:28 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:49:49 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:49:59 Questor: Wallet Balance Has Not Changed in [ 5 ] minutes.
15:50:10 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:50:32 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:50:53 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:51:00 Questor: Wallet Balance Has Not Changed in [ 6 ] minutes.
15:51:14 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:51:36 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:51:57 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:52:18 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:52:40 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:53:01 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:53:02 Questor: Wallet Balance Has Not Changed in [ 2 ] minutes.
15:53:22 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:53:43 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:54:03 Questor: Wallet Balance Has Not Changed in [ 3 ] minutes.
15:54:05 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:54:26 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:54:47 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:55:04 Questor: Wallet Balance Has Not Changed in [ 4 ] minutes.
15:55:09 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:55:30 Traveler.BookmarkDestination: undock bookmark does not exist and equals null
15:55:51 Traveler.BookmarkDestination: undock bookmark does not exist and equals null

Bot stays roughly 100m away from the station well within docking range.

**Comment by Blinker** [comment]
Just to add this is NOT always. This has happened only three times since latest build.

EVE logs only state the following.

"Notify Approaching Station Name."

**Comment by ISeeDEDPpl** [comment]
This should be fixed with the latest commit. 

When changing the distances in various places to use distances.cs I changed the docking distance to 0.
Technically the docking distance is 0 anything outside that and you will approach to (near?) zero first before actually docking. I changed the docking distance to 2400m which should resolve the issue. I was not able to replicate the problem with my Golem pilots. Please report back if you see the issue again.

**Comment by Blinker** [comment]
Just finished trying it out, worked perfectly.
