### ISSUE TITLE
Bleeding Edge Using Afterburner when target is out of range

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#400]
When questor tries to get in range to a new target it doesn t use a afterburner. He just slowboat to new targets till he can lock them.

**Comment by ISeeDEDPpl** [comment]
try again with bleedingedge. I changed how the IsApproaching and IsOrbiting stuff works a bit...

**Comment by kn0xv1lle** [comment]
Should be fixed
