### ISSUE TITLE
Bleeding Edge Problem recognizing target who is out of locking range

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#401]
Did that when target was 100km away after mission was restarted. Just warped to pocket target 100km aways and spams the debug log doing nothing.

00:08:04 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets below
00:08:04 [Combat.TargetCombatants] [1] Name [Centior Monster] Distance [105,27] TypeID [23992] groupID [623]
00:08:04 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets above
00:08:04 [Combat.TargetCombatants] TargetingMe [0] lowValueTargetingMe [0] highValueTargetingMe [0]
00:08:04 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in highValueTargetingMe)
00:08:04 [Combat.TargetCombatants] DebugTargetCombatants: 0 highValueTargetingMe targets
00:08:04 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in lowValueTargetingMe)
00:08:04 [Combat.TargetCombatants] DebugTargetCombatants: 0 lowValueTargetingMe targets
00:08:04 [Combat.TargetCombatants] DebugTargetCombatants: 0 NotYetTargetingMe targets
00:08:04 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:04 [combat Debug: GetBestTarget] Checking Closest Primary
00:08:04 [combat Debug: GetBestTarget] Checking Closest High Value
00:08:04 [combat Debug: GetBestTarget] Checking closest Low Value
00:08:04 [combat Debug: GetBestTarget] Checking use Low Value
00:08:04 [combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][105,27k][[truncatedID]62965] GroupID [623]
00:08:05 [Combat Debug: GetBestTarget] Attempting to get Best Target
00:08:05 [Combat Debug: GetBestTarget] Checking Closest Primary
00:08:05 [Combat Debug: GetBestTarget] Checking Closest High Value
00:08:05 [Combat Debug: GetBestTarget] Checking closest Low Value
00:08:05 [Combat Debug: GetBestTarget] Checking use Low Value
00:08:05 [Combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][105,11k][[truncatedID]62965] GroupID [623]
00:08:05 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:05 [combat Debug: GetBestTarget] Cant GetBest yet....Too Soon!
00:08:06 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets below
00:08:06 [Combat.TargetCombatants] [1] Name [Centior Monster] Distance [104,96] TypeID [23992] groupID [623]
00:08:06 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets above
00:08:06 [Combat.TargetCombatants] TargetingMe [0] lowValueTargetingMe [0] highValueTargetingMe [0]
00:08:06 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in highValueTargetingMe)
00:08:06 [Combat.TargetCombatants] DebugTargetCombatants: 0 highValueTargetingMe targets
00:08:06 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in lowValueTargetingMe)
00:08:06 [Combat.TargetCombatants] DebugTargetCombatants: 0 lowValueTargetingMe targets
00:08:06 [Combat.TargetCombatants] DebugTargetCombatants: 0 NotYetTargetingMe targets
00:08:06 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:06 [combat Debug: GetBestTarget] Checking Closest Primary
00:08:06 [combat Debug: GetBestTarget] Checking Closest High Value
00:08:06 [combat Debug: GetBestTarget] Checking closest Low Value
00:08:06 [combat Debug: GetBestTarget] Checking use Low Value
00:08:06 [combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][104,96k][[truncatedID]62965] GroupID [623]
00:08:07 [Combat Debug: GetBestTarget] Attempting to get Best Target
00:08:07 [Combat Debug: GetBestTarget] Checking Closest Primary
00:08:07 [Combat Debug: GetBestTarget] Checking Closest High Value
00:08:07 [Combat Debug: GetBestTarget] Checking closest Low Value
00:08:07 [Combat Debug: GetBestTarget] Checking use Low Value
00:08:07 [Combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][104,79k][[truncatedID]62965] GroupID [623]
00:08:07 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:07 [combat Debug: GetBestTarget] Cant GetBest yet....Too Soon!
00:08:08 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets below
00:08:08 [Combat.TargetCombatants] [1] Name [Centior Monster] Distance [104,63] TypeID [23992] groupID [623]
00:08:08 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets above
00:08:08 [Combat.TargetCombatants] TargetingMe [0] lowValueTargetingMe [0] highValueTargetingMe [0]
00:08:08 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in highValueTargetingMe)
00:08:08 [Combat.TargetCombatants] DebugTargetCombatants: 0 highValueTargetingMe targets
00:08:08 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in lowValueTargetingMe)
00:08:08 [Combat.TargetCombatants] DebugTargetCombatants: 0 lowValueTargetingMe targets
00:08:08 [Combat.TargetCombatants] DebugTargetCombatants: 0 NotYetTargetingMe targets
00:08:08 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:08 [combat Debug: GetBestTarget] Checking Closest Primary
00:08:08 [combat Debug: GetBestTarget] Checking Closest High Value
00:08:08 [combat Debug: GetBestTarget] Checking closest Low Value
00:08:08 [combat Debug: GetBestTarget] Checking use Low Value
00:08:08 [combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][104,63k][[truncatedID]62965] GroupID [623]
00:08:09 [Combat Debug: GetBestTarget] Attempting to get Best Target
00:08:09 [Combat Debug: GetBestTarget] Checking Closest Primary
00:08:09 [Combat Debug: GetBestTarget] Checking Closest High Value
00:08:09 [Combat Debug: GetBestTarget] Checking closest Low Value
00:08:09 [Combat Debug: GetBestTarget] Checking use Low Value
00:08:09 [Combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][104,47k][[truncatedID]62965] GroupID [623]
00:08:09 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:09 [combat Debug: GetBestTarget] Cant GetBest yet....Too Soon!
00:08:10 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets below
00:08:10 [Combat.TargetCombatants] [1] Name [Centior Monster] Distance [104,3] TypeID [23992] groupID [623]
00:08:10 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets above
00:08:10 [Combat.TargetCombatants] TargetingMe [0] lowValueTargetingMe [0] highValueTargetingMe [0]
00:08:10 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in highValueTargetingMe)
00:08:10 [Combat.TargetCombatants] DebugTargetCombatants: 0 highValueTargetingMe targets
00:08:10 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in lowValueTargetingMe)
00:08:10 [Combat.TargetCombatants] DebugTargetCombatants: 0 lowValueTargetingMe targets
00:08:10 [Combat.TargetCombatants] DebugTargetCombatants: 0 NotYetTargetingMe targets
00:08:10 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:10 [combat Debug: GetBestTarget] Checking Closest Primary
00:08:10 [combat Debug: GetBestTarget] Checking Closest High Value
00:08:10 [combat Debug: GetBestTarget] Checking closest Low Value
00:08:10 [combat Debug: GetBestTarget] Checking use Low Value
00:08:10 [combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][104,3k][[truncatedID]62965] GroupID [623]
00:08:11 [Combat Debug: GetBestTarget] Attempting to get Best Target
00:08:11 [Combat Debug: GetBestTarget] Checking Closest Primary
00:08:11 [Combat Debug: GetBestTarget] Checking Closest High Value
00:08:11 [Combat Debug: GetBestTarget] Checking closest Low Value
00:08:11 [Combat Debug: GetBestTarget] Checking use Low Value
00:08:11 [Combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][104,13k][[truncatedID]62965] GroupID [623]
00:08:11 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:11 [combat Debug: GetBestTarget] Cant GetBest yet....Too Soon!
00:08:12 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets below
00:08:12 [Combat.TargetCombatants] [1] Name [Centior Monster] Distance [103,95] TypeID [23992] groupID [623]
00:08:12 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets above
00:08:12 [Combat.TargetCombatants] TargetingMe [0] lowValueTargetingMe [0] highValueTargetingMe [0]
00:08:12 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in highValueTargetingMe)
00:08:12 [Combat.TargetCombatants] DebugTargetCombatants: 0 highValueTargetingMe targets
00:08:12 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in lowValueTargetingMe)
00:08:12 [Combat.TargetCombatants] DebugTargetCombatants: 0 lowValueTargetingMe targets
00:08:12 [Combat.TargetCombatants] DebugTargetCombatants: 0 NotYetTargetingMe targets
00:08:12 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:12 [combat Debug: GetBestTarget] Checking Closest Primary
00:08:12 [combat Debug: GetBestTarget] Checking Closest High Value
00:08:12 [combat Debug: GetBestTarget] Checking closest Low Value
00:08:12 [combat Debug: GetBestTarget] Checking use Low Value
00:08:12 [combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][103,95k][[truncatedID]62965] GroupID [623]
00:08:13 [Combat Debug: GetBestTarget] Attempting to get Best Target
00:08:13 [Combat Debug: GetBestTarget] Checking Closest Primary
00:08:13 [Combat Debug: GetBestTarget] Checking Closest High Value
00:08:13 [Combat Debug: GetBestTarget] Checking closest Low Value
00:08:13 [Combat Debug: GetBestTarget] Checking use Low Value
00:08:13 [Combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][103,77k][[truncatedID]62965] GroupID [623]
00:08:13 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:13 [combat Debug: GetBestTarget] Cant GetBest yet....Too Soon!
00:08:14 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets below
00:08:14 [Combat.TargetCombatants] [1] Name [Centior Monster] Distance [103,6] TypeID [23992] groupID [623]
00:08:14 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets above
00:08:14 [Combat.TargetCombatants] TargetingMe [0] lowValueTargetingMe [0] highValueTargetingMe [0]
00:08:14 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in highValueTargetingMe)
00:08:14 [Combat.TargetCombatants] DebugTargetCombatants: 0 highValueTargetingMe targets
00:08:14 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in lowValueTargetingMe)
00:08:14 [Combat.TargetCombatants] DebugTargetCombatants: 0 lowValueTargetingMe targets
00:08:14 [Combat.TargetCombatants] DebugTargetCombatants: 0 NotYetTargetingMe targets
00:08:14 [combat Debug: GetBestTarget] Attempting to get Best Target
00:08:14 [combat Debug: GetBestTarget] Checking Closest Primary
00:08:14 [combat Debug: GetBestTarget] Checking Closest High Value
00:08:14 [combat Debug: GetBestTarget] Checking closest Low Value
00:08:14 [combat Debug: GetBestTarget] Checking use Low Value
00:08:14 [combat Debug: GetBestTarget:] lowValueTarget is [Centior Monster][103,6k][[truncatedID]62965] GroupID [623]

**Comment by nico-rip** [comment]
https://github.com/nico-rip/Questor/commit/e3625983ad8f2db13dfd0b3aeb26102b13e4467a

Should fix
