### ISSUE TITLE
Bleeding Edge stay on killed target

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#403]
Watched this as questor killed a frigate. He killed it and stayed on it with primary weapon. Although drone target changed. Still tries to lock frigates which are no longer on grid

**Comment by kn0xv1lle** [comment]
Log when there are still targets left and questor doesn t recognize that.

http://privatepaste.com/4db51f658d

**Comment by ISeeDEDPpl** [comment]
this should be fixed in bleedingedge.
