### ISSUE TITLE
Mission Action Issue

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#409]
The latest build: abd7cdf82a8d96ff80dc24a0af67359c40f9f40b
Targeting works fine but Q sometimes not using Acceleration Gate and stuck,
In Mission Damsel in Distress destroy all entities and not go to:

`<action name="Kill">`
`<parameter name="Target" value="Kruul's Pleasure Gardens" />`
`<parameter name="BreakOnAttackers" value="True" />`
`</action>`

and stuck

**Comment by ISeeDEDPpl** [comment]
so the clearpocket action before the action you list above is not finishing?

**Comment by oldmeat** [comment]
I dont know, Q kill all entities and stop and after this only logs is "Wallet Time Balance ..."

**Comment by Daxten** [comment]
"After this"
you have to be more precise, please tell us what are the last log entries before the Wallet timer

**Comment by oldmeat** [comment]
Sorry for my english
http://privatepaste.com/0ce86ca004

**Comment by ISeeDEDPpl** [comment]
both clearpocket and kill should now be working. some attention now needs to be paid to all the other actions to make sure they are not FUBAR atm.

**Comment by oldmeat** [comment]
The latest BE:

Q go to mission correctly, target one NPC which not me attack/aggro and not shoot. 
Stay and wait probably for aggro from NPC

**Comment by ISeeDEDPpl** [comment]
What action? clearpocket? What mission?

**Comment by oldmeat** [comment]
http://privatepaste.com/bfbc332f43

Prophecy all time is targeted but not shoot.
Q not shoot too :]
