### ISSUE TITLE
Salvaging - No valuable items found

### ISSUE THREAD

**Issue by KingMike** [ISeeDEDPpl/Questor#41]
Hello,

Not sure if this is my issue only but since couple of days ago I'm seeing a strange salvaging behaviour.

Salvaging will found that most of the wrecks contain no valuable items and therefore are let in the wrecks.
The same item type will be picked up from another wreck tho...
At the moment around 90-95% of all items are left behind. It seems like it could be a timing issue maybe?

Anyone else is having this problem?? I have updated the items xml file to latest but still the same issue...

Thanks!

**Comment by ISeeDEDPpl** [comment]
This is not happening on my toons...  you can use the invtypes.xml linked here and see if it helps.

http://dl.dropbox.com/u/27150542/InvTypes.xml

I'll be pulling that file in the next 48hrs, so grab it while you can.

**Comment by KingMike** [comment]
it seems functionality of lootEverything has changed recently.
Until couple of days ago this command didn't influence after mission salvaging (only mission ship). it was always salvaging everything during after mission salv.
Now thats changed and if set to false after mission salvaging behaves very strange (as described in OP) but when enabled all is OK apart from the fact that my bots are now collecting loot during mission.
But again only from some wrecks so I cant really understand the logic behind this.

I have set lootEverything to true now (was set to false since I started using questor)  and after mission salvaging works ok but 
as I said my bots are now collecting some occasional loot during missions.

In some missions my tengu is now approaching every single wreck trying to loot it (doesnt have salvager or tractor)...

Was this an intended change to lootEverything functionality?

Thanks!

**Comment by KingMike** [comment]
This example:
`<action name="Loot">
          <parameter name="target" value="Cargo Container" />
          <parameter name="Item" value="Confiscated Viral Agent" />
        </action>`  
with `<lootEverything>true</lootEverything>` will approach every single wreck in the pocket even after the Viral Agent is in cargo.

same with this code:
```` <action name="Loot">
          <parameter name="Target" value="Cargo Container" />
          <parameter name="Item" value="Reports" />
        </action>

```

any mission that requires a specific item to be picked up (or any mission that has loot in xml) works like this now. loot all wrecks in mission ship then leave the pocket.

Is there any chance to return it to how it was previously? 
So I can set it to false and have aftermission salvaging still loot everything.

Thanks!
```

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/wiki/Salvaging-and-Looting-Settings

**Comment by ghost** [comment]
KingMike

`<LootEverything>True</LootEverything>`

Is a character.xml setting

Use this:

```
  <action name="LootItem">
    <parameter name="Item" value="DimsIsk"></parameter>
    <parameter name="Target" value="Dim"></parameter>
    <parameter name="Quantity" value="30"></parameter>
  </action>
```

as an example to only loot one item in a mission pocket.

**Comment by ISeeDEDPpl** [comment]
I assume this is now working? if you are still experiencing issues describe them here or irc...

**Comment by KingMike** [comment]
sorry wasn't able to test anything for a while so I'm going to close the issue and then reopen if needed later. 
Thanks again!
