### ISSUE TITLE
The latest Questor 02706ba6a696e0888d2d11dff89fd56ddc1ba228 not compile (errors)

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#413]
The latest Questor 02706ba6a696e0888d2d11dff89fd56ddc1ba228 not compile (errors)

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/3d0e842c03e5d5fbbebc594592cedafacf018adf
