### ISSUE TITLE
Q Not targeting valid targets and stuck in loop

### ISSUE THREAD

**Issue by Smellyarmpits** [ISeeDEDPpl/Questor#415]
Log is generating in an endless loop when there are valid targets:

20:47:14 [Salvage] Locking [Gist War General Wreck][14k][ID: [truncatedID]90048][14k away]
20:47:20 [Salvage] Activating tractorbeam [1] on [Gist War General Wreck][14k][ID: [truncatedID]90048]
20:47:23 [Drones] Recalling [ 5 ] drones because no NPC is targeting us within dronerange
20:47:25 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
20:47:27 [Combat] Out of range. ignoring orbit around structure.
20:47:27 [Combat] Initiating Orbit [Gist Commander][at 25k][ID: [truncatedID]86485]
20:47:29 [Combat] Changing [2] with [Ultraviolet L][85][TypeID: 259] so we can hit [Gist Commander][77k]
20:47:29 [Combat] Changing [3] with [Ultraviolet L][85][TypeID: 259] so we can hit [Gist Commander][77k]
20:47:29 [Combat] Changing [4] with [Ultraviolet L][85][TypeID: 259] so we can hit [Gist Commander][77k]
20:47:31 [Combat] Changing [1] with [Ultraviolet L][85][TypeID: 259] so we can hit [Gist Commander][77k]
20:47:31 [Combat] Activating weapon [2] on [Gist Commander][ID: [truncatedID]86485][77k away]
20:47:31 [Combat] Activating weapon [3] on [Gist Commander][ID: [truncatedID]86485][77k away]
20:47:32 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
20:47:33 [Combat] Activating weapon [1] on [Gist Commander][ID: [truncatedID]86485][77k away]
20:47:33 [Combat] Activating weapon [4] on [Gist Commander][ID: [truncatedID]86485][77k away]
20:47:46 [Salvage] Cargo Container [Gist War General Wreck][1k][ID: [truncatedID]90048] within loot range, unlocking container.
20:47:47 [Salvage] Opening container [Gist War General Wreck][1k][ID: [truncatedID]90048]
20:47:53 [Salvage] Opening container [Gist War General Wreck][1k][ID: [truncatedID]90048]
20:47:54 [Salvage.LootWrecks] Container [Gist War General Wreck][1k][ID: [truncatedID]90048] contained no valuable items
20:48:15 [Combat] Targeting non-aggressed NPC target [Gist Commander][ID: [truncatedID]86865][28k away]
20:48:15 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
20:48:15 [GetBestTarget: none] Could not determine a suitable target
20:48:16 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
20:48:16 [GetBestTarget: none] Could not determine a suitable target
20:48:16 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
20:48:17 [GetBestTarget: none] Could not determine a suitable target
20:48:17 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
20:48:17 [GetBestTarget: none] Could not determine a suitable target
20:48:18 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
20:48:19 [GetBestTarget: none] Could not determine a suitable target
20:48:19 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
20:48:19 [GetBestTarget: none] Could not determine a suitable target
20:48:20 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
20:48:20 [GetBestTarget: none] Could not determine a suitable target
20:48:21 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
20:48:21 [GetBestTarget: none] Could not determine a suitable target
20:48:21 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())

Relivant config file settings:
<killSentries>true</killSentries>
<shootWarpScramblersWithPrimaryWeapons>false</shootWarpScramblersWithPrimaryWeapons>
<speedNPCFrigatesShouldBeIgnoredByPrimaryWeapons>200</speedNPCFrigatesShouldBeIgnoredByPrimaryWeapons>
<distanceNPCFrigatesShouldBeIgnoredByPrimaryWeapons>14000</distanceNPCFrigatesShouldBeIgnoredByPrimaryWeapons>

   
    
  
  <addDampenersToPrimaryWeaponsPriorityTargetList>true</addDampenersToPrimaryWeaponsPriorityTargetList>
  
  <addECMsToPrimaryWeaponsPriorityTargetList>true</addECMsToPrimaryWeaponsPriorityTargetList>
  
  <addNeutralizersToPrimaryWeaponsPriorityTargetList>true</addNeutralizersToPrimaryWeaponsPriorityTargetList>
  
  <addTargetPaintersToPrimaryWeaponsPriorityTargetList>true</addTargetPaintersToPrimaryWeaponsPriorityTargetList>
  
  <addTrackingDisruptorsToPrimaryWeaponsPriorityTargetList>true</addTrackingDisruptorsToPrimaryWeaponsPriorityTargetList>
  
  <addWarpScramblersToPrimaryWeaponsPriorityTargetList>false</addWarpScramblersToPrimaryWeaponsPriorityTargetList>
  
  <addWebifiersToPrimaryWeaponsPriorityTargetList>false</addWebifiersToPrimaryWeaponsPriorityTargetList>

    
   
    
  
  <addDampenersToDronePriorityTargetList>true</addDampenersToDronePriorityTargetList>
  
  <addECMsToDroneTargetList>true</addECMsToDroneTargetList>
  
  <addNeutralizersToDronePriorityTargetList>true</addNeutralizersToDronePriorityTargetList>
  
  <addTargetPaintersToDronePriorityTargetList>true</addTargetPaintersToDronePriorityTargetList>
  
  <addTrackingDisruptorsToDronePriorityTargetList>true</addTrackingDisruptorsToDronePriorityTargetList>
  
  <addWarpScramblersToDronePriorityTargetList>true</addWarpScramblersToDronePriorityTargetList>
  
  <addWebifiersToDronePriorityTargetList>true</addWebifiersToDronePriorityTargetList>

  
  <NosDistance>38000</NosDistance>

  
  <maximumHighValueTargets>2</maximumHighValueTargets>
  <maximumLowValueTargets>3</maximumLowValueTargets>

---

As stated several targets are available at long range, but Q doesn't target them and continues the loop till i target manually and then it starts killing again.  Not sure what to do with this...

**Comment by Escalti0n** [comment]
same issue here

**Comment by ISeeDEDPpl** [comment]
ok, try bleedingedge, untested.

**Comment by Smellyarmpits** [comment]
This is Bleedingedge.. or am I missing some version?

**Comment by ISeeDEDPpl** [comment]
yes, bleedingedge.
