### ISSUE TITLE
Q sitting in station when should complete mission and not

### ISSUE THREAD

**Issue by Smellyarmpits** [ISeeDEDPpl/Questor#416]
Q sits in station looping EveMemManager when it should be turning in mission Bleedingedge (today):

21:02:49 [AgentInteraction] [xxxxxxxxxxxx] standing toward me is [8.70], minAgentGreyListStandings: [6]
21:02:49 [AgentInteraction] Mission enemy faction: Amarr Empire
21:02:49 [AgentInteraction] Declining blacklisted mission [Smash the Supplier]
21:02:49 [AgentInteraction] Mission enemy faction: Amarr Empire
21:02:49 [AgentInteraction] Declining blacklisted mission [Smash the Supplier] because of faction blacklist
21:02:55 [AgentInteraction] Agent decline timer detected. Current standings: 8.7. Minimum standings: 5.5
21:02:55 [AgentInteraction] Current standings [8.7] is above our configured minimum [5.5]. Declining [Smash the Supplier] note: WaitDecline is false
21:02:55 [AgentInteraction] Saying [Decline]
21:02:55 [AgentInteraction] Replying to agent
21:02:59 [Cleanup] Found a window that needs 'yes' chosen...
21:02:59 [Cleanup] Content of modal window (HTML): [If you decline a mission before 2013.06.15 05:16 you will lose standings with this agent, as well as his corp and faction. If you lose enough standings, you will no longer be able to talk to the agent. Are you sure you would like to decline this mission?]
21:03:00 [AgentInteraction] Replying to agent
21:03:04 [AgentInteraction] Saying [Request Mission]
21:03:04 [AgentInteraction] Waiting for mission
21:03:13 [AgentInteraction] [xxxxxxxxxxxxxxx] standing toward me is [7.80], minAgentGreyListStandings: [6]
21:03:13 [AgentInteraction] Declining blacklisted mission [Smash the Supplier]
21:06:42 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 495 MB
21:06:42 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
21:11:46 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 463 MB
21:11:46 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
21:16:49 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 463 MB
21:16:49 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
21:21:50 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 461 MB
21:21:50 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
21:26:53 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 461 MB
21:26:53 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
21:31:55 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 461 MB
21:31:55 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
21:36:57 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 461 MB
21:36:57 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
21:42:00 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 462 MB
21:42:00 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
21:47:01 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 462 MB
21:47:01 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
21:52:07 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 462 MB
21:52:07 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
21:57:10 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 463 MB
21:57:10 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
22:02:13 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 463 MB
22:02:13 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)

I manually open the view mission selection and away it goes...

**Comment by ISeeDEDPpl** [comment]
It looks like it is getting stuck in: AgentInteraction.DeclineMission

private void DeclineMission(string module)

Does this happen with every decline? lag related?

**Comment by ISeeDEDPpl** [comment]
if this occurs for ANYONE else please re-open. at the moment I cannot reproduce and Im not sure how your client is/was configured to cause this.
