### ISSUE TITLE
Q not attack structure  

### ISSUE THREAD

**Issue by Grafalck** [ISeeDEDPpl/Questor#417]
Q clear the pocket. then orbiting "Repair Station" and not attack.
Mission: Break Their Will

**Comment by ISeeDEDPpl** [comment]
I assume it gets targeted?

**Comment by ISeeDEDPpl** [comment]
Ill need a log with 
`<debugTargetCombatants>true</debugTargetCombatants>`
if its not getting targeted
and a log with
`<debugGetBestTarget>true</debugGetBestTarget>`
if its targeted but not shot at. 

what does your mission XML look like for this mission?

**Comment by Grafalck** [comment]
when i install 4.5 .net the problem disappeared)

**Comment by Grafalck** [comment]
when i install 4.5 .net the problem disappeared)
