### ISSUE TITLE
unloading loot to freight container doesnt work

### ISSUE THREAD

**Issue by KingMike** [ISeeDEDPpl/Questor#419]
[CombatMissionsBehavior] UnloadLoot: Begin
[UnloadLoot.MoveAmmo] Stacking Item Hangar
[UnloadLoot.MoveLoot] Moving [11] items from CargoHold to LootHangar
[Cache.StackLootHangar] Opening Inventory Window: waiting [2sec]
[Cache.StackLootHangar] Loot Container window named: [ ('InventoryStation', None) ] was found and its contents are being stacked

but nothing happens and loot is not unloaded from the salvage ship.

edit: latest bleedingedge

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge
