### ISSUE TITLE
questorexperimental 

### ISSUE THREAD

**Issue by evelover** [ISeeDEDPpl/Questor#421]
Sitting in dock after panic - dock trying undock and im think press undock again. Ship not undock and eve exit.

**Comment by Pluckyduck** [comment]
log, we not see dem....(logs!)

**Comment by evelover** [comment]
20:07:44 [Panic] Entered a station, lower panic mode
20:07:46 [Panic] We're in a station, resume mission
20:07:46 [Panic] We have recovered, resume mission
20:07:46 [CombatMissionsBehavior] Setting Destination to 1st bookmark from AgentID: 303279 with [Encounter] in the title
20:07:46 [TravelerDestination.MissionBookmarkDestination] Destination set to mission bookmark [Encounter (Deadspace) - Asasas]
20:07:48 [TravelerDestination.BookmarkDestination] This is not the destination station, undocking
20:09:48 [QuestorUI] The Last Session.IsReady = true was [120] seconds ago! This is bad. - Exiting EVE

Im think questor just press undock button twice. In odissey its means abort undocking. Need delay between first and second click on undock button or check undock state.

**Comment by Pluckyduck** [comment]
are you using Bedge or exp?  before the last patch yesterday, Exp was working. Untested after patch but i think at least one at it working.

**Comment by evelover** [comment]
Exp. May be its happen because  im have too much lags.

**Comment by Pluckyduck** [comment]
20:09:48 [QuestorUI] The Last Session.IsReady = true was [120] seconds ago! This is bad. - Exiting EVE

this is when you have lagged out and will spam this.
