### ISSUE TITLE
Error starting Quester

### ISSUE THREAD

**Issue by skorn777** [ISeeDEDPpl/Questor#422]
did everything according to the guide on the link http://forum.thehackerwithin.com/yaf_postst617_-Guide-2-0--Questor-Setup.aspx? =
After running the script specified on the link above - shows an error and does not start Quester. Please help. Here are the logs:

Stealthing questor.modules.dll
Failed to stealth questor.modules.dll
Stealthing mscoree.dll
Stealthed mscoree.dll [6bb90000][4a000]
Stealthing mscoreei.dll
Stealthed mscoreei.dll [6b970000][66000]
Stealthing fusion.dll
Stealthed fusion.dll [60610000][6000]
Stealthing mscorwks.dll
Stealthed mscorwks.dll [5ae60000][591000]
Stealthing mscorlib.ni.dll
Stealthed mscorlib.ni.dll [58c50000][dc3000]
Stealthing lavish.lavishvmruntime.dll
Failed to stealth lavish.lavishvmruntime.dll
Stealthing mscorjit.dll
Failed to stealth mscorjit.dll
Stealthing lavish.innerspace.dll
Failed to stealth lavish.innerspace.dll
Stealthing diasymreader.dll
Stealthed diasymreader.dll [64990000][aa000]
Stealthing system.ni.dll
Failed to stealth system.ni.dll
Stealthing system.drawing.ni.dll
Failed to stealth system.drawing.ni.dll
Stealthing system.windows.forms.ni.dll
Failed to stealth system.windows.forms.ni.dll
Stealthing system.configuration.ni.dll
Failed to stealth system.configuration.ni.dll
Stealthing system.xml.ni.dll
Failed to stealth system.xml.ni.dll
Stealthing gdiplus.dll
Failed to stealth gdiplus.dll
Stealthing system.core.ni.dll
Failed to stealth system.core.ni.dll
Stealthing system.xml.linq.ni.dll
Failed to stealth system.xml.linq.ni.dll
Stealthing innerspace.dll
Stealthed innerspace.dll [3300000][87000]
Stealthing is-kernel.dll
Stealthed is-kernel.dll [3000000][228000]
Stealthing isui.dll
Stealthed isui.dll [5000000][dc000]
Stealthing is-d3d9.dll
Stealthed is-d3d9.dll [6f550000][30000]
Stealthing is-d3d8.dll
Stealthed is-d3d8.dll [6ed50000][69000]
Stealthing is-d3d11.dll
Stealthed is-d3d11.dll [6ec20000][2f000]
Stealthing is-virtualinput.dll
Stealthed is-virtualinput.dll [6f300000][5d000]
Stealthing lavish.lavishvmruntime.dll
Failed to stealth lavish.lavishvmruntime.dll
Stealthing lavish.innerspace.dll
Failed to stealth lavish.innerspace.dll
Stealthing lavish.dll
Stealthed lavish.dll [71cf0000][1d000]

Inner Space Uplink connection established
Session name 'EVE Online1352' accepted
[console] [`] Command (Release): console "toggle"
[memoryindicator] [Ctrl+Alt+M] Command (Release): hudgroup "-toggle" "memory indicator"
[fpsindicator] [Ctrl+Alt+F] Command (Release): hudgroup "-toggle" "fps indicator"
fullscreen=WindowCharacteristics -size fullscreen -pos -viewable ${Display.DesktopX},${Display.DesktopY};fullscreenmouse
normal=normalsize;normalposition;normalmouse
tiny=tinysize;tinyposition;tinymouse
pipforeground=pipforegroundsize;pipforegroundposition;pipforegroundmouse
normalsize=WindowSize -viewable 1024x768
tinysize=WindowSize -viewable 256x192
pipforegroundsize=WindowSize -rescale -viewable ${Display.Width}x${Display.Height}
normalposition=WindowPos -viewable ${Display.DesktopX},${Display.DesktopY}
tinyposition=WindowPos ${Math.Calc[${Display.DesktopX}+10].Int},${Math.Calc[${Display.DesktopY}+10].Int}
pipforegroundposition=WindowPos -viewable ${Display.DesktopX},${Display.DesktopY}
fullscreenmouse=
normalmouse=
pipforegroundmouse=
tinymouse=
[fullscreenkey] [Shift+Alt+f] Command (Release): fullscreen
[normalkey] [Shift+Alt+n] Command (Release): normal
[tinykey] [Shift+Alt+t] Command (Release): tiny
[next] [Ctrl+Alt+x] Command (Release): uplink focus -next
[previous] [Ctrl+Alt+z] Command (Release): uplink focus -previous
Session name 'is1' accepted
[is1_key] [Ctrl+Alt+1] Command: WindowVisibility foreground;Event[OnInternalActivate]:Execute
binds=bind -list
GlobalBinds=GlobalBind -list
ISXStealth version 20130315 Loaded
Extension 'isxstealth' loaded
We are currently blocking MiniDumpWriteDump
Stealthing isxstealth.dll
Stealthed isxstealth.dll [6f8d0000][2a000]
Blocking IsDebuggerPresent() call.
Blocking IsDebuggerPresent() call.
Assembly "questor" was found, but could not be loaded following 4 different attempts:
exceptions[1]: System.IO.FileNotFoundException: Íåâîçìîæíî çàãðóçèòü ôàéë èëè ñáîðêó "file:///D:\EVE\questor" èëè îäèí èç
çàâèñèìûõ îò íèõ êîìïîíåíòîâ. Íå óäàåòñÿ íàéòè óêàçàííûé ôàéë.

Èìÿ ôàéëà: "file:///D:\EVE\questor"

   â System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity,
RuntimeAssembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean
suppressSecurityChecks)

   â System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity,
RuntimeAssembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean
suppressSecurityChecks)

   â System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity,
StackCrawlMark& stackMark, Boolean forIntrospection, Boolean suppressSecurityChecks)

   â System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue,
AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)

   â System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)

   â System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)

   â System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)

   â LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly1()

   â LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly()

Ïðåäóïðåæäåíèå: ðåãèñòðàöèÿ ïðèâÿçêè ñáîðîê âûêëþ÷åíà.

×òîáû âêëþ÷èòü ðåãèñòðàöèþ îøèáîê ïðèâÿçêè ñáîðîê, óñòàíîâèòå çíà÷åíèå ïàðàìåòðà ðååñòðà
[HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) â 1.

Ïðèìå÷àíèå. Ðåãèñòðàöèÿ îøèáîê ïðèâÿçêè ñáîðîê ìîæåò ïðèâåñòè ê íåêîòîðîìó ñíèæåíèþ ïðîèçâîäèòåëüíîñòè.

×òîáû îòêëþ÷èòü ýòó ôóíêöèþ, óäàëèòå ïàðàìåòð ðååñòðà [HKLM\Software\Microsoft\Fusion!EnableLog].

exceptions[2]: System.IO.FileNotFoundException: Íåâîçìîæíî çàãðóçèòü ôàéë èëè ñáîðêó "questor" èëè îäèí èç çàâèñèìûõ îò íè
êîìïîíåíòîâ. Íå óäàåòñÿ íàéòè óêàçàííûé ôàéë.

Èìÿ ôàéëà: "questor"

   â System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity,
RuntimeAssembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean
suppressSecurityChecks)

   â System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity,
RuntimeAssembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean
suppressSecurityChecks)

   â System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity,
StackCrawlMark& stackMark, Boolean forIntrospection, Boolean suppressSecurityChecks)

   â System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark&
stackMark, Boolean forIntrospection)

   â System.Reflection.Assembly.Load(String assemblyString, Evidence assemblySecurity)

   â System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)

   â System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)

   â LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly2()

   â LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly()

**Comment by frbyles** [comment]
when you compiled did you get any errors ? should be all white and yellow type and no red

**Comment by skorn777** [comment]
compile error was not - it was all white and yellow - red was not

**Comment by frbyles** [comment]
rerun .net 4.5 repair to original state and recompile

**Comment by frbyles** [comment]
i had issues also and i went ahead and installed 4.0 then 4.5 just to be sure i got everything right . also is your innerspace in my documents or program files ?

**Comment by skorn777** [comment]
my innerspace in program files.
I have is Microsoft.NET 4.0 and the need to put another top 4.5 version?

**Comment by frbyles** [comment]
idk im having permission issues atm i cant even test :(

**Comment by frbyles** [comment]
anyone know what version of visula studio i need to fix my permission errors ?

**Comment by skorn777** [comment]
well now put the 4.5 version and try it all over again

**Comment by frbyles** [comment]
k

**Comment by skorn777** [comment]
staged version 4.5 did it all over again - now that's a log: ((

Inner Space Uplink connection established
Session name 'EVE Online5872' accepted
[console] [`] Command (Release): console "toggle"
[memoryindicator] [Ctrl+Alt+M] Command (Release): hudgroup "-toggle" "memory indicator"
[fpsindicator] [Ctrl+Alt+F] Command (Release): hudgroup "-toggle" "fps indicator"
fullscreen=WindowCharacteristics -size fullscreen -pos -viewable ${Display.DesktopX},${Display.DesktopY};f
normal=normalsize;normalposition;normalmouse
tiny=tinysize;tinyposition;tinymouse
pipforeground=pipforegroundsize;pipforegroundposition;pipforegroundmouse
normalsize=WindowSize -viewable 1024x768
tinysize=WindowSize -viewable 256x192
pipforegroundsize=WindowSize -rescale -viewable ${Display.Width}x${Display.Height}
normalposition=WindowPos -viewable ${Display.DesktopX},${Display.DesktopY}
tinyposition=WindowPos ${Math.Calc[${Display.DesktopX}+10].Int},${Math.Calc[${Display.DesktopY}+10].Int}
pipforegroundposition=WindowPos -viewable ${Display.DesktopX},${Display.DesktopY}
fullscreenmouse=
normalmouse=
pipforegroundmouse=
tinymouse=
[fullscreenkey] [Shift+Alt+f] Command (Release): fullscreen
[normalkey] [Shift+Alt+n] Command (Release): normal
[tinykey] [Shift+Alt+t] Command (Release): tiny
[next] [Ctrl+Alt+x] Command (Release): uplink focus -next
[previous] [Ctrl+Alt+z] Command (Release): uplink focus -previous
Session name 'is1' accepted
[is1_key] [Ctrl+Alt+1] Command: WindowVisibility foreground;Event[OnInternalActivate]:Execute
binds=bind -list
GlobalBinds=GlobalBind -list
ISXStealth version 20130315 Loaded
Extension 'isxstealth' loaded
We are currently blocking MiniDumpWriteDump
Stealthing isxstealth.dll
Stealthed isxstealth.dll [6a9c0000][2a000]
Blocking IsDebuggerPresent() call.
Blocking IsDebuggerPresent() call.
Unhandled exception in application.
Outer Exception: System.ArgumentNullException: Çíà÷åíèå íå ìîæåò áûòü íåîïðåäåëåííûì.

Èìÿ ïàðàìåòðà: argument

   â Mono.Options.OptionSet.GetOptionParts(String argument, String& flag, String& name, String& sep, String& value) â
c:\Program Files (x86)\InnerSpace.NET Programs\Questor-experimental\Questor\Options.cs:ñòðîêà 1073

   â Mono.Options.OptionSet.Parse(String argument, OptionContext c) â c:\Program Files (x86)\InnerSpace.NET
Programs\Questor-experimental\Questor\Options.cs:ñòðîêà 1100

   â Mono.Options.OptionSet.Parse(IEnumerable`1 arguments) â c:\Program Files (x86)\InnerSpace.NET
Programs\Questor-experimental\Questor\Options.cs:ñòðîêà 998

   â Questor.Program.Main(String[] args) â c:\Program Files (x86)\InnerSpace.NET
Programs\Questor-experimental\Questor\Program.cs:ñòðîêà 98

   â System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)

   â System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)

   â System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)

   â LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly2()

   â LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly()

   â LavishVMRuntime.LVMDomainManager.AssemblyExecuter(Object Obj)

Stealthing directeve.dll
Failed to stealth directeve.dll
Stealthing questor.modules.dll
Failed to stealth questor.modules.dll
Stealthing mscoree.dll
Stealthed mscoree.dll [6a930000][4a000]
Stealthing mscoreei.dll
Stealthed mscoreei.dll [6a1f0000][7a000]
Stealthing fusion.dll
Stealthed fusion.dll [60610000][6000]
Stealthing mscorwks.dll
Stealthed mscorwks.dll [5a910000][591000]
Stealthing mscorlib.ni.dll
Stealthed mscorlib.ni.dll [58990000][fbf000]
Stealthing lavish.lavishvmruntime.dll
Failed to stealth lavish.lavishvmruntime.dll
Stealthing mscorjit.dll
Failed to stealth mscorjit.dll
Stealthing lavish.innerspace.dll
Failed to stealth lavish.innerspace.dll
Stealthing diasymreader.dll
Stealthed diasymreader.dll [5e600000][d4000]
Stealthing system.ni.dll
Stealthed system.ni.dll [59f90000][979000]
Stealthing system.drawing.ni.dll
Stealthed system.drawing.ni.dll [5c9f0000][191000]
Stealthing system.windows.forms.ni.dll
Stealthed system.windows.forms.ni.dll [57150000][c1d000]
Stealthing system.configuration.ni.dll
Failed to stealth system.configuration.ni.dll
Stealthing system.xml.ni.dll
Failed to stealth system.xml.ni.dll
Stealthing gdiplus.dll
Failed to stealth gdiplus.dll
Stealthing system.core.ni.dll
Failed to stealth system.core.ni.dll
Stealthing system.xml.linq.ni.dll

**Comment by Pluckyduck** [comment]
dont use that stealthing method, use the easyhooks2.dll, PRO TIP, get on irc and as the questions and then IDLE there while waiting for the answers.

**Comment by skorn777** [comment]
thanks for the help - this problem was solved - questor start - but now there was another problem. Everything seems to run but do not undertake the mission did not take place and the pilot does not take off from the station - please help - logs below:

[12:51:09] Loading [StartingQuestorSafetyScript.iss]
Loading isxstealth
ISXStealth version 20130315 Loaded
Extension 'isxstealth' loaded
[12:51:09] Done Loading [StartingQuestorSafetyScript.iss] Did it work?
We are currently blocking MiniDumpWriteDump
Stealthing isxstealth.dll
Stealthed isxstealth.dll [5fd60000][2a000]
12:51:11 [Startup] StartingQuestorSafetyScript - 3
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Starting DirectEve v1.330.4922.28677
You are using the anonymous license, please consider upgrading to a support license (http://support.thehackerwithin.com)
Copyright (c) 2012 - TheHackerWithin
http://www.thehackerwithin.com
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
12:51:14 [Startup] You have 0 Support Instances available [ Cache.Instance.DirectEve.HasSupportInstances() is false ]
12:51:14 [Startup] We have successfully logged in
12:51:14 [Startup] We are logged in: Launching Questor
12:51:15 [Questor] Schedule: NOT setup correctly: stoptime  set to [10] hours from now at [22:51]
12:51:15 [Questor] You can correct this by editing schedules.xml to have an entry for this toon
12:51:15 [Questor] Ex: <char user="" pw="MyPasswordForEVEHere" name="MyLoginNameForEVEHere" start="06:45"
stop="08:10" start2="09:05" stop2="14:20"/>
12:51:15 [Questor] make sure each toon has its own innerspace profile and specify the following startup program line:
12:51:15 [Questor] dotnet questor questor -x -c "MyEVECharacterName"
12:51:15 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 763 MB
12:51:16 [Settings] Loading Settings from [C:\Program Files (x86)\InnerSpace.NET Programs\Charname.xml]
12:51:16 [Settings] MissionsPath is: [C:\Program Files (x86)\InnerSpace.NET Programs\Caldari Missions]
12:51:16 [Settings] Loothangar [ItemsHangar]
12:51:16 [Settings] AmmoHangar [ItemHangar]
12:51:16 [Settings] Found more than one agent in your character XML: MultiAgentSupport is [True]
12:51:16 [Settings] Faction Fittings defined. Fitting manager will be used when appropriate.
12:51:16 [Settings] Loading Mission Fittings
12:51:16 [Settings]         Mission Fittings now has [0] entries
12:51:16 [Settings] Loading Mission Blacklist
12:51:16 [Settings]         Mission Blacklist now has [1] entries
12:51:16 [Settings] Loading Mission Greylist
12:51:16 [Settings]         Mission Greylist now has [0] entries
12:51:16 [Settings] Loading Faction Blacklist
12:51:16 [Settings]         Missions from the faction [Caldari State] will be declined
12:51:16 [Settings]         Missions from the faction [Gallente Federation] will be declined
12:51:16 [Settings]         Missions from the faction [Minmatar Republic] will be declined
12:51:16 [Settings]         Missions from the faction [Amarr Empire] will be declined
12:51:16 [Settings]         Missions from the faction [CONCORD Assembly] will be declined
12:51:16 [Settings]         Missions from the faction [Ammatar Mandate] will be declined
12:51:16 [Settings]         Missions from the faction [Khanid Kingdom] will be declined
12:51:16 [Settings]         Missions from the faction [Thukker Tribe] will be declined
12:51:16 [Settings]         Faction Blacklist now has [8] entries
12:51:16 [Settings] [1] Done Loading Settings from [C:\Program Files (x86)\InnerSpace.NET Programs\Charname.xml]
12:51:17 [Cache.AgentId] Unable to get agent details: trying again in a moment [Ññûëêà íà îáúåêò íå óêàçûâàåò íà
ýêçåìïëÿð îáúåêòà.]
12:51:20 [Cache.AgentId] Unable to get agent details: trying again in a moment [Ññûëêà íà îáúåêò íå óêàçûâàåò íà
ýêçåìïëÿð îáúåêòà.]
12:51:20 [Settings] Unable to locate agent []
12:51:21 [Cache.AgentId] Unable to get agent details: trying again in a moment [Ññûëêà íà îáúåêò íå óêàçûâàåò íà
ýêçåìïëÿð îáúåêòà.]
12:51:23 [Cache.AgentId] Unable to get agent details: trying again in a moment [Ññûëêà íà îáúåêò íå óêàçûâàåò íà
ýêçåìïëÿð îáúåêòà.]
12:51:23 [Settings] Unable to locate agent []
12:51:25 [Cache.AgentId] Unable to get agent details: trying again in a moment [Ññûëêà íà îáúåêò íå óêàçûâàåò íà
ýêçåìïëÿð îáúåêòà.]
12:51:27 [Cache.AgentId] Unable to get agent details: trying again in a moment [Ññûëêà íà îáúåêò íå óêàçûâàåò íà
ýêçåìïëÿð îáúåêòà.]
12:51:27 [Settings] Unable to locate agent []
12:51:28 [Cache.AgentId] Unable to get agent details: trying again in a moment [Ññûëêà íà îáúåêò íå óêàçûâàåò íà
ýêçåìïëÿð îáúåêòà.]
12:51:31 [Cache.AgentId] Unable to get agent details: trying again in a moment [Ññûëêà íà îáúåêò íå óêàçûâàåò íà
ýêçåìïëÿð îáúåêòà.]
12:51:31 [Settings] Unable to locate agent []
12:51:32 [Cache.AgentId] Unable to get agent details: trying again in a moment [Ññûëêà íà îáúåêò íå óêàçûâàåò íà
ýêçåìïëÿð îáúåêòà.]
12:51:35 [Cache.AgentId] Unable to get agent details: trying again in a moment [Ññûëêà íà îáúåêò íå óêàçûâàåò íà
ýêçåìïëÿð îáúåêòà.]
12:51:35 [Settings] Unable to locate agent []
DirectEve: Error: This method requires a support instance.
12:51:35 [RunOnceAfterStartup] IterateShipTargetValues - Loading [C:\Program Files (x86)\InnerSpace.NET
Programs\ShipTargetValues.xml]
12:51:35 [RunOnceAfterStartup] IterateInvTypes - Loading [C:\Program Files (x86)\InnerSpace.NET
Programs\InvTypes.xml]
12:51:36 [RunOnceAfterStartup] IterateUnloadLootTheseItemsAreLootItems - unable to find [C:\Program Files
(x86)\InnerSpace.NET Programs\UnloadLootTheseItemsAreLootItems.xml]
12:51:36 [RunOnceAfterStartup] Running Innerspace command: WindowText EVE - TheH4mm3r
12:51:36 [RunOnceAfterStartup] Running Innerspace command: timedcommand 100 windowtaskbar on TheH4mm3r
12:51:36 [Questor] Checking: Current time [07/13/2013 12:51:36] StopTimeSpecified [True] StopTime [ 13.07.2013
22:51:15] ManualStopTime = 13.07.2013 22:51:09
12:51:36 [Questor] Start Mission Behavior
Tray icon enabled
12:53:11 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
12:54:30 [Questor] Checking: Current time [07/13/2013 12:54:30] StopTimeSpecified [True] StopTime [ 13.07.2013
22:51:15] ManualStopTime = 13.07.2013 22:51:09
12:54:31 [Questor] Start Mission Behavior
12:55:11 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
12:56:12 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.

**Comment by frbyles** [comment]
You need to get the easyhook .dll,s off forums and open program.cs and delete the isxstealth region nd then save it. Recompile q nd test it again

Sent from my HTC Inspire™ 4G on AT&T

----- Reply message -----

**Comment by skorn777** [comment]
did everything you said and fantasy - all up :)
I wanted to clarify this easyhook32.dll analog  isxstealth - it will also hide all of the CCP as did  isxstealth?

and request more help - now I have another problem easier, questor mission takes loads the necessary ammo is flying on a mission and once drifted writes an error and does not shoot immediately turns around and flies back to the station and so the circle - these logs:

23:03:03 [Arm] Begin
23:03:05 [Arm] Activating combat ship
23:03:12 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
23:03:15 [Arm.MoveItems] Moving [240] units of Ammo  [Caldari Navy Mjolnir Heavy Missile] from [ AmmoHangar ] to
CargoHold
23:03:17 [Arm.MoveItems] Moving [6460] units of Ammo  [Caldari Navy Mjolnir Heavy Missile] from [ AmmoHangar ] to
CargoHold
23:03:19 [Arm] if (CurrentAmmoToLoad == null)
23:03:24 [Cleanup] Closing Inventory Windows: waiting [1]sec
23:03:25 [CombatMissionsBehavior.LocalWatch] local is clear
23:03:26 [CombatMissionsBehavior.WarpOut] No Bookmark
23:03:27 [CombatMissionsBehavior] Setting Destination to 1st bookmark from AgentID: 3019380 with [Encounter] in the
title
23:03:27 [TravelerDestination.MissionBookmarkDestination] Destination set to mission bookmark [Encounter
(Deadspace) - Waskisen]
23:03:29 [TravelerDestination.BookmarkDestination] This is not the destination station, undocking
23:03:50 [TravelerDestination.BookmarkDestination] Warping to bookmark [Encounter (Deadspace) -
Waskisen][7,53 AU away]
23:04:31 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [Encounter (Deadspace) - Waskisen]
23:04:32 [Combat] You are not in the CombatShipName [Tengu1] and / or the combatship has no weapons!
23:04:32 [Combat] Out of Ammo!
23:04:33 [Combat] You are not in the CombatShipName [Tengu1] and / or the combatship has no weapons!
23:04:33 [CombatMissionsBehavior.TravelHome] Destination: [Waskisen IX - Moon 11 - Corporate Police Force Logistic
Support]
23:04:33 [TravelerDestination.StationDestination] Destination set to [Waskisen IX - Moon 11 - Corporate Police
Force Logistic Support]
23:04:34 [Combat] You are not in the CombatShipName [Tengu1] and / or the combatship has no weapons!
23:04:35 [Combat] You are not in the CombatShipName [Tengu1] and / or the combatship has no weapons!
23:04:36 [Combat] You are not in the CombatShipName [Tengu1] and / or the combatship has no weapons!
23:04:36 [TravelerDestination.StationDestination] Warp to and dock at [Waskisen IX - Moon 11 - Corporate Police
Force Logistic Support][7,53 AU away]
23:04:37 [Combat] You are not in the CombatShipName [Tengu1] and / or the combatship has no weapons!
23:05:15 [Combat] You are not in the CombatShipName [Tengu1] and / or the combatship has no weapons!
23:05:15 [TravelerDestination.StationDestination] Dock at [Waskisen IX - Moon 11 - Corporate Police Force Logistic
Support] which is [-2k away]
23:05:16 [Combat] You are not in the CombatShipName [Tengu1] and / or the combatship has no weapons!
23:05:17 [Combat] You are not in the CombatShipName [Tengu1] and / or the combatship has no weapons!
23:05:18 [Combat] You are not in the CombatShipName [Tengu1] and / or the combatship has no weapons!
23:05:21 [TravelerDestination.StationDestination] Arrived in station
23:05:21 [CombatMissionsBehavior.TravelHome] Arrived at destination
23:05:22 [CombatMissionsBehavior.TravelHome] Arrived at destination

**Comment by skorn777** [comment]
Problem solved - thanks for your help
