### ISSUE TITLE
Unable to verify your support license, please try again later !

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#425]
Hi, 

I successfully compiled and loaded DaTeach questor master branch, but when it comes to launch questor compiled with source based on this fork and BleedingEdge branch, I got an error on licence check :

Blocking IsDebuggerPresent() call.
DirectEve: Exception during license check: Unable to verify your support license, please try again later !
00:35:06 [Startup] Error on Loading DirectEve, maybe server is down
00:35:06 [Startup] DirectEVE: Exception System.Security.SecurityException: Unable to verify your support license, please try again later !

Removing my licence file shows me another error telling me to download a licence so I think my licence file is found. I also tried again the DaTeach master source and it worked instantly, so I don't think licence server is down like it is echoing

Any suggestion on this problem ?

**Comment by frbyles** [comment]
Hey sebastor you need latest experimental 
https://github.com/ISeeDEDPpl/Questor

**Comment by ghost** [comment]
Thx for quick answer !

I'll try, but I see source is using DirectEve v1.330.4904.26383 on experimental branch whereas last version is DirectEve  v1.330.4922.28677 and it's updated to this version only on BleedingEdge branch. 
If I am using experimental branch with  DirectEve v1.330.4904.2638, must I put this version of DirectEve.dll in my innerspace folders ?

**Comment by frbyles** [comment]
you need to get on irc :) thats the best way but yes Isee experimental q will run with latest DE
theres a few more steps you need to take . but even though its just 3 things its a long instruction list 
But with latest Experim and DE once you compile with no errors and get settings setup correctly you should be up and running. 
http://forum.thehackerwithin.com/yaf_topics2_Questor.aspx
get on forum and pm me 

Also to make things as smooth as possible save this to a .bat file and run it as admin. If you go by the old guide and do the other stuff like .net 3.5 command line stuff it fucks everything up and its best to reformat windows start over. it took me 4 days to get Q running. But i am a noob tho

echo
pause
cd C:\Program Files (x86)
takeown /f Innerspace /R /D Y
pause
icacls Innerspace /grant *S-1-5-32-544:F /T /C /Q
pause

It wont let me comment again so i have to keep updating this one

**Comment by Pluckyduck** [comment]
Basic guide line
1. download the newest DE

1A/B either get stealthing download or easyhooks.dll
1. install Innerspace (or the new framework)
2. get either EXP or BleedingEdge (most up to date public Q's) place in .NET Program folder.  
3. make sure you are on 4.5 .NET.  
4. Create your character.xml
5. place newest DE in the DE folder in .NET Programs.
6.  USE the compile.bat and then transfertolive.bat.  If you are getting something in yellow, come back with what that is and if RED then do NOT run questor.
