### ISSUE TITLE
questor not warp to safespot

### ISSUE THREAD

**Issue by evelover** [ISeeDEDPpl/Questor#428]
in nostation system just to sun.

**Comment by ISeeDEDPpl** [comment]
log?

**Comment by evelover** [comment]
14:28:29 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [Encounter (Deadspace) - olololo]
14:28:30 [Panic] Start panicking, mission invaded by [1] frigates
14:28:30 [Panic] Invaded by: PlayerName [asasha] ShipTypeID [603] Distance [14,752k] Velocity [3426,01391601563]
14:28:31 [Panic] No station found in local?
14:28:31 [Panic] Warping to [olololo - Star][5,35 AU away]

**Comment by evelover** [comment]
Im create safespot with name for example safespot1 and in settings write <safeSpotBookmarkPrefix>safes</safeSpotBookmarkPrefix> its correct?

**Comment by evelover** [comment]
And trying in settings write full name of bookmark but not working too.

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge, it wanted a space after the safespotprefixname, that is no longer needed.  Any bookmark that starts with the safespotbookmarkprefix will work now.
