### ISSUE TITLE
Exp 31.10 Aug not seeing acceleration gate

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#429]
the first pocket had not actions specified and no problems.

the second pocket had now actions specified but with problems.

did a restart and enable debugActivateGate debug

14:25:21 [CombatMissionCtrl] if (closest.Distance [-1.9169921875] <= (int)Distances.GateActivationRange [2200])
14:25:21 [CombatMissionCtrl] if (closest.Distance >= -10100)
14:25:22 [CombatMissionCtrl] if (closest.Distance [-1.8798828125] <= (int)Distances.GateActivationRange [2200])
14:25:22 [CombatMissionCtrl] if (closest.Distance >= -10100)
14:25:23 [CombatMissionCtrl] if (closest.Distance [-1.8486328125] <= (int)Distances.GateActivationRange [2200])
14:25:23 [CombatMissionCtrl] if (closest.Distance >= -10100)
14:25:24 [CombatMissionCtrl] if (closest.Distance [-1.8291015625] <= (int)Distances.GateActivationRange [2200])
14:25:24 [CombatMissionCtrl] if (closest.Distance >= -10100)
14:25:25 [CombatMissionCtrl] if (closest.Distance [-1.810546875] <= (int)Distances.GateActivationRange [2200])
14:25:25 [CombatMissionCtrl] if (closest.Distance >= -10100)
14:25:26 [CombatMissionCtrl] if (closest.Distance [-1.791015625] <= (int)Distances.GateActivationRange [2200])
14:25:26 [CombatMissionCtrl] if (closest.Distance >= -10100)

**Comment by ISeeDEDPpl** [comment]
Do you have LootAll true? Do you have a tractorbeam?

**Comment by Pluckyduck** [comment]
This was with the mission runner.

No tractor beam.  

it was default setting, no mission xml

<lootEverything>true

**Comment by Pluckyduck** [comment]
unable to test to find bug

**Comment by ISeeDEDPpl** [comment]
this is fixed I assume. if not it needs logs again.. and the mission XML

**Comment by juandrito** [comment]
same problem here, with aceleration gate

**Comment by ISeeDEDPpl** [comment]
juandrito,
console logs, mission XML and open a new issue as this is HIGHLY likely to not be the same cause as the original issue. make sure you hve updated to latest experimental (or bleedingedge), OR at least give me what rev you are using and explain why you think you cant update.
