### ISSUE TITLE
odyssey 1.1 Error

### ISSUE THREAD

**Issue by skorn777** [ISeeDEDPpl/Questor#430]
after the patch odyssey 1.1 error has occurred - the ship does not take off from the dock - the log below:

11:58:40 [CombatMissionsBehavior.TravelHome] Destination: [Kinkaro X - Moon 3 - Tar Corporation]
11:58:40 [TravelerDestination.StationDestination] Destination set to [Kinkaro X - Moon 3 - Tar Corporation]
11:58:45 [Traveler] Error setting solar system destination [500001]
11:58:47 [Traveler] Error setting solar system destination [500001]
11:58:49 [Traveler] Error setting solar system destination [500001]
11:58:51 [Traveler] Error setting solar system destination [500001]
11:58:55 [Traveler] Error setting solar system destination [500001]

**Comment by ISeeDEDPpl** [comment]
fixed by updated DE
