### ISSUE TITLE
Questor not warp to mission and not use acceleration gate

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#432]
Questor start properly, but when undock and warp to gate, after jump not warp to mission, when i manually warp to mission he not use acceleration gate too. 
I test the latest BE and Experimental, i download the latest DE too. 
This is log: 

15:xx:xx [TravelerDestination.BookmarkDestination] Warping to bookmark [Encounter (Deadspace) - xx][xx
AU away]
15:xx:xx [TravelerDestination.BookmarkDestination] Warping to bookmark [Encounter (Deadspace) - xx][xx
AU away]
15:xx:xx [TravelerDestination.BookmarkDestination] Warping to bookmark [Encounter (Deadspace) - xx][xx
AU away]
15:xx:xx [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 2 ] minutes.
15:xx:xx [TravelerDestination.BookmarkDestination] Warping to bookmark [Encounter (Deadspace) - xx][xx
AU away]

**Comment by oldmeat** [comment]
I turn on <debugTraveler>true</debugTraveler> but show the same, nothing more

**Comment by oldmeat** [comment]
In old Questor release, which before patch work perfectly this issue appear too.

**Comment by evelover** [comment]
Same problem

**Comment by oldmeat** [comment]
The problem was resolved, download the latest DE

**Comment by evelover** [comment]
use a v1.330.5000.33862 first gate to pocket 1 activated, second gate to pocket 2 not.

**Comment by oldmeat** [comment]
Acceleration gate bug is issue the latest build of Questor: https://github.com/ISeeDEDPpl/Questor/issues/429 
i use old release and for me this problem not exist.
