### ISSUE TITLE
Delay issues from panic undock (current EXP)

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#433]
Even with timer that was added for the pop up.  if shield or cap flee, still Q will undock to quick.  

  Watched it happen a few times now.  easy to reproduce with high cap threshold on panic

**Comment by ISeeDEDPpl** [comment]
logs?

If it panics from nor enough capacitor... it warps to station and docks. If no station avail it'll warp to the sun and wait for the cap to regen above the "safe to return" threshold. (at least it should!)

What is actually happening?! Either describe the problem in great detail or find the logs (hint: logs would be better)

**Comment by Pluckyduck** [comment]
what debug would you like?

**Comment by ISeeDEDPpl** [comment]
none, just the regular logs...

**Comment by Pluckyduck** [comment]
http://pastebin.com/bCG6aesx

as requested with note in the middle to help.

**Comment by ISeeDEDPpl** [comment]
k, hopefully fixed in bleedingedge.
