### ISSUE TITLE
Does not activate weapons with targets available. (BleedingEdge)

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#434]
Seems the issue comes up after a a priority action happens (Web, Scram etc). 

Let me know what debugging you want me to run and ill get you logs.

**Comment by ISeeDEDPpl** [comment]
the targets that are avail, are they targeted? or not targeted?

**Comment by ISeeDEDPpl** [comment]
if they ARE NOT targeted reproduce with DebugTargetCombatants set to true
if they ARE targeted reproduce with DebugGetBestTarget set to true
you can turn em both on if you arent sure. The log will be quite large. You may want to wait to turn those on until you are in the pocket where the problem occurs. FYI: You can enable/disable the debug settings on the fly during a mission.

**Comment by ghost** [comment]
I will run that when I get home from work.

The specific mission I tested had me landing at the first acceleration gate. 4 frigates to kill, none did any priority actions and thus It targeted and killed them all.

Next pocket, landed started locking and engaging High Priority Targets (BS) and then I was Sensor Dampened | Webbed | Scrammed. Weapons just shut off and drones were only engaging targets. I have to check if they were set to aggressive or not.

The NPC remained targeted, and questor continued to target/detarget npcs per priority. Just not shoot. Ill get those logs running and update with them when I get home.

**Comment by ghost** [comment]
pffft, doubter =)... I did scrap my old Settings and used the one directly from bleedingedge. I also use turrets and not missiles.

**Comment by ghost** [comment]
07:49:27 [Cache.potentialCombatTargets] DebugTargetCombatants: list of __entities below
07:49:27 [Cache.potentialCombatTargets] [1] Name [Striker Alvatis Wreck] Distance [64.69] TypeID [26592] groupID [186]
07:49:27 [Cache.potentialCombatTargets] [2] Name [Disintegrator Alvum Wreck] Distance [54.81] TypeID [26592] groupID [186]
07:49:27 [Cache.potentialCombatTargets] [3] Name [Hobgoblin II] Distance [0.73] TypeID [2456] groupID [100]
07:49:27 [Cache.potentialCombatTargets] [4] Name [Striker Alvatis Wreck] Distance [56.05] TypeID [26592] groupID [186]
07:49:27 [Cache.potentialCombatTargets] [5] Name [Hobgoblin II] Distance [0.73] TypeID [2456] groupID [100]
07:49:27 [Cache.potentialCombatTargets] [6] Name [Striker Alvatis Wreck] Distance [68.77] TypeID [26592] groupID [186]
07:49:27 [Cache.potentialCombatTargets] [7] Name [Disintegrator Alvum Wreck] Distance [58.86] TypeID [26592] groupID [186]
07:49:27 [Cache.potentialCombatTargets] [8] Name [Hobgoblin II] Distance [0.73] TypeID [2456] groupID [100]
07:49:27 [Cache.potentialCombatTargets] [9] Name [Hobgoblin II] Distance [0.73] TypeID [2456] groupID [100]
07:49:27 [Cache.potentialCombatTargets] [10] Name [Hobgoblin II] Distance [0.73] TypeID [2456] groupID [100]
07:49:27 [Cache.potentialCombatTargets] [11] Name [Striker Alvatis Wreck] Distance [49.93] TypeID [26592] groupID [186]
07:49:27 [Cache.potentialCombatTargets] [12] Name [Acceleration Gate] Distance [6.3] TypeID [17831] groupID [366]
07:49:27 [Cache.potentialCombatTargets] [13] Name [Fire Cloud] Distance [68.13] TypeID [10131] groupID [227]
07:49:27 [Cache.potentialCombatTargets] [14] Name [Infested Station Ruins] Distance [70.69] TypeID [16736] groupID [319]
07:49:27 [Cache.potentialCombatTargets] [15] Name [Frozen Corpse] Distance [77.02] TypeID [10041] groupID [226]
07:49:27 [Cache.potentialCombatTargets] [16] Name [Frozen Corpse] Distance [72.26] TypeID [10041] groupID [226]
07:49:27 [Cache.potentialCombatTargets] [17] Name [Frozen Corpse] Distance [84.62] TypeID [10041] groupID [226]
07:49:27 [Cache.potentialCombatTargets] [18] Name [Ship Carcass] Distance [59.04] TypeID [10305] groupID [226]
07:49:27 [Cache.potentialCombatTargets] [19] Name [Rock Formation] Distance [55.4] TypeID [10783] groupID [226]
07:49:27 [Cache.potentialCombatTargets] [20] Name [Beacon] Distance [8.46] TypeID [10124] groupID [226]
07:49:27 [Cache.potentialCombatTargets] [21] Name [Acidic Cloud] Distance [80.9] TypeID [10760] groupID [227]
07:49:27 [Cache.potentialCombatTargets] [22] Name [Tower Sentry Drone II] Distance [79.39] TypeID [18027] groupID [383]
07:49:27 [Cache.potentialCombatTargets] [23] Name [Frozen Corpse] Distance [84.09] TypeID [10041] groupID [226]
07:49:27 [Cache.potentialCombatTargets] [24] Name [Ship Carcass] Distance [68.95] TypeID [10305] groupID [226]
07:49:27 [Cache.potentialCombatTargets] [25] Name [Drone Hive] Distance [60.87] TypeID [18012] groupID [319]
07:49:27 [Cache.potentialCombatTargets] [26] Name [Rock Formation] Distance [31.44] TypeID [10787] groupID [226]
07:49:27 [Cache.potentialCombatTargets] [27] Name [Ship Carcass] Distance [39.72] TypeID [10305] groupID [226]
07:49:27 [Cache.potentialCombatTargets] [28] Name [Elite Drone Parasite] Distance [40.21] TypeID [21814] groupID [802]
07:49:27 [Cache.potentialCombatTargets] [29] Name [Elite Drone Parasite] Distance [40.21] TypeID [21814] groupID [802]
07:49:28 [Cache.potentialCombatTargets] [30] Name [Abandoned Drill] Distance [60.61] TypeID [13835] groupID [226]
07:49:28 [Cache.potentialCombatTargets] [31] Name [Elite Drone Parasite] Distance [66.5] TypeID [21814] groupID [802]
07:49:28 [Cache.potentialCombatTargets] [32] Name [Elite Drone Parasite] Distance [66] TypeID [21814] groupID [802]
07:49:28 [Cache.potentialCombatTargets] [33] Name [Tower Sentry Drone II] Distance [48.06] TypeID [18027] groupID [383]
07:49:28 [Cache.potentialCombatTargets] [34] Name [Elite Drone Parasite] Distance [67.67] TypeID [21814] groupID [802]
07:49:28 [Cache.potentialCombatTargets] DebugTargetCombatants: list of __entities above
07:49:28 [potentialCombatTargets] [1]: no targets found !!! _entities [4]
07:45:51 [GetBestTarget: none] Could not determine a suitable target

**Comment by ghost** [comment]
5 Elite Drone Parasites 2 of which are targeting me.
2 Tower Sentry Drone II 2 of which are targeting me.

**Comment by ghost** [comment]
Manual targeting makes questor detarget the target.

**Comment by ghost** [comment]
Were any of them doing priority actions like web, scram, damp, neut etc

**Comment by ghost** [comment]
No

**Comment by ghost** [comment]
It found 4 entities when there was actually 5

**Comment by ghost** [comment]
7 to be exact

**Comment by ghost** [comment]
5 that the code lists as being suitable for entities

**Comment by ghost** [comment]
07:41:51 [-] -----------------------------------------------------------------
07:41:51 [CombatMissionCtrl] Pocket [1] loaded, executing the following actions
07:41:51 [CombatMissionCtrl] Action [ 1 ] Kill [target: Tower Sentry Drone II] [ignoreattackers: True] [numbertoignore: 1]
07:41:51 [CombatMissionCtrl] Action [ 2 ] MoveToBackground [target: Acceleration Gate]
07:41:51 [CombatMissionCtrl] Action [ 3 ] ClearWithinWeaponsRangeOnly
07:41:51 [CombatMissionCtrl] Action [ 4 ] ClearPocket
07:41:51 [CombatMissionCtrl] Action [ 5 ] Activate [target: Acceleration Gate]
07:41:51 [-] -----------------------------------------------------------------
07:41:51 [-] -----------------------------------------------------------------
07:41:51 [Statistics.ObjectStatistics] Logging info on the [26] objects in this pocket to [C:\Program Files (x86)\InnerSpace.NET Programs\log\Njai Hill\PocketObjectStats\Njai Hill - Silence The Informant - 1 - ObjectStatistics.csv]
07:41:52 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:52 [GetBestTarget: none] Could not determine a suitable target
07:41:52 [CombatMissionCtrl.KillClosestByName] Adding [Tower Sentry Drone II] Speed [0k/s] Distance [56.33] [ID: [truncatedID]13182] as a PrimaryWeaponPriorityTarget [PriorityKillTarget]
07:41:52 [CombatMissionCtrl.KillClosestByName] Adding [Tower Sentry Drone II] Speed [0k/s] Distance [88.41] [ID: [truncatedID]13181] as a PrimaryWeaponPriorityTarget [PriorityKillTarget]
07:41:52 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:52 [GetBestTarget: none] Could not determine a suitable target
07:41:53 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:53 [GetBestTarget: none] Could not determine a suitable target
07:41:54 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:54 [GetBestTarget: none] Could not determine a suitable target
07:41:54 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:54 [GetBestTarget: none] Could not determine a suitable target
07:41:55 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:55 [GetBestTarget: none] Could not determine a suitable target
07:41:56 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:56 [GetBestTarget: none] Could not determine a suitable target
07:41:56 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:56 [GetBestTarget: none] Could not determine a suitable target
07:41:57 [Combat] Targeting non-aggressed NPC target [Elite Drone Parasite][GroupID: 802][TypeID: 21814][ID: [truncatedID]13189][53k away]
07:41:57 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:57 [GetBestTarget: none] Could not determine a suitable target
07:41:58 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:58 [GetBestTarget: none] Could not determine a suitable target
07:41:58 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:58 [GetBestTarget: none] Could not determine a suitable target
07:41:59 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:41:59 [GetBestTarget: none] Could not determine a suitable target
07:42:00 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:00 [GetBestTarget: none] Could not determine a suitable target
07:42:00 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:00 [GetBestTarget: none] Could not determine a suitable target
07:42:01 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:01 [GetBestTarget: none] Could not determine a suitable target
07:42:02 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:04 [Combat] Activating painter [1] on [Elite Drone Parasite][ID: [truncatedID]13188][52k away]
07:42:04 [Combat] Activating weapon [1] on [Elite Drone Parasite][ID: [truncatedID]13188][52k away]
07:42:08 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:14 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:15 [CombatMissionCtrl.Kill [target: Tower Sentry Drone II] [ignoreattackers: True] [numbertoignore: 1]] Ignoring [Elite Drone Parasite][ID: [truncatedID]13189][53k away] due to ignoreAttackers paramater
07:42:17 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Elite Drone Parasite to make room for [OutOfRange or Ignored]
07:42:19 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Elite Drone Parasite to make room for [OutOfRange or Ignored]
07:42:20 [Defense] Shields: [95%] Cap: [86%] Shield Booster: [1] activated
07:42:20 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:20 [GetBestTarget: none] Could not determine a suitable target
07:42:21 [Combat] Targeting non-aggressed NPC target [Striker Alvatis][GroupID: 801][TypeID: 18075][ID: [truncatedID]14544][81k away]
07:42:21 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:21 [GetBestTarget: none] Could not determine a suitable target
07:42:22 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:22 [GetBestTarget: none] Could not determine a suitable target
07:42:23 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:23 [GetBestTarget: none] Could not determine a suitable target
07:42:24 [Defense] Shields: [100%] Cap: [85%] Shield Booster: [1] deactivated [2] sec reactivation delay
07:42:24 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:24 [GetBestTarget: none] Could not determine a suitable target
07:42:25 [Combat] Targeting non-aggressed NPC target [Striker Alvatis][GroupID: 801][TypeID: 18075][ID: [truncatedID]14542][83k away]
07:42:25 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:25 [GetBestTarget: none] Could not determine a suitable target
07:42:26 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:26 [GetBestTarget: none] Could not determine a suitable target
07:42:27 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:27 [GetBestTarget: none] Could not determine a suitable target
07:42:28 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:28 [GetBestTarget: none] Could not determine a suitable target
07:42:30 [Combat] Targeting non-aggressed NPC target [Striker Alvatis][GroupID: 801][TypeID: 18075][ID: [truncatedID]14541][85k away]
07:42:30 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:30 [GetBestTarget: none] Could not determine a suitable target
07:42:30 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:30 [GetBestTarget: none] Could not determine a suitable target
07:42:31 [Defense] Shields: [96%] Cap: [85%] Shield Booster: [1] activated
07:42:31 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:31 [GetBestTarget: none] Could not determine a suitable target
07:42:33 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:33 [GetBestTarget: none] Could not determine a suitable target
07:42:33 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:33 [GetBestTarget: none] Could not determine a suitable target
07:42:35 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:37 [Combat] Using Optimal Range: Approaching target [Striker Alvatis][ID: [truncatedID]14544][82k away]
07:42:37 [Combat] Activating painter [1] on [Striker Alvatis][ID: [truncatedID]14544][82k away]
07:42:37 [Combat] Activating weapon [1] on [Striker Alvatis][ID: [truncatedID]14544][82k away]
07:42:39 [Defense] Shields: [100%] Cap: [83%] Shield Booster: [1] deactivated [2] sec reactivation delay
07:42:41 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:45 [Combat] Activating weapon [1] on [Striker Alvatis][ID: [truncatedID]14542][81k away]
07:42:46 [Defense] Shields: [95%] Cap: [83%] Shield Booster: [1] activated
07:42:47 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:49 [Combat] Activating painter [1] on [Striker Alvatis][ID: [truncatedID]14544][82k away]
07:42:50 [Combat] Targeting high value target [Disintegrator Alvum][ID: [truncatedID]14545][89k away] highValueTargets.Count [3]
07:42:50 [Combat] Targeting high value target [Disintegrator Alvum][ID: [truncatedID]14546][90k away] highValueTargets.Count [3]
07:42:52 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Striker Alvatis to make room for [PrimaryWeaponPriorityTargets]
07:42:53 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:42:54 [Drones] [5] Drones Launched
07:42:55 [Combat] Activating weapon [1] on [Striker Alvatis][ID: [truncatedID]14544][79k away]
07:42:56 [Defense] Shields: [100%] Cap: [80%] Shield Booster: [1] deactivated [2] sec reactivation delay
07:43:03 [Defense] Shields: [95%] Cap: [80%] Shield Booster: [1] activated
07:43:05 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:43:06 [Combat] Targeting high value target [Striker Alvatis][ID: [truncatedID]14543][77k away] highValueTargets.Count [3]
07:43:06 [Combat] Targeting high value target [Striker Alvatis][ID: [truncatedID]14541][80k away] highValueTargets.Count [3]
07:43:07 [Defense] Shields: [100%] Cap: [78%] Shield Booster: [1] deactivated [2] sec reactivation delay
07:43:07 [Combat] Using Optimal Range: Approaching target [Striker Alvatis][ID: [truncatedID]14542][74k away]
07:43:07 [Combat] Activating weapon [1] on [Striker Alvatis][ID: [truncatedID]14542][74k away]
07:43:08 [Combat [TargetCombatants]Combat.TargetCombatants] Unlocking Disintegrator Alvum to make room for [PrimaryWeaponPriorityTargets]
07:43:11 [Combat] Activating painter [1] on [Striker Alvatis][ID: [truncatedID]14542][72k away]
07:43:15 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:43:16 [Defense] Shields: [95%] Cap: [79%] Shield Booster: [1] activated
07:43:16 [Combat] Targeting high value target [Disintegrator Alvum][ID: [truncatedID]14546][78k away] highValueTargets.Count [3]
07:43:17 [Combat] Activating weapon [1] on [Disintegrator Alvum][ID: [truncatedID]14545][75k away]
07:43:21 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:43:23 [Combat] Using Optimal Range: Approaching target [Striker Alvatis][ID: [truncatedID]14543][69k away]
07:43:23 [Combat] Activating painter [1] on [Striker Alvatis][ID: [truncatedID]14543][69k away]
07:43:27 [Defense] Shields: [100%] Cap: [76%] Shield Booster: [1] deactivated [2] sec reactivation delay
07:43:27 [Combat] Activating weapon [1] on [Striker Alvatis][ID: [truncatedID]14543][68k away]
07:43:27 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:43:31 [Defense] Shields: [96%] Cap: [76%] Shield Booster: [1] activated
07:43:33 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:43:35 [Combat] Activating painter [1] on [Disintegrator Alvum][ID: [truncatedID]14545][67k away]
07:43:37 [Combat] Activating weapon [1] on [Disintegrator Alvum][ID: [truncatedID]14545][66k away]
07:43:39 [Combat] Using Optimal Range: Approaching target [Disintegrator Alvum][ID: [truncatedID]14545][65k away]
07:43:40 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:43:45 [Defense] Shields: [100%] Cap: [73%] Shield Booster: [1] deactivated [1] sec reactivation delay
07:43:46 [Combat] Activating weapon [1] on [Striker Alvatis][ID: [truncatedID]14543][61k away]
07:43:46 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:43:48 [Combat] Activating painter [1] on [Striker Alvatis][ID: [truncatedID]14543][60k away]
07:43:50 [Defense] Shields: [96%] Cap: [73%] Shield Booster: [1] activated
07:43:54 [Defense] Shields: [100%] Cap: [73%] Shield Booster: [1] deactivated [2] sec reactivation delay
07:43:54 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:43:56 [Combat] Using Optimal Range: Approaching target [Disintegrator Alvum][ID: [truncatedID]14546][59k away]
07:43:56 [Combat] Activating weapon [1] on [Disintegrator Alvum][ID: [truncatedID]14546][59k away]
07:43:59 [Defense] Shields: [96%] Cap: [73%] Shield Booster: [1] activated
07:44:00 [Combat] Activating painter [1] on [Disintegrator Alvum][ID: [truncatedID]14546][58k away]
07:44:00 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:44:03 [Defense] Shields: [100%] Cap: [71%] Shield Booster: [1] deactivated [2] sec reactivation delay
07:44:04 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:44:06 [Combat] Activating weapon [1] on [Striker Alvatis][ID: [truncatedID]14541][57k away]
07:44:07 [Defense] Shields: [96%] Cap: [72%] Shield Booster: [1] activated
07:44:10 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
07:44:12 [Combat] Using Optimal Range: Approaching target [Striker Alvatis][ID: [truncatedID]14541][54k away]
07:44:12 [Combat] Activating painter [1] on [Striker Alvatis][ID: [truncatedID]14541][54k away]
07:44:14 [Defense] Shields: [100%] Cap: [70%] Shield Booster: [1] deactivated [2] sec reactivation delay
07:44:19 [Defense] Shields: [96%] Cap: [71%] Shield Booster: [1] activated
07:44:20 [GetBestTarget: none] Could not determine a suitable target
07:44:21 [GetBestTarget: none] Could not determine a suitable target
07:44:22 [GetBestTarget: none] Could not determine a suitable target

**Comment by ghost** [comment]
07:42:15 [CombatMissionCtrl.Kill [target: Tower Sentry Drone II] [ignoreattackers: True] [numbertoignore: 1]] Ignoring [Elite Drone Parasite][ID: [truncatedID]13189][53k away] due to ignoreAttackers paramater

**Comment by ghost** [comment]
Number to Ignore isnt ignoring the Tower Sentry...

**Comment by Pluckyduck** [comment]
if you want to ignore the sentry make sure you have it turned off in the mission.xml(not in it) and character.xml (true/false).

**Comment by ghost** [comment]
So it attacks the sentry after i turn on attack sentrys, which is different from exp and now it killed both drone towers and kills 1 Elite Drone Parasite and leaves one targeted then just sits there.

**Comment by ghost** [comment]
I noticed it will ignore the wrong things with ignore commands.

**Comment by ISeeDEDPpl** [comment]
reproduce with latest bleedingedge pls. DebugTargetCombatants needs to be on.
You can also (better?) hit the log entities on grid button under the states tab (press details to see the tabs) when it occurs.

**Comment by ISeeDEDPpl** [comment]
Dim, create a separate issue if ignore is not working as you expect it to. please.
