### ISSUE TITLE
BE i downloaded last night 

### ISSUE THREAD

**Issue by frbyles** [ISeeDEDPpl/Questor#436]
wont kill some LCO's for instance 
`<?xml version="1.0" encoding="utf-8"?>`
`<mission>`
`<pockets>`
`<pocket id="0">`
`<damagetype>Thermal</damagetype>`
`<actions>`
`<action name="ClearPocket" />`
`<action name="Kill">`
`<parameter name="Target" value="Zor" />`
`</action>`
`<action name="Kill">`
`<parameter name="Target" value="Outpost Headquarters" />`
`</action>`
`<action name="Done" />`
`</actions>`
`</pocket>`
`</pockets>`
`</mission>`
just targets and keeps at range the Outpost in The Right Hand Of Zazzmatazz.xml

**Comment by ISeeDEDPpl** [comment]
what rev did you test? 
[ fb3c083f90b25ff2e766f1f2b1870ac53b4f9f5c ]
should be working fine. 
it was fixed in [ 6889e57d97f4be3b27ec02e2b86227c98b0558d6 ] 

My guess is that you have a rev from before it was fixed. If not... I need a log with 
`<DebugGetBestTarget>true</DebugGetBestTarget>`

**Comment by ISeeDEDPpl** [comment]
fixed some other issues in BE related to this.
