### ISSUE TITLE
Targets but does not engage Sentry Turrets

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#437]
Will target, but not engage Sentry turret.

This is with Kill sentry set to True.

**Comment by ISeeDEDPpl** [comment]
Is this during ClearPocket or a Kill action? both?

Can I get a log with `<debugGetBestTarget>true</debugGetBestTarget>`
because of the spam this causes you probably do not want to activate that debug option until you are experiencing the issue (i.e. dont have it on the whole mission)

**Comment by ghost** [comment]
ClearPocket

**Comment by ISeeDEDPpl** [comment]
needs logs if I can get em.

**Comment by ghost** [comment]
The specific pocket had
3x Tower Sentry Drone II
5x Tower Sentry Drone III

It would not perform the kill action for the LCO. It had multiple Tower Sentry targeted, just not engaged.

18:59:17 [-] -----------------------------------------------------------------
18:59:17 [-] -----------------------------------------------------------------
18:59:17 [CombatMissionCtrl] Mission Timer Currently At: [23] min
18:59:17 [CombatMissionCtrl] Max Range is currently: 81k
18:59:17 [-] -----------------------------------------------------------------
18:59:17 [-] -----------------------------------------------------------------
18:59:17 [CombatMissionCtrl] Pocket [3] loaded, executing the following actions
18:59:17 [CombatMissionCtrl] Action [ 1 ] ClearPocket
18:59:17 [CombatMissionCtrl] Action [ 2 ] Kill [target: Road House]
18:59:17 [CombatMissionCtrl] Action [ 3 ] Done
18:59:17 [-] -----------------------------------------------------------------
18:59:17 [-] -----------------------------------------------------------------
18:59:17 [Statistics.ObjectStatistics] Logging info on the [14] objects in this pocket to [C:\Program Files (x86)\InnerSpace.NET Programs\log\Hi_MyEVECharacterNameRedacted_\PocketObjectStats\Hi_MyEVECharacterNameRedacted_ - Silence The Informant - 3 - ObjectStatistics.csv]
18:59:18 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:18 [GetBestTarget: none] Could not determine a suitable target
18:59:19 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:19 [GetBestTarget: none] Could not determine a suitable target
18:59:19 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:19 [GetBestTarget: none] Could not determine a suitable target
18:59:20 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:20 [GetBestTarget: none] Could not determine a suitable target
18:59:21 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:21 [GetBestTarget: none] Could not determine a suitable target
18:59:21 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:21 [GetBestTarget: none] Could not determine a suitable target
18:59:22 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:22 [GetBestTarget: none] Could not determine a suitable target
18:59:23 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:23 [GetBestTarget: none] Could not determine a suitable target
18:59:23 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:23 [GetBestTarget: none] Could not determine a suitable target
18:59:24 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:24 [GetBestTarget: none] Could not determine a suitable target
18:59:25 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:25 [GetBestTarget: none] Could not determine a suitable target
18:59:25 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:25 [GetBestTarget: none] Could not determine a suitable target
18:59:26 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
18:59:27 [Combat] Out of range. ignoring orbit around structure.
18:59:27 [Combat] Initiating Orbit [Kioran Jeraulek][at 30k][ID: [truncatedID]98241]
18:59:27 [Combat] Activating painter [1] on [Kioran Jeraulek][ID: [truncatedID]98241][78k away]
18:59:27 [Combat] Activating weapon [1] on [Kioran Jeraulek][ID: [truncatedID]98241][78k away]
18:59:45 [Defense] Shields: [75%] Cap: [54%] Shield Booster: [1] activated
19:00:02 [Defense] Shields: [98%] Cap: [42%] Shield Booster: [1] deactivated [2] sec reactivation delay
19:00:02 [CombatMissionCtrl] Finished Action.ClearPocket
19:00:02 [CombatMissionCtrl] Starting Action.Kill [target: Road House]
19:00:03 [GetBestTarget: none] Could not determine a suitable target
19:00:04 [GetBestTarget: none] Could not determine a suitable target
19:00:05 [GetBestTarget: none] Could not determine a suitable target
19:00:06 [GetBestTarget: none] Could not determine a suitable target
19:00:07 [GetBestTarget: none] Could not determine a suitable target
19:00:08 [GetBestTarget: none] Could not determine a suitable target
19:00:09 [GetBestTarget: none] Could not determine a suitable target
19:00:10 [GetBestTarget: none] Could not determine a suitable target
19:00:11 [GetBestTarget: none] Could not determine a suitable target
19:00:13 [GetBestTarget: none] Could not determine a suitable target
19:00:13 [GetBestTarget: none] Could not determine a suitable target
19:00:15 [GetBestTarget: none] Could not determine a suitable target
19:00:16 [GetBestTarget: none] Could not determine a suitable target
19:00:17 [GetBestTarget: none] Could not determine a suitable target
19:00:18 [GetBestTarget: none] Could not determine a suitable target
19:00:19 [GetBestTarget: none] Could not determine a suitable target
19:00:20 [GetBestTarget: none] Could not determine a suitable target
19:00:21 [Combat] Targeting low value target [Tower Sentry Drone III][ID: [truncatedID]98251][43k away] lowValueTargets.Count [0]
19:00:21 [GetBestTarget: none] Could not determine a suitable target
19:00:22 [GetBestTarget: none] Could not determine a suitable target
19:00:23 [GetBestTarget: none] Could not determine a suitable target
19:00:24 [GetBestTarget: none] Could not determine a suitable target
19:00:25 [Combat] Targeting low value target [Tower Sentry Drone II][ID: [truncatedID]98246][44k away] lowValueTargets.Count [0]
19:00:25 [GetBestTarget: none] Could not determine a suitable target
19:00:26 [GetBestTarget: none] Could not determine a suitable target
19:00:27 [Defense] Shields: [74%] Cap: [44%] Shield Booster: [1] activated
19:00:27 [GetBestTarget: none] Could not determine a suitable target
19:00:28 [GetBestTarget: none] Could not determine a suitable target
19:00:29 [GetBestTarget: none] Could not determine a suitable target
19:00:30 [GetBestTarget: none] Could not determine a suitable target
19:00:31 [GetBestTarget: none] Could not determine a suitable target
19:00:32 [GetBestTarget: none] Could not determine a suitable target
19:00:33 [GetBestTarget: none] Could not determine a suitable target
19:00:34 [GetBestTarget: none] Could not determine a suitable target
19:00:35 [GetBestTarget: none] Could not determine a suitable target
19:00:36 [GetBestTarget: none] Could not determine a suitable target
19:00:37 [GetBestTarget: none] Could not determine a suitable target
19:00:38 [GetBestTarget: none] Could not determine a suitable target
19:00:39 [GetBestTarget: none] Could not determine a suitable target
19:00:40 [GetBestTarget: none] Could not determine a suitable target
19:00:41 [GetBestTarget: none] Could not determine a suitable target
19:00:42 [GetBestTarget: none] Could not determine a suitable target
19:00:43 [GetBestTarget: none] Could not determine a suitable target
19:00:44 [Defense] Shields: [96%] Cap: [33%] Shield Booster: [1] deactivated [2] sec reactivation delay
19:00:44 [GetBestTarget: none] Could not determine a suitable target
19:00:45 [GetBestTarget: none] Could not determine a suitable target
19:00:46 [GetBestTarget: none] Could not determine a suitable target
19:00:47 [GetBestTarget: none] Could not determine a suitable target
19:00:48 [GetBestTarget: none] Could not determine a suitable target
19:00:49 [GetBestTarget: none] Could not determine a suitable target
19:00:50 [GetBestTarget: none] Could not determine a suitable target
19:00:51 [GetBestTarget: none] Could not determine a suitable target
19:00:52 [GetBestTarget: none] Could not determine a suitable target
19:00:53 [Combat] Targeting low value target [Tower Sentry Drone III][ID: [truncatedID]98239][44k away] lowValueTargets.Count [0]
19:00:53 [GetBestTarget: none] Could not determine a suitable target
19:00:54 [GetBestTarget: none] Could not determine a suitable target
19:00:55 [GetBestTarget: none] Could not determine a suitable target
19:00:56 [GetBestTarget: none] Could not determine a suitable target
19:00:57 [GetBestTarget: none] Could not determine a suitable target
19:00:58 [GetBestTarget: none] Could not determine a suitable target
19:01:00 [GetBestTarget: none] Could not determine a suitable target
19:01:01 [GetBestTarget: none] Could not determine a suitable target
19:01:02 [GetBestTarget: none] Could not determine a suitable target
19:01:03 [GetBestTarget: none] Could not determine a suitable target
19:01:04 [GetBestTarget: none] Could not determine a suitable target
19:01:05 [GetBestTarget: none] Could not determine a suitable target
19:01:06 [GetBestTarget: none] Could not determine a suitable target
19:01:07 [GetBestTarget: none] Could not determine a suitable target
19:01:07 [QuestorUI] Launching [C:\Program Files (x86)\InnerSpace.NET Programs\Caldari Missions 4 Level\Silence The Informant.xml]
19:01:08 [GetBestTarget: none] Could not determine a suitable target
19:01:09 [GetBestTarget: none] Could not determine a suitable target
19:01:10 [Defense] Shields: [75%] Cap: [35%] Shield Booster: [1] activated

**Comment by ghost** [comment]
Here is log with DebugGetBestTarget

Have Kill Target specified on this one, but it doesnt see it in targets.

Also other Sentry Turrets on field its not seeing.

13:54:14 [-] -----------------------------------------------------------------
13:54:14 [-] -----------------------------------------------------------------
13:54:14 [CombatMissionCtrl] Mission Timer Currently At: [15] min
13:54:14 [CombatMissionCtrl] Max Range is currently: 81k
13:54:14 [-] -----------------------------------------------------------------
13:54:14 [-] -----------------------------------------------------------------
13:54:14 [CombatMissionCtrl] Pocket [1] loaded, executing the following actions
13:54:14 [CombatMissionCtrl] Action [ 1 ] Kill [target: Drone Energy Neutralizer Sentry I] [target: Drone Stasis Sentry I]
13:54:14 [CombatMissionCtrl] Action [ 2 ] WaitUntilTargeted [timeout: 30]
13:54:14 [CombatMissionCtrl] Action [ 3 ] ClearPocket
13:54:14 [CombatMissionCtrl] Action [ 4 ] Kill [target: Infested Station]
13:54:14 [CombatMissionCtrl] Action [ 5 ] Activate [target: Navigational Beacon]
13:54:14 [-] -----------------------------------------------------------------
13:54:14 [-] -----------------------------------------------------------------
13:54:14 [Statistics.ObjectStatistics] Logging info on the [93] objects in this pocket to [C:\Program Files (x86)\InnerSpace.NET Programs\log\Hi_MyEVECharacterNameRedacted_\PocketObjectStats\Hi_MyEVECharacterNameRedacted_ - Evolution - 1 - ObjectStatistics.csv]
13:54:15 [combat Debug: GetBestTarget (Weapons):] Attempting to get Best Target
13:54:15 [combat Debug: GetBestTarget (Weapons):] Checking Closest Primary
13:54:15 [combat Debug: GetBestTarget (Weapons):] Checking Calling Target
13:54:15 [combat Debug: GetBestTarget (Weapons):] Checking Closest High Value
13:54:15 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
13:54:15 [combat Debug: GetBestTarget (Weapons):] Checking closest Low Value
13:54:15 [GetBestTarget: none] Could not determine a suitable target
13:54:15 [GetBestTarget (Weapons): none] .
13:54:15 [GetBestTarget (Weapons): none] ALL potentialCombatTargets LISTED BELOW
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][89.7k][[truncatedID]29270][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Matriarch Alvus][53.23k][[truncatedID]33021][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Alvus Queen][47.45k][[truncatedID]33023][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Strain Hunter Alvi][23.84k][[truncatedID]33024][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Strain Hunter Alvi][23.31k][[truncatedID]33025][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Strain Hunter Alvi][27.87k][[truncatedID]33026][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Strain Devilfish Alvi][17.46k][[truncatedID]33027][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Devilfish Alvi][17.96k][[truncatedID]29312][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][20.45k][[truncatedID]29258][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][16.85k][[truncatedID]29259][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][50.02k][[truncatedID]29262][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][50.69k][[truncatedID]29263][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][50.46k][[truncatedID]29265][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][88.56k][[truncatedID]29268][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][89.45k][[truncatedID]29269][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][89.46k][[truncatedID]29271][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Strain Infester Alvi][17.76k][[truncatedID]29311][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Devilfish Alvi][33.44k][[truncatedID]29314][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Strain Splinter Alvi][19.53k][[truncatedID]29315][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Strain Splinter Alvi][14.56k][[truncatedID]29316][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Matriarch Alvus][106.3k][[truncatedID]35495][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Siege Alvatis][103.56k][[truncatedID]35496][isTarget: False] GroupID [801]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Exterminator Alvatis][105.69k][[truncatedID]35497][isTarget: False] GroupID [801]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Alvus Queen][112.19k][[truncatedID]35505][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Alvus Queen][110.98k][[truncatedID]35506][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Enforcer Alvatis][113.56k][[truncatedID]35498][isTarget: False] GroupID [801]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Alvus Queen][111.41k][[truncatedID]35504][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][49.49k][[truncatedID]29264][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Weapons): none] ALL potentialCombatTargets LISTED ABOVE
13:54:15 [GetBestTarget (Weapons): none] .
13:54:15 [GetBestTarget (Drones): none] .
13:54:15 [GetBestTarget (Drones): none] ALL potentialCombatTargets LISTED BELOW
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Worker Drone][89.7k][[truncatedID]29270][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Matriarch Alvus][53.23k][[truncatedID]33021][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Alvus Queen][47.45k][[truncatedID]33023][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Strain Hunter Alvi][23.84k][[truncatedID]33024][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Strain Hunter Alvi][23.31k][[truncatedID]33025][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Strain Hunter Alvi][27.87k][[truncatedID]33026][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Strain Devilfish Alvi][17.46k][[truncatedID]33027][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Devilfish Alvi][17.96k][[truncatedID]29312][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Worker Drone][20.45k][[truncatedID]29258][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Worker Drone][16.85k][[truncatedID]29259][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Worker Drone][50.02k][[truncatedID]29262][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Worker Drone][50.69k][[truncatedID]29263][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Worker Drone][50.46k][[truncatedID]29265][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Worker Drone][88.56k][[truncatedID]29268][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Worker Drone][89.45k][[truncatedID]29269][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Worker Drone][89.46k][[truncatedID]29271][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Strain Infester Alvi][17.76k][[truncatedID]29311][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Devilfish Alvi][33.44k][[truncatedID]29314][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Strain Splinter Alvi][19.53k][[truncatedID]29315][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Strain Splinter Alvi][14.56k][[truncatedID]29316][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Matriarch Alvus][106.3k][[truncatedID]35495][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Siege Alvatis][103.56k][[truncatedID]35496][isTarget: False] GroupID [801]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Exterminator Alvatis][105.69k][[truncatedID]35497][isTarget: False] GroupID [801]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Alvus Queen][112.19k][[truncatedID]35505][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Alvus Queen][110.98k][[truncatedID]35506][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Enforcer Alvatis][113.56k][[truncatedID]35498][isTarget: False] GroupID [801]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Alvus Queen][111.41k][[truncatedID]35504][isTarget: False] GroupID [802]
13:54:15 [GetBestTarget (Drones): none] Debug entities: [Worker Drone][49.49k][[truncatedID]29264][isTarget: False] GroupID [805]
13:54:15 [GetBestTarget (Drones): none] ALL potentialCombatTargets LISTED ABOVE
13:54:15 [GetBestTarget (Drones): none] .
13:54:16 [Combat Debug: GetBestTarget (Weapons):] Attempting to get Best Target
13:54:16 [Combat Debug: GetBestTarget (Weapons):] Checking Closest Primary
13:54:16 [Combat Debug: GetBestTarget (Weapons):] Checking Calling Target
13:54:16 [Combat Debug: GetBestTarget (Weapons):] Checking Closest High Value
13:54:16 [Combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
13:54:16 [Combat Debug: GetBestTarget (Weapons):] Checking closest Low Value
13:54:16 [GetBestTarget: none] Could not determine a suitable target
13:54:16 [GetBestTarget (Weapons): none] .
13:54:16 [GetBestTarget (Weapons): none] ALL potentialCombatTargets LISTED BELOW
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][89.6k][[truncatedID]29270][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Matriarch Alvus][53.07k][[truncatedID]33021][isTarget: False] GroupID [802]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Alvus Queen][47.27k][[truncatedID]33023][isTarget: False] GroupID [802]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Strain Hunter Alvi][23.79k][[truncatedID]33024][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Strain Hunter Alvi][23.46k][[truncatedID]33025][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Strain Hunter Alvi][28.03k][[truncatedID]33026][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Strain Devilfish Alvi][17.55k][[truncatedID]33027][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Devilfish Alvi][18.08k][[truncatedID]29312][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][20.63k][[truncatedID]29258][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][17.01k][[truncatedID]29259][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][50.24k][[truncatedID]29262][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][50.53k][[truncatedID]29263][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][50.67k][[truncatedID]29265][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][88.45k][[truncatedID]29268][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][89.35k][[truncatedID]29269][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][89.44k][[truncatedID]29271][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Strain Infester Alvi][17.68k][[truncatedID]29311][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Devilfish Alvi][33.11k][[truncatedID]29314][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Strain Splinter Alvi][19.5k][[truncatedID]29315][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Strain Splinter Alvi][14.44k][[truncatedID]29316][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Matriarch Alvus][106.28k][[truncatedID]35495][isTarget: False] GroupID [802]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Siege Alvatis][103.55k][[truncatedID]35496][isTarget: False] GroupID [801]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Exterminator Alvatis][105.44k][[truncatedID]35497][isTarget: False] GroupID [801]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Alvus Queen][112.25k][[truncatedID]35505][isTarget: False] GroupID [802]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Alvus Queen][110.95k][[truncatedID]35506][isTarget: False] GroupID [802]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Enforcer Alvatis][113.52k][[truncatedID]35498][isTarget: False] GroupID [801]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Alvus Queen][111.37k][[truncatedID]35504][isTarget: False] GroupID [802]
13:54:16 [GetBestTarget (Weapons): none] Debug entities: [Worker Drone][49.35k][[truncatedID]29264][isTarget: False] GroupID [805]
13:54:16 [GetBestTarget (Weapons): none] ALL potentialCombatTargets LISTED ABOVE
13:54:16 [GetBestTarget (Weapons): none] .
13:54:16 [combat Debug: GetBestTarget (Weapons):] Attempting to get Best Target
13:54:16 [combat Debug: GetBestTarget (Weapons):] Checking Closest Primary
13:54:16 [combat Debug: GetBestTarget (Weapons):] Checking Calling Target
13:54:16 [combat Debug: GetBestTarget (Weapons):] Checking Closest High Value
13:54:16 [combat Debug: GetBestTarget (Weapons):] get closest: if (potentialCombatTargets.Any())
13:54:16 [combat Debug: GetBestTarget (Weapons):] Checking closest Low Value

**Comment by ISeeDEDPpl** [comment]
should be fixed. 
please open a new issue if you are still experiencing issue(s)
