### ISSUE TITLE
Silence The Informant, LCO not Targeted / Engaged.

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#438]
21:24:53 [Cache.potentialCombatTargets] DebugTargetCombatants: list of __entities below
21:24:53 [Cache.potentialCombatTargets] [1] Name [Road House] Distance [45.1] TypeID [19559] groupID [494] IsNPC [True] IsNPCByGroupID [False]
21:24:53 [Cache.potentialCombatTargets] [2] Name [Scanner Post] Distance [108.3] TypeID [13106] groupID [319] IsNPC [True] IsNPCByGroupID [False]
21:24:53 [Cache.potentialCombatTargets] [3] Name [Shipyard] Distance [56.96] TypeID [18567] groupID [319] IsNPC [True] IsNPCByGroupID [False]
21:24:53 [Cache.potentialCombatTargets] DebugTargetCombatants: list of __entities above
21:24:53 [potentialCombatTargets] [1]: no targets found !!! _entities [3]

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge. thank you.
