### ISSUE TITLE
Panic Mode recovering Mission not working when docked in station

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#439]
Using latest experimental and newest bleeding edge when questor goes in panic and dock in station it will not undock and recover the mission.

Log is

14:51:39 [Combat] Activating painter [1] on [Starbase Stasis Tower][ID: [truncatedID]60602][16k away]
14:51:39 [Combat] Activating weapon  [1] on [Starbase Stasis Tower][ID: [truncatedID]60602][16k away]
14:51:46 [Panic] Start panicking, capacitor [14%] below [15%] S[62%] A[100%] C[14%]
14:51:47 [Panic] Warping to [Veisto V - Moon 4 - Propel Dynamics Factory][19,22 AU away]
14:51:48 [Panic] Warping will be attempted again after [4sec]
14:51:57 [Defense] Shields: [62%] Cap: [1%] Shield Booster: [1] activated
14:51:59 [Defense] Shields: [62%] Cap: [1%] Shield Booster: [1] activated
14:52:35 [Panic] We have warped off:  My ShipType: [Drake Navy Issue] My ShipName [Buhu]
14:52:35 [Panic] Docking with [Veisto V - Moon 4 - Propel Dynamics Factory][0 AU away]
14:52:39 [Panic] Entered a station, lower panic mode
14:52:40 [Panic] We're in a station, resume mission
14:52:40 [Panic] We have recovered, resume mission
14:52:41 [CombatMissionsBehavior] Setting Destination to 1st bookmark from AgentID: 3016838 with
[Encounter] in the title
14:52:41 [TravelerDestination.MissionBookmarkDestination] Destination set to mission bookmark
[Encounter - Veisto]
14:52:43 [TravelerDestination.BookmarkDestination] This is not the destination station, undocking

But he stays at station and is not undocking.

**Comment by ISeeDEDPpl** [comment]
odd.
the next line (after alot of comments) is:
Cache.Instance.DirectEve.ExecuteCommand(DirectCmd.CmdExitStation);
which simply tells DirectEVE to exit the station...

is it possible that the session change or cooldown hasnt been completed yet (we probably need to pay more attention to that tbh)?

**Comment by kn0xv1lle** [comment]
Was That a question or just a thought about the Problem? ;)

**Comment by Pluckyduck** [comment]
ISDP, that is correct, it is exiting station before Client is ready to exit.

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/26d1bce51268c6fe6f0ca6a4e64be353555b4e76
