### ISSUE TITLE
Speed Tanking problem

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#440]
Problem is when warping to a mission and enemy npc are in range he doesn t start speed tanking and stand still on spot.
When every npc is out of range he react correctly and burns towards them and start a orbit.
Using newest Bleeding Edge

18:36:35 [CombatMissionCtrl.WaitUntilTargeted [timeout: 15]] We have been targeted!
18:36:35 [CombatMissionCtrl] Finished Action.WaitUntilTargeted [timeout: 15]
18:36:35 [CombatMissionCtrl] Starting Action.ClearPocket
18:36:37 [Combat] Activating weapon  [1] on [Pithatis Executor][ID: [truncatedID]40650][21k away]
18:36:38 [Combat] Targeting high value target [Pithatis Executor][ID: [truncatedID]40649][25k away]
highValueTargets.Count [1]
18:36:41 [Combat] Activating painter [1] on [Pithatis Executor][ID: [truncatedID]40650][21k away]
18:36:42 [Drones] [4] Drones Launched
18:36:43 [Drones] Engaging [ 4 ] drones on [Pithatis Executor][ID: [truncatedID]40650]21k away]
18:36:50 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 3 ] minutes.
18:36:50 [Defense] Shields: [85%] Cap: [80%] Shield Booster: [1] activated
18:36:52 [Combat] Targeting high value target [Pithatis Executor][ID: [truncatedID]40658][27k away]
highValueTargets.Count [2]
18:36:54 [EntityCache.LockTarget] [TargetCombatants.HighValueTargetingMeEntity] tried to lock
[Pithatis Executor][26,63k][[truncatedID]40658][2] targets already, can retarget in [18]
18:36:55 [Drones] Engaging [ 4 ] drones on [Pithatis Executor][ID: [truncatedID]40649]25k away]

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge
