### ISSUE TITLE
Ignore not properly working - BleedingEdge

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#441]
http://pastebin.com/39z9uV2i

Check out these logs.

As you will see I have additions to Ignore List:
[CombatMissionCtrl.Ignore [add: Guristas Webifier] [add: Guristas Kyoukan]] Updated ignore list

While they are ignored, and not been removed or cleared yet:
[Combat] Targeting low value target [Guristas Kyoukan][ID: [truncatedID]46879][43k away] lowValueTargets.Count [1]

So they are still targeted while ignored, and my drones engaged them (have to confirm if drones are set aggresive or not).

**Comment by ISeeDEDPpl** [comment]
are their other scenarios where this occurs? narrowing this down to wtf is happening might take multiple different mission logs...

The low value target targeting stuff in Combat.CargetCombatants seems to check the IsIgnored status correctly and shouldn't be targeting anything that is on the ignored list, thus my confusion.

**Comment by ISeeDEDPpl** [comment]
this should no longer be an issue. please post logs if it re-occurs
