### ISSUE TITLE
auto clear pocket if gate is locked, ****low**** level priority!

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#444]
easy fix is to create xml but dont know if this is the only mission that does this.

rouge drones harrassment low level misson

[Cleanup] Content of modal window (HTML): [This gate is locked! There are synchronized gate scramblers on
all hostile entities in this deadspace pocket. Unless you are physically inside one of them to unscramble the signal, you
must simply clear the vicinity of enemy ships. So grab your guns.]

**Comment by ISeeDEDPpl** [comment]
done, needs testing. 

hrm, ok, 1st try did not work... Ill look at this again in a few days.

**Comment by Pluckyduck** [comment]
hard one to find but will continue to monitor, cause am dedicated like that!

**Comment by ISeeDEDPpl** [comment]
fixed.
