### ISSUE TITLE
##request## random delay timer for auto restart on lag disconnection

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#445]
Can we get a random delay timer before restarting on a lag disconnect.  nothing like 5 or more clients logging in at the same time. 2 -5 minutes in the random high/low.

**Comment by ISeeDEDPpl** [comment]
see time.cs:
public int ReLogDelayMinimum_seconds = 35;                    //DO NOT set this lower than 20 or so seconds!
public int ReLogDelayMaximum_seconds = 60;

**Comment by Pluckyduck** [comment]
thanks, seems to be working Great!
