### ISSUE TITLE
CTD when questor is set to NOT autostart

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#446]
questor is set to not autostart before completing a mission and it will CTD when going to the idle state.

**Comment by ISeeDEDPpl** [comment]
is this repeatable for you? Ive been disabling autostart all night on and off and have not had this happen (repeatably)...

I actually did have eve ctd once but thought it was EVE not questor =/

**Comment by ghost** [comment]
this seems to be fixed
