### ISSUE TITLE
Questor loots contraband

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#447]
Q is looting contraband

**Comment by Grafalck** [comment]
confirm, exact same problem for me

**Comment by Pluckyduck** [comment]
logs, they gets created......they need to be shared......

**Comment by ISeeDEDPpl** [comment]
enable debugLootWrecks please
if its doing it during a mission it should happily scoop drugs from a jetcan when in the Combathelper state (same salvage routine runs for both)
if you reproduce it in your home system ( Station to safespot or planet) you should be fine its only gates that the customs NPCs hit your standings

**Comment by ISeeDEDPpl** [comment]
fixed.
