### ISSUE TITLE
Setting <lootContainer></lootContainer> not working

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#452]
With None audit log container, and properly named, will not unload loot into container.

with settings <code>`<lootContainer>loot</lootContainer>`</code> and Giant Freight container named loot. Nothing is moved when unloadloot is attempted.

<code>`21:39:22 [DebugHangarsBehavior] UnloadLoot: Begin
21:39:23 [UnloadLoot.MoveAmmo] Stacking Item Hangar
21:39:28 [UnloadLoot.MoveLoot] Moving [10] items from CargoHold to LootHangar
21:39:37 [Cache.StackLootHangar] Loot Container window named: [ ('InventoryStation', None) ] was found and its contents are being stacked
21:39:37 [DebugHangarsBehavior.Unloadloot] CharacterMode: [Combat Missions], AfterMissionSalvaging: [True], DebugHangarsBehaviorState: [Idle]`</code>

When Open LootContainer is pressed:
<code>`21:29:41 [QuestorUI] Close LootContainer button was pressed
21:29:42 [DebugHangars] DebugHangarsState.CloseLootContainer:
21:29:42 [DebugHangars] DebugInventoryWindows: *** Start Listing Inventory Windows ***
21:29:42 [DebugHangars] ---------------------------- #[1]
21:29:42 [DebugHangars] DebugInventoryWindows.Name: [('InventoryStation', None)]
21:29:42 [DebugHangars] DebugInventoryWindows.Type: [form.InventoryPrimary]
21:29:42 [DebugHangars] DebugInventoryWindows.Caption: [Inventory]
21:29:42 [DebugHangars] DebugInventoryWindows: *** End Listing Inventory Windows ***`</code>

**Comment by ISeeDEDPpl** [comment]
this should now be fixed.
