### ISSUE TITLE
Not Closest = True mission action messed up

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#454]
<Dim>         `<action name="Kill">`
<Dim>           `<parameter name="Target" value="Kruul's Pleasure Gardens" />`
<Dim>           `<parameter name="NotClosest" value="true" />`
<Dim>           `<parameter name="NumberToIgnore" value="1" />`
<Dim>         `</action>`

**Comment by ISeeDEDPpl** [comment]
you have to surround XML with a tilde or backtick (same key), `

**Comment by ISeeDEDPpl** [comment]
fixed, but you probably want
`<action name="Kill">`
`<parameter name="Target" value="Kruul's Pleasure Gardens" />`
`<parameter name="NumberToIgnore" value="1" />`
`</action>`

which would ignore the closest one and kill the furthest one away,
