### ISSUE TITLE
Questor doesnt recall drones when set state to GotoBase in middle of mission

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#455]

**Comment by ISeeDEDPpl** [comment]
it is supposed to...
can you reproduce this when you are NOT scrambled please?

**Comment by ISeeDEDPpl** [comment]
ping.

**Comment by ISeeDEDPpl** [comment]
...

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/cbdcc1ca6ae108abc305532d708acaf0ec21f1b7
