### ISSUE TITLE
last BE, hung at trainer 

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#457]
Auto log in did as supposed to.

did the skills check.  stop at that point. 

I manually added training and then had to move to CombatMissionBehavior

Running steady with no complaints found.

**Comment by Pluckyduck** [comment]
updated skill training and restarted, goes right into CombatMissionBehavior.

**Comment by ISeeDEDPpl** [comment]
fixed, I hope. pls test

**Comment by Pluckyduck** [comment]
10:06:50 [SkillTrainer] Note: SkillTrainer just entered the Error State. There is likely a missing skill plan or
broken contents of the skillplan!

spams but never keeps going past this point.
