### ISSUE TITLE
last transfertolive.bat not running.

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#458]
line 6 and line 10 seem to be reversed

i have a local copy i use and i replaced with and works fine.

Also, I modified line 54 to put into correct build folder

**Comment by Pluckyduck** [comment]
C:\Program Files (x86)\InnerSpace.NET Programs

is my location for the folder.  I do think that is what caused some of the problems.

**Comment by ISeeDEDPpl** [comment]
fixed.

**Comment by Pluckyduck** [comment]
thanks
