### ISSUE TITLE
Dedicated salvager full cargo.

### ISSUE THREAD

**Issue by sigmastk** [ISeeDEDPpl/Questor#459]
I have noticed bug with dedicated salvager. I have setting in char.xml  
<reserveCargoCapacity>80</reserveCargoCapacity>

When dedicated salvager reaches whole cargo - reserveCargoCapacity, it stuck in this loop:

`
21:00:02 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:00:02 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:00:02 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:00:03 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:00:03 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:00:03 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:00:03 [Salvage] Opening container [Cargo Container][1k][ID: [truncatedID]22072]
21:00:04 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:00:04 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:00:04 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:00:04 [Salvage.ActivateSalvagers] Debug: if (wrecks.Count == 0)
21:00:05 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:00:05 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:00:05 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:00:06 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:00:06 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:00:06 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:00:07 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:00:07 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:00:07 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
`

But, when I manually loot one more item, it recognize that it has full cargo and go to base:

`
21:02:04 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:02:04 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:02:05 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:02:05 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:02:05 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:02:05 [Salvage] Opening container [Cargo Container][1k][ID: [truncatedID]22072]
21:02:06 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:02:06 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:02:06 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:02:06 [Salvage.ActivateSalvagers] Debug: if (wrecks.Count == 0)
21:02:07 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:02:07 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:02:07 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:02:08 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:02:08 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:02:08 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:02:09 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:02:09 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:02:09 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
21:02:09 [Salvage.ActivateSalvagers] Debug: if (wrecks.Count == 0)
21:02:10 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
21:02:10 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
21:02:10 [DedicatedBookmarkSalvageBehavior.Salvage] We are full, go to base to unload
21:02:11 [DedicatedBookmarkSalvagerBehavior] Destination: [Base]
21:02:11 [TravelerDestination.StationDestination] Destination set to [Base]
21:02:16 [Traveler] Setting destination to [Tsukuras]
21:02:18 [Traveler] Warping to [Base][20.61 AU away]
21:03:02 [Traveler] Jumping to [Base]
21:03:21 [TravelerDestination.StationDestination] Warp to and dock at [Base][19.61 AU away]
21:04:04 [TravelerDestination.StationDestination] Dock at [Base] which is [0k away]
21:04:08 [TravelerDestination.StationDestination] Arrived in station
21:04:09 [DedicatedBookmarkSalvagerBehavior] UnloadLoot: Begin
`

**Comment by sigmastk** [comment]
Hi, here is more logs with new build:

This is point when it reached "full cargo":

`
22:43:15 [Salvage] Opening container [Cargo Container][0k][ID: [truncatedID]88594]
22:43:15 [Salvage.LootWrecks] Looting container [Cargo Container][0k][ID: [truncatedID]88594], [1] valuable items
22:43:16 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
22:43:16 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
22:43:16 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:43:16 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
22:43:16 [Salvage.ActivateSalvagers] Debug: if (wrecks.Count == 0)
`

And this is loop until last line where it says wasnt in warp fro 20ish minutes ...

`
22:46:06 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:46:06 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
22:46:07 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
22:46:07 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
22:46:07 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:46:07 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
22:46:07 [Salvage.ActivateSalvagers] Debug: if (wrecks.Count == 0)
22:46:08 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
22:46:08 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
22:46:08 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:46:08 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
22:46:09 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
22:46:09 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
22:46:09 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:46:09 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
22:46:09 [Salvage] Opening container [Cargo Container][1k][ID: [truncatedID]84271]
22:46:10 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
22:46:10 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
22:46:10 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:46:10 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
22:46:10 [Salvage.ActivateSalvagers] Debug: if (wrecks.Count == 0)
22:46:11 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
22:46:11 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
22:46:11 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:46:11 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
22:46:12 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
22:46:12 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
22:46:12 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:46:12 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
22:46:13 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
22:46:13 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
22:46:13 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:46:13 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
22:46:13 [Salvage.ActivateSalvagers] Debug: if (wrecks.Count == 0)
22:46:14 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
22:46:14 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
22:46:14 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:46:14 [DedicatedBookmarkSalvagerBehavior] salvage: we have more wrecks to salvage
22:46:15 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
22:46:15 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
22:46:15 [DedicatedSalvager] CurrentCapacity [690.890625] UsedCapacity [610.7][80]
22:46:15 [DedicatedBookmarkSalvagerBehavior] It has been over 20 min since we were last in warp. Assuming something went wrong: setting GoToBase
22:46:16 [DedicatedBookmarkSalvagerBehavior] Destination: [Base]
22:46:16 [TravelerDestination.StationDestination] Destination set to [Base]
`

**Comment by ISeeDEDPpl** [comment]
fixed
