### ISSUE TITLE
<optimalRange> for turret users

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#460]
Seems Questor does not reference the optimalRange settings for turrets. When I land on field, I stay where I land, unless I am completely out of range. Then I move into range for target by pulsing my ab (which is odd). 

I tried to debug navigateongrid, but nothing outputs for it. Let me know what logs you would like.

**Comment by Pluckyduck** [comment]
if you updated your setting file, make sure you updated your AB/MWD cap setting.  Default is 55.

**Comment by ghost** [comment]
I can confirm the default AB/MWD setting is 55 and 5000 for distance. When I noticed the pulsing AB, my cap was at 75%+.

**Comment by ISeeDEDPpl** [comment]
fixed.
