### ISSUE TITLE
<optimalRange> on closest entity rather than primaryweapontarget

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#461]
Seems after the latest batch of commits last night, the optimalRange setting is keeping at range the closest entity, (npc frigates mostly) rather than the primaryweapontarget.

Also, for frigates, the optimalRange settings should be ignored and instead we should have it align to celestial so as to not spin in circles in space.

**Comment by ISeeDEDPpl** [comment]
fix needs testing.

**Comment by ISeeDEDPpl** [comment]
fixed?

**Comment by ghost** [comment]
From my observation, it is still wanting to keep at range closest targets and not the target my turrets are shooting.

**Comment by ISeeDEDPpl** [comment]
hrm. and the log with debugNavigateOnGrid confirms this? The code looks right... =/

**Comment by ghost** [comment]
debugNavigateOnGrid produces nothing

**Comment by ISeeDEDPpl** [comment]
nothing?! 
it should give at least a: "NavigateIntoRange Started" (and probably more) when it lands on grid...
it will only run through NavigateOnGrid every 15-30 seconds as we do not want to spam movement commands (approach/orbit, etc)

**Comment by ISeeDEDPpl** [comment]
alot has changed in the past few weeks. please confirm this is still a problem, or is resolved...

**Comment by ISeeDEDPpl** [comment]
...

**Comment by ISeeDEDPpl** [comment]
I do not bieleve this to still be an issue. if you can reproduce it please re-open.
