### ISSUE TITLE
Done Action Issue

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#462]
In the latest BE: 2e98e1d5d2c2013d59fa13a6625983510247c971
When i do in frigate class ship low lvl mission, when Q go to Action Done sometimes hang up and stay in place or sometimes goes ahead...
On console write: Starting Done action or something like that and after this Wallet Ballance ....

**Comment by ISeeDEDPpl** [comment]
i think I found/fixed the issue... please attempt to reproduce with: 
https://github.com/ISeeDEDPpl/Questor/commit/8a345bcc17a3e2af6820a0e3338c98a47595f6cb
