### ISSUE TITLE
Issue with skilltrainer

### ISSUE THREAD

**Issue by sigmastk** [ISeeDEDPpl/Questor#463]
I have noticed issue with BE and skilltrainer. It works fine when skills are inserted. But when it need to insert skill it does nothing (just skip them)

Skills are in local hangar (toon is using local hangar as ammo hangar - grabing ammo w/o problems).

Here is my skillplan-my toon name.txt :

`
Mechanics III
Weapon Upgrades I
Weapon Upgrades II
Missile Launcher Operation I
Missile Launcher Operation II
Energy Grid Upgrades I
Energy Grid Upgrades II
Tactical Shield Manipulation I
Shield Operation I
Shield Operation II
Light Missiles I
Shield Compensation I
Jury Rigging I
Missile Launcher Operation III
Caldari Frigate III
Shield Operation III
Caldari Destroyer I
Caldari Destroyer II
Caldari Destroyer III
Weapon Upgrades III
Caldari Cruiser I
Caldari Cruiser II
Caldari Cruiser III
Target Management I
Energy Grid Upgrades III
Drones I
Scout Drone Operation I
Afterburner I
Shield Upgrades I
Jury Rigging II
Jury Rigging III
Launcher Rigging I
Shield Rigging I
Hull Upgrades I
Hull Upgrades II
Drones II
Target Management II
Target Management III
Drones III
Drones IV
Scout Drone Operation II
Scout Drone Operation III
Shield Management I
Shield Management II
Shield Management III
Target Painting I
Capacitor Management I
Capacitor Management II
Capacitor Management III
Capacitor Systems Operation I
Capacitor Systems Operation II
Capacitor Systems Operation III
Weapon Upgrades IV
Heavy Missiles I
Heavy Missiles II
Heavy Missiles III
Missile Bombardment I
Missile Bombardment II
Missile Bombardment III
Missile Bombardment IV
Missile Launcher Operation IV
Missile Projection I
Missile Projection II
Missile Projection III
Rapid Launch I
Rapid Launch II
Rapid Launch III
Rapid Launch IV
Target Navigation Prediction I
Target Navigation Prediction II
Target Navigation Prediction III
Warhead Upgrades I
Warhead Upgrades II
Warhead Upgrades III
Acceleration Control I
Acceleration Control II
Evasive Maneuvering I
Evasive Maneuvering II
Warp Drive Operation I
Warp Drive Operation II
Warp Drive Operation III
Cybernetics I
Cybernetics II
Cybernetics III
Shield Operation IV
Kinetic Shield Compensation I
Kinetic Shield Compensation II
Shield Upgrades II
Signature Analysis I
`

Toon has finished Shield Operation III (16th on the list) and need to insert rest of the skills (first one is Caldari Destroyer I). It does not import any of them, it just add to queue Weapon Upgrades IV which is 53rd on the list (but it has it in head)

Here are logs when I turn on debugging for SkillTrainer :  <debugSkillTraining>True</debugSkillTraining> 

`
MissionsPath is: [C:\Program Files (x86)\InnerSpace\.NET Programs\Caldari Missions 1 Level]
23:28:25 [Settings] Loothangar [ItemsHangar]
23:28:25 [Settings] AmmoHangar [ItemHangar]
23:28:25 [Settings] Found only one agent in your character XML: MultiAgentSupport is [False]
23:28:25 [Settings] Faction Fittings defined. Fitting manager will be used when appropriate.
23:28:25 [Settings] Loading Mission Fittings
23:28:25 [Settings] Mission Fittings now has [0] entries
23:28:25 [Settings] Loading Mission Blacklist
23:28:25 [Settings] Mission Blacklist now has [12] entries
23:28:25 [Settings] Loading Mission Greylist
23:28:25 [Settings] Mission Greylist now has [0] entries
23:28:25 [Settings] Loading Faction Blacklist
23:28:25 [Settings] Missions from the faction [Caldari State] will be declined
23:28:25 [Settings] Faction Blacklist now has [1] entries
23:28:25 [Settings] [1] Done Loading Settings from [C:\Program Files (x86)\InnerSpace\.NET Programs\Mi_MyEVECharacterNameRedacted_.xml]
23:28:25 [Cache.CurrentAgent] [ Agent Name ] AgentID [ 00000000 ]
23:28:26 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 2 ] minutes.
23:28:26 [Questor] Checking: Current time [10/17/2013 23:28:26] StopTimeSpecified [True] StopTime [ 10/18/2013 23:00:00] ManualStopTime = 10/18/2013 09:26:44
23:28:26 [Questor.SkillQueueCheck] Current Training Queue Length is [00:00:00]
23:28:26 [Questor.SkillQueueCheck] Training Queue currently has room. [24 hours free]
23:28:26 [SkillTrainer] Starting SkillTrainer
23:28:26 [SkillTrainer] It is Time to Start SkillTrainer again...
23:28:28 [SkillTrainer] LoadPlan
23:28:28 [importSkillPlan] Loading SkillPlan from [C:\Program Files (x86)\InnerSpace\.NET Programs\skillPlan-Mi_MyEVECharacterNameRedacted_.txt]
23:28:29 [SkillTrainer] ReadCharacterSheetSkills
23:28:29 [readMyCharacterSheetSkills] if (!MyCharacterSheetSkills.Any())
23:28:30 [SkillTrainer] ReadCharacterSheetSkills
23:28:30 [Skills.MyCharacterSheetSkills] [2] SkillName [Caldari Frigate] lvl [3] SkillPoints [19918] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [3] SkillName [Jury Rigging] lvl [1] SkillPoints [500] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [4] SkillName [Social] lvl [3] SkillPoints [20640] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [5] SkillName [Negotiation] lvl [2] SkillPoints [2829] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [6] SkillName [Diplomacy] lvl [2] SkillPoints [1415] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [7] SkillName [Connections] lvl [3] SkillPoints [24000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [8] SkillName [Mining] lvl [2] SkillPoints [1415] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [9] SkillName [Mechanics] lvl [3] SkillPoints [8000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [10] SkillName [Shield Compensation] lvl [1] SkillPoints [500] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [11] SkillName [Science] lvl [3] SkillPoints [8000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [12] SkillName [Astrometrics] lvl [1] SkillPoints [750] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [13] SkillName [Power Grid Management] lvl [3] SkillPoints [8000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [14] SkillName [Navigation] lvl [3] SkillPoints [8000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [15] SkillName [Shield Operation] lvl [3] SkillPoints [8000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [16] SkillName [Tactical Shield Manipulation] lvl [1] SkillPoints [1000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [17] SkillName [Energy Grid Upgrades] lvl [2] SkillPoints [2829] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [18] SkillName [CPU Management] lvl [3] SkillPoints [8000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [19] SkillName [Gunnery] lvl [2] SkillPoints [1415] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [20] SkillName [Small Hybrid Turret] lvl [3] SkillPoints [8000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [21] SkillName [Weapon Upgrades] lvl [3] SkillPoints [16141] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [22] SkillName [Missile Launcher Operation] lvl [3] SkillPoints [8000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [23] SkillName [Light Missiles] lvl [3] SkillPoints [16000] inTraining [False]
23:28:30 [Skills.MyCharacterSheetSkills] [24] SkillName [Spaceship Command] lvl [3] SkillPoints [8000] inTraining [False]
23:28:31 [SkillTrainer] CheckTrainingQueue
23:28:31 [SkillPlan.CheckTrainingQueue:] if (Cache.Instance.DirectEve.Skills.AreMySkillsReady)
23:28:31 [SkillPlan.CheckTrainingQueue:] Current Training Queue Length is [00:00:00]
23:28:31 [SkillPlan.CheckTrainingQueue:] Training Queue currently has room. [24 hours free]
23:28:31 [AddPlannedSkillToQueue] SkillPlan: skill [Mechanics] level [3]
23:28:31 [AddPlannedSkillToQueue] CharacterSheet: [Mechanics] is already at the planned level
23:28:31 [AddPlannedSkillToQueue] SkillPlan: skill [Weapon Upgrades] level [4]
23:28:31 [AddPlannedSkillToQueue] CharacterSheet: [Weapon Upgrades] needs to be training now.
23:28:34 [Questor] Start Mission Behavior
23:28:35 [Statistics: WriteSessionLogStarting] Writing session data to [ C:\Program Files (x86)\InnerSpace\.NET Programs\log\Mi_MyEVECharacterNameRedacted_\Mi_MyEVECharacterNameRedacted_.Sessions.log ]
23:28:35 [CombatMissionsBehavior] Random start delay of [3] seconds
23:28:39 [RunOnceAfterStartup] IterateShipTargetValues - Loading [C:\Program Files (x86)\InnerSpace\.NET Programs\ShipTargetValues.xml]
23:28:39 [RunOnceAfterStartup] IterateInvTypes - Loading [C:\Program Files (x86)\InnerSpace\.NET Programs\InvTypes.xml]
23:28:40 [RunOnceAfterStartup] IterateUnloadLootTheseItemsAreLootItems - Loading [C:\Program Files (x86)\InnerSpace\.NET Programs\UnloadLootTheseItemsAreLootItems.xml]
`

**Comment by sigmastk** [comment]
Another strange behaviour. I have reordered drones skill to be Drones I, II , III and put Weapon Upgrades IV to end of queue.

I placed Drones I to queue at the end (there is 7ish hrs left), apply. Run questor, and it adds Weapon Upgrades to IV right after ...

here are logs :

`
23:47:39 [Questor.SkillQueueCheck] Current Training Queue Length is [16:16:35]
23:47:39 [Questor.SkillQueueCheck] Training Queue currently has room. [7.72 hours free]
23:47:39 [SkillTrainer] Starting SkillTrainer
23:47:39 [SkillTrainer] It is Time to Start SkillTrainer again...
23:47:41 [SkillTrainer] LoadPlan
23:47:41 [importSkillPlan] Loading SkillPlan from [C:\Program Files (x86)\InnerSpace\.NET Programs\skillPlan-Mi_MyEVECharacterNameRedacted_.txt]
23:47:42 [SkillTrainer] ReadCharacterSheetSkills
23:47:42 [readMyCharacterSheetSkills] if (!MyCharacterSheetSkills.Any())
23:47:43 [SkillTrainer] ReadCharacterSheetSkills
23:47:43 [Skills.MyCharacterSheetSkills] [2] SkillName [Caldari Frigate] lvl [3] SkillPoints [19918] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [3] SkillName [Jury Rigging] lvl [1] SkillPoints [500] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [4] SkillName [Social] lvl [3] SkillPoints [20640] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [5] SkillName [Negotiation] lvl [2] SkillPoints [2829] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [6] SkillName [Diplomacy] lvl [2] SkillPoints [1415] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [7] SkillName [Connections] lvl [3] SkillPoints [24000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [8] SkillName [Mining] lvl [2] SkillPoints [1415] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [9] SkillName [Mechanics] lvl [3] SkillPoints [8000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [10] SkillName [Shield Compensation] lvl [1] SkillPoints [500] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [11] SkillName [Caldari Destroyer] lvl [0] SkillPoints [103] inTraining [True]
23:47:43 [Skills.MyCharacterSheetSkills] [12] SkillName [Science] lvl [3] SkillPoints [8000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [13] SkillName [Astrometrics] lvl [1] SkillPoints [750] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [14] SkillName [Power Grid Management] lvl [3] SkillPoints [8000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [15] SkillName [Navigation] lvl [3] SkillPoints [8000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [16] SkillName [Shield Operation] lvl [3] SkillPoints [8000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [17] SkillName [Tactical Shield Manipulation] lvl [1] SkillPoints [1000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [18] SkillName [Energy Grid Upgrades] lvl [2] SkillPoints [2829] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [19] SkillName [CPU Management] lvl [3] SkillPoints [8000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [20] SkillName [Gunnery] lvl [2] SkillPoints [1415] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [21] SkillName [Small Hybrid Turret] lvl [3] SkillPoints [8000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [22] SkillName [Drones] lvl [0] SkillPoints [0] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [23] SkillName [Weapon Upgrades] lvl [3] SkillPoints [16536] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [24] SkillName [Missile Launcher Operation] lvl [3] SkillPoints [8000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [25] SkillName [Light Missiles] lvl [3] SkillPoints [16000] inTraining [False]
23:47:43 [Skills.MyCharacterSheetSkills] [26] SkillName [Spaceship Command] lvl [3] SkillPoints [8000] inTraining [False]
23:47:44 [SkillTrainer] CheckTrainingQueue
23:47:44 [SkillPlan.CheckTrainingQueue:] if (Cache.Instance.DirectEve.Skills.AreMySkillsReady)
23:47:44 [SkillPlan.CheckTrainingQueue:] Current Training Queue Length is [16:16:28]
23:47:44 [SkillPlan.CheckTrainingQueue:] Training Queue currently has room. [7.73 hours free]
23:47:44 [AddPlannedSkillToQueue] SkillPlan: skill [Mechanics] level [3]
23:47:44 [AddPlannedSkillToQueue] CharacterSheet: [Mechanics] is already at the planned level
23:47:44 [AddPlannedSkillToQueue] SkillPlan: skill [Weapon Upgrades] level [4]
23:47:44 [AddPlannedSkillToQueue] Skill in the queue [Caldari Destroyer] InTraining [False] Level [1] SkillPoints[0] SkillTimeConstant[0] Planned Skill[Weapon Upgrades] Planned Level[4]
23:47:44 [AddPlannedSkillToQueue] Skill in the queue [Caldari Destroyer] InTraining [False] Level [2] SkillPoints[0] SkillTimeConstant[0] Planned Skill[Weapon Upgrades] Planned Level[4]
23:47:44 [AddPlannedSkillToQueue] Skill in the queue [Caldari Destroyer] InTraining [False] Level [3] SkillPoints[0] SkillTimeConstant[0] Planned Skill[Weapon Upgrades] Planned Level[4]
23:47:44 [AddPlannedSkillToQueue] Skill in the queue [Energy Grid Upgrades] InTraining [False] Level [3] SkillPoints[0] SkillTimeConstant[0] Planned Skill[Weapon Upgrades] Planned Level[4]
23:47:44 [AddPlannedSkillToQueue] Skill in the queue [Drones] InTraining [False] Level [1] SkillPoints[0] SkillTimeConstant[0] Planned Skill[Weapon Upgrades] Planned Level[4]
23:47:44 [AddPlannedSkillToQueue] CharacterSheet: [Weapon Upgrades] needs to be training now.
23:47:47 [Questor] Start Mission Behavior
23:47:48 [Statistics: WriteSessionLogStarting] Writing session data to [ C:\Program Files (x86)\InnerSpace\.NET Programs\log\Mi_MyEVECharacterNameRedacted_\Mi_MyEVECharacterNameRedacted_.Sessions.log ]
23:47:48 [CombatMissionsBehavior] Random start delay of [4] seconds
23:47:52 [RunOnceAfterStartup] IterateShipTargetValues - Loading [C:\Program Files (x86)\InnerSpace\.NET Programs\ShipTargetValues.xml]
23:47:52 [RunOnceAfterStartup] IterateInvTypes - Loading [C:\Program Files (x86)\InnerSpace\.NET Programs\InvTypes.xml]
23:47:52 [RunOnceAfterStartup] IterateUnloadLootTheseItemsAreLootItems - Loading [C:\Program Files (x86)\InnerSpace\.NET Programs\UnloadLootTheseItemsAreLootItems.xml]
23:47:52 [RunOnceAfterStartup] Running Innerspace command: timedcommand 100 windowtaskbar on Mi_MyEVECharacterNameRedacted_
`

**Comment by ISeeDEDPpl** [comment]
these issues are likely resolved now. If you continue to have problems please open a new issue w logs as these seem to be resolved. any misbehavior is likely due to a different (but related?) bug.
