### ISSUE TITLE
Done Action Issue - still exist

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#464]
In the latest BE: bb40b3db89e79d7bba4725a6e71257762526d811
When i do in frigate class ship low lvl mission, when Q go to Action Done sometimes hang up and stay in place or sometimes goes ahead...
On console write: Starting Done action or something like that and after this Wallet Ballance ....

**Comment by ISeeDEDPpl** [comment]
doh.
please update to latest bleedingedge. Add the debug setting: 
`<debugDoneAction>true</debugDoneAction>`
and reproduce the issue. I need to know exactly where its getting stuck to fix it.

**Comment by oldmeat** [comment]
I download the latest BE and i set <debugDoneAction>true</debugDoneAction>. 
Now i did about 20 missions and this issue not appear. 
I close this issue, when he appear i create new with new logs.
Thx
