### ISSUE TITLE
Search loot - issue

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#465]

**Comment by oldmeat** [comment]
When Q searching wrecks in loot action, one by one, always fly to outermost wreck.

**Comment by ISeeDEDPpl** [comment]
are you saying it flys to the outermost wreck first?
if you want to loot only a particular wreck (cetain item) use lootitem!
loot will loot the field. (ALL unlooted wrecks!)

We can change the order in which the wrecks are checked if you like, but it SHOULD be doing closest first.

**Comment by oldmeat** [comment]
I noticed this bug, because i have some errors in my xml mission file. When Q go to wreck use lootitem option and not find item he check all other wrecks. But he always go to outermost wreck, not one time, always. 
Example: Q not find item go to outermost wreck, check wreck - not find item, go outermost wreck - not find item, go outermost wreck. This is very odd behavior :)
Probably when mission xml is ok, this bug not exist. I do not test after mission salvaging yet and i don't know how Q behavior in this state. I'll be test this day after tomorrow.

**Comment by oldmeat** [comment]
Fix in  24d531e5ac9c4cbf51908a7e6f5f2831ef6bd46e
