### ISSUE TITLE
After Panic not shooting

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#468]
In the BE: bb40b3db89e79d7bba4725a6e71257762526d811
When Q back to mission from station after panic state, targeting properly but not shoot and doing nothing

**Comment by ISeeDEDPpl** [comment]
odd, debugGetBestTarget? anything funny in the logs?

**Comment by oldmeat** [comment]
In the latest BE: 6851caa7bd8d36593a264af01f4487c0e7949ba4
When i GetBestTarget set to true, after Panic Q open fire after 30 seconds.
I have do more tests.
