### ISSUE TITLE
Heavy orbit spam when hitting structures

### ISSUE THREAD

**Issue by drpetarvojvodic** [ISeeDEDPpl/Questor#47]
Sorry about the ccc it was a typo:) 

What i wanted to say is:

Whether hitting Drone structure or pleasure house in Damsel in destres it spams orbit every single second in the log. It's a big problem. i can paste the logs if you can use it.

**Comment by ISeeDEDPpl** [comment]
pls do. at least a small section.... it should spam every 15(ish) seconds

the LCOs it is getting away from have a HUGE 'docking ring' for lack of a better term... area around the actual structure where you are still at 0. It does take a min to get outside their radius... I may need to special case those as something we ignore being close to but I would like to avoid that as we may get stuck against one of them if we totally ignore em.

**Comment by drpetarvojvodic** [comment]
here it is. I ended up using your older build from a week ago where that problem is not happening.. Hope this helps

02:44:35 MissionController.Kill [target: Drone Structure]: StartOrbiting: Target in range
02:44:36 MissionController.Kill [target: Drone Structure]: StartOrbiting: Target in range
02:44:37 MissionController.Kill [target: Drone Structure]: StartOrbiting: Target in range
02:44:38 MissionController.Kill [target: Drone Structure]: StartOrbiting: Target in range
02:44:39 MissionController.Kill [target: Drone Structure]: StartOrbiting: Target in range
02:44:40 MissionController.Kill [target: Drone Structure]: StartOrbiting: Target in range
02:44:41 MissionController.Kill [target: Drone Structure]: StartOrbiting: Target in range
02:44:42 MissionController.Kill [target: Drone Structure]: StartOrbiting: Target in range
02:44:43 MissionController.Kill [target: Drone Structure]: StartOrbiting: Target in range
....
and
05:39:38 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: Reload if [True] && [0] == 0 AND [6695] < [109000]
05:39:46 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:47 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:49 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:50 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:51 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:52 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:53 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:54 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:55 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:56 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:57 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range
05:39:58 MissionController.Kill [target: Kruul's Pleasure Gardens] [breakonattackers: True]: StartOrbiting: Target in range

**Comment by ISeeDEDPpl** [comment]
console log spam fixed. 

https://github.com/ISeeDEDPpl/Questor/commit/e07698b2ca851d43a7e2dca5071840119dfa5219
