### ISSUE TITLE
After Mission Salvaging not working

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#470]
In the latest BE: b97c046150391fdde601989368240a2d8f67ee58

Q go to wrecks, go to nearest wreck and stoping doing nothing. 

logs:

13:22:54 [Arm.ActivateSalvageShip] Done
13:22:58 [CombatMissionsBehavior.BeginAftermissionSalvaging] Salvaging at first oldest bookmarks
13:22:58 [TravelerDestination.BookmarkDestination] Destination set to bookmark [ xxx]
13:23:02 [TravelerDestination.BookmarkDestination] This is not the destination station, undocking
13:23:20 [TravelerDestination.BookmarkDestination] Warping to bookmark [Salvage: xxx][17,54 AU away]
13:24:16 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [Salvage: xxx]
13:24:17 [CombatMissionsBehavior: Salvage] Opening Cargohold of active ship: waiting [3sec]
13:24:20 [Salvage.NavigateIntorangeOfWrecks] Approaching [Caldari Navy Raven Wreck] which is [13k away]
13:24:44 [Salvage.NavigateIntorangeOfWrecks] Stop ship, ClosestWreck [1329] is in scooprange + [1790] and we were approaching
13:25:00 [Salvage.NavigateIntorangeOfWrecks] Approaching [Caldari Navy Raven Wreck] which is [3k away]
13:25:25 [Salvage.NavigateIntorangeOfWrecks] Stop ship, ClosestWreck [1639] is in scooprange + [1790] and we were approaching
13:26:26 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 2 ] minutes.
13:27:26 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 3 ] minutes.

i set debugSalvage on true.

13:28:16 [CombatMissionsBehavior] salvage: attempting to open cargo hold
13:28:16 [CombatMissionsBehavior] salvage: done opening cargo hold
13:28:16 [CombatMissionsBehavior] salvage: attempting to open cargo hold
13:28:16 [CombatMissionsBehavior] salvage: done opening cargo hold
13:28:17 [CombatMissionsBehavior] salvage: attempting to open cargo hold
13:28:17 [CombatMissionsBehavior] salvage: done opening cargo hold
13:28:18 [CombatMissionsBehavior] salvage: attempting to open cargo hold
13:28:18 [CombatMissionsBehavior] salvage: done opening cargo hold
13:28:19 [CombatMissionsBehavior] salvage: attempting to open cargo hold
13:28:19 [CombatMissionsBehavior] salvage: done opening cargo hold
13:28:20 [CombatMissionsBehavior] salvage: attempting to open cargo hold
13:28:20 [CombatMissionsBehavior] salvage: done opening cargo hold
13:28:21 [CombatMissionsBehavior] salvage: attempting to open cargo hold
13:28:21 [CombatMissionsBehavior] salvage: done opening cargo hold

**Comment by ISeeDEDPpl** [comment]
fixed in latest targeting branch. 
If their are any targeting issues in that branch please open another issue for that.
As soon as the targeting branch is stable I want to fold it back into bleedingedge (and then fold bleedingedge back into experimental and master)
