### ISSUE TITLE
Mission Kill action not working on Targeting branch

### ISSUE THREAD

**Issue by sigmastk** [ISeeDEDPpl/Questor#472]
Targeting: 5a36b56a633dbedd7fdb942b652cc6daf85d9f0e

I have this issue spotted on several missions. Atm, on mission Lights Out LVL3.

I have turned on this debugging: `<debugKillAction>True</debugKillAction>`

Here are logs, if you need anything more, please reply here and I will try to fetch:

`
9:56:15 [Cache.SetmissionXmlPath] [C:\Program Files (x86)\InnerSpace\.NET Programs\Caldari Missions 3 Level\Lights Out-Gallente Federation.xml] not found.
19:56:15 [Cache.SetmissionXmlPath] [C:\Program Files (x86)\InnerSpace\.NET Programs\Caldari Missions 3 Level\Lights Out.xml] found!
19:56:15 [Cache] Using Settings Orbit distance [11000]
19:56:15 [Cache] Using Settings OptimalRange [0]
19:56:15 [-] -----------------------------------------------------------------
19:56:15 [-] -----------------------------------------------------------------
19:56:15 [CombatMissionCtrl] Mission Timer Currently At: [19] min
19:56:15 [CombatMissionCtrl] Max Range is currently: 45k
19:56:15 [-] -----------------------------------------------------------------
19:56:15 [-] -----------------------------------------------------------------
19:56:15 [CombatMissionCtrl] Pocket [0] loaded, executing the following actions
19:56:15 [CombatMissionCtrl] Action [ 1 ] Kill [target: Gallente Starbase Control Tower]
19:56:15 [CombatMissionCtrl] Action [ 2 ] Kill [target: Gallente Lieutenant]
19:56:15 [CombatMissionCtrl] Action [ 3 ] ClearPocket
19:56:15 [CombatMissionCtrl] Action [ 4 ] Done
19:56:15 [-] -----------------------------------------------------------------
19:56:15 [-] -----------------------------------------------------------------
19:56:15 [Statistics.ObjectStatistics] Logging info on the [89] objects in this pocket to [C:\Program Files (x86)\InnerSpace\.NET Programs\log\Op_MyEVECharacterNameRedacted_\PocketObjectStats\Op_MyEVECharacterNameRedacted_ - Lights Out - 0 - ObjectStatistics.csv]
19:56:16 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:16 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:16 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:16 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:16 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
19:56:17 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:17 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:17 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:17 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:17 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
19:56:18 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:18 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:18 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:18 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:18 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
19:56:18 [Combat] Initiating Orbit [Gallente Starbase Control Tower][at 11k][ID: [truncatedID]03662]
19:56:19 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:19 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:19 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:19 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:19 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
19:56:20 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:20 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:20 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:20 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:20 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
19:56:21 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:21 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:21 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:21 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:21 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
19:56:22 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:22 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:22 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:22 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:22 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
19:56:23 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 3 ] minutes.
19:56:23 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:23 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:23 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:23 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:23 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
19:56:24 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:24 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:24 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:24 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:24 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
19:56:25 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:25 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:25 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:25 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:25 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
19:56:26 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] targetNames [1][Gallente Starbase Control Tower]
19:56:26 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] proceeding to kill the target (this is spammy, but useful debug info)
19:56:26 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] Cache.Instance.PreferredPrimaryWeaponTarget =[ Gallente Starbase Control Tower ][[truncatedID]03662]
19:56:26 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Below (if any)
19:56:26 [CombatMissionCtrl[0].Kill [target: Gallente Starbase Control Tower]] PrimaryWeaponPriorityTargets Above (if any)
`

Also, on another char, diferent mission, it uses only Drones to kill target. He is not engaging it with primary weapon.

After panic, it does come back to misssion and then Questor is in ClearPocket Action, it does not even lock targets at all.

After another return to mission, it does target only one NPC and send only drones to it.

I have turned on this settings : 
`
<debugKillTargets>True</debugKillTargets>
<debugKillAction>True</debugKillAction>
<debugTargetCombatants>True</debugTargetCombatants>
`
This are logs I have collected:

`
20:05:30 [Cache.SetmissionXmlPath] [C:\Program Files (x86)\InnerSpace\.NET Programs\Caldari Missions 3 Level\Technological Secrets (1 of 3)-Thukker Tribe.xml] not found.
20:05:30 [Cache.SetmissionXmlPath] [C:\Program Files (x86)\InnerSpace\.NET Programs\Caldari Missions 3 Level\Technological Secrets (1 of 3).xml] found!
20:05:30 [Cache] Using Settings Orbit distance [5000]
20:05:30 [Cache] Using Settings OptimalRange [0]
20:05:30 [-] -----------------------------------------------------------------
20:05:30 [-] -----------------------------------------------------------------
20:05:30 [CombatMissionCtrl] Mission Timer Currently At: [28] min
20:05:30 [CombatMissionCtrl] Max Range is currently: 45k
20:05:30 [-] -----------------------------------------------------------------
20:05:30 [-] -----------------------------------------------------------------
20:05:30 [CombatMissionCtrl] Pocket [0] loaded, executing the following actions
20:05:30 [CombatMissionCtrl] Action [ 1 ] ClearPocket
20:05:30 [CombatMissionCtrl] Action [ 2 ] Loot [target: Cargo Container] [item: Mercenary Pilot]
20:05:30 [CombatMissionCtrl] Action [ 3 ] Done
20:05:30 [-] -----------------------------------------------------------------
20:05:30 [-] -----------------------------------------------------------------
20:05:30 [Statistics.ObjectStatistics] Logging info on the [60] objects in this pocket to [C:\Program Files (x86)\InnerSpace\.NET Programs\log\Pe_MyEVECharacterNameRedacted_\PocketObjectStats\Pe_MyEVECharacterNameRedacted_ - Technological Secrets (1 of 3) - 0 - ObjectStatistics.csv]
20:05:31 [Combat] Initiating Orbit [Thukker Mercenary Eliminator][at 5k][ID: [truncatedID]03196]
20:05:37 [Combat.KillTargets] [60] Activating Painters
20:05:37 [Combat.KillTargets] [60] Activating Webs
20:05:37 [Combat.KillTargets] [60] Activating WarpDisruptors
20:05:37 [Combat.KillTargets] [60] Activating RemoteRepairers
20:05:37 [Combat.KillTargets] [60] Activating Nos
20:05:37 [Combat.KillTargets] [60] Activating Weapons
20:05:39 [Combat.KillTargets] [61] Activating Painters
20:05:39 [Combat.KillTargets] [61] Activating Webs
20:05:39 [Combat.KillTargets] [61] Activating WarpDisruptors
20:05:39 [Combat.KillTargets] [61] Activating RemoteRepairers
20:05:39 [Combat.KillTargets] [61] Activating Nos
20:05:39 [Combat.KillTargets] [61] Activating Weapons
20:05:41 [Combat.KillTargets] [62] Activating Painters
20:05:41 [Combat.KillTargets] [62] Activating Webs
20:05:41 [Combat.KillTargets] [62] Activating WarpDisruptors
20:05:41 [Combat.KillTargets] [62] Activating RemoteRepairers
20:05:41 [Combat.KillTargets] [62] Activating Nos
20:05:41 [Combat.KillTargets] [62] Activating Weapons
20:05:43 [Combat.KillTargets] [63] Activating Painters
20:05:43 [Combat.KillTargets] [63] Activating Webs
20:05:43 [Combat.KillTargets] [63] Activating WarpDisruptors
20:05:43 [Combat.KillTargets] [63] Activating RemoteRepairers
20:05:43 [Combat.KillTargets] [63] Activating Nos
20:05:43 [Combat.KillTargets] [63] Activating Weapons
20:05:44 [Drones] [4] Drones Launched
20:05:45 [Defense] Shields: [75%] Cap: [96%] Shield Booster: [1] activated
20:05:45 [Combat.KillTargets] [64] Activating Painters
20:05:45 [Combat.KillTargets] [64] Activating Webs
20:05:45 [Combat.KillTargets] [64] Activating WarpDisruptors
20:05:45 [Combat.KillTargets] [64] Activating RemoteRepairers
20:05:45 [Combat.KillTargets] [64] Activating Nos
20:05:45 [Combat.KillTargets] [64] Activating Weapons
20:05:46 [Drones] Engaging [ 4 ] drones on [Thukker Mercenary Eliminator][ID: [truncatedID]03196]22k away]
20:05:48 [Combat.KillTargets] [65] Activating Painters
20:05:48 [Combat.KillTargets] [65] Activating Webs
20:05:48 [Combat.KillTargets] [65] Activating WarpDisruptors
20:05:48 [Combat.KillTargets] [65] Activating RemoteRepairers
20:05:48 [Combat.KillTargets] [65] Activating Nos
20:05:48 [Combat.KillTargets] [65] Activating Weapons
20:05:50 [Combat.KillTargets] [66] Activating Painters
20:05:50 [Combat.KillTargets] [66] Activating Webs
20:05:50 [Combat.KillTargets] [66] Activating WarpDisruptors
20:05:50 [Combat.KillTargets] [66] Activating RemoteRepairers
20:05:50 [Combat.KillTargets] [66] Activating Nos
20:05:50 [Combat.KillTargets] [66] Activating Weapons
20:05:53 [Combat.KillTargets] [67] Activating Painters
20:05:53 [Combat.KillTargets] [67] Activating Webs
20:05:53 [Combat.KillTargets] [67] Activating WarpDisruptors
20:05:53 [Combat.KillTargets] [67] Activating RemoteRepairers
20:05:53 [Combat.KillTargets] [67] Activating Nos
20:05:53 [Combat.KillTargets] [67] Activating Weapons
20:05:55 [Combat.KillTargets] [68] Activating Painters
20:05:55 [Combat.KillTargets] [68] Activating Webs
20:05:55 [Combat.KillTargets] [68] Activating WarpDisruptors
20:05:55 [Combat.KillTargets] [68] Activating RemoteRepairers
20:05:55 [Combat.KillTargets] [68] Activating Nos
20:05:55 [Combat.KillTargets] [68] Activating Weapons
20:05:58 [Combat.KillTargets] [69] Activating Painters
20:05:58 [Combat.KillTargets] [69] Activating Webs
20:05:58 [Combat.KillTargets] [69] Activating WarpDisruptors
20:05:58 [Combat.KillTargets] [69] Activating RemoteRepairers
20:05:58 [Combat.KillTargets] [69] Activating Nos
20:05:58 [Combat.KillTargets] [69] Activating Weapons
20:06:00 [Combat.KillTargets] [70] Activating Painters
20:06:00 [Combat.KillTargets] [70] Activating Webs
20:06:00 [Combat.KillTargets] [70] Activating WarpDisruptors
20:06:00 [Combat.KillTargets] [70] Activating RemoteRepairers
20:06:00 [Combat.KillTargets] [70] Activating Nos
20:06:00 [Combat.KillTargets] [70] Activating Weapons
20:06:02 [Combat.KillTargets] [71] Activating Painters
20:06:02 [Combat.KillTargets] [71] Activating Webs
20:06:02 [Combat.KillTargets] [71] Activating WarpDisruptors
20:06:02 [Combat.KillTargets] [71] Activating RemoteRepairers
20:06:02 [Combat.KillTargets] [71] Activating Nos
20:06:02 [Combat.KillTargets] [71] Activating Weapons
20:06:05 [Combat.KillTargets] [72] Activating Painters
20:06:05 [Combat.KillTargets] [72] Activating Webs
20:06:05 [Combat.KillTargets] [72] Activating WarpDisruptors
20:06:05 [Combat.KillTargets] [72] Activating RemoteRepairers
20:06:05 [Combat.KillTargets] [72] Activating Nos
20:06:05 [Combat.KillTargets] [72] Activating Weapons
20:06:08 [Combat.KillTargets] [73] Activating Painters
20:06:08 [Combat.KillTargets] [73] Activating Webs
20:06:08 [Combat.KillTargets] [73] Activating WarpDisruptors
20:06:08 [Combat.KillTargets] [73] Activating RemoteRepairers
20:06:08 [Combat.KillTargets] [73] Activating Nos
20:06:08 [Combat.KillTargets] [73] Activating Weapons
20:06:12 [Combat.KillTargets] [74] Activating Painters
20:06:12 [Combat.KillTargets] [74] Activating Webs
20:06:12 [Combat.KillTargets] [74] Activating WarpDisruptors
20:06:12 [Combat.KillTargets] [74] Activating RemoteRepairers
20:06:12 [Combat.KillTargets] [74] Activating Nos
20:06:12 [Combat.KillTargets] [74] Activating Weapons
20:06:14 [Combat.KillTargets] [75] Activating Painters
20:06:14 [Combat.KillTargets] [75] Activating Webs
20:06:14 [Combat.KillTargets] [75] Activating WarpDisruptors
20:06:14 [Combat.KillTargets] [75] Activating RemoteRepairers
20:06:14 [Combat.KillTargets] [75] Activating Nos
20:06:14 [Combat.KillTargets] [75] Activating Weapons
`

**Comment by sigmastk** [comment]
Confirming this behaviour in commit : 836d7f67b8b66a83fd265267dee06996377fc581

It wont shoot targets at all.

**Comment by dalikman** [comment]
also confirming weapons not being activated on target (but painters are).

13:31:06 [CombatMissionCtrl] Max Range is currently: 84k
13:31:06 [-] -----------------------------------------------------------------
13:31:06 [-] -----------------------------------------------------------------
13:31:06 [CombatMissionCtrl] Pocket [1] loaded, executing the following actions
13:31:06 [CombatMissionCtrl] Action [ 1 ] WaitUntilTargeted [timeout: 15]
13:31:06 [CombatMissionCtrl] Action [ 2 ] ClearPocket
13:31:06 [CombatMissionCtrl] Action [ 3 ] Activate [target: Acceleration Gate]
13:31:06 [-] -----------------------------------------------------------------
13:31:06 [-] -----------------------------------------------------------------
13:31:06 [Statistics.ObjectStatistics] Logging info on the [24] objects in this pocket to [C:\Program Files (x86)\InnerSpace.NET Programs\log\Sa_MyEVECharacterNameRedacted_\PocketObjectStats\Sa_MyEVECharacterNameRedacted_ - Angel Extravaganza - 1 - ObjectStatistics.csv]
13:31:06 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets below
13:31:06 [Combat.TargetCombatants] [1] Name [Gistum Liquidator] Distance [81.5] TypeID [16896] groupID [595]
13:31:06 [Combat.TargetCombatants] [2] Name [Gistum Breaker] Distance [83.62] TypeID [16889] groupID [595]
13:31:06 [Combat.TargetCombatants] [3] Name [Gistum Defeater] Distance [82.67] TypeID [16898] groupID [595]
13:31:06 [Combat.TargetCombatants] [4] Name [Gistum Defeater] Distance [82.48] TypeID [16898] groupID [595]
13:31:06 [Combat.TargetCombatants] DebugTargetCombatants: list of entities we consider PotentialCombatTargets above
13:31:06 [Combat] Target [Gistum Liquidator] as a priority target.
13:31:09 [Combat.KillTargets] We do not have a killtarget targeted, waiting
13:31:11 [Combat.KillTargets] We do not have a killtarget targeted, waiting
13:31:12 [CombatMissionCtrl[1].WaitUntilTargeted [timeout: 15]] We have been targeted!
13:31:12 [CombatMissionCtrl] Finished Action.WaitUntilTargeted [timeout: 15]
13:31:12 [CombatMissionCtrl] Starting Action.ClearPocket
13:31:14 [Combat] Out of range. ignoring orbit around structure.
13:31:14 [Combat] Initiating Orbit [Gistum Liquidator][at 15k][ID: [truncatedID]29268]
13:31:14 [Combat.KillTargets] [1] Activating Painters
13:31:14 [Combat] Activating painter [1] on [Gistum Liquidator][ID: [truncatedID]29268][81k away]
13:31:14 [Combat.KillTargets] [1] Activating Webs
13:31:14 [Combat.KillTargets] [1] Activating WarpDisruptors
13:31:14 [Combat.KillTargets] [1] Activating RemoteRepairers
13:31:14 [Combat.KillTargets] [1] Activating Nos
13:31:14 [Combat.KillTargets] [1] Activating Weapons
13:31:17 [Combat.KillTargets] [2] Activating Painters
13:31:17 [Combat] Activating painter [2] on [Gistum Liquidator][ID: [truncatedID]29268][80k away]
13:31:17 [Combat.KillTargets] [2] Activating Webs
13:31:17 [Combat.KillTargets] [2] Activating WarpDisruptors
13:31:17 [Combat.KillTargets] [2] Activating RemoteRepairers
13:31:17 [Combat.KillTargets] [2] Activating Nos
13:31:17 [Combat.KillTargets] [2] Activating Weapons
13:31:20 [Combat.KillTargets] [3] Activating Painters
13:31:20 [Combat.KillTargets] [3] Activating Webs
13:31:20 [Combat.KillTargets] [3] Activating WarpDisruptors
13:31:20 [Combat.KillTargets] [3] Activating RemoteRepairers
13:31:20 [Combat.KillTargets] [3] Activating Nos
13:31:20 [Combat.KillTargets] [3] Activating Weapons
13:31:22 [Combat.KillTargets] [4] Activating Painters

**Comment by ISeeDEDPpl** [comment]
this should be resolved now.
