### ISSUE TITLE
Dedicated salvager wont target wrecks and salvage latest Targeting branch

### ISSUE THREAD

**Issue by sigmastk** [ISeeDEDPpl/Questor#473]
I am using this build from Targeting branch: 5a36b56a633dbedd7fdb942b652cc6daf85d9f0e

I have noticed that dedicated salvager is not collecting loot. It goes to salvage BM, but it does not target wrecks .

I have this settings regarding salvage (it wa working fine in BE branch) :+1: 

`
<afterMissionSalvaging>True</afterMissionSalvaging>
<lootEverything>True</lootEverything>
<lootOnlyWhatYouCanWithoutSlowingDownMissionCompletion>false</lootOnlyWhatYouCanWithoutSlowingDownMissionCompletion>
<doNotDoANYSalvagingOutsideMissionActions>false</doNotDoANYSalvagingOutsideMissionActions>
`

I have turned this logs on : 
`
<debugTargetWrecks>True</debugTargetWrecks>
<debugSalvage>True</debugSalvage>
`
This are logs I have collected:

`
20:19:55 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [******: 1619]
20:19:55 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: Gate not found, we can start salvaging
20:19:56 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:19:56 [DedicatedSalvageBehavior: Salvage] Opening Cargohold of active ship: waiting [3sec]
20:19:56 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:19:57 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:19:58 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:19:59 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:19:59 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:00 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:01 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:01 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:02 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:03 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:04 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:04 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:05 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:06 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:06 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:08 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:09 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:09 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:10 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:11 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:11 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:12 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:13 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:14 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:14 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:15 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:16 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:16 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:17 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:18 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:18 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:19 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:20 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:20 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:21 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:22 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:23 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:23 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:24 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:25 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:26 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:26 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:27 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:28 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:29 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:29 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:30 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:31 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:31 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
20:20:32 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:33 [DedicatedBookmarkSalvagerBehavior] salvage: attempting to open cargo hold
20:20:33 [DedicatedBookmarkSalvagerBehavior] salvage: done opening cargo hold
`

**Comment by ISeeDEDPpl** [comment]
try: https://github.com/ISeeDEDPpl/Questor/commit/be124adaa862750a70067b7bfb2253d139e9c75f

**Comment by sigmastk** [comment]
I now get full cargo (it is empty) when it warps to salvage BM. Then it warp to station for unload. And again the whole process in loop. Build is Targeting branch <= 836d7f67b8b66a83fd265267dee06996377fc581

I have turned on this settings:
`
<debugCargoHold>true</debugCargoHold>
<debugSalvage>true</debugSalvage>
`
Here are logs I have colected:

`
16:33:29 [TravelerDestination.StationDestination] Arrived in station
16:33:30 [DedicatedBookmarkSalvagerBehavior] UnloadLoot: Begin
16:33:49 [UnloadLoot.MoveAmmo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
16:33:53 [UnloadLoot] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
16:33:54 [CombatMissionsBehavior.BeginAftermissionSalvaging] Salvaging at first oldest bookmarks
16:33:54 [DedicatedBookmarkSalvagerBehavior] CheckBookmarkAge: There are [ 3 ] more salvage bookmarks older then:10/26/2013 13:48:54, left to process
16:33:55 [Arm] Activating salvage ship
16:33:57 [Arm.ActivateSalvageShip] Done
16:34:01 [DedicatedBookmarkSalvagerBehavior.Salvager] Salvaging at first oldest bookmarks created on: 10/26/2013 09:35:04
16:34:01 [TravelerDestination.BookmarkDestination] Destination set to bookmark [*****: 1324]
16:34:14 [TravelerDestination.BookmarkDestination] This is not the destination station, undocking
16:34:32 [TravelerDestination.BookmarkDestination] Warping to bookmark [*****: 1324][5.17 AU away]
16:35:34 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [*****: 1324]
16:35:34 [DedicatedBookmarkSalvagerBehavior] GotoSalvageBookmark: Gate not found, we can start salvaging
16:35:35 [DedicatedBookmarkSalvagerBehavior] salvage::: attempting to open cargo hold
16:35:35 [DedicatedSalvageBehavior: Salvage] Opening Cargohold of active ship: waiting [2sec]
16:35:35 [DedicatedBookmarkSalvagerBehavior] salvage::: done opening cargo hold
16:35:35 [DedicatedBookmarkSalvageBehavior.Salvage] We are full, go to base to unload
16:35:36 [DedicatedBookmarkSalvagerBehavior] Destination: [BASE]
16:35:36 [TravelerDestination.StationDestination] Destination set to [BASE]
16:35:39 [TravelerDestination.StationDestination] Warp to and dock at [BASE][5.17 AU away]
`

**Comment by sigmastk** [comment]
I is working in last Targeting branch 98c957c3e7f900dbdfa3267200e26b4d7ec40fdd
