### ISSUE TITLE
BE/Testing branch  Contraband fix

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#474]
itemscache.cs line 154
salvage.cs line 730

AIMEDs, are not a contraband item.
Tested this morning by commenting them out and picked up the item as supposed to.

the item was listed on mission.xml but was not picking them up.

**Comment by ISeeDEDPpl** [comment]
fixed in targeting branch. soon it will get merged back into bleedingedge, etc
