### ISSUE TITLE
Wont target Hulk in Mining Misappropriation

### ISSUE THREAD

**Issue by Dynafire** [ISeeDEDPpl/Questor#475]
Can you add Hulk to the target list please :dancers:

**Comment by ISeeDEDPpl** [comment]
This should be fixed. If it is will a problem please dig up your pocket object statistics log and paste the line for that Hulk into this issue.

**Comment by Dynafire** [comment]
Illegal Miner;34;29466;927;11;True;False;-1;20;9000951853000241782;

**Comment by ISeeDEDPpl** [comment]
This should now be working ok.
