### ISSUE TITLE
not targetting/killing mission objectives

### ISSUE THREAD

**Issue by dalikman** [ISeeDEDPpl/Questor#476]
Questor isn't targeting mission objectives (ie, structures you need to kill, and often loot) and instead just orbits the structure in question.  I have double checked the relevant mission xmls and they look fine and have loaded ok.  I have had this behaviour on every commit I have tried (BE, Targeting and E) for maybe the last 3 weeks, and includes the latest from today.

In the sample log below, it should (as per the mission xml) kill the "Powerful EM Forcefield" and it seems to acknowledge that, but the behaviour is that it orbist the structure instead indefinitely.

15:30:19 [Combat.KillTargets] killtarget [Powerful EM Forcefield][9k][[truncatedID]90682] is not yet ReadyToShoot, LockedTarget [False]
15:30:20 [Combat.TargetCombatants] DebugTargetCombatants: if (Cache.Instance.potentialCombatTargets.Any()) was false - nothing to shoot?
15:30:20 [Combat.TargetCombatants] DebugTargetCombatants: list of entities below
15:30:20 [Combat.TargetCombatants] [1] Name [Powerful EM Forcefield] Distance [8.7] TypeID [17763] groupID [319]
15:30:20 [Combat.TargetCombatants] [2] Name [Tower Sentry Drone II] Distance [28.36] TypeID [18027] groupID [383]
15:30:20 [Combat.TargetCombatants] [3] Name [Tower Sentry Drone II] Distance [38.88] TypeID [18027] groupID [383]
15:30:20 [Combat.TargetCombatants] [4] Name [Tower Sentry Drone II] Distance [22.93] TypeID [18027] groupID [383]
15:30:20 [Combat.TargetCombatants] DebugTargetCombatants: list of entities above
15:30:20 [Combat.TargetCombatants] primaryWeaponTargetsToTarget [0] droneTargetsToTarget [0] activeTargets [0]
15:30:20 [Combat.TargetCombatants] Untarget stuff (if needed)
15:30:20 [Combat.TargetCombatants] Target a weapon target)
15:30:20 [Combat.TargetCombatants] if (toTarget == null)
15:30:22 [Combat.KillTargets] killtarget [Powerful EM Forcefield][9k][[truncatedID]90682] is not yet ReadyToShoot, LockedTarget [False]
15:30:23 [Combat.TargetCombatants] DebugTargetCombatants: if (Cache.Instance.potentialCombatTargets.Any()) was false - nothing to shoot?
15:30:23 [Combat.TargetCombatants] DebugTargetCombatants: list of entities below
15:30:23 [Combat.TargetCombatants] [1] Name [Powerful EM Forcefield] Distance [8.63] TypeID [17763] groupID [319]
15:30:23 [Combat.TargetCombatants] [2] Name [Tower Sentry Drone II] Distance [27.63] TypeID [18027] groupID [383]
15:30:23 [Combat.TargetCombatants] [3] Name [Tower Sentry Drone II] Distance [38.57] TypeID [18027] groupID [383]
15:30:23 [Combat.TargetCombatants] [4] Name [Tower Sentry Drone II] Distance [22.33] TypeID [18027] groupID [383]
15:30:23 [Combat.TargetCombatants] DebugTargetCombatants: list of entities above
15:30:23 [Combat.TargetCombatants] primaryWeaponTargetsToTarget [0] droneTargetsToTarget [0] activeTargets [0]
15:30:23 [Combat.TargetCombatants] Untarget stuff (if needed)
15:30:23 [Combat.TargetCombatants] Target a weapon target)
15:30:23 [Combat.TargetCombatants] if (toTarget == null)
15:30:25 [Combat.KillTargets] killtarget [Powerful EM Forcefield][9k][[truncatedID]90682] is not yet ReadyToShoot, LockedTarget [False]
15:30:26 [Combat.TargetCombatants] DebugTargetCombatants: if (Cache.Instance.potentialCombatTargets.Any()) was false - nothing to shoot?
15:30:26 [Combat.TargetCombatants] DebugTargetCombatants: list of entities below
15:30:26 [Combat.TargetCombatants] [1] Name [Powerful EM Forcefield] Distance [9.47] TypeID [17763] groupID [319]
15:30:26 [Combat.TargetCombatants] [2] Name [Tower Sentry Drone II] Distance [27.97] TypeID [18027] groupID [383]
15:30:26 [Combat.TargetCombatants] [3] Name [Tower Sentry Drone II] Distance [39.24] TypeID [18027] groupID [383]
15:30:26 [Combat.TargetCombatants] [4] Name [Tower Sentry Drone II] Distance [22.79] TypeID [18027] groupID [383]
15:30:26 [Combat.TargetCombatants] DebugTargetCombatants: list of entities above
15:30:26 [Combat.TargetCombatants] primaryWeaponTargetsToTarget [0] droneTargetsToTarget [0] activeTargets [0]
15:30:26 [Combat.TargetCombatants] Untarget stuff (if needed)
15:30:26 [Combat.TargetCombatants] Target a weapon target)
15:30:26 [Combat.TargetCombatants] if (toTarget == null)

**Comment by ISeeDEDPpl** [comment]
please reproduce the above logs with current experimental.

I think your range might be lower than the distance needed to hit the EM forcefield? Your maxRange (lower of targeting and weapons range) is part of the logging you'd see now. 

IF that is the case we can add some special case for that as needed...

**Comment by ISeeDEDPpl** [comment]
fixed in experimental and bleedingedge.
