### ISSUE TITLE
(issues)Re-Add Per-Frame Caching in EntityCache (there is more optimization t…

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#477]
causes a ton of client lag

did some killing but just orbited a wreck

08:25:21 [Cache.SetmissionXmlPath] [C:\Program Files (x86)\InnerSpace.NET Programs\expbuild\Caldari Missions 2\Technological Secrets (1 of 3).xml] found!
08:25:21 [Cache] Using Settings Orbit distance [30000]
08:25:21 [Cache] Using Settings OptimalRange [0]
08:25:21 [-] -----------------------------------------------------------------
08:25:21 [-] -----------------------------------------------------------------
08:25:21 [CombatMissionCtrl] Mission Timer Currently At: [4] min
08:25:21 [CombatMissionCtrl] Max Range is currently: 46k
08:25:21 [-] -----------------------------------------------------------------
08:25:21 [-] -----------------------------------------------------------------
08:25:21 [CombatMissionCtrl] Pocket [0] loaded, executing the following actions
08:25:21 [CombatMissionCtrl] Action [ 1 ] ClearPocket
08:25:21 [CombatMissionCtrl] Action [ 2 ] LootItem [target: Cargo Container] [item: Mercenary Pilot]
08:25:21 [CombatMissionCtrl] Action [ 3 ] Loot
08:25:21 [CombatMissionCtrl] Action [ 4 ] Done
08:25:21 [-] -----------------------------------------------------------------
08:25:21 [-] -----------------------------------------------------------------
08:25:21 [Statistics.ObjectStatistics] Logging info on the [24] objects in this pocket to [C:\Program Files (x86)\InnerSpace.NET Programs\expbuild\log\sl_MyEVECharacterNameRedacted_\PocketObjectStats\sl_MyEVECharacterNameRedacted_ - Technological Secrets (1 of 3) - 0 - ObjectStatistics.csv]
08:25:21 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]8575]
08:25:22 [Combat] Lock Target [Thukker Mercenary Fighter][[MaskedID]8571] PreferredPWPT [[MaskedID]8571] PreferedDPT [!0!]
08:25:24 [Combat] Out of range. ignoring orbit around structure.
08:25:24 [EntityCache] Initiating Orbit [Thukker Mercenary Fighter][at 30k][ID: [MaskedID]8571]
08:25:29 [Combat] Activating weapon [1] on [Thukker Mercenary Fighter][ID: [MaskedID]8571][24k away]
08:25:32 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 3 ] minutes.
08:25:40 [Combat] Target [Thukker Mercenary Fighter] does not need to be shot at the moment, untargeting
08:25:45 [Combat] Activating weapon [1] on [Thukker Mercenary Fighter][ID: [MaskedID]8571][28k away]
08:25:51 [Combat] Lock Target [Thukker Mercenary Fighter][[MaskedID]8572] PreferredPWPT [[MaskedID]8572] PreferedDPT [!0!]
08:25:53 [Combat] Out of range. ignoring orbit around structure.
08:25:53 [EntityCache] Initiating Orbit [Thukker Mercenary Fighter][at 30k][ID: [MaskedID]8572]
08:25:59 [Combat] Activating weapon [1] on [Thukker Mercenary Fighter][ID: [MaskedID]8572][30k away]
08:26:16 [Combat] Out of range. ignoring orbit around structure.
08:26:16 [EntityCache] Initiating Orbit [Thukker Mercenary Fighter][at 30k][ID: [MaskedID]8575]
08:26:17 [Combat] Lock Target [Thukker Mercenary Fighter][[MaskedID]8573] PreferredPWPT [[MaskedID]8573] PreferedDPT [!0!]
08:26:23 [Combat] Activating weapon [1] on [Thukker Mercenary Fighter][ID: [MaskedID]8573][30k away]
08:26:30 [Defense] Shields: [75%] Cap: [51%] Shield Booster: [1] activated
08:26:34 [Defense] Shields: [79%] Cap: [44%] Shield Booster: [1] deactivated [2] sec reactivation delay
08:26:34 [Combat] Out of range. ignoring orbit around structure.
08:26:34 [EntityCache] Initiating Orbit [Thukker Mercenary Fighter][at 30k][ID: [MaskedID]8573]
08:26:40 [Combat] Lock Target [Thukker Mercenary Fighter][[MaskedID]8575] PreferredPWPT [[MaskedID]8573] PreferedDPT [!0!]
08:26:42 [Combat] Lock Target [Thukker Mercenary Fighter][[MaskedID]8574] PreferredPWPT [[MaskedID]8574] PreferedDPT [!0!]
08:26:48 [Combat] Activating weapon [1] on [Thukker Mercenary Fighter][ID: [MaskedID]8574][32k away]
08:26:55 [Combat] Target [Thukker Mercenary Fighter] does not need to be shot at the moment, untargeting
08:26:58 [Combat] Out of range. ignoring orbit around structure.
08:26:58 [EntityCache] Initiating Orbit [Thukker Mercenary Fighter][at 30k][ID: [MaskedID]8574]
08:27:05 [Defense] Shields: [74%] Cap: [36%] Shield Booster: [1] activated
08:27:06 [Combat] Lock Target [Thukker Mercenary Fighter][[MaskedID]8575] PreferredPWPT [[MaskedID]8574] PreferedDPT [!0!]
08:27:09 [Defense] Shields: [78%] Cap: [29%] Shield Booster: [1] deactivated [2] sec reactivation delay
08:27:14 [Combat] Activating weapon [1] on [Thukker Mercenary Fighter][ID: [MaskedID]8575][31k away]
08:27:16 [Combat] Out of range. ignoring orbit around structure.
08:27:16 [EntityCache] Initiating Orbit [Thukker Mercenary Fighter][at 30k][ID: [MaskedID]8575]
08:27:32 [Combat] Lock Target [Thukker Mercenary Fighter][[MaskedID]8575] PreferredPWPT [[MaskedID]8575] PreferedDPT [!0!]
08:27:32 [EntityCache.LockTarget] [Combat] tried to lock [Thukker Mercenary Fighter][29.76k][[MaskedID]8575][0] targets already, LockTarget failed (unknown reason)
08:27:32 [EntityCache.LockTarget] [Combat] tried to lock [Thukker Mercenary Fighter][29.76k][[MaskedID]8575][0] targets already, LockTarget failed: target was not in Entities List
08:27:32 [EntityCache.LockTarget] [Combat] tried to lock [Thukker Mercenary Fighter][29.76k][[MaskedID]8575][0] targets already, LockTarget aborted: target is already being targeted
08:27:32 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]8575]
08:27:36 [CombatMissionCtrl] Finished Action.ClearPocket
08:27:36 [CombatMissionCtrl] Starting Action.LootItem [target: Cargo Container] [item: Mercenary Pilot]
08:27:37 [CombatMissionCtrl[0].LootItem [target: Cargo Container] [item: Mercenary Pilot]] Approaching target [Thukker Mercenary Fighter Wreck][ID: [MaskedID]8819] which is at [55k away]
08:28:39 [Combat] Lock Target [Thukker Mercenary Rookie][[MaskedID]9587] PreferredPWPT [[MaskedID]9587] PreferedDPT [!0!]
08:28:40 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9587]
08:28:42 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9587]
08:28:44 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9587]
08:28:46 [Combat] Target [Thukker Mercenary Rookie] does not need to be shot at the moment, untargeting
08:28:47 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:28:49 [Combat] Lock Target [Thukker Mercenary Fighter][[MaskedID]9593] PreferredPWPT [[MaskedID]9593] PreferedDPT [!0!]
08:28:50 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:28:52 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:28:54 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:28:57 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:29:00 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:29:03 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:29:06 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:29:09 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:29:13 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:29:16 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:29:18 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9593]
08:29:20 [Combat] Lock Target [Thukker Mercenary Rookie][[MaskedID]9592] PreferredPWPT [[MaskedID]9592] PreferedDPT [!0!]
08:29:20 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9592]
08:29:22 [Combat] Target [Thukker Mercenary Fighter] does not need to be shot at the moment, untargeting
08:29:22 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9592]
08:29:24 [Combat] Target [Thukker Mercenary Fighter] does not need to be shot at the moment, untargeting
08:29:24 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9592]
08:29:26 [Combat.Killtargets] Unable to find the PreferredPrimaryWeaponTarget!!! [][[MaskedID]9592]

**Comment by ISeeDEDPpl** [comment]
I doubt it, actually I had 2-3times more client lag before I added this commit. The time it was raking to run __GetBestTarget (I assume, as the lag went away wkith getbesttarget disabled) is why I added it =/ 
We probably do need more caching to eliminate the lag... or at least a deeper investigation as to where all the processing time is going (the fact that the processig time is taking more than one eve frame of time is causing what we see as lag).
