### ISSUE TITLE
Nov 2 BE/EXP (c6ab2a1217 and 50e74f069) CTD at mission location

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#478]
both CTD 

http://privatepaste.com/7cde61ad21

the log is the best one, this is with EXP, disablegetbesttarget True

the rest seem to get to mission and crash when started

**Comment by ISeeDEDPpl** [comment]
this is now fixed in latest experimental and bleedingedge
It is helpful to know what commits are not working. It is a godsend when you know exactly what commit worked and the next commit broke functionality.

**Comment by Pluckyduck** [comment]
easy enough, what i try to do and what i try to get other to document as well.
