### ISSUE TITLE
loot action and lootitem

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#479]
IOrderedEnumerable<EntityCache> containers = Cache.Instance.Containers.Where(e => !Cache.Instance.LootedContainers.Contains(e.Id)).OrderByDescending(e => e.Distance);

should replace

IOrderedEnumerable < EntityCache > containers = Cache.Instance.Containers.Where(e => !Cache.Instance.LootedContainers.Contains(e.Id)).OrderBy(e => e.Id);

**Comment by ISeeDEDPpl** [comment]
done.

**Comment by Pluckyduck** [comment]
thanks and that was a fun one to work out.
