### ISSUE TITLE
Bug - Approaching changes target with every cycle

### ISSUE THREAD

**Issue by Blafasl** [ISeeDEDPpl/Questor#48]
Something that happens in Sooth the Salvage Beast. When the ship is trying to approach a Science vessel it changes its target with every iteration. So it doesn't finish the Lootitem action and the Bot is stuck in the storyline mission looping through targets to approach.

Using your newest fork. Speedtanking on. Tengu with afterburner. Changes the target when its 32km away from it or every 14-17 seconds.

**Comment by ISeeDEDPpl** [comment]
yes, Im not exactly sure how to fix this as it is written... 
it seems to me that you could "moveto" one of the cans. 
Then loot it...
then ignore the closest can
then moveto another can
Then loot it...
then ignore the closest can
then moveto another can
etc...
until you had the # of items you needed...

**Comment by Blafasl** [comment]
I will try to tinker with the XML a bit to see if i find a way around it.
But it would may be useful to have a quantity and a closest parameter for the ignore action.
Right now when i put the science vessel on ignore it will ignore every Science vessel, i think.

**Comment by ISeeDEDPpl** [comment]
The only other way to fix this would be to set a variable in cache.instance.movetotargetID (or similar) and use that to approach the specific ID... then once in range reset that variable to null, add that ID to a list of things we have already processed and repeat the process for all items with the same name, grab the next ID, shove it into movetotargetID, etc, etc

Ill see about adding this to the queue... if someone beats me to it, great =)

**Comment by zeptorem** [comment]
I'm having this a lot, it invariably causes a wallet shutdown pretty much every session. I imagine it'd also make it really easy to detect bots.

**Comment by ISeeDEDPpl** [comment]
Hrmmm... I was unaware that this was an issue for other missions. I'll resolve this tomorrow... I'm surprised that I haven't run into this problem with any other mission other than sooth the salvage beast

**Comment by ISeeDEDPpl** [comment]
ok, this was easier to fix than I thought
I'll push the fix to github momentarily

**Comment by zeptorem** [comment]
Thanks man, very much appreciated

**Comment by zeptorem** [comment]
I've encountered it most recently in Intercept the Saboteurs

**Comment by ISeeDEDPpl** [comment]
This has been fixed
