### ISSUE TITLE
Small freezes in the latest exp.

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#481]
In the latest exp branch: 4500d670eba15bc671462a91c34960dc5247ff12

After 20min run mission, my eve working odd. 
Every second i have fraction of a second freeze. 
FPS go to down from 60 to 20 every second, even when pocket is clear and bot not aggro anything and go to acceleration gate.

Update:
When Q back to base and change state to after mission salvaging, freezes not appear, fps is stable.

**Comment by botina** [comment]
Same here just my fps goes down to 0.5 (In mission: Unauthorized Military Presence).

**Comment by ISeeDEDPpl** [comment]
odd... try pausing/unpausing every 10 min or so and see if it misbehaves...
In the meantime Ill find the leak =/
