### ISSUE TITLE
Prop mod cycling

### ISSUE THREAD

**Issue by dalikman** [ISeeDEDPpl/Questor#483]
Hi,

I've noticed a while back (about a month ago, but before that had not used Q for a year) that questor has been cycling the prop mod when it should be leaving it on continuously.

I'm pretty sure its not a config error, because:

minimumPropulsionModuleDistance is at 100 (and this happens at way above 100m)
minimumPropulsionModuleCapacitor is at 15 (confirmed above this cap)
speedTank is a true

I haven't posted any logs because I don't see anything relevant in there, but if I should turn on one of the debug options, let me know.

Specifically I have noticed this happening when questor is in combat (ie, orbiting a target).  When approaching an object the prop mod stays on as it should.

Thanks.

**Comment by dalikman** [comment]
I should add I am using a fairly recent commit (~3-4 days old).

**Comment by ISeeDEDPpl** [comment]
please test: https://github.com/ISeeDEDPpl/Questor/commit/2871a3a5cbc846ca1d27d6f197438f46a947a5de
this should behave better.

**Comment by dalikman** [comment]
thanks a lot, I'll test today and let you know.

**Comment by ISeeDEDPpl** [comment]
confirmed fixed in latest Experimental/Bleedingedge: https://github.com/ISeeDEDPpl/Questor/commit/82625a3035dee8356a8a4a3e3ead1113643534db
