### ISSUE TITLE
Not prioritising statis towers

### ISSUE THREAD

**Issue by dalikman** [ISeeDEDPpl/Questor#484]
Hi,

Questor does not seem to be prioritising (or even killing at all) stasis towers.

I must admit, I do have killSentries set to false since I am not interesting in clearing all towers, but I'm pretty sure Questor used to (a long time ago maybe) prioritise towers if they were applying ewar such as webbing.

Am I doing something wrong, is this simply desired questor behaviour or have I found a bug?

No log since nothing of note, but happy to turn on the relevant debug option if that helps.

I am using a fairly recent commit (~3-4 days old).

Thanks.

**Comment by Pluckyduck** [comment]
when making these....."I am using a fairly recent commit (~3-4 days old)" do no good, find the build and link it with at least the first 6 to 8 character in the name

**Comment by ISeeDEDPpl** [comment]
in this case the date range is enough. in the future it may not be.

**Comment by ISeeDEDPpl** [comment]
this should now behave as intended. if it is a sentry and killsentries is false we do not targetor shoot the sentry UNLESS it is also an ewartarget (any ewar type!)

**Comment by dalikman** [comment]
thanks.

sorry plucky, i was being lazy, and I was sure this and the other issue I raised were present in all recent (<1 month) commits.  I'll post the exact one next time though :)

**Comment by Pluckyduck** [comment]
sorry for being a bulldog on helping ISDP out.  he does push out a lot of commits to help keep track of the updates and I learn from them and it is way easier to find it if you know the commit.
