### ISSUE TITLE
SkillPlan.cs injection fails for skills groupid  != 270

### ISSUE THREAD

**Issue by duketwo** [ISeeDEDPpl/Questor#486]
IEnumerable<DirectItem> items = Cache.Instance.ItemHangar.Items.Where(k => k.GroupId == (int)Group.SkillBooks).ToList(); line 262

group.SkillBooks =   groupiD = 270

skills have several group id's, so the injection of skills fails in most cases.

**Comment by ISeeDEDPpl** [comment]
fixed.

Thank You!
