### ISSUE TITLE
Bug: WatchForActiveWars set to false - still panics if WarDec is present. 

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#494]
{WatchForActiveWars>false</WatchForActiveWars}

TO CLARIFY: currently there is a bug in how panic script handles the situation where we are WarDec'ed, but have specifically defined in "WatchForActiveWars" that we DO NOT WANT this check to be performed. 

What Works: panic and cache correctly finds out that we are in fact at war and initiates panic action, debug went through all steps ok, so this functionality is working correctly, it does not panic when wardec is not present. DE returns correct value, cache catches ir passes to panic, panic panics. 

However, there is problem in programing logic that somehow does not take into consideration what we defined in settings. The "false" bool value pulled from xml does not stop it from calling panic.

Error COULD lie in either parsing setting from xml to cache (seems ok at a glance), or in panic mechanism logic, or in the way cache stores IsAtWar value w/o taking the setting in xml into account. 

SYMPTOM: WatchForActiveWars is set to "false", tho it still detects a WARDEC in progress and panics after undocking. Stays in panic mode until you quit questor. Manually switching to other actions still drops to panic action and pauses.

XX:54:02 [TravelerDestination.MissionBookmarkDestination] Destination set to mission bookmark [Encounter (Deadspace) - XXXXXXXX]
XX:54:04 [TravelerDestination.SolarSystemDestination] Exiting station
XX:54:24 [Defense] Shields: [100%] Cap: [100%] Shield Booster: [1] activated
XX:54:24 [TravelerDestination.BookmarkDestination] Warping to bookmark [Encounter (Deadspace) - XXXXX][10,01 AU away]
XX:54:25 [IsCorpInWar] Your corp is involved in a war, be careful
XX:54:25 [Cache] Your corp is involved in a war, Starting panic!

BleedingEdge commit b2d0eafa5f
ISeeDEDPpl authored 4 days ago 
DirectEve
v1.330.5071.29327
using Innerspace 1.12 Build 5944 , ISXDK v33

**Comment by CasualBod** [comment]
leaving the field empty, as in deleting the word "true" and instead of writing "false" leaving it empty between >< does not seem to have any effect. It still panics. setting value to "false" still causes it to ignore the setting and panic.

Also tried moving the setting to common.xml - same thing, still panics out on "false" or no value.

**Comment by CasualBod** [comment]
applied a crude & dirty fix in Panic.cs (it now resets panic to Idle state instead of StartPanicking every time active war check is called:

```
                if (Settings.Instance.WatchForActiveWars && Cache.Instance.IsCorpInWar)
                {
                    Logging.Log("Cache", "Your corp is involved in a war, Starting panic!", Logging.Orange);
                    _States.CurrentPanicState = PanicState.Idle; // changed from PanicState.StartPanicking;
                    //return;
                }
```

As I am unable to find the cause of this panic loop.

**Comment by CasualBod** [comment]
UPDATE: Made some clarification on where the bug lies in first post. Hope that helps to find a fix. If you need me to debug and give you more logs, I can do so, tho wardec expires this evening.

**Comment by ISeeDEDPpl** [comment]
fixed: typo in the provided template settings.xml
watchForActiveWars not WatchForActiveWars, the settings elements ARE case sensitive. 
sorry about that
