### ISSUE TITLE
Intended? Does not use station insta-undock bookmarks.

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#495]
commit b2d0eafa5f
ISeeDEDPpl authored 4 days ago 
DirectEve
v1.330.5071.29327

As per title, questor ignores .xml settings and does not warp to pre-set instant warp-out bookmark. Checked if everything is typed in correctly.

 Older versions of questor used to parse that setting no problem and it used to work, nothing has been altered in that part of config file.

**Comment by xelj** [comment]
same

**Comment by ISeeDEDPpl** [comment]
Ill look into this this weekend. I changed how this is handled. It is supposed to use those bookmarks as part of traveler off stations AND gates...

**Comment by ISeeDEDPpl** [comment]
please test this again. this should now be working. keep in mind that we now default to using the setting:
`<undockprefix>Insta</undockprefix>`
if that setting is not available (blank or missing) we fall back to using the old setting. 
`<bookmarkWarpOut>Insta</bookmarkWarpOut>`
