### ISSUE TITLE
Asteroid Targeting Issue, _targetAsteroid in MiningBehavior.cs invalidated after every call of ProcessState

### ISSUE THREAD

**Issue by philoman2** [ISeeDEDPpl/Questor#497]
As reference type, _targetAsteroid accepts a referece pointing to a instance of asteroid EntityCache returned by Cache.Instance.EntitiesOnGrid.Where(...) and are invalidated in next call of ProcessState, that is to say the reference pointing to no valid asteroid and Cache.Instance.EntityById(_targetAsteroid.Id) returning null.

**Comment by ISeeDEDPpl** [comment]
I have resolved those issues with the miner. There are certainly others... ass you come across em report em and Ill fix. 

The miner hasnt seen much testing/debugging, but should be very close to functional.
