### ISSUE TITLE
Mining Bot edits

### ISSUE THREAD

**Issue by Monkey7539** [ISeeDEDPpl/Questor#500]
Okay so I have been trying to get the mining functionality working and found a missing piece of code.

I believe we need to add in the following line of code after line 972 in Questor.Modules.Lookup Settings.cs

```
            MiningShipName = (string)CharacterSettingsXml.Element("miningShipName") ?? (string)CommonSettingsXml.Element("miningShipName") ?? "My Exhumer of Destruction";
```

Now I could be wrong. My coding abilities are not up to the rest of yours by a long shot. Also I noticed that when the character gets to a belt that is empty it goes into an endless loop of "Could not find suitable asteroid" then "Setting dest to asteroid field 1" not sure how to fix yet.

**Comment by ISeeDEDPpl** [comment]
yes, that line was missing, I guess it never got merged in from the mining behavior branch with the other changes.
thank you.

Ive also made some changes that are likely to fix the empty belt issue. please open another issue (with logs) if you are able to reproduce it after updating to latest bleedingedge.
