### ISSUE TITLE
Mining infinite loop

### ISSUE THREAD

**Issue by Monkey7539** [ISeeDEDPpl/Questor#501]
Mining behavior gets to the belt then gets stuck in a loop choosing which asteroid to mine. Log below:

21:17:06 [MiningBehavior]Setting Destination to 1st Asteroid belt.
21:18:04 [MiningBehavior]Setting Destination to 1st Asteroid belt.
21:18:05 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]
21:18:06 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]
21:18:07 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]
21:18:08 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]
21:18:09 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]
21:18:10 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]
21:18:11 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]
21:18:12 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]
21:18:13 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]
21:18:14 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]
21:18:15 [Mining: []Asteroid (Plagioclase)][21k] GroupID [458]

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge, sry about that...
