### ISSUE TITLE
Mining still looping

### ISSUE THREAD

**Issue by Monkey7539** [ISeeDEDPpl/Questor#502]
Mining behavior gets to the belt then gets stuck in a loop choosing which asteroid to mine. Log below:

18:12:12 [MiningBehavior]Setting Destination to 1st Asteroid belt.
18:13:10 [MiningBehavior]Setting Destination to 1st Asteroid belt.
18:13:11 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:12 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:13 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:14 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:15 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:16 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:17 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:18 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:19 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:20 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:22 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:23 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:24 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:25 [Mining: []Asteroid (Rich Plagioclase)][20k] GroupID [458]
18:13:26 [Mining: []Asteroid (Azure Plagioclase)][20k] GroupID [458]
18:13:27 [Mining: []Asteroid (Azure Plagioclase)][20k] GroupID [458]
18:13:28 [Mining: []Asteroid (Azure Plagioclase)][20k] GroupID [458]
18:13:29 [Mining: []Asteroid (Azure Plagioclase)][20k] GroupID [458]
18:13:30 [Mining: []Asteroid (Azure Plagioclase)][20k] GroupID [458]
18:13:31 [Mining: []Asteroid (Azure Plagioclase)][20k] GroupID [458]
18:13:32 [Mining: []Asteroid (Azure Plagioclase)][21k] GroupID [458]
18:13:33 [Mining: []Asteroid (Azure Plagioclase)][21k] GroupID [458]
18:13:34 [Mining: []Asteroid (Azure Plagioclase)][21k] GroupID [458]
18:13:35 [Mining: []Asteroid (Azure Plagioclase)][21k] GroupID [458]

**Comment by ISeeDEDPpl** [comment]
The commit I had meant to push to bleedingedge was only in my local tree. I just pushed the update, along with another commit. please test.

**Comment by Monkey7539** [comment]
No Luck. Still looping in the same spot.

**Comment by ISeeDEDPpl** [comment]
ok, latest commit should resolve that.
