### ISSUE TITLE
trouble with capacitor injectors, undock bookmark and bastion modules

### ISSUE THREAD

**Issue by Cyrixx** [ISeeDEDPpl/Questor#503]
1) Arm not load cap booster in cargo
          16:58:15 [Arm]No Capacitor Injectors found on the ship, no cap boosters will be loaded! 
  Heavy capacitor booster II fitted on ship and save in fitting manager
2) Questor dont use undock bookmark
     bookmark near the station at which the ship
     There is no record in the console about undock bookmark
3) questor dont use bastion, bastion fitted on ship and save in fitting manager, and mission.xml written switch the bastion

please be advised what could be wrong. I used win7 x64, Win8 x64, compiling questor without errors. use latest branch Experimental and BleedingEdge. I have support license instances. previously used questor in June and dont have problem.

**Comment by ISeeDEDPpl** [comment]
1)You can add the setting: 
`<armLoadCapBoosters>true</armLoadCapBoosters>`
to force loading cap boosters. there seems to be an issue in questor detecting modules on your ship before you undock. Ill have to look into that. 
2) undock bm is a known issue. I broke it, Ill fix this weekend.
3) what message do you get if any when the ActivateBastion action runs? Console log output would be useful.

in the future please create one 'issue' on github per issue. combining things generally makes following what is fixed and what is not difficult.

**Comment by Cyrixx** [comment]
Thank you very much! armLoadCapBoosters>true</armLoadCapBoosters  this works great!

3) ActivateBastion. Could you please give an example of a mission or pocket where works correctly "ActivateBastion". I think that I have an error in mission.xml

Console log 
    17:03:16 [CombatMissionCtrl] Pocket [1] loaded, executing the following actions
    17:03:16 [CombatMissionCtrl] Action [ 1 ] ActivateBastion [deactivateafterseconds: 20]       [deactivateifnothingtargetedwithinrange: true]
17:03:16 [CombatMissionCtrl] Action [ 2 ] WaitUntilTargeted [timeout: 15]
17:03:16 [CombatMissionCtrl] Action [ 3 ] ClearPocket
17:03:16 [CombatMissionCtrl] Action [ 4 ] ActivateBastion [deactivateafterseconds: 5] [deactivateifnothingtargetedwithinrange: true]
17:03:16 [CombatMissionCtrl] Action [ 5 ] WaitUntilTargeted [timeout: 20]
17:03:16 [CombatMissionCtrl] Action [ 6 ] ClearPocket
17:03:16 [CombatMissionCtrl] Action [ 7 ] Activate [target: Acceleration Gate]

17:03:17 [ActivateBastion] [1] BastionModule: IsActive [False] IsDeactivating [False] InLimboState [False] Duration [60000] TypeId [33400]

**Comment by ISeeDEDPpl** [comment]
ok, update to latest bleedingedge. I just made a fix for the activation of bastion modules.
