### ISSUE TITLE
ActivateBastion action may not be deactivating Bastion module

### ISSUE THREAD

**Issue by KingMike** [ISeeDEDPpl/Questor#509]
Hola,

I see this every couple of missions.
Bastion module will not deactivate and just keeps cycling green.

I use in all my mission xmls:

```
  <action name="ActivateBastion">
    <parameter name="DeactivateAfterSeconds" value="5" />
    <parameter name="DeactivateIfNothingTargetedWithinRange" value="true" /> 
  </action>
```

I don't think this makes any difference.
There is nothing in logs. It just keeps going green for ever.

only thing i see is:

[CombatMissionCtrl.Activate] BastionMode is active, we cannot move, aborting attempt to Activate until bastion deactivates

but it will not deactivate.

Thanks!

**Comment by Cyrixx** [comment]
Turn off auto-repeat on the module bastion, this solves the problem. Questor automatically turn on bastion when it is necessary.

**Comment by ISeeDEDPpl** [comment]
It is supposed to deactivate/flash red the module as soon as the DeactivateAfterSeconds as expired... 
try updating and adding debugActivateBastion true

**Comment by ISeeDEDPpl** [comment]
turning off auto repeat will not totally solve the issue as there will be some missions you want it to run for 2-3 cycles.
I will have to add some additional code for it to auto-reactivate up until the DeactivateAfterSeconds time if you have auto repeat off. Ill do that this weekend.

**Comment by KingMike** [comment]
had no more issues with this since.
Looks all OK now.
Thanks.
