### ISSUE TITLE
LootItem issues

### ISSUE THREAD

**Issue by KingMike** [ISeeDEDPpl/Questor#512]
In missions where Loot or LootItem with target/item is being used, there are issues.
I use doNotDoANYSalvagingOutsideMissionActions true so I am not sure if its related to that or not.

But it will ignore all salvaging (as it should) until it needs to loot the specific item.
Then it will lock all wrecks in range and will start looting (will not unlock any wrecks anymore) and will start approaching the container or wreck that has the item it needs.
Then it will loot the item and will just sit there not moving or doing anything.

missions where I observed this:
Damsel, Unauthorised military presence and Stop the thief.

**Comment by ISeeDEDPpl** [comment]
so you have a salvager fitted? Is it salvaging in addition to looting?

**Comment by ISeeDEDPpl** [comment]
I made some adjustments to salvage.cs that may help if you didnt have a salvager fitted (so wrecks we being emptied by potentially not unlocked properly)

**Comment by KingMike** [comment]
Thanks!

Yes I have the salvager but it is not being used by Questor when this happens.

I just find it strange that this gets only triggered when a lootitem is used.
It will not lock any wreck the whole mission.
When its time to lock a specific container container it will lock all wrecks instead. There is something going wrong at that moment.

I will test the new version today see if it makes any difference.

**Comment by ISeeDEDPpl** [comment]
For clarity's sake:
There are only 2 things that will disable the background salvaging during a mission. speedtank = true and doNotDoANYSalvagingOutsideMissionActions = true.

When you do lootitem it effectively re-enables the background looting/salvaging.
the salvager.cs background routine wants to loot/salvage all wrecks and will do so given the chance (when its working right anyhow...). When the loot action is completed the openwrecks variable is set to false again and the background salvaging stops again. 

the Loot Action(s) (in your misison XML) are not actually responsible for looting/salvaging that is done by the salvage.cs routine. The loot actions just make sure that we are approaching the right wreck(s) and are responsible for having us switch to the next action when we have looted the right item (or all items depending on your settings).

**Comment by ISeeDEDPpl** [comment]
If it reoccurs still ,please get me a log with debugSalvage and debugLootWrecks on... you do not need to turn them on until it gets stuck. debug settings take effect on the fly.

**Comment by KingMike** [comment]
interesting.
is it possible its confusing wrecks with containers?

from logs:

``` xml
[Salvage] Cargo Container [Mercenary Commander Wreck][1k][ID: [MaskedID]2721] within loot range, unlocking container.
[Salvage] Opening container [Mercenary Commander Wreck][1k][ID: [MaskedID]2721]
```

But Mercenary Commander is a wreck not a container.

also here:

``` xml
[CombatMissionCtrl[0].LootItem [target: Cargo Container] [item: The Damsel]] Approaching target [Seven Death Dealer Wreck][[MaskedID]3699] which is at [8k away]
```

it looks like it believes it is approaching a container but it is in fact approaching a wreck.

also when its trying to create a salvage bookmark:

``` xml
[BookmarkPocketForSalvaging] Entered: BookmarkPocketForSalvaging
[BookmarkPocketForSalvaging] LootEverything [False] UnlootedContainers [22] MinimumWreckCount [5] We will wait until everything in range is looted.
[BookmarkPocketForSalvaging] if (Cache.Instance.UnlootedContainers.Count [22] (w => w.Distance <= RangeToConsiderWrecksDuringLootAll [48000]) > 0)
```

All 22 wrecks are looted but it thinks they are not. Maybe because it thinks they are containers.

**Comment by KingMike** [comment]
using f793c4b4380ab619171bb1b5b76cbd66a7ccf2a4

There is still problem with creating of a bookmark.

``` xml
[BookmarkPocketForSalvaging] Entered: BookmarkPocketForSalvaging
[BookmarkPocketForSalvaging] LootEverything [False] UnLootedContainers [10LootedContainers [9] MinimumWreckCount [5] We will wait until everything in range is looted.
[BookmarkPocketForSalvaging] if (Cache.Instance.UnlootedContainers.Count [10] (w => w.Distance <= RangeToConsiderWrecksDuringLootAll [48000]) > 0)
[Salvage] SalvageState.TargetWrecks:
[BookmarkPocketForSalvaging] Entered: BookmarkPocketForSalvaging
[BookmarkPocketForSalvaging] LootEverything [False] UnLootedContainers [10LootedContainers [9] MinimumWreckCount [5] We will wait until everything in range is looted.
```

looks like something misspelled here?
UnLootedContainers [10LootedContainers

If will finish clearing the pocket and then will keep looping through the lines above.

**Comment by ISeeDEDPpl** [comment]
ok, found and fixed the cause of it getting stuck, but if you want after mission salvage bookmarks created you need both LootAll and LootOnlyWhatYouCanWithoutSlowingDownMissionCompletion both false. If either is true it is going to loot what is in range and continue (without making a bookmark for after mission salvaging!)
