### ISSUE TITLE
some error in dedicated salvager

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#513]
Not a big deal but get an error during dedicated salvager when bookmarks are empty and he needs to refresh i guess.

Exception during event execution: System.ArgumentNullException: Der Wert darf nicht NULL sein.

Parametername: source

   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)

   bei Questor.Behaviors.DedicatedBookmarkSalvagerBehavior.ProcessState() in c:\Questor-51fd869ca4740b4f69faa4812b8b4b3433d40a0a\Questor\Behaviors\DedicatedBookmarkSalvagerBehavior.cs:Zeile 416.

   bei Questor.Questor.EVEOnFrame(Object sender, EventArgs e) in c:\Questor-51fd869ca4740b4f69faa4812b8b4b3433d40a0a\Questor\Questor.cs:Zeile 682.

   bei DirectEve.DirectEve.(Object , EventArgs )

   bei DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   bei LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
Exception during event execution: System.ArgumentNullException: Der Wert darf nicht NULL sein.

**Comment by kn0xv1lle** [comment]
Ok looks like this is always happen when he finish all salvage bookmarks. So he gives out error when there are no salvage bookmarks left because he is not refreshing and warping back to station to unload.
Also there is some issue when salvager is started in space he give out the error that he is unable to locate the agent unless the agent name is correctly definied in the agent list.

**Comment by ISeeDEDPpl** [comment]
the exception has been fixed. the agent issue will not be fixed for a bit. There is still some refactoring (small, but Im lazy atm) that needs to be done. The dedicated salvager is only meant to be used in conjunction with mission runnning questors. Adding the agents list to the dedicated salvager, while logically silly, is not a huge leap, or difficult.

**Comment by kn0xv1lle** [comment]
Well its just about to tell the dedicated salvager where his homebase is. I thought it works like this way because its a pain in the ass if questor or eve crash in space you have to login manually and fly him back to base.
