### ISSUE TITLE
open and closing  cargo on last BE fd391ebe943bb1

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#514]
last BE just open and closes the cargo hold with the log below.

20:47:30 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:30 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:30 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:30 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:30 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:30 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:32 [CurrentShipsCargo] Cache.Instance.DirectEve.ExecuteCommand(DirectCmd.OpenCargoHoldOfActiveShip);
20:47:32 [CloseCargoHold] Cargohold was not open, no need to close
20:47:35 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:35 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:35 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:35 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:35 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:35 [CurrentShipsCargo] DebugCargoHold: cargoHold window is ready and is a secondary inventory window
20:47:54 [CurrentShipsCargo] Cache.Instance.DirectEve.ExecuteCommand(DirectCmd.OpenCargoHoldOfActiveShip);

works fine with my destroyer but not with the drake.  suggestions?

**Comment by ISeeDEDPpl** [comment]
this should be fixed in bleedingedge, and seems to have been a combo of a misconfiguration (no transport ship?) and an unnecessary closing of the cargohold of your current ship (that didnt change because it couldnt find the transportship it wanted to use).
