### ISSUE TITLE
Bleeding edge - 4f8fd991ac6b35 (slight behind but should not make a diff)

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#515]
LootItem

  Q was heading to correct can and locked a wreck right before getting into range of the can.  the current wreck was labeled with contra band and discarded BUT also the can that contained the required lootItem was marked as emptied.  

logs below.

09:34:37 [Salvage] Locking [Sanshas Transport Ship Wreck][20k][ID: 
[MaskedID]1472][20k away]
09:34:38 [Salvage] Debug: containersInRange count [0]
09:34:41 [Salvage] Debug: containersInRange count [0]
09:34:44 [Salvage] Debug: containersInRange count [0]
09:34:46 [Salvage] Cargo Container [Sanshas Transport Ship Wreck][2k][ID: [MaskedID]1854] within loot range,
unlocking container.
09:34:47 [Salvage] Opening container [Sanshas Transport Ship Wreck][1k][ID: [MaskedID]1854]
09:34:49 [Salvage] Locking [Cargo Container][19k][ID: [MaskedID]2328][19k away]
09:34:50 [Salvage] Opening container [Sanshas Transport Ship Wreck][1k][ID: [MaskedID]1854]
09:34:50 [Salvage] LootWrecks: Cache.Instance.ContainerInSpace.Window is ready
09:34:50 [Salvage.LootWrecks] Found [1] items in [Sanshas Transport Ship Wreck][1k][[MaskedID]1854]
09:34:50 [Salvage.LootWrecks] [Crash] is not the mission item and is considered Contraband: ignore it
09:34:50 [Salvage.LootWrecks] Container [Sanshas Transport Ship Wreck][1k][ID: [MaskedID]1854] contained no valuable
items
09:34:51 [Salvage] [1][::2] Activating tractorbeam [2] on [Sanshas Transport Ship Wreck][18k][[MaskedID]1472]
09:34:52 [Salvage] Cargo Container [Cargo Container][18k][ID: [MaskedID]2328] wreck is empty, unlocking container.
09:34:53 [CombatMissionCtrl[1].LootItem [target: Cargo Container] [item: Confiscated Viral Agent]] Approaching target
[Sanshas Transport Ship Wreck][[MaskedID]1472] which is at [18k away]
09:34:53 [Salvage.LootWrecks] We have already looted [9000978782000031854]
09:34:55 [Salvage] Cargo Container [Cargo Container][17k][ID: [MaskedID]2328] wreck is empty, unlocking container.
09:34:56 [Salvage] Debug: containersInRange count [0]
09:34:59 [Salvage] Debug: containersInRange count [0]
09:35:02 [Salvage] Debug: containersInRange count [0]
09:35:05 [Salvage] Debug: containersInRange count [0]
09:35:07 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 8 ] minutes.
09:35:08 [Salvage] Debug: containersInRange count [0]
09:35:12 [Salvage] Debug: containersInRange count [0]
09:35:15 [Salvage] Debug: containersInRange count [0]
09:35:18 [Salvage] Debug: containersInRange count [0]
09:35:20 [Salvage] Cargo Container [Sanshas Transport Ship Wreck][1k][ID: [MaskedID]1472] within loot range,
unlocking container.
09:35:21 [Salvage] Opening container [Sanshas Transport Ship Wreck][0k][ID: [MaskedID]1472]

Going to keep run to check again with out using a tractor beam.

**Comment by ISeeDEDPpl** [comment]
I am not seeing the issue in the logs, if its showing up there... seems to me that if we were marking "the wrong" wreck as looted this issue would have come up before now. 

If the problem is decipherable in the logs please point it out...

**Comment by Pluckyduck** [comment]
09:34:50 [Salvage.LootWrecks] Found [1] items in [Sanshas Transport Ship Wreck][1k][[MaskedID]1854]
09:34:50 [Salvage.LootWrecks] [Crash] is not the mission item and is considered Contraband: ignore it
09:34:50 [Salvage.LootWrecks] Container [Sanshas Transport Ship Wreck][1k][ID: [MaskedID]1854] contained no valuable
items
09:34:51 [Salvage] [1][::2] Activating tractorbeam [2] on [Sanshas Transport Ship Wreck][18k][[MaskedID]1472]
09:34:52 [Salvage] Cargo Container [Cargo Container][18k][ID: [MaskedID]2328] wreck is empty, unlocking container.
09:34:53 [CombatMissionCtrl[1].LootItem [target: Cargo Container] [item: Confiscated Viral Agent]] Approaching target
[Sanshas Transport Ship Wreck][[MaskedID]1472] which is at [18k away]
09:34:53 [Salvage.LootWrecks] We have already looted [9000978782000031854]
09:34:55 [Salvage] Cargo Container [Cargo Container][17k][ID: [MaskedID]2328] wreck is empty, unlocking container.

I had to watch it to catch it, it added crash that was 1k away in a wreck to the contraband but also said the 18k cargo container was emtpy(this has the lootitem in it). from what it seems, that once it added the contraband item, it added everything that it was in range and approaching.

**Comment by ISeeDEDPpl** [comment]
odd: that logging is only triggered if you dont have a salvager fitted AND _directEntity.IsEmpty is true.
that means that DE is telling us that the container at 17k is empty.

**Comment by Pluckyduck** [comment]
when i manually went up to it, looted fine.

**Comment by ISeeDEDPpl** [comment]
Something in DE/EVE is causing this bug as noted above. I can disable the "if the wreck is empty and we dont have a salvager ignore that wreck" stuff if needed, but seems a shame to ignore a DE/EVE bug if we can get a DE dev to look into it and fix it.

**Comment by ISeeDEDPpl** [comment]
This should no longer occur. If it happens again please re-open with as much detail as possible.
