### ISSUE TITLE
QuestorManager (and BuyLPI.exe?) LP Buyer Exception

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#518]
http://privatepaste.com/173bc12452

It's really useful option because manual search of specific implants takes much time.

**Comment by ISeeDEDPpl** [comment]
How are you starting QuestorManager? 
somehow:
System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
isnt returning the location where QuestorManager.exe (and more importantly invtypes.xml) is located.

Is it possible that you dont have a InvTypes.xml in your .net Programs directory (or whatever dir holds your questor.exe and questormanager.exe files)?

More details on exactly what lead to that exception would potentially be useful.

**Comment by oldmeat** [comment]
This error appear when i start Lp buyer from gui. When i start from console: dotnet q1 questormanager then 
[QuestorManager] Start
[QuestorManager] BuyLPI: Begin
[LPStore] Opening loyalty point store
and nothing happens
