### ISSUE TITLE
user errors on 9021bffda08bfdf02e Bleeding edge

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#519]
9021bffda08bfdf02e

is trying to fire weapons during reloads, causing exceptions during missions .

i had the weapons ungrouped.... i sent a lot!  =(

setting up log now.

grouping weapons stopped the error, hard to catch this one.

checking to see if the auto reload was causing this problem. =(

**Comment by Pluckyduck** [comment]
paused and ungrouped the weapons and no still tried to reload and activate the weapons

14:16:48 [Combat] Targeting non-aggressed NPC target [Pithi Plunderer][GroupID: 615][TypeID:
17001][[MaskedID]8860][14k away]
14:16:55 [debug ReloadAll:] [ 11 ] charges in in [1] total weapons, minimum of [6] charges, MaxCharges is [36]
14:16:57 [debug ReloadAll:] [ 11 ] charges in in [1] total weapons, minimum of [6] charges, MaxCharges is [36]
14:17:00 [debug ReloadAll:] [ 11 ] charges in in [1] total weapons, minimum of [6] charges, MaxCharges is [36]
14:17:00 [Combat] Activating weapon  [1] on [Pithum Ascriber][[MaskedID]8864][22k away]
14:17:25 [Combat] Targeting high value target [Pithum Mortifier][[MaskedID]8866][33k away] highValueTargets.Count [0]
14:17:26 [debug ReloadAll:] [ 8 ] charges in in [1] total weapons, minimum of [6] charges, MaxCharges is [36]
14:17:26 [Combat] Activating weapon  [1] on [Pithi Plunderer][[MaskedID]8860][17k away]
14:17:31 [Combat] Targeting low  value target [Pithi Wrecker][[MaskedID]8862][7k away] lowValueTargets.Count [0]
14:17:34 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 8 ] minutes.
14:17:36 [debug ReloadAll:] [ 7 ] charges in in [1] total weapons, minimum of [6] charges, MaxCharges is [36]
14:17:36 [Combat] Activating weapon  [1] on [Pithum Mortifier][[MaskedID]8866][34k away]
14:18:07 [Combat] Reloading [1] with [Scourge Heavy Missile][50][TypeID: 209]
14:18:07 [Combat] Reloading [2] with [Scourge Heavy Missile][50][TypeID: 209]
14:18:07 [Combat] Reloading [3] with [Scourge Heavy Missile][50][TypeID: 209]
14:18:07 [Combat] Reloading [4] with [Scourge Heavy Missile][50][TypeID: 209]
14:18:07 [Combat] Reloading [5] with [Scourge Heavy Missile][50][TypeID: 209]
14:18:07 [Combat] Reloading [6] with [Scourge Heavy Missile][50][TypeID: 209]
14:18:09 [debug ReloadAll:] We are already reloading, wait
14:18:09 [Combat] Activating weapon  [1] on [Pithum Mortifier][[MaskedID]8866][36k away]
14:18:09 [debug ReloadAll:] We are already reloading, wait
14:18:09 [Combat] Activating weapon  [2] on [Pithum Mortifier][[MaskedID]8866][36k away]
14:18:09 [debug ReloadAll:] We are already reloading, wait
14:18:09 [debug ReloadAll:] We are already reloading, wait

paused and ungrouped the weapons and no still tried to reload and activate the weapons.

**Comment by ISeeDEDPpl** [comment]
yeah, autoreload is likely the problem... I'll look into it.

**Comment by Pluckyduck** [comment]
did not have a problem with it after i grouped the weapons back to a single group

**Comment by ISeeDEDPpl** [comment]
this should now be fixed in bleedingedge.

**Comment by Pluckyduck** [comment]
i will test out, but took a little bit of watching but i did end up seeing errors after i grouped them but not the spam to the spam Nth level with them ungrouped.  thanks @ISeeDEDPpl
