### ISSUE TITLE
Tank speed

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#52]
in the last version questor not tank speed, arrive in the mission and not move if is in target range

**Comment by ISeeDEDPpl** [comment]
this was a bug a week ago that is supposed to be fixed. 

'
if (Settings.Instance.SpeedTank)
            {   //this should be only executed when no specific actions
                if (DateTime.Now > Cache.Instance.NextOrbit)
                {
                    if (target.Distance + (int)Cache.Instance.OrbitDistance < Cache.Instance.MaxRange)
                    {
                        //Logging.Log("MissionController." + _pocketActions[_currentAction] + ": StartOrbiting: Target in range");
                        if (!Cache.Instance.IsApproachingOrOrbiting)
                        {
                            Logging.Log("We are not approaching nor orbiting");
                            var orbitStructure = true;
                            var structure = Cache.Instance.Entities.Where(i => i.GroupId == (int)Group.LargeCollidableStructure || i.Name.Contains("Gate") || i.Name.Contains("Beacon")).OrderBy(t => t.Distance).OrderBy(t => t.Distance).FirstOrDefault();

```
                        if (orbitStructure && structure != null)
                        {
                            structure.Orbit((int)Cache.Instance.OrbitDistance);
                            Logging.Log("MissionController." + _pocketActions[_currentAction] + ": Initiating Orbit [" + structure.Name + "][ID: " + structure.Id + "]");
                        }
                        else
                        {
                            target.Orbit(Cache.Instance.OrbitDistance);
                            Logging.Log("MissionController." + _pocketActions[_currentAction] + ": Initiating Orbit [" + target.Name + "][ID: " + target.Id + "]");
                        }
                        Cache.Instance.NextOrbit = DateTime.Now.AddSeconds((int)Time.OrbitDelay_seconds);
                        return;
                    }
                }
                else
                {
                    Logging.Log("MissionController." + _pocketActions[_currentAction] + ": Possible out of range. ignoring orbit around structure");
                    target.Orbit(Cache.Instance.OrbitDistance);
                    Logging.Log("MissionControllercode." + _pocketActions[_currentAction] + ": Initiating Orbit [" + target.Name + "][ID: " + target.Id + "]");
                    Cache.Instance.NextOrbit = DateTime.Now.AddSeconds((int)Time.OrbitDelay_seconds);
                    return;
                }
            }
        }
```

'

**Comment by ISeeDEDPpl** [comment]
the code above is in missioncontroller... and looks to me like it should work in all cases. I have not had another other reports of it not working. Could you please verify that you are working with the latest version of experimental?

https://github.com/ISeeDEDPpl/Questor

if it is not working please include some of the console output when you enter a pocket.
