### ISSUE TITLE
Storyline decline

### ISSUE THREAD

**Issue by yomon598** [ISeeDEDPpl/Questor#520]
Hey! Modified Questor to actually decline storyline missions, as I find it useful, so edited AgentInteraction.cs, so for the storyline missions, it looks like:

```
if (_States.CurrentStorylineState == StorylineState.DeclineMission || _States.CurrentStorylineState == StorylineState.AcceptMission)
            {

                Logging.Log("AgentInteraction.DeclineMission", "Saying [Decline]", Logging.Yellow);
                //Cache.Instance.Mission.RemoveOffer();
                _States.CurrentStorylineState = StorylineState.Idle;
                _States.CurrentCombatMissionBehaviorState = CombatMissionsBehaviorState.GotoBase;
                _States.CurrentAgentInteractionState = AgentInteractionState.Idle;

                decline.Say();
                _nextAgentAction = DateTime.UtcNow.AddSeconds(Cache.Instance.RandomNumber(3, 7));
                //Cache.Instance.AgentBlacklist.Add(Cache.Instance.CurrentStorylineAgentId);
                //Statistics.Instance.MissionCompletionErrors = 0;
                return;


            }
```

The problem is that GenericCombatStoryline, unlike the normal combat behavior, uses AgentInteraction.Purpose = AgentInteractionPurpose.AmmoCheck, which, in AgentInteraction.DeclineMission causes a "deadlock", because of : 

```
if (Purpose == AgentInteractionPurpose.AmmoCheck)
            {
                if (Settings.Instance.DebugDecline) Logging.Log("AgentInteraction.DeclineMission", "if (Purpose == AgentInteractionPurpose.AmmoCheck) return", Logging.Debug);

                return;
            }
```

What do you think the best fix would be for this? Changing  Purpose to AgentInteractionPurpose.StartMission fixes this, but I'm not familiar to everything that goes on in Questor yet and also, it doesn't seem like the intuitive best way.
Thanks for any suggestions.

**Comment by ISeeDEDPpl** [comment]
odd that seems like a glaring bug to me. Ive fixed that in bleedingedge. 
I added a new setting: `<declineStorylinesInsteadofBlacklistingfortheSession>false</declineStorylinesInsteadofBlacklistingfortheSession>`
it defaults to false, but you can set it true for the behavior you are looking for. 
by default the behavior stays the same (sans the bug I just fixed)

**Comment by ISeeDEDPpl** [comment]
you may already realize that you can now add storylines to your blacklist and it will decline any blacklisted storyline. nice addition. Note: it will also use your greylist if configured and decline certain storylines if your standings are above your configured greylist threshold.

**Comment by Pluckyduck** [comment]
I was adding them in the grey/black for an approved/disapproved fashion so that i could configure if i had the require ship or xml needed for each mission.

but being able to decline them, could be nice.  Would this limit the way i am doing that?  I do not want to decline all of them but just not do them until i have got the character ready for them?

**Comment by ISeeDEDPpl** [comment]
if you do not change your settings the current behavior is the same as it was.
