### ISSUE TITLE
Cache.CheckifRouteIsAllHighSec is bugged

### ISSUE THREAD

**Issue by yomon598** [ISeeDEDPpl/Questor#521]
Missed a zero, should be 60000000, instead of 6000000, so this would still return true for a route that goes through low sec.
Prolly this wasn't spotted before because it seems people tend to their storylines manually, in part.

**Comment by ISeeDEDPpl** [comment]
I'll fix...
personally I just keep my mission hub far far away from lowsec =) Of course the last time I had to pick a new system was before that feature existed =/

**Comment by Pluckyduck** [comment]
it is nice if you can do it but some times, you need to move =)
