### ISSUE TITLE
LootItem issue

### ISSUE THREAD

**Issue by yomon598** [ISeeDEDPpl/Questor#522]
If for some reason you are already approaching the container that's the target of the LootItem command, the command can fail - wait indefinitely.This happens, for example, if you issue a MoveTo/MoveToBackground command to the default scoop distance, as it uses KeepAtRange, which questor sees as an approach, so it deducts that it's approaching the container, yet it will never get within Distances.SafeScoopRange.

As a side question, as I looked through EntityCache.cs, was wondering, shouldn't it set 
Cache.Instance.Approaching = this; just after the _directEntity.Approach(); call rather than at the start, where it does now? Also, maybe set  Cache.Instance.Approaching = null; in the catch block ?
Cheers!

**Comment by ISeeDEDPpl** [comment]
good catch!
