### ISSUE TITLE
Combat.ProcessState System.NotImplementedException

### ISSUE THREAD

**Issue by rmrfslash** [ISeeDEDPpl/Questor#524]
http://pastebin.com/uGrEuXy9

**Comment by rmrfslash** [comment]
fresh bleedingedge branch w/ DE 1.330.5163.40583

**Comment by Pluckyduck** [comment]
As stated above, with guns drooped or not.  almost reloaded and reloaded fully with same rewsults.

http://privatepaste.com/f15dc45c9d/5135

**Comment by Pluckyduck** [comment]
Updated to DE and tested again with older build that does not have all @ISeeDEDPpl updates in it. 

build is based on Questor-adf96cd78345b4820be36fb03635bd8688a69f52
and updated to:
Questor-004cf4b3eaacdfc5f2e400dce9b54f4a1747f15e (14 Feb 2014)

I have not merged in anything past this build and what looks like could be causing this major problems would be @https://github.com/ISeeDEDPpl/Questor/tree/6cb81f68f2ce2b1fab7311c26dd91958d435eda6

i am still seeing some thing wrong in the monitor so this is not a "everything is clear to go update"

**Comment by ISeeDEDPpl** [comment]
this should now be fixed in bleedingedge.
