### ISSUE TITLE
Combat.ReloadNormalAmmo System.NotImplementedException

### ISSUE THREAD

**Issue by rmrfslash** [ISeeDEDPpl/Questor#525]
http://pastebin.com/FzgnsuLS

**Comment by rmrfslash** [comment]
fresh bleedingedge branch w/ DE 1.330.5163.40583

**Comment by rmrfslash** [comment]
I think it didn't load the correct ammo initially

**Comment by ISeeDEDPpl** [comment]
this should be fixed in bleedingedge.
