### ISSUE TITLE
Tractor beam priority issue

### ISSUE THREAD

**Issue by yomon598** [ISeeDEDPpl/Questor#527]
As we talked on IRC, opening an issue for the Salvager problem.
Questor starts approaching the container in which the target item of the LootItem action resides, however it prioritizes wrecks for the tractor beams, so, as long as there are other lootables around, it won't tractor the cargo container, wasting time.Not a serious issue, but less than optimal I guess.

**Comment by ISeeDEDPpl** [comment]
fixed here: https://github.com/ISeeDEDPpl/Questor/commit/683f6fa1588829996c5196ed1987261bbb95185a

please test.
