### ISSUE TITLE
reload errors still happening https://github.com/ISeeDEDPpl/Questor/commit/4016bfdf54b55aee5b9f3b6cfd7be22ddd17413c

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#528]
still getting reload errors on https://github.com/ISeeDEDPpl/Questor/commit/4016bfdf54b55aee5b9f3b6cfd7be22ddd17413c

trying to catch them in the action. been sitting here and doing nothing else......my eyes are burning....

**Comment by ISeeDEDPpl** [comment]
I just increased the delay before allowing questor to shoot again after reloading a weapon (from 12 to 18 seconds). The delay is likely different for each weapon system. If I can get the exact reload time for all the diff weapon systems (ouch!) I will customize it to not wait longer than necessary based on the type of weapon being reloaded.

**Comment by Pluckyduck** [comment]
sir!  10 seconds for everything but lazer(instant)!

**Comment by ISeeDEDPpl** [comment]
I think we have finally squished this one.
