### ISSUE TITLE
Questor not shoot

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#529]
In the latest BE commit 683f6fa1588829996c5196ed1987261bbb95185a Questor not shoot. 
Undock, go to mission, target enemies, engage drones to targets but not shoot.
http://privatepaste.com/79affb3369

**Comment by CasualBod** [comment]
Bit more info on the issue: Shooting and targeting works only **UNTIL FIRST RELOAD!** Then EVE client gives pop-up message "all weapons in group are already fully loaded". And **Q no longer engages any targets afterwards**. Nor targets new ones if weapons are activated manually.

Using grouped heavy assault missiles. Correct ammo types and weapon group defined.

ALSO: while **(aftermission) salvaging** - **does not use tractor beams on wrecks**, only targets them, then only loots ones that it slowboats within range to. Salvager modules working fine, it's just **tractor beams** that are not working.

latest subscribed DE, innerspace, Q commit 683f6fa1588829996c5196ed1987261bbb95185a

**Comment by oldmeat** [comment]
/CasualBod change post then this is not actually/ :)

**Comment by Pluckyduck** [comment]
@oldmeat is the grouped cruise missile launchers working for you?  I know you are having problems with after mission salvaging?  Please clarify.

**Comment by oldmeat** [comment]
I try with grouped and ungrouped and not working. When i test yesterday i ungroup weapons and he start shoot as long as have ammo in bays, after reload again not shoot.  When he shoot from  ungrouped weapons then not shot from all, one sometimetes two bays not use.

**Comment by oldmeat** [comment]
About after mission salvaging, i test few commits before and Questor not use tractor beams.

**Comment by oldmeat** [comment]
I test master version, and the same not shoot

**Comment by oldmeat** [comment]
the latest logs wits debugActivateWeapons on true: http://privatepaste.com/873a17fda3

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge. If you continue to have problems please reproduce the log.

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/ac43582dabee0cce39759b1f8fdcabc09ba95bde
