### ISSUE TITLE
Tries to lock wreck's before exiting warp

### ISSUE THREAD

**Issue by drpetarvojvodic** [ISeeDEDPpl/Questor#53]
When doing the salvage and warping to the buckmark, a few seconds before it actually exit's warp it tries to lock surrounding wrecks.
Ma by to wait until out of warp and than try to lock wrecks.

**Comment by ISeeDEDPpl** [comment]
Good catch. Ive fixed this locally... Ill commit a fix to github tonight after its had some testing.

**Comment by ISeeDEDPpl** [comment]
this has been committed.
