### ISSUE TITLE
Tractor beams not working

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#530]
While **(aftermission) salvaging** - **does not use tractor beams on wrecks**, only targets them, then only loots ones that it slowboats within range to. Salvager modules working fine, it's just **tractor beams** that are not working.

(using Noctis for aftermissionsalvaging)

latest subscribed DE, innerspace, Q commit 683f6fa1588829996c5196ed1987261bbb95185a

**Comment by ISeeDEDPpl** [comment]
Can I get a log with 
`<debugTractorBeams>true</debugTractorBeams>`
please

**Comment by ISeeDEDPpl** [comment]
This should be fixed in bleedingedge. Please test.

**Comment by oldmeat** [comment]
I test and confirm, fixed in 1317119639a2fa4f78ebe48336257c0b3e48251a.
Issue to close
