### ISSUE TITLE
Mission name issue

### ISSUE THREAD

**Issue by yomon598** [ISeeDEDPpl/Questor#531]
Hello! If mission name contains special characters, it is parsed incorrectly.
For example, "  Are You Receiving? (1 of 3)  " is seen as "  Are You Receiving (1 of 3)  "
and "  After The Seven (4 of 5) "Ruse"  " as "  After The Seven (4 of 5) Ruse  ".
The solution is probably modifying Cache.Cs:FilterPath.

**Comment by yomon598** [comment]
My bad, the solution would probably be to use Cache.Instance.Mission.Name instead of MissionName in some places.

**Comment by ISeeDEDPpl** [comment]
better solution would be to run the blacklisted mission names through Cache.cs:FilterPath when loading them from the XML

**Comment by ISeeDEDPpl** [comment]
fixed: https://github.com/ISeeDEDPpl/Questor/commit/7ab466af4959a3d4795aa1ad3df9619614c574c9
