### ISSUE TITLE
Questormanager freeze in travel mode.

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#535]
In the latest commit: 4ae8b86ec5f2343f0ab363d7aac2b004fd786152
When i try set name solar system QM properly show system. But not possible flag any one from list because Q automaticaly clear highlights and QM freeze

**Comment by ISeeDEDPpl** [comment]
SideNote: You realize you can set autopilot (manually) and set the CombatMissionState (not QuestorState) to Traveler yes? 

That of course does not negate the fact that QuestorManagers traveler should be working, but figured I'd ask.

**Comment by oldmeat** [comment]
I did not know :) Thx

**Comment by ISeeDEDPpl** [comment]
Qm should not freeze anymore after that lat commit (2 min ago). It may however still get pissed if it hasnt had time to refresh after populating the SearchResults box. 
If it does, just press the BttnAddTraveler button again.
