### ISSUE TITLE
Afterburner management not working with SpeedTank enabled

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#536]
- Does not activate afterburner initially (at pocket start) 
- on orbit 
- on keep at range
- does not pursue targets who are not withing range of guns using afterburner. Slowboats to them instead.

I assume this only happens while speedtank is enabled, cause noone else has complained, and majority uses Chinese Navy Ravens. I'm running 30Km heavy assault tengu on speedtank.

I'll try to come up with log with debug options, regular log shows nothing in particular for now. Has been happening for at least 5 last commits. Ever since new module activation wait timers were implemented.

**Comment by ISeeDEDPpl** [comment]
This really needs a log w: 
`<debugSpeedMod>true</debugSpeedMod>`
keep in mind you can test it with a lower level mission (lvl1?)

**Comment by CasualBod** [comment]
will compile latest and will try to get logs after dt

**Comment by ISeeDEDPpl** [comment]
Fixed in bleedingedge.
