### ISSUE TITLE
Q crashes EVE process, fails to load DE.

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#537]
Q crashes EVE process, fails to load DE.

latest commit e7c14cb249
ISeeDEDPpl ISeeDEDPpl authored 3 hours ago 

Elevated Powershell compiler curses all red with compile errors.
compiling through **compile.bat** does not show any errors, just warnings.

client crashes and I was unable to capture a screenshot, but what still could be read of the window were exceptions:
Questor.modules...\cache.cs line 37 
Questor.modules...\cache.cs line 6792 

contacted oldmeat and we figured that https://github.com/ISeeD...0ab363d7aac2b004fd786152 is what still works. I rolled back to this build and it's working.

It seems that resulting binaries in /bin/debug/ are somehow broken, launching for instance file updateinvtypes.exe results in it crashing with windows error, instead of regular small program window.

**Comment by ISeeDEDPpl** [comment]
does it log nothing to file?
you can type the following at an innerspace prompt and get a log:
"
log wtf.log
dotnet q1 questor.exe
"
Then you can find the log in your innerspace directory, in this case named wtf.log
be careful when copying/pasting it, it may contain info you do not need to share. Read through it carefully and add only the necessary exception info to this issue, please.

**Comment by CasualBod** [comment]
https://privatepaste.com/c1ea815df7

the output of log. Now pasted on external link for ease of reading.

the red-alert for me is that it crashes w/o loading DE and it's security first, that could raise some flags.

latest BleedingEdge commit e7c14cb249
DE v1.330.5163.40583
InnerSpace v1.12 (5957)
Powershell 6.2.9200.16398

compiled using .bat file.

**Comment by ISeeDEDPpl** [comment]
this should now be fixed in bleedingedge / experimental / master, they are all currently equivalent

**Comment by ISeeDEDPpl** [comment]
note: you should be running exefile.exe with at least 2 command line switches.
/noBreakpadUpload - turns off the uploading of crashdumps
/noconsole - turns of the text console we dont need/use/want for eve

optionally it is also a good idea to add
"
127.0.0.1           crashes.eveonline.com
"
to: %systemroot%\system32\drivers\etc\hosts

**Comment by CasualBod** [comment]
Thank you, didn't know about parameters, had hosts done.
