### ISSUE TITLE
Loot Action on ships with no salvagers

### ISSUE THREAD

**Issue by yomon598** [ISeeDEDPpl/Questor#538]
Seems like, on ships without salvagers, the Loot action does not finish until it also checks empty wrecks.

**Comment by ISeeDEDPpl** [comment]
highly likely to be fixed here: github.com/ISeeDEDPpl/Questor/commit/e8b83ccaf0f9e8f4b598d2a04a97a6a5482fc49f

**Comment by yomon598** [comment]
Thanks!
