### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#539]
https://github.com/ISeeDEDPpl/Questor/tree/e8b83ccaf0f9e8f4b598d2a04a97a6a5482fc49f

Microsoft (R) Build Engine version 4.0.30319.18408
[Microsoft .NET Framework, version 4.0.30319.18444]
Copyright (C) Microsoft Corporation. All rights reserved.

"C:\Questor-BleedingEdge\Questor.Modules\Questor.M
odules.csproj" (Clean;Build target) (1) ->
(CoreCompile target) ->
  Caching\EntityCache.cs(4257,21): error CS0161: 'Questor.Modules.Caching.Entit
yCache.KeepAtRange(int)': not all code paths return a value [C:\Questor-BleedingEdge\Questor.Modules\Questor.Modules.csproj]

```
4 Warning(s)
1 Error(s)
```

**Comment by ISeeDEDPpl** [comment]
fixed.
