### ISSUE TITLE
<MinAgentGreyListStandings>

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#54]
18:50:52 Questor: Random start delay of [3] seconds
18:50:57 Questor: EVE instance: totalMegaBytesOfMemoryUsed - 954 MB
18:50:58 AgentInteraction: Start conversation [Start Mission]
18:50:58 AgentInteraction: Waiting for conversation
18:51:00 AgentInteraction: Replying to agent
18:51:08 AgentInteraction: Waiting for mission
18:51:13 AgentInteraction: Faction fitting: Default
18:51:13 AgentInteraction: Loading mission xml [Rogue Drone Harassment]
18:51:13 AgentInteraction: Accepting mission [Rogue Drone Harassment]
18:51:17 AgentInteraction: Saying [Accept]
18:51:17 AgentInteraction: Closing conversation
18:51:18 Questor: Wallet Balance Has Not Changed in [ 2 ] minutes.
18:51:23 AgentInteraction: Done
18:51:24 Arm: Begin
18:51:25 Arm: Activating combat ship
18:51:26 Cache: Mission: Rogue Drone Harassment - Faction: Default - Fitting: em - Ship:  - ChangeMissionShipFittings: True
18:51:27 Arm: Done Opening Item hangar: proceeding to Cargo Hold
18:51:28 Arm: Fitting
18:51:29 Arm: Fitting: em - currentFit: kin
18:51:29 Arm: Opening Fitting Manager: waiting [5sec]
18:51:35 Arm: Looking for fitting em
18:51:35 Arm: Found fitting [ em ] waiting [5sec]
18:51:35 Arm: Closing Fitting Manager
and the mission go head

the question is

I have Rogue Drone Harassmen mission in greylist

the standing with agent is +8,5

<MinAgentGreyListStandings>6.5</MinAgentGreyListStandings>

Why questor not decline the mission ???

i use your last exp branch

**Comment by ISeeDEDPpl** [comment]
I changed some logging to help debug this. please update and re-post logs

**Comment by ISeeDEDPpl** [comment]
evidentally you want to debug thi susing a new issue... closing this old one as it likely no longer pertains
