### ISSUE TITLE
QuestorManager traveler mode exceptions

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#540]
In the latest BE build: 70ff53a8bc8369accded8b693a3272efac015da3
Now QM not loop but throw exceptions
http://privatepaste.com/f81a54bbb6

**Comment by ISeeDEDPpl** [comment]
Can you get that same log with questormanager.pdb available in .net programs so we get line numbers?

**Comment by oldmeat** [comment]
are you mean use traveler on standalone dotnet questormanager questormanager?

**Comment by ISeeDEDPpl** [comment]
your description says your using questormanager. 
whatever dotnet program you are using make sure you have a *.pdb available with the *.exe you are running and reproduce the log. 
The previous log indicates the *.pdb file is not there, no line numbers...

**Comment by oldmeat** [comment]
Before i run QM from gui, now i use QM standalone and try use traveler ... when i try highlight name of station then he immediately unchecked this. Few seconds later eve crash. I don't have any exceptions in logs

**Comment by ISeeDEDPpl** [comment]
if this is still a problem I need exact reproduction steps please. logs would be great if someone can generate them. If nothing else you can type "log wtf.log" at an innerspace prompt before triggering the issue and any logging to the console will also goto wtf.log in your innerspace folder.

**Comment by oldmeat** [comment]
in the latest experimental version 72df7c8629bbf47b49796f4c65465964fe7523ea  questor manager not work. 
When i try: dotnet qm questormanager then i got message about license and gui start but not work, i try use traveler but gui not responding..

logs: 

Starting DirectEve v1.330.5217.41300
Registered to xxxx
You are currently using x of x support instances
Copyright (c) 2012 - TheHackerWithin
http://www.thehackerwithin.com

nothing more
