### ISSUE TITLE
avoidBumpingThings not working

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#544]
avoidBumpingThings>true</avoidBumpingThings

seems to be broken, does nothing to avoid collision, stays hugging large collideable objects for looooong periods of time (until it struggles-off or, in worst case, until no wallet-update shutdown

No sure  this setting ever worked correctly, but I have been bumping things surprisingly often now.

**Comment by ISeeDEDPpl** [comment]
wow, this is been broke awhile =(

fixed in bleedingedge. https://github.com/ISeeDEDPpl/Questor/commit/3095137527888942b698362ff7ecc6363c3c0762
