### ISSUE TITLE
permanent loop and crash (aftermission salvaging) - Traveler Bookmark Destination 

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#545]
latest commit 5162ee81ad

LOG:
http://privatepaste.com/3d813a0420

when doing **aftermissionsalvaging** happens when done salvaging last salvage bookmark in system.

12:32:06 [TravelerDestination.BookmarkDestination] Warping to **undock bookmark** [**salvagebookmark 1048**][0 AU away]

When done salvaging in **home-system** just **loops permanently.**

When done salvaging last bookmark **outside of home system** (1 jump away in this case), initiating call for destination to **UNDOCK BOOKMARK** (???) **crashes EVE client**.

12:47:36 [TravelerDestination.BookmarkDestination] Warping to undock bookmark [bookmark 1117][0 AU away]

it calls for undock bookmark, while **actual** bookmark that it calls is last **salvage bookmark**. in this case bookmark1117 was our last salvage bookmark.

undock settings not defined:
  undockprefix></undockprefix

  bookmarkWarpOut></bookmarkWarpOut

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge here: https://github.com/ISeeDEDPpl/Questor/commit/f057cfc8238f74f9e797976c82dba9358dd1633e
