### ISSUE TITLE
combat.cs around line 2225 add in transport name for ship as well

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#549]
if (!Cache.Instance.InWarp && !Cache.Instance.MyShipEntity.IsFrigate && !Cache.Instance.MyShipEntity.IsCruiser && Cache.Instance.ActiveShip.GivenName != Settings.Instance.SalvageShipName && Cache.Instance.ActiveShip.GivenName != Settings.Instance.TransportShipName)

**Comment by ISeeDEDPpl** [comment]
added to bleedingedge

**Comment by Pluckyduck** [comment]
thanks!
