### ISSUE TITLE
[BUG]MissionController.ClearPocket: ReloadALL: Reload if [True]

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#55]
I have sometimes a problem with the fact that the bot is hanging on a mission and does not attack the target. ISDPPL write the customer's fault or lag eve but when i push manual missiles everything returns to normal operation. http://pastebin.com/08ih551L

**Comment by oldmeat** [comment]
But target is active and visible on top window, i must only click on missile launcher and everything back to work properly.

**Comment by oldmeat** [comment]
I've noticed that now the problem occurred at a time when the launcher I have remnants of a former missile other than those needed for this mission. I manually reloaded and bot returned to normal operation.

**Comment by oldmeat** [comment]
But this does not happen every time, but from time to time.

**Comment by ISeeDEDPpl** [comment]
odd..

**Comment by ISeeDEDPpl** [comment]
try this branch:
https://github.com/ISeeDEDPpl/Questor/tree/DebugActivateWeapons

I will need the resulting logs when you experience the issue again. The logs will be spammy, but it shouldnt be too bad, a few days of logs would likely still be under a few MB...  I hope =)

**Comment by oldmeat** [comment]
Today again encountered this problem. Problems log in https://github.com/ISeeDEDPpl/Questor/tree/DebugActivateWeapons branch: http://pastebin.com/uGAUTB8j .
When i manually change old ammo in bay from exp to em, bot start work properly.

**Comment by ISeeDEDPpl** [comment]
Until I can come up with a real fix... make sure you have at least 2 groups of guns.

**Comment by oldmeat** [comment]
I have ungrouped all guns and the problem still exist. I opened two clients the same time on the same pc 2 different bots and I noticed with both of them are stuck at the same time. Of course,enough just group the weapon, reload or anything and everything returns to work

**Comment by ISeeDEDPpl** [comment]
at the same time?! that is very odd...

**Comment by ISeeDEDPpl** [comment]
can you generate that log again please. I need at least 3 min of it not working. in that log above it looks like it could have been waiting a timer to expire... Id need a longer log to confirm

The issue Dim experienced was a different issue and Dim's prob is now fixed. 
Is this issue still occurring occasionally? If so please login to IRC and convo me when you have time to discuss.
