### ISSUE TITLE
faction mission name problem

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#551]
Fitting manager is not working correct as it is not seeing the icon or something.  everything is default

was originally found this way:
Cant get it to load a fitting based on a mission that does not have a faction icon.

**Comment by Pluckyduck** [comment]
tested with vanilla build of your @ISeeDEDPpl  build as well =(

**Comment by ISeeDEDPpl** [comment]
what mission/faction is it not finding?

**Comment by Pluckyduck** [comment]
two things.
1. found this one and needs to be added to AgentInterations.cs around line 1052:
   if (Settings.Instance.UseFittingManager && !logoMatch.Success)
   (Reasoning) it will run both and if we do find the logo, it will still default to the "default" fitting
2. the faction names have to be the same as in faction.xml file, found this one after going over it a few times (user side error and not a Questor/DE)
