### ISSUE TITLE
deal with EVE's new window logging

### ISSUE THREAD

**Issue by yomon598** [ISeeDEDPpl/Questor#553]
As you may or may not be aware, EVE now logs window actions - windows being opened, with special attention to the first time a window is being open (have a look at code.ccp\abTestCore folder).Hence, a lot of changes are probably needed:
- randomization of timing when windows are open, especially the first time they are open
- cleanup of all redundant window close/open
- assure that normal course of action is being taken everywhere (window is opened before doing anything related to it ) - this is probably already true though
- less important as it's probably harder to implement - a bit of randomization of the actions taken - e.g. don't always use the same in station sequence to arm, if window closing/opening is involved (don't always repair/open dronebay in same order and so on).
  The windows that are currently being monitored, as far as I remember:
- character selection click
- mail
- wallet
- corporationpanel
- assets
- journal
- charactersheet
- peopleandplaces
- help
- inventory
- market
- scienceandindustry
- fitting
- repairshop
- insurance
- bountyoffice
- militia
- reprocessing
- store

That means it can be considered all window interaction is monitored.Oh, and windows that are being reopened automatically (on session change, for example) are not logged.
P.S. As you mentioned Ferox's branch, he said in station whole process thing takes a lot less in his, so a review would be awesome, with all the window thing in mind.In any case, thanks!

**Comment by ISeeDEDPpl** [comment]
Notes Inline:
- randomization of timing when windows are open, especially the first time they are open
  `in relation to our own startup time? doable. 
  At the moment we only track the last time the window was open and make sure we do not attempt to re-open it too quickly (most are set to a number of single digit seconds)`
- cleanup of all redundant window close/open
  `This will likely need logging of our own to see. We do close windows that will need to be re-opened, but so do players. (drone windows, ship hangars, etc) The biggest issue will be when and how non-random the timing is. the logging I'll add will help us see that.`
- assure that normal course of action is being taken everywhere (window is opened before doing anything related to it ) - this is probably already true though
  `This may not be true with all inventory stuff. Most, yes, but not all.`
- less important as it's probably harder to implement - a bit of randomization of the actions taken - e.g. don't always use the same in station sequence to arm, if window closing/opening is involved (don't always repair/open dronebay in same order and so on).
  `this is doable, but will take some refactoring in arm. I'll add it to the todo.`

The windows that are currently being monitored, as far as I remember:
- character selection click *barely use it, I'll add some more randomization to the timing in the login routine.
- mail  \* questor does not yet use it
- wallet \* questor does not yet use it
- corporationpanel (I assume this is the corp panel, not the corp hangar) \* questor does not yet use it
- assets \* questor does not yet use it, but could, noted.
- journal \* questor uses it, but keeps it open, only opening it once upon startup. Adding a random delay to this should be doable.
- charactersheet \* questor does not yet use it, but could, noted.
- peopleandplaces \* questor does not yet use it, but could, noted.
- help \* questor does not yet use it
- inventory
- market \* questor does yet use it, but not often, this may need TLC. 
- scienceandindustry \* questor does not yet use it
- fitting \* this may need TLC
- repairshop \* this may need TLC
- insurance \* questor does not yet use it
- bountyoffice \* questor does not yet use it
- militia \* questor does not yet use it
- reprocessing \* this may need TLC
- store \* questor does not yet use it

I'll use the above list to prioritize the order things get tackled in. thank you.
