### ISSUE TITLE
(Request) new kill action based on target stats

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#555]
Add to the existing function of kill so that we can destroy targets to a preset damage reading (example for agro control: damsel in distress)
      ....action name="Kill">
        ...parameter name="IgnoreAttackers" value="true" />
        ...parameter name="BreakOnAttackers" value="true" />
        ...parameter name="NotClosest" value="true" />
        ...parameter name="NumberToIgnore" value="50" />
        ...parameter name="AttackUntilBelowShield" value="50" /> **************
        ...parameter name="AttackUntilBelowArmor" value="50" /> **************
        ...parameter name="Target" value="Dim" />
      .../action>

**Comment by ISeeDEDPpl** [comment]
yeah, I actually like that much better... very easy to add too.

**Comment by ISeeDEDPpl** [comment]
done. please test.

**Comment by Pluckyduck** [comment]
will test in a few days  and thanks
