### ISSUE TITLE
(Request) Improve login delays

### ISSUE THREAD

**Issue by duketwo** [ISeeDEDPpl/Questor#556]
Ferox improved the login behaviour in his recent build a lot by reducing the delays. 
Probably a random 1-3s delay after AtLogin,Server Status == OK && AtCharsel is enough?

Always getting bored when ill try to test something using autologin :/

or make the delays modifyable by the xml, instead of using static min, max values

**Comment by ISeeDEDPpl** [comment]
The way program.cs and questor.cs are structured at the moment we cant/dont load the character XML until after the account is logged in and character selected and logging in.

It is on my todo list to fix that, but its non-trivial.

There are still hard coded delays in time.cs, but there are more of them and the delays are reduced. feel free to adjust them and recompile (not perfect but workable). Latest BleedingEdge should be MUCH faster and more customizable.

**Comment by duketwo** [comment]
we're still having a >40 second delay on both loginsteps because 
public int QuestorBeforeLoginPulseDelay_seconds = 40; is used as local pulse delay. 
ive tried with 5 seconds, works good.

**Comment by duketwo** [comment]
if (ServerStatusCheck <= 6){
                    ServerStatusCheck++;
                    _nextPulse = DateTime.UtcNow.AddSeconds(30);
                    return;
}

Can we reduce this also to somewhat lower? Because often the server status isn't already loaded when we start questor, then were stuck for another 30

**Comment by ISeeDEDPpl** [comment]
fixed both. thank you.
