### ISSUE TITLE
All equipped salvagers group on same wreck

### ISSUE THREAD

**Issue by Raudkoer** [ISeeDEDPpl/Questor#560]
While it is needed for low skill pilot,it IS wasting time and lowering Isk/Hr for more trained pilots.

**Comment by ISeeDEDPpl** [comment]
The spreading of tractors is working as intended though? just not salvagers?

**Comment by Raudkoer** [comment]
Yes,personally using 6 tractors 2 salvagers,will try even 7 tractors 1 salvager,,,at 95 km tractor range-takes long time to pull,then to salvage wrecks

**Comment by Raudkoer** [comment]
3 salvagers-5 tractors,still groups all 3 salvagers,plenty of wrecks within 6000 m (4-5)

**Comment by Raudkoer** [comment]
using old build toonname.xml (cos i hate reworking those),change was in toonname.xml?

**Comment by ISeeDEDPpl** [comment]
no, not in this case. logs would help. 

unrelated to this: use winmerge (or similar tool) to merge the 2 XMLs

**Comment by ISeeDEDPpl** [comment]
ok, this should now be fixed. If it still reoccurs after updating I will need a console log with debugSalvage set to true.

thank you!

**Comment by Raudkoer** [comment]
still salvages as grouped,switched logging on
