### ISSUE TITLE
(Push) do not use EW on Zor

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#562]
on combat.cs

Mod this:

if (killTarget.IsReadyToShoot)
                            {
                                i++;
                                if (Settings.Instance.DebugKillTargets) Logging.Log("Combat.KillTargets", "[" + i + "] Activating Bastion", Logging.Debug);
                                ActivateBastion(); //by default this will deactivate bastion when needed, but NOT activate it, activation needs activate = true
                                if (!killTarget.Name.Contains("Zor"))
                                {
                                    if (Settings.Instance.DebugKillTargets) Logging.Log("Combat.KillTargets", "[" + i + "] Activating Painters", Logging.Debug);
                                    ActivateTargetPainters(killTarget);
                                    if (Settings.Instance.DebugKillTargets) Logging.Log("Combat.KillTargets", "[" + i + "] Activating Webs", Logging.Debug);
                                    ActivateStasisWeb(killTarget);
                                    if (Settings.Instance.DebugKillTargets) Logging.Log("Combat.KillTargets", "[" + i + "] Activating WarpDisruptors", Logging.Debug);
                                    ActivateWarpDisruptor(killTarget);
                                    if (Settings.Instance.DebugKillTargets) Logging.Log("Combat.KillTargets", "[" + i + "] Activating RemoteRepairers", Logging.Debug);
                                    ActivateRemoteRepair(killTarget);
                                    if (Settings.Instance.DebugKillTargets) Logging.Log("Combat.KillTargets", "[" + i + "] Activating NOS/Neuts", Logging.Debug);
                                    ActivateNos(killTarget);
                                    if (Settings.Instance.DebugKillTargets) Logging.Log("Combat.KillTargets", "[" + i + "] Activating SensorDampeners", Logging.Debug);
                                    ActivateSensorDampeners(killTarget);
                                }
                                else
                                {
                                    if (Settings.Instance.DebugTargetElectronicWarefare) { Logging.Log("Debug Electronic Warefare mod", "we can not activate them on Zor and skipped the check", Logging.Debug); }
                                }

**Comment by Pluckyduck** [comment]
here is the same thing posted in http://privatepaste.com/9c79500ae3/12356

The main thing that i did was add all of the electronic warfare stuff under the conditional statement to make sure the target was not Zor, he is protected and this causes errors as we can activate on him.

**Comment by ISeeDEDPpl** [comment]
fixed this a little differently. behaves the same. 
thank you!
