### ISSUE TITLE
(request) when lagging out.

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#563]
when lagging out and Questor has started a new timedcommand to restart the client, can we send a close client.  I recovered from a lag event today and got into a licence loop failure.

**Comment by Pluckyduck** [comment]
will add in suggestion as soon as i get one.

**Comment by ISeeDEDPpl** [comment]
Logs? It should have closed the existing eve client during the DirecteveDispose

`public static void DirecteveDispose()`
`{`
`Logging.Log("Questor", "started calling DirectEve.Dispose()", Logging.White);`
`Cache.Instance.DirectEve.Dispose(); //could this hang?`
`Logging.Log("Questor", "finished calling DirectEve.Dispose()", Logging.White);`
`Process.GetCurrentProcess().Kill();`
`Environment.Exit(0);`
`}`

**Comment by ISeeDEDPpl** [comment]
this should no loner occur. please let me know if you see anything similar.
