### ISSUE TITLE
Modules not work and in station odd behavior

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#567]
I test yesterday BE build on L2 missions. 
Questor not turn on any modules, hardeners, afterburners, sensor boosters.
Only use missile bays. 

And on station, when unload all loot from ship to hangar he open and close hangar 9 times.

**Comment by ISeeDEDPpl** [comment]
should all be working today. there were a few small bugs that caused big issues =/ 
afaik they are all fixed. please reply to this issue if you are still having trouble with: 268f8e4872a01ad1f492341bcc3637af19cbfc53

**Comment by oldmeat** [comment]
I test now the latest build 2e7c11ea4593b0ded848bbe1fde2caa30fe7cc36.
Questor hangup when gui start, not crash only not respond...

**Comment by ISeeDEDPpl** [comment]
fixed. any other issues to report w: c08955210fd5d666b9ff786130c6bf0f8346d0ea
?

**Comment by oldmeat** [comment]
bbea424b6923f5c8c003246c0236c02569ed7acd
Now gui start properly. I have set autostart false. I turn on autostart on gui. Questor unload loot on station and go to idle and nothing happens ... few seconds after this RG terminated process. 

xx:xx:31 [CombatMissionsBehavior] UnloadLoot: Begin
xx:xx:36 [CombatMissionsBehavior.Unloadloot] CharacterMode: [Combat Missions], AfterMissionSalvaging: [False], CombatMissionsBehaviorState: [Idle]
xx:xx:36 [Questor] Start Mission Behavior

**Comment by ISeeDEDPpl** [comment]
that was a different bug, should all be fixed now. if you are having trouble please open an issue w logs.
