### ISSUE TITLE
The latest build not work properly

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#569]
In the latest build:

Questor-82d0cfec26180b2a4b1c346ed8271ea0a7f89df6

Questor start properly, get and accept mission and:

18:34:34 [LoadSpecificAmmo] Clearing existing list of Ammo To load
18:34:34 [LoadSpecificAmmo] Adding [Scourge Light Missile] to the list of MissionAmmo to load
18:34:35 [AgentInteraction] Saying [Accept]
18:34:37 [AgentInteraction] Attempting to close Agent Window
18:34:38 [AgentInteraction] Done
18:34:38 [Arm] Begin
18:34:42 [] missionForBookmarkInfo.State: [1]
18:34:42 [] missionForBookmarkInfo.AgentId: [xxx]
18:34:42 [] agentId: [xxx]

and questor have state Execute Mission but stay in station

**Comment by Cyrixx** [comment]
Yes, I also have problems, Q does not take ammo and drones and cap booster, not reload launchers, writes in the console of the absence of drones / ammo in hangars (they're just there!). please tell me what the latest stable build?

**Comment by oldmeat** [comment]
I use very old build, from more than 1 year ago

**Comment by ISeeDEDPpl** [comment]
the reason this issue was opened should be fixed. 

If their are other issues please create another  and attach the relevant logs. 
If you are having trouble with Arm the logs will probably show the location of the bug with debugArm and debugHangars both set to true.

**Comment by oldmeat** [comment]
Q not take ammo and go to mission with empty cargo and back to station and again go to mission without ammo....
When i compile the latest BE 2342b06ed82a444eefe17273018c7f12a8630634 then i get very many warnings ... about 30
06:43:59 [AgentInteraction] Mission XML specified the Mission Damagetype for [xxx] is [Kinetic]
06:43:59 [LoadSpecificAmmo] Clearing existing list of Ammo To load
06:43:59 [LoadSpecificAmmo] Adding [Scourge Light Missile] to the list of MissionAmmo to load
06:44:01 [AgentInteraction] Attempting to close Agent Window
06:44:01 [AgentInteraction] Done
06:44:02 [Arm] Begin
06:44:06 [CombatMissionsBehavior] Setting Destination to 1st bookmark from AgentID: xxx with [Encounter] in the title
06:44:06 [TravelerDestination.MissionBookmarkDestination] Destination set to mission bookmark [Encounter (Deadspace) -
Hilaban]
06:44:06 [CombatMissionsBehavior] MissionSolarSystem is [DirectEve.DirectLocation]

...

06:42:53 [Combat] ReloadNormalAmmo: not enough [Kinetic] ammo in cargohold: MinimumCharges: [6]
06:42:53 [Combat] Out of Ammo!

**Comment by ISeeDEDPpl** [comment]
regenerate that log with debugArm and debugHangars both true please.

**Comment by oldmeat** [comment]
I download the latest BE 054479cb7701cf00dba4b0aade5d4fa89ec8edd6
This time Q stop in last line ... 

http://privatepaste.com/fba3f11e1a

**Comment by oldmeat** [comment]
Now i test: 1cc9b9914bc31e39d41b4f8d3779754393c9fc31
Q properly get ammo but not undock ... stay in the same moment.

The same last line in before logs:

07:04:38 [CombatMissionsBehavior] We have no mission bookmark available for our current/normal agent
07:06:35 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 2 ] minutes.

and when i close questor gui then i got exception: 

http://privatepaste.com/c3bb476205

**Comment by ISeeDEDPpl** [comment]
yeah, that last exception is harmless. its a side effect of how we are unloading the appdomain at exit.

Ive made 2 more commits fixing bugs in arm and reload.
both arm and reload are now working for me. please try again with bleedingedge.

**Comment by oldmeat** [comment]
still stuck on:
[CombatMissionsBehavior] We have no mission bookmark available for our current/normal agent

and not undock

**Comment by ISeeDEDPpl** [comment]
multiple agents? storyline mission? anything special about this mission?

**Comment by ISeeDEDPpl** [comment]
even after restarting eve? (not just questor)...

**Comment by ISeeDEDPpl** [comment]
I just added more logging to MissionSettings.GetMissionBookmark, please update/recompile and try again. I will nee the logs if its still failing for you.

**Comment by oldmeat** [comment]
after restart eve, works fine :)

**Comment by oldmeat** [comment]
I close this issue now, if i find another bugs then i open new issue. Thx
