### ISSUE TITLE
Serious problem with ammo

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#572]
I set in mission xml damage type Kinetic, and Q get from station properly ammunition,
but on mission he want other ammo (EM) and back to station.

http://privatepaste.com/9664123262

**Comment by ISeeDEDPpl** [comment]
please re-test this. I have made some changes that should keep this from re-occurring.

**Comment by oldmeat** [comment]
When my ship back from mission and try unload ammo then loop and nothing happens

04:57:40 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:41 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:41 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:42 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:42 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:43 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:43 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:43 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:44 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:44 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:45 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:45 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)
04:57:45 [UnloadLoot.MoveAmmo] if (Cache.Instance.CurrentShipsCargo == null)

**Comment by ISeeDEDPpl** [comment]
ok, update and try again pls. 72df7c8629bbf47b49796f4c65465964fe7523ea should resolve that.

**Comment by oldmeat** [comment]
fixed in https://github.com/ISeeDEDPpl/Questor/commit/72df7c8629bbf47b49796f4c65465964fe7523ea thx
