### ISSUE TITLE
Q don't take drones

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#573]
In the latest exp 72df7c8629bbf47b49796f4c65465964fe7523ea
Q don't take drones and go to mission without drones.

11:55:28 [AgentInteraction] Done
11:55:28 [Arm] Begin
11:55:29 [Arm.MoveDrones] MoveDrones
11:55:32 [Arm.MoveAmmo] Moving [5000] units of Ammo [Mjolnir Fury Cruise Missile] from [ AmmoHangar ] to CargoHold
11:55:34 [Arm.MoveAmmo] Done
11:55:36 [GetMissionBookmark] MissionBookmark Found
...

**Comment by ISeeDEDPpl** [comment]
this should now be fixed in bleedingedge. please test.
54bf7bbd9fe91a65ee020d5d9e3085afcc3804ee

**Comment by oldmeat** [comment]
fixed in the latest experimental
