### ISSUE TITLE
Questor stuck when repair

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#575]
In the latest exp and BE.
When Q open repair window then not confirm repair cost and stuck.

http://privatepaste.com/0f260b81f8

**Comment by ISeeDEDPpl** [comment]
when this occurs please change the questor GUI 1st combobox to DebugWindows and provide the logs here. Specifically I need the data from the repair window... a screenshot showing the repair window (everything else can be cropped out) may be helpful too.

**Comment by oldmeat** [comment]
This is screen shot:
http://i59.tinypic.com/fz6q2p.jpg
and this is logs:
http://privatepaste.com/df39d27d5b

**Comment by ISeeDEDPpl** [comment]
fixed. incidentally this change by ccp seem to indicate that questor may have trouble closing other windows in future EVE patches. if you notice other windows not closing I will need similar screenshots and debugWindows logs.
