### ISSUE TITLE
DirectEve.Dispose() not work

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#576]
Eve not closed.
http://privatepaste.com/a04668a07b

**Comment by ISeeDEDPpl** [comment]
DirectEve.Dispose() works fine. that call releases DirectEVE licenses. in what scenario are you noticing EVE not closing when you think it should? I need more of the console logs please.

There are times when we restart EVE and times when we just shutdown questor (and leave EVE up to be manually restarted if desired). generally if you dont push buttons and quesor wants to restart on its own it kills the current EVE session so the new session that it scheduled in the innerspace uplink can take over. (Note: this restarting does NOT yet work when standalone! although it probably could with a little effort)

**Comment by oldmeat** [comment]
This problem appear when Q stuck after repair problem. When i manually confirm this repair window then i see dispose not close eve window. I close now, when i get this problem again then i open again.
