### ISSUE TITLE
Decline mission problem

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#578]
Q stuck after decline mission:
http://i60.tinypic.com/2czromf.jpg

**Comment by ISeeDEDPpl** [comment]
Odd, can I get the output from DebugWindows for that? there seems to be something changed there...

**Comment by oldmeat** [comment]
Now i get exceptions when he decline mission: 

http://privatepaste.com/aa9ceda0bb

**Comment by ISeeDEDPpl** [comment]
did you have that file: [ C:\Program Files (x86)\InnerSpace.NET Programs\SessionDataCache\xxx\agents__mission_decline_times.csv ]
open in another program? excel? notepad? its saying it cant write to that file because it is in use.

**Comment by oldmeat** [comment]
nope, but this time i close few minutes before gui and launch questor from console again dotnet q1 questor ... maybe he not close link from previous session. Next time i put logs from debug Windows.

**Comment by ISeeDEDPpl** [comment]
if this is still an issue please re-open w the requested logs.
