### ISSUE TITLE
Out of ammo problem

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#579]
In the latest BE d4009cde38275147fa3fd13e951e55a8a2c556f4 problem with out of ammo is back. Q take properly ammo, go to mission and: "Out of ammo"
http://privatepaste.com/fc683e6cc8

**Comment by ISeeDEDPpl** [comment]
What mission? Is that mission using special ammo?
Does it only effect this mission? It would be helpful to have the log during arm when this occurs...

**Comment by oldmeat** [comment]
http://privatepaste.com/236508cfb1

When i restart eve, then he do it this mission properly without "Out of ammo"

**Comment by oldmeat** [comment]
In mission i got dc and relog. 
When i log in and questor start then i got this: 

http://privatepaste.com/6ad214e962

and when he back to station then:

http://privatepaste.com/e5aab53b17

**Comment by ISeeDEDPpl** [comment]
we are still missing the Arm log before undocking and experiencing the issue...
