### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#58]
in Questor.Modules.Arm.ProcessState() in C:\Questor\ISeeDEDPpl-Questor-77e9774\Questor.Modules\Arm.cs:riga 559    

in Questor.Questor.OnFrame(Object sender, EventArgs e) in C:\Questor\ISeeDEDPpl-Questor-77e9774\Questor\Questor.cs:riga 809

Log error in the last branch

**Comment by Blafasl** [comment]
I get the same error but only with my Tengu chars. Golem pilots are running fine.

**Comment by marivx** [comment]
yes my  char is in tengu

**Comment by Blafasl** [comment]
marivx, could you please post the complete exception?

The most important port is the first line which you didn't post. I already rolled back to a previous version so i cant provide it in a manner of time.

**Comment by ISeeDEDPpl** [comment]
This has been fixed locally. Ill push to github in the next 10 min.
