### ISSUE TITLE
Problem undock noctis

### ISSUE THREAD

**Issue by apotecario** [ISeeDEDPpl/Questor#580]
When the mission ends and changes to noctis stays in the station doing nothing.

I passed on all missions

Console:

17:24:43 [UnloadLoot.MoveAmmo] Done
17:24:43 [UnloadLoot.MoveMissionGateKeys] Done
17:24:46 [UnloadLoot.MoveLoot] Done
17:24:46 [UnloadLoot.StackLootHangar] Loot was worth an estimated [0] isk in buy-orders
17:24:46 [CombatMissionsBehavior.BeginAftermissionSalvaging] Salvaging at first oldest bookmarks
17:24:46 [CombatMissionsBehavior.Unloadloot] There are [ 2 ] more salvage bookmarks left to process
17:24:46 [CombatMissionsBehavior.UnloadLoot] The last after mission salvaging session was [53min] ago
17:24:47 [CombatMissionsBehavior.BeginAftermissionSalvaging] Next Bookmark refresh in [3min]
17:24:49 [CloseCargoHold] Cargohold was not open, no need to close
17:24:49 [BeginAfterMissionSalvaging.ActivateSalvageShip] Making [caca] active
17:24:51 [BeginAfterMissionSalvaging.ActivateSalvageShip] Done
17:25:47 [CombatMissionsBehavior.BeginAftermissionSalvaging] Next Bookmark refresh in [2min]
17:26:47 [CombatMissionsBehavior.BeginAftermissionSalvaging] Next Bookmark refresh in [1min]
17:27:25 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 2 ] minutes.
17:27:47 [CombatMissionsBehavior.BeginAftermissionSalvaging] Next Bookmark refresh in [3min]
17:28:25 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 3 ] minutes.
17:28:47 [CombatMissionsBehavior.BeginAftermissionSalvaging] Next Bookmark refresh in [2min]
17:29:25 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 4 ] minutes.

**Comment by ISeeDEDPpl** [comment]
fixed: 8bf7ca3b87defe92a46c7d791ce4ab62a4c77003

please test.

**Comment by apotecario** [comment]
Perfect !!

thx

**Comment by juandrito** [comment]
Hi, i have same problem now:

00:10:48 [CombatMissionsBehavior.BeginAftermissionSalvaging] Next Bookmark refresh in [1min]
00:11:48 [CombatMissionsBehavior.BeginAftermissionSalvaging] Next Bookmark refresh in [3min]
00:12:27 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 2 ] minutes.
00:12:48 [CombatMissionsBehavior.BeginAftermissionSalvaging] Next Bookmark refresh in [2min]
