### ISSUE TITLE
Not targeting npc

### ISSUE THREAD

**Issue by aprofec** [ISeeDEDPpl/Questor#581]
Hi there. Sometimes you do not select npc, and remains in that state until I select them, and only then begins to attack. Or kill one and go without doing anything else, until I return to select.

17:17:34 [Defense] Shields: [98%] Cap: [68%] Shield Booster: [1] activated
17:17:35 [InSpace [ True ] InWarp [ False ] InStation [ False ] NextTargetAction [ 3,6449225 seconds] DebugDisableTargetCombatants [ False ]] 
17:17:36 [InSpace [ True ] InWarp [ False ] InStation [ False ] NextTargetAction [ 2,4108519 seconds] DebugDisableTargetCombatants [ False ]] 
17:17:37 [Defense] Shields: [100%] Cap: [67%] Shield Booster: [1] deactivated [1] sec reactivation delay
17:17:37 [InSpace [ True ] InWarp [ False ] InStation [ False ] NextTargetAction [ 1,1477797 seconds] DebugDisableTargetCombatants [ False ]] 
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: Remove any target that is out of range
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: Priority Target Handling
17:17:39 [Combat.TargetCombatants] We have [1] PWPT. We have [0] TargetsAndTargeting. We have [0] PWPT that are already targeted
17:17:39 [Combat.TargetCombatants] if (PrimaryWeaponsPriorityTargetUnTargeted > 0)
17:17:39 [Combat.TargetCombatants] if (!UnlockHighValueTarget(Combat.TargetCombatants, PrimaryWeaponPriorityTargets return;
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: [1] primaryWeaponPriority targets
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: Drone Priority Target Handling
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: [1] dronePriority targets
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: Preferred Primary Weapon target handling
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: Preferred Drone target handling
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: Do we have enough targets? Locked [0] Locking [0] Total [0] Slots Total [7]
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: Aggro Handling
17:17:39 [Combat.TargetCombatants] TargetingMe [4] lowValueTargetingMe [2] targeted [0] ::: highValueTargetingMe [2] targeted [0] LCOs [6]
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in highValueTargetingMe)
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: [2] highValueTargetingMe targets
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: [1][Pith Usurper][32,87k][groupID612]
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: [1][Pith Usurper][32,91k][groupID612]
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: foreach (EntityCache entity in lowValueTargetingMe)
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: [2] lowValueTargetingMe targets
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: lowValueTargetingMe [1][Spider Drone II][7,51k] groupID [ 805]
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: lowValueTargetingMe [1][Guristas Cruise Missile Batteries][22,67k] groupID [ 383]
17:17:39 [Combat.TargetCombatants] DebugTargetCombatants: [4] NotYetTargetingMe targets
17:17:40 [InSpace [ True ] InWarp [ False ] InStation [ False ] NextTargetAction [ 3,7869307 seconds] DebugDisableTargetCombatants [ False ]] 
17:17:41 [InSpace [ True ] InWarp [ False ] InStation [ False ] NextTargetAction [ 2,5798616 seconds] DebugDisableTargetCombatants [ False ]] 
17:17:42 [Defense] Shields: [98%] Cap: [68%] Shield Booster: [1] activated
17:17:42 [InSpace [ True ] InWarp [ False ] InStation [ False ] NextTargetAction [ 1,3157893 seconds] DebugDisableTargetCombatants [ False ]] 
17:17:43 [InSpace [ True ] InWarp [ False ] InStation [ False ] NextTargetAction [ 0,0937194 seconds] DebugDisableTargetCombatants [ False ]]

**Comment by ISeeDEDPpl** [comment]
what ship? weapons? - does this happen without any primary weapons, drones only?

**Comment by ISeeDEDPpl** [comment]
Is this occurring for anyone else?

**Comment by ISeeDEDPpl** [comment]
no one else seems to be having this issue. If it is still occurring for you I need more information on shiptype/ammotype/mission/etc/etc
