### ISSUE TITLE
Salvaging problem

### ISSUE THREAD

**Issue by apotecario** [ISeeDEDPpl/Questor#582]
When will there is a salvager and container by the system will stop. If you manually loot the cargo container system is operated.

Does not always happen.

**Comment by Pluckyduck** [comment]
logs...are needed/required

**Comment by apotecario** [comment]
Gets stuck when a container in space and wreck, if wreck and target the tractor manually activate the system is operated.

14:59:25 [Salvage] Activating salvager [5] on [Gistii Impaler Wreck][ID: [MaskedID]0498] we have [1] wrecks targeted in salvager range
14:59:25 [Salvage] Activating salvager [6] on [Gistii Impaler Wreck][ID: [MaskedID]0498] we have [1] wrecks targeted in salvager range
14:59:25 [Salvage] Activating salvager [7] on [Gistii Impaler Wreck][ID: [MaskedID]0498] we have [1] wrecks targeted in salvager range
14:59:25 [Salvage] Activating salvager [8] on [Gistii Impaler Wreck][ID: [MaskedID]0498] we have [1] wrecks targeted in salvager range
14:59:26 [Salvage.NavigateIntorangeOfWrecks] Stop ship, ClosestWreck [1322] is in scooprange + [1790] and we were approaching
14:59:34 [Salvage] Activating salvager [5] on [Gistii Impaler Wreck][ID: [MaskedID]0498] we have [1] wrecks targeted in salvager range
14:59:34 [Salvage] Activating salvager [6] on [Gistii Impaler Wreck][ID: [MaskedID]0498] we have [1] wrecks targeted in salvager range
14:59:34 [Salvage] Activating salvager [7] on [Gistii Impaler Wreck][ID: [MaskedID]0498] we have [1] wrecks targeted in salvager range
14:59:34 [Salvage] Activating salvager [8] on [Gistii Impaler Wreck][ID: [MaskedID]0498] we have [1] wrecks targeted in salvager range
15:00:04 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 5 ] minutes.
15:00:58 [Salvage] Stacking CargoHold: waiting [-162sec]
15:00:58 [Salvage] Done stacking
15:01:01 [Salvage] Stacking CargoHold: waiting [-165sec]
15:01:02 [Salvage] Done stacking
15:01:04 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 6 ] minutes.
15:03:04 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 2 ] minutes.
15:04:04 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 3 ] minutes.
15:05:04 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 4 ] minutes.
15:06:04 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 5 ] minutes.
15:07:04 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 6 ] minutes.
15:08:04 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 7 ] minutes.
15:09:05 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 8 ] minutes.
15:10:05 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 9 ] minutes.

**Comment by ISeeDEDPpl** [comment]
So this happens with the dedicated and/or after mission salvager? does it ever happen during missions?

another log may help... if it gets stuck, enable debugSalvage and debugNavigateIntoRange (no need to restart after doing so, those take effect immediately. then re-post those logs.

**Comment by aprofec** [comment]
The same happens to me. I enabled what you put into debug and this is the result. 1 wreck in space in range at 4km

20:05:16 [CombatMissionsBehavior] salvage: we **cannot ever** approach in salvage.cs so this section _is_ needed
20:05:16 [Salvage] SalvageState.SalvageWrecks:
20:05:16 [Salvage.ActivateSalvagers] Debug: if (wrecks.Count == 0)
20:05:16 [CombatMissionsBehavior] salvage: we **cannot ever** approach in salvage.cs so this section _is_ needed
20:05:17 [CombatMissionsBehavior] salvage: we **cannot ever** approach in salvage.cs so this section _is_ needed
20:05:17 [Salvage] SalvageState.TargetWrecks:
20:05:17 [CombatMissionsBehavior] salvage: we **cannot ever** approach in salvage.cs so this section _is_ needed

**Comment by Pluckyduck** [comment]
@ISeeDEDPpl , i am having the problem in local build like this one.  It happens when it does not open a can and loot it.  It only seems to happen when i have something that is on the do not loot list(drop, drugs and stuff).

**Comment by ISeeDEDPpl** [comment]
this should no longer occur. if it is still happening I need a new log with debugSalvage and debugLootWrecks
