### ISSUE TITLE
AgentInteraction issue when declining missions

### ISSUE THREAD

**Issue by dextorious** [ISeeDEDPpl/Questor#584]
When encountering a blacklisted mission Questor (latest BE) inefficiently fumbles through the agent interaction windows, manages to decline the mission and promptly gets stuck. I took a quick glance at the relevant code and didn't see anything obviously wrong, so I'm submitting the following log (produced with debugAgentInteractionReplyToAgent and debugDecline both enabled):

http://privatepaste.com/049cb7cbc1

The last 2 lines of that log go on ad infinitum. I'll submit a pull request if I manage to fix it.

**Comment by dextorious** [comment]
Adding a simple delay appears to have solved this issue for now. I submitted a pull request accordingly.

EDIT: Still seems to occasionally bug out, just got harder to reproduce. I'll keep looking.

**Comment by ISeeDEDPpl** [comment]
this should be resolved.
please re-open w with logs if you see it reoccur
