### ISSUE TITLE
Ammo Problem

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#586]
In the latest BE build: 9c663b71090f66a867e886a197397519fd98f5a1 
When in mission file we have more than one ammo type, then Q have problem with this because he get only 1 type and when he should change ammo on mission then he throw ammo problem and back to base.

**Comment by ISeeDEDPpl** [comment]
both listed in the root of the mission?
link your mission XML please.

**Comment by oldmeat** [comment]
Sorry, i don't know why i not got notification on my mail from github about this respond ...
XML mission file: http://privatepaste.com/6aaed6f019
This error: http://privatepaste.com/b0f79798d8

**Comment by ISeeDEDPpl** [comment]
this should now be fixed in bleedingedge. please test.
