### ISSUE TITLE
EM and OutOfAmmo error

### ISSUE THREAD

**Issue by aprofec** [ISeeDEDPpl/Questor#587]
Hello. Randomly asks me in some missions ammo em, when should you use another type and season again, and sometimes gives error "out of ammo" when ammunition in the hangar. Do not use containers. For the error "out of ammo" I go to the state tab and change "combat state" to "idle" and everything is working again normally. This started after the last patch ccp. Errors gives them randomly with any mission and not always.

18:25:27 [Combat] ReloadNormalAmmo:: not enough [EM] ammo in cargohold: MinimumCharges: [4] Note: CurrentDamageType [EM]
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [CurrentDamageType] Note: ManualDamageType, PocketDamageType, MissionDamageType and FactionDamageType we all NULL, defaulting to EM
18:25:27 [Combat] ReloadNormalAmmo:: not enough [EM] ammo in cargohold: MinimumCharges: [4] Note: CurrentDamageType [EM]
18:26:01 [TravelerDestination.StationDestination] Arrived in station
18:26:01 [CombatMissionsBehavior] UnloadLoot: Begin
18:26:06 [UnloadLoot.MoveAmmo] Moving [1] Ammo Stacks [3128] Total Units to AmmoHangar
18:26:07 [UnloadLoot.MoveAmmo] Done
18:26:07 [UnloadLoot.MoveMissionGateKeys] Done
18:26:10 [UnloadLoot.MoveLoot] Done
18:26:10 [UnloadLoot.StackLootHangar] Loot was worth an estimated [0] isk in buy-orders
18:26:10 [CombatMissionsBehavior.UnloadLoot] _States.CurrentCombatState == CombatState.OutOfAmmo
18:26:11 [CombatMissionsBehavior] Random start delay of [3] seconds
18:26:14 [Cleanup] EVE instance: totalMegaBytesOfMemoryUsed - 883 MB
18:26:15 [Switch] Begin
18:26:15 [SwitchShip] Activating combat ship
18:26:16 [CombatMissionsBehavior.TravelHome] Destination: []
18:26:16 [TravelerDestination.StationDestination] Destination set to []
18:26:18 [TravelerDestination.StationDestination] Arrived in station
18:26:18 [CombatMissionsBehavior] UnloadLoot: Begin
18:26:20 [UnloadLoot.MoveLoot] Done
18:26:20 [UnloadLoot.StackLootHangar] Loot was worth an estimated [0] isk in buy-orders
18:26:20 [CombatMissionsBehavior.UnloadLoot] _States.CurrentCombatState == CombatState.OutOfAmmo
18:26:21 [CombatMissionsBehavior] Random start delay of [6] seconds
18:26:27 [Cleanup] EVE instance: totalMegaBytesOfMemoryUsed - 883 MB
18:26:28 [AgentInteraction] Start conversation [Start Mission]
18:26:30 [AgentInteraction] Replying to agent
18:26:33 [AgentInteraction] ReplyToAgent: Found complete button, Changing Purpose to CompleteMission
18:26:33 [AgentInteraction] Saying [Complete Mission]
18:26:35 [AgentInteraction] Attempting to close Agent Window
18:26:36 [AgentInteraction] Done
18:26:36 [CombatMissionsBehavior] UnloadLoot: Begin
18:26:38 [UnloadLoot.MoveLoot] Done
18:26:38 [UnloadLoot.StackLootHangar] Loot was worth an estimated [0] isk in buy-orders
18:26:39 [CombatMissionsBehavior.UnloadLoot] _States.CurrentCombatState == CombatState.OutOfAmmo

**Comment by kn0xv1lle** [comment]
Yeah i got that error to. Instead of using the right ammo like scourge it says out of ammo because no em ammo is in cargo. Obviously not when said in mission xml use scourge. ^^

**Comment by ISeeDEDPpl** [comment]
this should be fixed in bleedingedge.
