### ISSUE TITLE
Questor wont start

### ISSUE THREAD

**Issue by Escalati0n** [ISeeDEDPpl/Questor#589]
Hello,

Questor: latest BleedingEdge
Questor stuck on the following screen when i start it up.

13:13:48 [Startup:o] OptionallyLoadPreLoginSettingsFromINI was false!
13:13:48 [Startup] Starting Instance of DirectEVE using Innerspace
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Starting DirectEve v1.330.5439.17761
Copyright (c) 2012 - TheHackerWithin
http://www.thehackerwithin.com
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
13:13:49 Startup] DirectEVE should now be active: see above for any messages from DirectEVE
13:14:39 [Startup] We have successfully logged in
13:14:39 [Startup] We are logged into EVE: unRegistering LoginOnFrame Event, wait 3 sec

**Comment by ISeeDEDPpl** [comment]
ok, found the prob, committing a fix soonish

**Comment by Escalati0n** [comment]
latest BleedingEdge: 4528879b7dd6b887a25e619a5f782dc3810033ee
if I try to start questor, no questor window open, the same with questormanager.
I tried to start questor with dotnet questor and  dotnet q1 questor -x -c "Charname"

I also had no problems with the last experimental in the forum.
http://forum.thehackerwithin.com/yaf_postsm8945_Is-Questor-still-working.aspx#post8945

Von: ISeeDEDPpl [mailto:notifications@github.com] 
Gesendet: Samstag, 13. Dezember 2014 02:29
An: ISeeDEDPpl/Questor
Cc: Escalati0n
Betreff: Re: [Questor] Questor wont start (#589)

what github rev/hash?

Latest Bleedingedge starts ok for me. (revision:  https://github.com/ISeeDEDPpl/Questor/commit/00a96fb19fb2002d3182d5a48651eb8213bcc387 00a96fb)

**Comment by oldmeat** [comment]
Escalation try download any license to .NET Folder 
http://forum.thehackerwithin.com/yaf_postsm8945_Is-Questor-still-working.aspx#post8945
old Questor check is license file exist...

**Comment by Escalati0n** [comment]
Thx oldmeat, in the latest bleedingedge 8d5a83f4d97b36857c1c92f81839fd82de0e5832 

this issue seemes fixed for me.

Von: oldmeat [mailto:notifications@github.com] 
Gesendet: Montag, 22. Dezember 2014 18:14
An: ISeeDEDPpl/Questor
Cc: Escalati0n
Betreff: Re: [Questor] Questor wont start (#589)

Escalation try download any license to .NET Folder 
http://forum.thehackerwithin.com/yaf_postsm8945_Is-Questor-still-working.aspx#post8945
old Questor check is license file exist...
