### ISSUE TITLE
<MinAgentGreyListStandings>6.5</MinAgentGreyListStandings>

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#59]
20:56:10 Questor: Random start delay of [5] seconds
20:56:18 Questor: EVE instance: totalMegaBytesOfMemoryUsed - 606 MB
20:56:19 AgentInteraction: Start conversation [Start Mission]
20:56:19 AgentInteraction: Waiting for conversation
20:56:25 AgentInteraction: Replying to agent
20:56:32 AgentInteraction: Waiting for mission
20:56:36 Questor: Wallet Balance Has Not Changed in [ 4 ] minutes.
20:56:38 AgentInteraction: [Agent X] standing toward me is [9,07], minAgentGreyListStandings: [-1,7]
20:56:38 AgentInteraction: Faction fitting: Default
20:56:38 AgentInteraction: Loading mission xml [Infiltrated Outposts]
20:56:38 AgentInteraction: Accepting mission [Infiltrated Outposts]
20:56:42 AgentInteraction: Saying [Accept]
20:56:42 AgentInteraction: Closing conversation
20:56:47 AgentInteraction: Done
20:56:48 Arm: Begin

I have 9.2 of standing e set greylist at 6.5 but still not work
use the last branch

**Comment by ISeeDEDPpl** [comment]
settings.cs
`
MinAgentGreyListStandings = (float?)xml.Element("minGreyListStandings") ?? (float)-1.7;
`
so your XML needs to have
`
<minGreyListStandings>6.5</minGreyListStandings>
`

Evidentally the issue is in your character settings xml as the greylist setting isnt being read correctly in settings.cs

**Comment by ISeeDEDPpl** [comment]
after looking at this again Ive corrected the setting in settings.cs and the example settings.xml to use
<minAgentGreyListStandings>6.5</minAgentGreyListStandings>
