### ISSUE TITLE
Unable to locate agent

### ISSUE THREAD

**Issue by jjbrunton** [ISeeDEDPpl/Questor#592]
23:07:24 [Cache.CurrentAgent] [ Tuga Nato ] AgentID [ 3016815 ]
23:07:24 [Settings] Unable to locate agent [Tuga Nato]
23:07:24 [Questor] Checking: Current time [03/02/2015 23:07:24] StopTimeSpecified [True] StopTime [ 03/03/2015 09:07:21] ManualStopTime = 03/03/2015 09:06:25
23:07:24 [Questor] Start Mission Behavior
23:07:25 [CombatMissionsBehavior] Random start delay of [2] seconds
23:07:29 [CombatMissionsBehavior.TravelHome] Destination: []
23:07:29 [TravelerDestination.StationDestination] Destination set to []
23:07:32 [Startup] Launching QuestorUI

I have added the agent to address book but it is still unable to locate it.

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge
