### ISSUE TITLE
Constantly reloads

### ISSUE THREAD

**Issue by jjbrunton** [ISeeDEDPpl/Questor#593]
I am using an Atron with these ammo types setup:

 `<ammoTypes>`
`<ammoType typeId="222" damageType="EM"        range="1000" quantity="1000" />`
`<ammoType typeId="222" damageType="Kinetic"   range="1000" quantity="1000" />`
`<ammoType typeId="222" damageType="Thermal"   range="1000" quantity="1000" />`
`<ammoType typeId="222"  damageType="Explosive" range="1000" quantity="1000" />`
`</ammoTypes>`

It appears to constantly attempt to reload the weapons..

12:10:32 [ReloadAmmo] Reloading [1] [75mm Gatling Rail I] with [Antimatter Charge S][1]
12:10:33 [ReloadAmmo] Reloading [2] [75mm Gatling Rail I] with [Antimatter Charge S][1]
12:10:34 [ReloadAmmo] Reloading [3] [75mm Gatling Rail I] with [Antimatter Charge S][1]
12:10:44 [ReloadAmmo] Reloading [1] [75mm Gatling Rail I] with [Antimatter Charge S][1]
12:10:45 [ReloadAmmo] Reloading [2] [75mm Gatling Rail I] with [Antimatter Charge S][1]
12:10:46 [ReloadAmmo] Reloading [3] [75mm Gatling Rail I] with [Antimatter Charge S][1]

**Comment by ISeeDEDPpl** [comment]
Does it have the ammo to perform the reload?

**Comment by jjbrunton** [comment]
Yes

**Comment by ISeeDEDPpl** [comment]
I need a log with debugReloadAll set true.

**Comment by jjbrunton** [comment]
...

**Comment by jjbrunton** [comment]
The line "Reload Logic 1" is just something I added to see what code was being called.

**Comment by ISeeDEDPpl** [comment]
ok, fixed in bleedingedge. thank you.
