### ISSUE TITLE
Statistics wrong when using Golem with aftermissionsalvaging

### ISSUE THREAD

**Issue by Blafasl** [ISeeDEDPpl/Questor#60]
As for some mission its more effective to use a noctics afterwards a mission where many large wrecks are still left it seems to wreck the statistics.

xx.04.2012 09:06:57;The Sansha Spies;0;1184000;13176;282749;0;72;172368;0;94;100;86;18;17;17;
xx.04.2012 09:16:43;The Rogue Slave Trader (1 of 2);0;3563750;100890;1755;0;0;0;0;93;101;67;24;26;26;
xx.04.2012 09:32:46;Downing The Slavers (2 of 2);0;1501000;3421916;3844;0;192;459648;0;91;100;73;75;42;42;
xx.04.2012 10:07:00;Recon (1 of 3);0;8275000;1650258;295696;0;392;627200;0;94;100;83;370;24;24;
xx.04.2012 10:23:54;The Sansha Spies;0;5210500;0;2529;0;108;258552;0;94;100;80;20;41;41;
xx.04.2012 10:33:33;Dread Pirate Scarlet;0;3280000;12740404;314251;0;184;294400;0;91;100;52;120;19;19;
xx.04.2012 11:00:41;Gone Berserk;27;1891000;23230815;4738;0;332;531200;0;101;101;101;158;27;54;
xx.04.2012 11:41:34;The Score;0;17103567;15861825;4694;0;452;1082088;0;94;100;84;36;8;8;

There are some things wrong in the CustomDatedStatitistics:
1. Time (not TotalMissionTime) is in nearly all cases 0. Something it contains a number but it doenst match right with the log ingame.
2. When the golem pilot is switching to a noctics after a mission AfterMissionsalvageTime seems to be resetted and also sets the TotalMissionTime also to 0 which is makes the log wrong. You can see that at the "The Score" "The Sansha Spies" and the "Recon (1 of 3)" line. The times are too short and unrealistic (400m/h).
3. As the golem is capable to salvage while its doing the mission, it seems that most of the time it runs the AfterMissionsalvageTime timer instead of the normal mission time.

I tried to fix it myself, but i fucked it up (newbie to programming), so i found it getter to give this issue to you in the hope of fixing it.

**Comment by ISeeDEDPpl** [comment]
Unfortunately with the current level of logging debugging this is difficult. I am going to commit some detailed mission stats logging to the console log, which is long overdue and should help everyone a bit.

**Comment by Blafasl** [comment]
Any ETA on when you will commit those changes? Just out of interest :)

**Comment by ISeeDEDPpl** [comment]
committed
