### ISSUE TITLE
<minAgentGreyListStandings>6.5</minAgentGreyListStandings>

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#61]
14:44:46 Questor: Random start delay of [2] seconds
14:44:50 Questor: EVE instance: totalMegaBytesOfMemoryUsed - 636 MB
14:44:51 AgentInteraction: Start conversation [Start Mission]
14:44:51 AgentInteraction: Waiting for conversation
14:44:55 AgentInteraction: Replying to agent
14:45:03 AgentInteraction: Waiting for mission
14:45:08 AgentInteraction: [Agent x] standing toward me is [9,20], minAgentGreyListStandings: [6,5]
14:45:08 AgentInteraction: Faction fitting: Default
14:45:08 AgentInteraction: Loading mission xml [The Wildcat Strike]
14:45:08 AgentInteraction: Accepting mission [The Wildcat Strike]
14:45:12 AgentInteraction: Saying [Accept]
14:45:12 AgentInteraction: Closing conversation
14:45:16 AgentInteraction: Done

this mission is in greylist

i have set the last  branch and set the standin at 6.5 but questor still accept this mission

the file xml there is this 

<minAgentGreyListStandings>6.5</minAgentGreyListStandings>

**Comment by ISeeDEDPpl** [comment]
the mission name from your settings XML was being converted to lowercase before comparison, the name of the mission from game was not. this is now fixed.
