### ISSUE TITLE
Schedules.xml

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#62]
not work.

Questor not finish at specific time.

**Comment by ISeeDEDPpl** [comment]
It does not finish at a specific time, it finishes on the next IDLE state after the specified time. Normally that means that the time will pass during a mission and the next time questor is back in station 9and done with aftermission salvaging if any) it will enter the idle state and check to see if it should exit.

**Comment by ISeeDEDPpl** [comment]
if this is not working for you you need to give more details... especially what does questor say in the console log for: 

Logging.Log("[Startup] Start Time: " + _startTime + " - Stop Time: " + stopTimeText);
