### ISSUE TITLE
Salvager toon

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#63]
In the last brach not work , come to the first Bookmark and when finish questor :

21:07:07 Salvage: We've moved to the next Pocket [10077k away]
21:07:08 Salvage: We've moved to the next Pocket [10077k away]
21:07:09 Salvage: We've moved to the next Pocket [10077k away]
21:07:10 Salvage: We've moved to the next Pocket [10077k away]
21:07:11 Salvage: We've moved to the next Pocket [10077k away]
21:07:12 Salvage: We've moved to the next Pocket [10077k away]
21:07:13 Salvage: We've moved to the next Pocket [10077k away]

not change bookmark , but stopped with this log

**Comment by ISeeDEDPpl** [comment]
this has been fixed
