### ISSUE TITLE
Dedicated Salvager toon 

### ISSUE THREAD

**Issue by marivx** [ISeeDEDPpl/Questor#64]
Have problem when try to get this conteiner

http://pastebin.com/r40Vuzi8

go in loop

**Comment by ISeeDEDPpl** [comment]
is this the dedicated salvager mode?

**Comment by marivx** [comment]
Yes not Work toon not undock

**Comment by ISeeDEDPpl** [comment]
k, I'll look into this next week when the restructuring is complete. The dedicated salvage toon code is going through a rewrite atm.

**Comment by ISeeDEDPpl** [comment]
let me know if this is still an issue...

**Comment by marivx** [comment]
last relise NOT WORK

**Comment by ISeeDEDPpl** [comment]
that is not a helpful comment... logs? if you are seeing a different issue from the above please open a new issue.

**Comment by marivx** [comment]
No still not work
abaut 30 min not undock 
13:32:16 DedicatedBookmarkSalvagerBehavior: Unloadloot: Character mode is BookmarkSalvager and no bookmarks salvage.
13:32:20 DedicatedBookmarkSalvagerBehavior.LocalWatch: local is clear
13:32:21 Arm: Activating salvage ship
13:58:17 Questor: Wallet Balance Has Not Changed in [ 26 ] minutes.
13:59:17 Questor: Wallet Balance Has Not Changed in [ 27 ] minutes.

**Comment by ISeeDEDPpl** [comment]
Please try again with latest experimental. open another issue if you experience any issues.

**Comment by marivx** [comment]
Still not warp out when there is npc
