### ISSUE TITLE
Enemies Abound 2of5

### ISSUE THREAD

**Issue by vv734** [ISeeDEDPpl/Questor#65]
not grab Encoded Data Chip

console log:
17:22:31 CourierMissionState: Moving [Encoded Data Chip][1006494545447] to cargo
17:22:32 CourierMission: mission item is: Encoded Data Chip
17:22:32 CourierMissionState: Moving [Encoded Data Chip][1006494545447] to cargo
17:22:33 CourierMission: mission item is: Encoded Data Chip
17:22:34 CourierMission: mission item is: Encoded Data Chip
17:22:34 CourierMissionState: Moving [Encoded Data Chip][1006494545447] to cargo

**Comment by ISeeDEDPpl** [comment]
this should now be fixed. please test
