### ISSUE TITLE
When AfterMissionSalvaging IN SALVAGE SHIP - Combat: No weapons with GroupId [510] found!

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#66]
When using ISeeDEDPpl Experimental Branch:

It's rather strange for questor to be trying to activate missile lauchers on a salvage ship AFTER looting is done and just before docking.
When running afterMissionsalvaging with same character on NOCTIS ship (4xSalvagers+4xTractors fitted), after looting and salvaging is done, it tries to activate weapons groupID 510 which is heavy missile laucher II group.

LOG:

16:36:41 Questor.Salvage: Finished salvaging the room
16:36:42 Salvage: Stacking items
16:36:42 Questor.Salvage: Finished salvaging the room
16:36:42 Questor.Salvage: We have salvaged all bookmarks, go to base
16:36:43 Combat: No weapons with GroupId [510] found!
16:36:45 TravelerDestination.StationDestination: Destination set to [System X - Moon X - Unknown Sation]
16:36:45 Combat: No weapons with GroupId [510] found!
16:36:45 Traveler: Setting destination to [SystemX]
16:36:46 Combat: No weapons with GroupId [510] found!
16:36:46 Traveler: Warping to [SystemX][16,83 AU away]
16:36:47 Combat: No weapons with GroupId [510] found!
16:37:37 Salvage: Done stacking
16:37:37 Combat: No weapons with GroupId [510] found!
16:37:38 Traveler: Jumping to [SystemX]
16:37:38 Combat: No weapons with GroupId [510] found!
16:37:39 Combat: No weapons with GroupId [510] found!
16:37:40 Combat: No weapons with GroupId [510] found!
16:37:41 Combat: No weapons with GroupId [510] found!
16:37:42 Combat: No weapons with GroupId [510] found!
16:37:52 TravelerDestination.StationDestination: Warp to and dock at [System X - Moon X - Unknown Sation][2,12 AU away]
16:37:53 Questor: Wallet Balance Has Not Changed in [ 2 ] minutes.
16:38:39 Combat: No weapons with GroupId [510] found!
16:38:40 TravelerDestination.StationDestination: Dock at [System X - Moon X - Unknown Sation] which is [2k away]
16:38:40 Combat: No weapons with GroupId [510] found!
16:38:41 Combat: No weapons with GroupId [510] found!
16:38:42 Combat: No weapons with GroupId [510] found!
16:38:43 Combat: No weapons with GroupId [510] found!
16:38:44 Combat: No weapons with GroupId [510] found!
16:38:45 Combat: No weapons with GroupId [510] found!
16:38:46 Combat: No weapons with GroupId [510] found!
16:38:47 Combat: No weapons with GroupId [510] found!
16:38:48 Combat: No weapons with GroupId [510] found!
16:38:49 Combat: No weapons with GroupId [510] found!
16:38:50 Combat: No weapons with GroupId [510] found!
16:38:51 Combat: No weapons with GroupId [510] found!
16:39:04 TravelerDestination.StationDestination: Arrived in station
16:39:05 Questor: UnloadLoot: Begin

**Comment by ISeeDEDPpl** [comment]
this should already be fixed in experimental

https://github.com/ISeeDEDPpl/Questor/commit/042819c5b9e94c137de66cb259629b036eb97295

what version are you running?

**Comment by CasualBod** [comment]
I'm using ISeeDEDPpl-Questor-08e3383

Compiled it yesterday from experimental branch, I did use #compile#.bat for that purpose.

I've tried multiple times, every time the log looks pretty much the same, it starts just after salvaging is declared done, then repeats the 510 loop at every gate back to station, then just before docking.

**Comment by ISeeDEDPpl** [comment]
The console log messages were harmless (and annoying)...
the latest commit should resolve it for good.

**Comment by CasualBod** [comment]
1 error occurs when trying to compile latest commit ISeeDEDPpl-Questor-2584fd6
while executing E:\questor>%systemroot%\Microsoft.Net\FrameWork\v4.0.30319\msbuild.exe command. As well as when executing #compile#.bat

"E:\questor\Questor.sln" (default target) (1) ->
"E:\questor\Questor\Questor.csproj" (default target) (2) ->
"E:\questor\Questor.Modules\Questor.Modules.csproj" (default target) (3) ->
(CoreCompile target) ->
  Combat.cs(723,121): error CS0117: 'Questor.Modules.Logging' does not contain
a definition for 'red' [E:\questor\Questor.Modules\Questor.Modules.csproj]

```
12 Warning(s)
1 Error(s)
```

Time Elapsed 00:00:03.45

**Comment by ISeeDEDPpl** [comment]
bah.. sec

**Comment by ISeeDEDPpl** [comment]
fixed.

**Comment by CasualBod** [comment]
When using the new "dontreloadintraveler" branch build ISeeDEDPpl-Questor-b32aa10 questor locks a target then just stands doing nothing when it arrives at a pocket with NPCs. It does not respond to aggro either. Locks up targets but does not shoot. I'm not sure what caused it exactly, maybe the new "dont reload in traveler function"

0:03:51 MissionController: Pocket [1] loaded, executing the following actions
10:03:51 MissionController: Action [ 1 ] ClearPocket
10:03:51 MissionController: Action [ 2 ] Loot
10:03:51 MissionController: Action [ 3 ] Activate [target: Acceleration Gate]
10:03:51 ------------------------------------------------------------------
10:03:51 ------------------------------------------------------------------
10:03:52 MissionController.ClearPocket: Adding [Centatis Phantasm][ID: 9000000000000596746] as a priority target
10:03:53 MissionController.ClearPocket: Targeting [Centatis Phantasm][ID: 9000000000000596746][17k away]
10:04:33 Questor: Wallet Balance Has Not Changed in [ 2 ] minutes.
10:05:33 Questor: Wallet Balance Has Not Changed in [ 3 ] minutes.

BTW which branch should I use now ? I'm somewhat confused but still eager to help :)

EDIT: just tested "experimental" branch build ISeeDEDPpl-Questor-4f629f8 and it fails to engage weapons too.

**Comment by CasualBod** [comment]
I see you already fixed the issues, thank you for fast fix and all the other small improvements that happened while you were at it. 

Working as of build ISeeDEDPpl-Questor-6183b47 from "experimental" branch.
