### ISSUE TITLE
Suggestion: Questor to check for lowsec points in a route.

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#67]
A way for questor to check for low sec points in a auto pilot route for storyline missions.

**Comment by ISeeDEDPpl** [comment]
When added it will also check for regular missions instead of the simple HTML check for "low sec systems in the route" or whatever it is polling for now.

**Comment by ISeeDEDPpl** [comment]
This is done for storylines... but still needs to be integrated into regular missions iirc
