### ISSUE TITLE
Dedicated Salvager

### ISSUE THREAD

**Issue by grio43** [ISeeDEDPpl/Questor#69]
Just cleared cache and all settings. Salvage sits and does nothing. 

http://pastebin.com/fSpFNnL5

**Comment by ISeeDEDPpl** [comment]
consider it disabled until next week when I finish the dedicated salvage behavior that will drop into the restructured questor...  if you can manage to find the fix the issue in current before that let me know and Ill commit your patch in the meantime.

**Comment by ISeeDEDPpl** [comment]
this should now be fixed. Please report any issues to see with the new behavior in separate issues.
