### ISSUE TITLE
Experemental branch - issue when starting questor

### ISSUE THREAD

**Issue by Irenicus1977** [ISeeDEDPpl/Questor#7]
Ok i seem to be getting this error when i start questor

http://i42.tinypic.com/ulges.png

**Comment by ISeeDEDPpl** [comment]
yes, you need to type

dotnet questor questor -h

at an innerspace prompt within eve. It explains what you need to give questor as command line switches. Evidently you are passing the wrong commands to questor.

**Comment by Irenicus1977** [comment]
This issue apear because of field  "optimalRange" in setting.xml was empty,
Maybe comments in setting.xml should be changed.

**Comment by ISeeDEDPpl** [comment]
I corrected the comment.
