### ISSUE TITLE
Stacking items in corphangar

### ISSUE THREAD

**Issue by happel** [ISeeDEDPpl/Questor#71]
Since one of the commits a few days ago Questor doesn't stack the items in the corphangar anymore after unloading loot or ammo. It happens both after salvaging and after a mission when the bot puts ammo back in the hangar.

The console log shows only this:

xx:xx:18 TravelerDestination.StationDestination: Arrived in station
xx:xx:20 Questor: UnloadLoot: Begin
xx:xx:20 Unloadloot will Continue in [ 1 ] sec
xx:xx:25 UnloadLoot: Loot was worth an estimated [x,xxx,xxx] isk in buy-orders
xx:xx:26 UnloadLoot: Moving Ammo to AmmoHangar [corpHangar_000000000]
xx:xx:26 UnloadLoot: Waiting for items to move
xx:xx:30 UnloadLoot: Stacking items in Ammo Hangar: resuming in [ 4 sec ]
xx:xx:34 UnloadLoot: Stacking items in Ammo Hangar: resuming in [ -3 sec ]
xx:xx:37 UnloadLoot: Stacking items in Loot Hangar: resuming in [ -4 sec ]
xx:xx:42 UnloadLoot: Done
xx:xx:42 Questor: Unloadloot: No more salvaging bookmarks. Setting FinishedSalvaging Update.
xx:xx:43 Statistics: WriteMissionStatistics: We do not have loyalty points with the current agent yet,

If I can help out with a different log, or if there is something I'm missing, please let me know.

**Comment by Blinker** [comment]
Latest commit being used and having same problem as above.

**Comment by ISeeDEDPpl** [comment]
please test now.

**Comment by ISeeDEDPpl** [comment]
ok, I broke down and duplicated the openloothangar and openammohangar methods into closeloothangar and closeammohangar methods.. and it is now behaving as it should. 

I tested in diff corps and different toons, all now stack correctly using the restructuring branch.
