### ISSUE TITLE
Cov. ops cloak bug

### ISSUE THREAD

**Issue by xelj** [ISeeDEDPpl/Questor#74]
Q is trying to activate the cloak near the gate and station,it seems that checking distance of 2,000 meters is not working.
In addition, often because of stealth on the first try fails to jump the gate, and ship them hanging around 30 seconds, which is not very good.

**Comment by ISeeDEDPpl** [comment]
This has been fixed locally. I'll apply the fix to git in the next hour or two.

**Comment by ISeeDEDPpl** [comment]
please re-test this and let me know.

**Comment by xelj** [comment]
Now all ok, thx
