### ISSUE TITLE
Afterburner abuse of activate/deactivate when orbiting

### ISSUE THREAD

**Issue by tetrikx** [ISeeDEDPpl/Questor#75]
When using the orbit option, the afterburner should be always active because usually it is used by speedtanking ships.

In the current build, the afterburner gets deactivated when approaching or orbiting no matter the other options because of this line in defence.cs:

// Should we deactivate the module?
bool deactivate = !Cache.Instance.IsApproachingOrOrbiting;

Changing this deactivate check only to approaching status, the issue will be resolved:

// Should we deactivate the module?
bool deactivate = !Cache.Instance.IsApproaching;

How to test: set speedTank=true in xml settings file and watch the afterburner icon during the mission. It shouldnt activate than quickly deactivate.

**Comment by ISeeDEDPpl** [comment]
ahh, thank you for the breakdown... I'll commit that immediately.
