### ISSUE TITLE
Modal window when deleting bookmarks

### ISSUE THREAD

**Issue by tetrikx** [ISeeDEDPpl/Questor#76]
Most of us dont get this window because at some distant point in the past it was set to never appear again. But a new installation of eve will trigger it:

It's about the modal window triggered when deleting bookmarks. I dont have the exact text of the window. If someone can get that text would be great.

After getting the text of the window, a code similar to this:

```
     foreach (DirectWindow window in Cache.Instance.Windows)
     {
        if (window.Name == "modal")
        {
           bool sayyes = false;
           if (!string.IsNullOrEmpty(window.Html))
           {
              //
              // Modal Dialogs the need "yes" pressed
              //
              sayyes |= window.Html.Contains("delete bookmark");
           }
           if (sayyes)
           {
              Logging.Log("Cleanup: Found a window that needs 'yes' chosen...");
              Logging.Log("Cleanup: Content of modal window (HTML): [" + (window.Html ?? string.Empty).Replace("\n", "").Replace("\r", "") + "]");
              window.AnswerModal("Yes");
              continue;
           }
        }
     }
```

will have to be inserted where deleting bookmarks actions are required.

**Comment by oldmeat** [comment]
It would be very useful

**Comment by tetrikx** [comment]
Most probably a simple
sayyes |= window.Html.Contains("bookmark");

in the "in space shit" category of cleanup.cs will be enough

**Comment by ISeeDEDPpl** [comment]
this has been added.
If you find any more windows that needs closing with "out of the box" settings please open another issue.

**Comment by tetrikx** [comment]
I got the text of the modal window for bookmark removal confirmation:
"Are you sure you want to remove location?"

Please update it. Thanks

**Comment by ISeeDEDPpl** [comment]
done
