### ISSUE TITLE
Bug: Corrupt Session At Login Screen!

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#80]
Perhaps logging in too fast? I am seeing it insta login sometimes also... and this means that after login it wont even wait for the the entire loading screen to finish before it selects the character.

Also me and some other people noticing that autologin is possibly making eve crash at login.

**Comment by ISeeDEDPpl** [comment]
yes, this is likely a side effect of changing the pulsedelay in program.cs, well technically the
"QuestorBeforeLoginPulseDelay_seconds" from 60(seconds) to 20(seconds)
40 seconds should be long enough for all PCs and still be short enough that you'll never land in a pocket of NPCs without questor.cs running.
