### ISSUE TITLE
Bug:  if drones under attack Q is not returning dones to bay

### ISSUE THREAD

**Issue by Irenicus1977** [ISeeDEDPpl/Questor#83]
if drones under attack Q is not returning dones to bay. So i am loosong my drones very quickly.

**Comment by ISeeDEDPpl** [comment]
I revered the changes to drones.cs, please re-test

**Comment by hehbro** [comment]
Issue still there with newest commit, only recall command is the following

Drones: Recalling drones because no NPC is targeting us within dronerange

**Comment by ISeeDEDPpl** [comment]
ok this should now be fixed. tests ok between two toons, one shooting the others drones and the drones pull in, every time.
