### ISSUE TITLE
 valuedump doesn't work

### ISSUE THREAD

**Issue by KingMike** [ISeeDEDPpl/Questor#87]
it crashes the eve for me shortly after starting it so I don't know what kind of error exactly it shows...

i tried both from questormanager and as standalone dotnet valuedump.

**Comment by ghost** [comment]
are you sure you are using the innerspace startup profile that has exefile.exe in ccp/bin or are you using the launcher to start eve through innerspace......

**Comment by KingMike** [comment]
im using exefile in CCP\bin folder. 
are you saying it works for you? 

im getting:
System.NullReferenceException: Object reference not set to an instance of an object.
ItemCache.cs:line 127
ItemCache.cs:line 261
ValueDumpUI.cs:line 539
ValueDumpUI.cs:line 525

**Comment by ISeeDEDPpl** [comment]
I'll look into it tonight / tomorrow. For now you should be able to use the standalone valuedump from a previous git version as a workaround.

**Comment by ISeeDEDPpl** [comment]
fixed: not exactly the way I wanted to fix it tbh, but its working...
https://github.com/ISeeDEDPpl/Questor/commit/0975af33473001aae8ce96d17d0c19a143725159
