### ISSUE TITLE
i would like to keep drones aggroing when sensor damped

### ISSUE THREAD

**Issue by ISeeDEDPpl** [ISeeDEDPpl/Questor#9]
<ahaw> okey! i would like to keep drones aggroing when sensor dumped
<ahaw> as far as I know there is aggresive mode for them
<ISeeDEDPpl> you can set that in the client, no need for a questor setting....
<ISeeDEDPpl> unless you want that to change 'on the fly' in whichcase we will need support in directeve to change that
<ahaw> but when no targets questor will pull drones to drone bay
<ISeeDEDPpl> ahh
<ISeeDEDPpl> ok, I can fix that
<ahaw> but still it should check shield of them
<ISeeDEDPpl> of course

**Comment by Pluckyduck** [comment]
ISDP, when you put them on aggressive mode, they attack anything and everything.  or better said, they attack all triggers first!

**Comment by ISeeDEDPpl** [comment]
yeah, this IRC log was difficult to follow without the names =/  the point was that, even if you set them on aggressive, questor pulls drones when sensor damped to the point where it cant target anything.

He wanted a setting (or a default behavior?) that allowed him as his choice to set drones on aggressive and keep questor from pulling drones when damped to hell (or ECMd to hell id imagine)
