### ISSUE TITLE
Loot not stacking in container

### ISSUE THREAD

**Issue by drokk99** [ISeeDEDPpl/Questor#90]
using 3be0601, it gets stuck at the end of unloadloot, can't seem to stack the items in a general freight container, if I manually open the container it stacks and completes unloadloot..

19:41:15 [UnloadLoot] Moving Ammo to AmmoHangar [hangarFloor]
19:41:15 [UnloadLoot] Waiting for items to move
19:41:18 [UnloadLoot] Stacking items in Ammo Hangar: resuming in [ 4 sec ]
19:41:22 [Cache.StackAmmoHangar] Stacking Item Hangar: waiting [4sec]
19:41:51 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
19:42:14 [Cache.StackLootHangar] Loot Container named: [ containerWindow_some numbers ] was found and its contents are being stacked
19:42:15 [UnloadLoot] Done

gets stuck at the [Cache.StackAmmoHangar] Stacking Item Hangar: waiting [4sec], then continues on after i open the container myself

**Comment by ISeeDEDPpl** [comment]
you said container, but you meant hangar I assume...

**Comment by ISeeDEDPpl** [comment]
or you meant that it got stuck stacking the loothangar... which is defined as a freight container

**Comment by drokk99** [comment]
yeah, inside a freight container, it moves items but doesn't stack them until the container is opened manually

**Comment by ISeeDEDPpl** [comment]
this should be fixed. If not please get me an up to date console log with current experimental.

**Comment by drokk99** [comment]
Still not working, new issue has been opened with console log, closing this one
