### ISSUE TITLE
Exception when starting questor

### ISSUE THREAD

**Issue by Blafasl** [ISeeDEDPpl/Questor#91]
i am using the newest commit b99d1195e9b6b733cf7a8e38c156bd6342756465 after running an older version for quite a while now. Some things has changed so i rebuilded everything from the settings.xml file.

I dont know if its a bug or if something is wrong in my settings but when the 3 different bots log in and are going to start i get this log with an exception:

xx:x3:38 [Startup] Login account [xxxxxx]
xx:x3:38 [Startup] Waiting for Character Selection Screen
xx:x4:17 [Startup] Activating character [xxxxxx]
xx:x4:57 [Startup] We've successfully logged in
xx:x4:57 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 534 MB
xx:x4:58 [Settings] Loading Settings from [C:\Program Files\InnerSpace.NET Programs\xxxxxx.xml]
xx:x4:58 [Settings] MissionsPath is: [C:\Program Files\InnerSpace.NET Programs\Missions]
xx:x4:58 [Settings] Testing: LavishScript Version 1.96
xx:x4:58 [Settings] Found only one agent in your character XML: MultiAgentSupport is [False]
xx:x4:58 [Settings] Faction Fittings defined. Fitting manager will be used when appropriate.
xx:x4:58 [Cache.CurrentAgent] [ xxxxxx xxxxxx  ] AgentID [ xxxxxxxx ]
xx:x4:58 [Logging][ xxxxxx xxxxxx ] AgentID [ xxxxxxxx ]
xx:x5:00 [Questor] Start Mission Behavior
xx:x5:01 [Statistics] It is unlikely a mission has been run yet this session... No Mission log needs to be written.
xx:x5:02 [CombatMissionsBehavior] Random start delay of [38] seconds
xx:x5:08 [Statistics] Writing session data to [ C:\Program Files\InnerSpace.NET Programs\log\xxxxxxx\xxxxxxx.Sessions.log ]
xx:x5:45 [TravelerDestination.StationDestination] Destination set to [xxxxxx x - Moon x - xxxxxxxxxxxxx xxxxxxxxxxx xxxxx]
xx:x6:00 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
xx:x7:00 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
xx:x8:00 [Questor] Wallet Balance Has Not Changed in [ 4 ] minutes.
...

---

Exception during event execution: System.NullReferenceException: the object reference not set to an instance of an object

   at Questor.Modules.Caching.Cache.get_Agent() in x:\Questor\Questor.Modules\Caching\Cache.cs:Zeile 878.

   at Questor.Behaviors.CombatMissionsBehavior.TravelToAgentsStation()

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState()

   at Questor.Questor.OnFrame(Object sender, EventArgs e)

   at ..(DirectEve , Object , LSEventArgs )

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

---

Exception during event execution: System.NullReferenceException: the object reference not set to an instance of an object

   at Questor.Modules.Combat.Combat.ProcessState() in x:\Questor\Questor.Modules\Combat\Combat.cs:Zeile 814.

   at Questor.Behaviors.CombatMissionsBehavior.TravelToAgentsStation()

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState()

   at Questor.Questor.OnFrame(Object sender, EventArgs e)

   at ..(DirectEve , Object , LSEventArgs )

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

---

This error happens only if the bot is sitting in a station.  When i manually undock it before it is in the "Gotobase" State, the bot docks up again and run missions fine.

So i dont know what is wrong. I rebuilded everything from new used KDiff to find any errors or typos in my settings but cant find one. Thats why i am posting this here because i dont know what to do else.

**Comment by Blafasl** [comment]
I saw your comment in the forums. I will add lines when a bot is restarting and throws this error out again.

**Comment by Blafasl** [comment]
Got it.
Also i seems there are 2 execptions which are alternating, i edited it into my first post.

When i manually stop questor after the exception and undock it myself and unpause it after, the bot returns to its state and runs fine.

**Comment by ISeeDEDPpl** [comment]
This has been resolved in: 0efbd34ffbfe7a4ab62e0fdbd7c0e33c96c720bd

Please test, confirm that it is fixed, and close this issue if resolved for you.

**Comment by Blafasl** [comment]
forget to close it. Error seems to be fixed, thanks :)
