### ISSUE TITLE
Multiagent Support

### ISSUE THREAD

**Issue by Beechead** [ISeeDEDPpl/Questor#92]
I have multiple agents in my settings xml, but when standing goes below threshold for agent x, my character will not go to agent y to continue running missions, I need to manually prioritize the agent and restart questor for my character to go to the new agent.

**Comment by ISeeDEDPpl** [comment]
It will be much easier to pinpoint the issue if you were able to go through the console logs and find the output from the point where your Agent_A falls below the threshold and you expect it to switch to Agent_B. 

feel free to join IRC and send the logs to me there... or here on the issue whichever you are comfortable with.

**Comment by ISeeDEDPpl** [comment]
This has been resolved.
