### ISSUE TITLE
Kill target parameter or new action:  Clear agro

### ISSUE THREAD

**Issue by Tehtsuo** [ISeeDEDPpl/Questor#93]
Can we get a parameter to use for an existing action, or a new action, that allows us to target and attack something, and then clear anything that turns hostile as a result?  Preferably this would only attack one such target, then go on to the next in the mission file, allowing us to order groups of ships in missions to clear one at a time.

**Comment by ISeeDEDPpl** [comment]
yes: the target  / kill something action already exists...
you want something like:

`
<action name="KillClosestByName">
        <parameter name="NotClosest" value="false"></parameter>
        <parameter name="Target" value="Savage Lord"></parameter>
</action>
<action name="KillClosestByName" /action>
<action name="ClearWithinWeaponsRangeAggroOnly"></action> 
`
or
`
<action name="KillClosestByName">
        <parameter name="NotClosest" value="false"></parameter>
        <parameter name="Target" value="Savage Lord"></parameter>
</action>
<action name="KillClosestByName" /action>
<action name="ClearAggro"></action> 
`
