### ISSUE TITLE
Kill target parameter:  Target value

### ISSUE THREAD

**Issue by Tehtsuo** [ISeeDEDPpl/Questor#94]
Can we get a parameter or action that allows us to order targets based on value?  In many missions the highest value target is a trigger for reinforcements, it would be best to kill that last.

**Comment by CasualBod** [comment]
you can implement this in the mission actions in your mission.xml with existing action parameters already. Just add the name of the target you want to ignore.

**Comment by ISeeDEDPpl** [comment]
DE does not have NPC bounties. We would need to use the generic values from the XML which would not be all that valuable tbh.
