### ISSUE TITLE
After Mission Salvaging problem

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#95]
very often questor hang up when loot wreck, because loot window not always open corectly and all time shows refresh icon.

**Comment by ISeeDEDPpl** [comment]
please set <debugLootWrecks>true</debugLootWrecks> in your character config xml
and get me the console log when that occurs. Ive been trying to unsuccessfully reproduce that for nearly 3 hours now

**Comment by oldmeat** [comment]
In the latest at the moment commit 8c3c3e5164, problem still exist but if i manually close item loot window, questor back to the work and continue salvage

**Comment by ISeeDEDPpl** [comment]
try again with latest experimental please. I increased the time between opening wrecks... eventually lootwrecks() in salvage.cs is going to need to be rewritten. I think bbday is already doing it.

**Comment by oldmeat** [comment]
The latest for the moment commit 66f4d20d21:
Bot does not collect loot because the window is not refreshed. Now do not hang right away because collect salvage, and hangs when finished salvaging.
I try close multiple windows but doesnt effect. 
I've noticed that every time when the window is not refreshing, use the button / loot all / makes the bot continues to work

**Comment by ISeeDEDPpl** [comment]
Can I get a console log when this happens with <debugLootWrecks>true</debugLootWrecks> in your characters settings xml?

**Comment by oldmeat** [comment]
http://pastebin.com/J8DJuiLa

and next stuck:

http://pastebin.com/Axvirmjc

and again:

http://pastebin.com/HyWBMmpT
