### ISSUE TITLE
Suggestion:  Add an agent blacklist

### ISSUE THREAD

**Issue by eveguy** [ISeeDEDPpl/Questor#97]
I've had an issue with the odd storyline mission originating in highsec but with a route that requires a trip through lowsec.  This is a pain in the ass.  One way to fix this would be adding the ability to blacklist agents that give missions like this or agents in systems that are in systems that require a trip through lowsec to reach.

**Comment by ISeeDEDPpl** [comment]
this should not be needed now that we specifically check the route for every storyline agent.
